### ISSUE TITLE
When cloning to another machine, need to edit postgresql.conf?

### ISSUE THREAD

**Issue by mattbunter** [pgbackrest/pgbackrest#1043]
1. pgBackRest version:
2.23
2. PostgreSQL version:
12
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS 7
4. Did you install pgBackRest from source or from a package?
RPM

If using pgbackrest to restore to another machine (aka cloning), I presume before starting the Postgresql service of the cloned database, that one should modify the 
archive_mode
and
archive_command
parameters in postgresql.conf to avoid writing WALs into the directories of the 'original' database.

Can this be confirmed please?

**Comment by mattbunter** [comment]
FYI : in my humble opinion, yes, vital that both the archive_mode AND archive_commands are modified in postgresql.conf (I put archive_mode = off and archive_command = '/bin/true' to avoid causing 'corruption' of your existing backups.

**Comment by sfrost** [comment]
If you're cloning to another server and bringing it up as a new primary then yes, you absolutely should adjust archive_mode/archive_command to avoid push WAL from that clone into your production repository.  Now that pgbackrest is writing into postgresql.auto.conf (required as part of the changes in PG12), we have been considering adding a specific option to do this for you as part of a restore.

We should probably add something to the documentation or the user guide to call this out specifically though.  This issue is specifically covered in the Crunchy Data pgBackRest tutorial, which you can go through here to learn more about working with pgBackRest:

https://learn.crunchydata.com/pg-administration/courses/basic-postgresql-for-dbas-12/pgbackrest/

**Comment by mattbunter** [comment]
Maybe instead of using 'restore' in the pgbackrest command, use 'clone' instead which would automagically modify the postgresql.conf for these parameters.

**Comment by mattbunter** [comment]
Two more PITRs done recenty, both worked after having edited postgresql.conf (the archive_mode and archive_command parameters).

**Comment by dwsteele** [comment]
I'm not very excited about a `clone` command. Commands are fairly heavyweight in pgBackRest so creating one to modify a single aspect is not what we do. It seems like a `--clone` option passed to restore would work just as well and be much simpler.

**Comment by mattbunter** [comment]
As you like, just need to ensure that the archive_command isn't set to push WALs to the same place as your source.

**Comment by dwsteele** [comment]
We have added the `archive-mode` option to handle this case, see 8c2960fab3.
