### ISSUE TITLE
wal segment size is 33554432 but must be 16777216 for PostgreSQL <= 10

### ISSUE THREAD

**Issue by aldredza** [pgbackrest/pgbackrest#1058]
1. pgBackRest version: 
    - pgBackRest 2.06

2. PostgreSQL version: 
    - v10.5

3. Operating system/version : 
    - Red Hat Enterprise Linux Server 7.5

4. Did you install pgBackRest from source or from a package?
    - Installed from source

5. Please attach the following as applicable:

7. Describe the issue:
    - wal segment size changed to 32MB duing source configure.
        [postgres@rheldb data]$ /pgs001/PostgreSQL/v10.5/bin/psql -c 'SHOW wal_segment_size;'
         wal_segment_size 
        ------------------
         32MB
        (1 row)
      
      pgbackrest restore fails with error message:
ERROR: [029]: wal segment size is 33554432 but must be 16777216 for PostgreSQL <= 10
2020-05-29 18:55:15.194 P00   INFO: archive-get command end: aborted with exception [029]

Is there a workaround that allows using non-default wal segment size with PostgreSQL 10.5?

[logfile.txt](https://github.com/pgbackrest/pgbackrest/files/4703358/logfile.txt)
[postgresql.conf.txt](https://github.com/pgbackrest/pgbackrest/files/4703360/postgresql.conf.txt)
[pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/4703361/pgbackrest.conf.txt)

**Comment by dwsteele** [comment]
There's no setting that will enable this. When variable WAL sizes were properly introduced in PG11 there were also a number of code changes and fixes around variable sizes. We judged that variable WAL sizes were not sufficiently stable in prior versions and since a custom build is required it isn't testable in our framework either.

If you want to use a different WAL size we recommend upgrading to >= PG11.

**Comment by aldredza** [comment]
Thank you! Appreciate the feedback!
