### ISSUE TITLE
Restoring from S3 on a different machine

### ISSUE THREAD

**Issue by asoltesz** [pgbackrest/pgbackrest#1066]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

version 2.25

2. PostgreSQL version:

12.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

CentOS 7

4. Did you install pgBackRest from source or from a package?

package (CrunchyData Postgres Operator)

5. Please attach the following as applicable:

Stanza-create fails with this:
~~~
time="2020-06-10T16:47:04Z" level=info msg="pgo-backrest starts"
time="2020-06-10T16:47:04Z" level=info msg="debug flag set to false"
time="2020-06-10T16:47:04Z" level=info msg="backrest stanza-create command requested"
time="2020-06-10T16:47:04Z" level=info msg="backrest command will be executed for both local and s3 storage"
time="2020-06-10T16:47:04Z" level=info msg="command to execute is [pgbackrest stanza-create  --db-host=172.18.0.13 --db-path=/pgdata/hippo && pgbackrest stanza-create  --db-host=172.18.0.13 --db-path=/pgdata/hippo --repo-type=s3]"
time="2020-06-10T16:47:04Z" level=info msg="command is pgbackrest stanza-create  --db-host=172.18.0.13 --db-path=/pgdata/hippo && pgbackrest stanza-create  --db-host=172.18.0.13 --db-path=/pgdata/hippo --repo-type=s3 "
time="2020-06-10T16:47:06Z" level=error msg="command terminated with exit code 28"
time="2020-06-10T16:47:06Z" level=info msg="output=[]"
time="2020-06-10T16:47:06Z" level=info msg="stderr=[ERROR: [028]: backup and archive info files exist but do not match the database\n       HINT: is this the correct stanza?\n       HINT: did an error occur during stanza-upgrade?\n]"
time="2020-06-10T16:47:06Z" level=error msg="command terminated with exit code 28"
~~~

7. Describe the issue:

I am having trouble understanding how one can restore in the following situation:
- Backups were saved to a remote S3 repo
- Postgres host and local backrest repo completely destroyed (whole machine crashed)
- I have a new machine with the same Postgres/pgbackrest version installed
- I would like to restore from S3 but the system-id on the new machine will always be different from the the one that was used to create the backups to S3, so create-stanza fails on the existing S3 bucket

I didn't find information in the Guide for this situation.

How do I create the stanza and restore to the new machine?

**Comment by asoltesz** [comment]
Thanks, I managed to do the restore.

**Comment by Venryx** [comment]
For others finding this, just wanted to mention that if you're getting this error when using:
```
spec:
  backups:
    pgbackrest:
      restore:
        [...]
```

Then try using the alternate restore approach:
```
spec:
  dataSource:
    [...]
```

The second type can work even if the database system-id differs between the backup and the target cluster, whereas the first cannot.

For reference, here is the code that causes the `backup and archive info files exist but do not match the database` error: https://github.com/pgbackrest/pgbackrest/blob/bd0081fec87ee32fa57adf5c882a6cad5394eaa0/src/command/check/common.c#L152-L157

**Comment by Venryx** [comment]
Nevermind, it seems that the error can occur regardless of whether you use the `restore` or `dataSource` approaches. (the `dataSource` approach was working for me because it avoided a different error I think; but it had the error come up again when I reset the cluster)

Anyway, it appears that the postgres system-identifier is set during initialization of the `postgrescluster/myapp` CRD, and then stays around until the cluster is destroyed/reset, or the CRD is recreated (eg. using the Tilt UI to force-update/restart/reset it).

If that reset/recreation is performed however, how should one go about resetting the system identified back to what it was, so that it can use the set of backups that had already been created?

**Comment by dwsteele** [comment]
> A) Load in the configuration from it (so the system-id matches for subsequent backups/restores)

The system identifier cannot be updated in Postgres.

> Realize that there are no actual base-backups in the backup-repo, and thus ignore it (or just log a warning).

The thing to do here is issue a stanza-upgrade or maybe better, a stanza-delete/stanza-create since the repo is pretty useless without backups.

> This works, but is not terribly obvious to new users; perhaps a special error message could be displayed for the backup-repo exists, but without actual backups case, to clarify to new users what should be done.

This seems like something you should suggest at https://github.com/CrunchyData/postgres-operator. Actually, that  pretty much goes for all of this.
