### ISSUE TITLE
ERROR: [029]: wal segment size is 67108864 but must be 16777216 for PostgreSQL <= 10

### ISSUE THREAD

**Issue by palabre** [pgbackrest/pgbackrest#1077]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:  2.27

2. PostgreSQL version: 10.9

3. Operating system/version -  Redhat.6

4. Did you install pgBackRest from source or from a package?
From source

7. Describe the issue:

I am creating a stanza for a postgresql 10.9 and i am getting following error

**The command I run is**

[postgres log]$ /grapps/postgres/pgbackrest/bin/pgbackrest --stanza=*****  --log-path=/grapps/postgres/pgbackrest/log --config=/grapps/postgres/pgbackrest/conf/pgbackrest.conf --log-level-console=detail --db-port=5432 stanza-create

(I hide the name of the cluster because it contains the name of the server)

**And the error i got is** 

2020-06-17 13:49:11.250 P00  ERROR: [029]: wal segment size is 67108864 but must be 16777216 for PostgreSQL <= 10
2020-06-17 13:49:11.350 P00   INFO: stanza-create command end: aborted with exception [029]

Can you help

thanks

**Comment by dwsteele** [comment]
There's no setting that will enable this. When variable WAL sizes were properly introduced in PG11 there were also a number of code changes and fixes around variable sizes. We judged that variable WAL sizes were not sufficiently stable in prior versions and since a custom build is required it isn't testable in our framework either.

If you want to use a different WAL size we recommend upgrading to >= PG11.

**Comment by palabre** [comment]
Hi David

Thanks
