### ISSUE TITLE
Making full backups with archive_mode=off in a single node environment

### ISSUE THREAD

**Issue by andriitar** [pgbackrest/pgbackrest#1080]
Hi,
Is it possible to keep pgbackrest running, make full backups within a standalone Postgres with disabled archive_mode? 
In some cases, customers either can or do want to enable archiving (wal_level=minimal). However, they would like to make backups by pgbackrest.

Andrii.

PS. and thanks for all the hard work on this project!

**Comment by dwsteele** [comment]
> Is it possible to keep pgbackrest running, make full backups within a standalone Postgres with disabled archive_mode?

No. `wal_level > minimal` is absolutely required for online backups. This is not a pgBackRest limitation, see https://www.postgresql.org/docs/current/continuous-archiving.html#BACKUP-LOWLEVEL-BASE-BACKUP.

It is possible to do an online backup using pg_basebackup with `archive_mode=off` but `wal_level` must still be  `> minimal`. We don't support this method of WAL archiving because it is quite slow.

No matter what, the WAL generated during the backup must be preserved and available at restore time or recovery will fail.

> PS. and thanks for all the hard work on this project!

We're glad you like it!

**Comment by andriitar** [comment]
Thank you for your reply.
I've asked this because when we tried to keep `wal_level=replica` and `archive_mode=on` but put a dummy to archive_command (/bin/true), pgbackrest stopped work with an error.

Also, I have a problematic situation with the endless growth of WAL files (their count) in the main directory ../pg_wal. Yes, that's a bit different question but it's where it comes from. 
To stop this growth, a customer changed `archive_command` to /bin/true but backups stopped work after this change. Then, he disabled `archive_mode=off` but kept `wal_level` - backups didn't work. Now, the env (stand-alone) is set to disabled archiving and minimal wal_level. It stopped the growing WALs but I need to figure out how to set all of it correct to achieve two goals -  handle WAL growing and make pgbackrest work.

According to your comment 'It is possible to do an online backup using pg_basebackup with archive_mode=off but wal_level must still be > minimal. ' - I'll try to set it up on my environment and test it.

Thanks.

**Comment by dwsteele** [comment]
> According to your comment 'It is possible to do an online backup using pg_basebackup with archive_mode=off but wal_level must still be > minimal. '

`pg_basebackup` is not a general-purpose backup solution so we don't recommend it, i.e. it doesn't manage WAL, backup expiration, etc.

If WAL volume is a problem, it is possible to only archive WAL during backups. See https://github.com/pgbackrest/pgbackrest/issues/900 for details on how this can be done. We have not tested this method but it looks like it works.

In general, though, it is important to allocate resources for backups (i.e. disk space) since they are an important part of any enterprise. If space is a problem, you might consider using an object store like S3.

**Comment by andriitar** [comment]
Thank you. I think this question can be closed.
