### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by fvannee** [pgbackrest/pgbackrest#1085]
https://github.com/pgbackrest/pgbackrest/issues/879

This might still be nice to implement at some point. If not for production environments, it is really useful in testing/development environments where sometimes you're forced behind proxies.

**Comment by dwsteele** [comment]
We're sure this would be useful in some cases but it is not currently on our development roadmap. The overall value seems too small to be worth the extra code, test cases, and complexity. In general, we don't recommend proxies for pgBackRest because of the high load it can put on the proxy and the resulting performance penalty for the backup.
