### ISSUE TITLE
community package not compiled with zstandard 

### ISSUE THREAD

**Issue by jacks33** [pgbackrest/pgbackrest#1109]
Hello,

it seems pgbackrest  community package is not compiled with zstandard compression library:
http://download.postgresql.org/pub/repos/yum/common/redhat/rhel-7.6-x86_64/pgbackrest-2.27-2.rhel7.x86_64.rpm
I  have an error  message when trying to backup.

**Comment by pgstef** [comment]
Hi,

On what OS are you trying to install it?
Have you tried by manually install `libzstd-devel` before pgbackrest?

The [rpm spec file](https://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob_plain;f=rpm/redhat/master/common/pgbackrest/master/pgbackrest.spec;hb=HEAD) doesn't seem to require `libzstd-devel bzip2-devel` indeed but installing it manually should help I guess.

**Comment by dwsteele** [comment]
Is this the error you are getting: `pgBackRest not compiled with zst support`?

RHEL7 does not include zstd packages in the base distro. They are available in EPEL but I think it is a reasonable choice to avoid requiring EPEL for a backup utility. That's just a guess, though, since we don't maintain the yum packages.

If you'd like to find out you can post on the `pgsql-pkg-yum` mailing list.

**Comment by jacks33** [comment]
Indeed that's
ERROR: [032]: pgBackRest not compiled with zst support
2020-07-21 09:59:48.843 P00   INFO: backup command end: aborted with exception [032]

I'll contact mailing list then.

Thanks for your help
