### ISSUE TITLE
Feature Request - Support changing of decompression method without breaking backup

### ISSUE THREAD

**Issue by anayrat** [pgbackrest/pgbackrest#1127]
Hello!

We are interested by zstd compression but we can't use it without breaking our backups.

Could it be possible for pgbackrest to detect compression algorithm and use the right decompression method?

Thanks

**Comment by dwsteele** [comment]
You can change `compress-type` any time you like, but it will not take effect for backups until the next full backup (archive changes immediately). If you change it early each backup before the next full will WARN that `compress-type` was changed for that backup, so it is best to make the change the night before your next full backup.

**Comment by anayrat** [comment]
Thanks! So if I understand we will never break our previous backup? The warning will appear during the backup or the restore?
For the context we must be able to restore our cluster at any time for the last year. I was afraid we won't be able to restore our previous backup.

**Comment by dwsteele** [comment]
The warning only appears on the backup, and only until the next full backup. A backup set must have the same compression.

You'll be able to restore older backups compressed using gzip with a newer version of pgBackRest. However, you will not be able to restore a newer backup that uses bzip2/zsdt/lz4 with an older version of pgBackRest. Also, not all compression types are available on all platforms, so it's possible to create a backup that cannot be read on all platforms. Only gzip/bzip2 are available in all pgBackRest builds.

So, think about what platforms you need to support before moving to something new like zstd. lz4 is supported pretty much everywhere so that's safer.

**Comment by anayrat** [comment]
> The warning only appears on the backup, and only until the next full backup. A backup set must have the same compression.

Ok, thanks. And pgbackrest will be able to decompress wal even if some of them have been compressed with gzip and other with zstd?

> You'll be able to restore older backups compressed using gzip with a newer version of pgBackRest. However, you will not be able to restore a newer backup that uses bzip2/zsdt/lz4 with an older version of pgBackRest. Also, not all compression types are available on all platforms, so it's possible to create a backup that cannot be read on all platforms. Only gzip/bzip2 are available in all pgBackRest builds.
> 
> So, think about what platforms you need to support before moving to something new like zstd. lz4 is supported pretty much everywhere so that's safer.

Thanks, we use debian and zstd exists since old stable (stretch).

**Comment by dwsteele** [comment]
> And pgbackrest will be able to decompress wal even if some of them have been compressed with gzip and other with zstd?

Yes, as long as you are using a newer version that supports both.

**Comment by anayrat** [comment]
Thanks for all your answers!
