### ISSUE TITLE
Corrupt Repository Due to unchanged archive command

### ISSUE THREAD

**Issue by threenotrump** [pgbackrest/pgbackrest#1161]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.28

2. PostgreSQL version: 12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: centos 7 

4. Did you install pgBackRest from source or from a package? Package

 Hello 

I am new to pgbackrest I tried to search my problem but failed to find a solution. 

While doing pitr to a new server I forgot change archive_command , started postgres and it corrupted the repository.

In order to prevent a case like that is there a way to block receving wal files except trusted servers?

Is there a way to find these "bad" wal files and remove it from the repository?

Best Regards

**Comment by sfrost** [comment]
pgbackrest already checks to see if the WAL file is for the right database ID, but unfortunately, that's going to be the case when you restore the right server.

We do have a pull request open now and which will hopefully be in the next, or a soon to come, release which will allow you to ask pgbackrest to explicitly disable archiving as part of the restore, which will help with this.  That's only going to be available on v12 and above though since we don't modify the postgresql.auo.conf in older versions.

Changing the database ID on a restore is another possible option that we could implement that would help to address this and would work for older releases, but it's a fair bit of additional code to make that happen.

One of the challenges is- how would pgbackrest know if it's a trusted server or not?  How do we know that it's not a newly promoted primary?  Unfortunately, there's not a trivial answer to that- feel free to share any suggestions you have.

**Comment by threenotrump** [comment]
Hello Mr Frost

Thank you for the quick reply.

Its a bit of a problem to corrupt repository easily. I was lucky it was just a test environment.

I can offer 2 possible solutions but i dont know how hard will it be to implement.

1-) Maybe a trusted serves parameter can be added per stanza

2-) Keep the wals in a seperate directory for each ip than these wal files may be identified and deleted.

**Comment by dwsteele** [comment]
> Maybe a trusted serves parameter can be added per stanza

As of 2.28 you can use the `archive-mode` option to disable archiving.

> Keep the wals in a seperate directory for each ip than these wal files may be identified and deleted.

We are considering something like this for a future repository version.

**Comment by threenotrump** [comment]
Hello Mr Steele

Thanks for the reply.

Disabling archiving through archive-mode parameter or postgresql.conf  works but what I am trying to say is its prone to human error.

IMHO pgbackrest should have mechanisms to prevent human errors as much as possible.

Best Regards

**Comment by dwsteele** [comment]
> IMHO pgbackrest should have mechanisms to prevent human errors as much as possible.

Understood, but adding a new option that is required for archiving would break existing installations. We are planning to revisit this in the next repo format.

**Comment by sfrost** [comment]
We do have a lot of mechanisms in place to try and prevent human error, and work with PG itself to make changes to help try and address that (one thing we recently did was get .history files to be pushed up sooner, to reduce the chances of a history file not being seen when a promotion happens and ending up with the same timeline being picked by multiple systems and having breakage result...  So, at least today, you're less likely to end up with actual corruption in the WAL as long as you're promoting each system, you'll just end up with multiple timelines that you'll have to sort through, which is a much better place to be in).

Perhaps there's more we can do, sure, and we're interested in making such improvements but it sounds like such a change would require a new repo format and we aren't likely to introduce one in the near-term as it'd cause a lot of breakage and it doesn't seem like it's quite worth it to do that yet.
