### ISSUE TITLE
How to size the parameter archive-push-queue-max ?

### ISSUE THREAD

**Issue by cheucheu** [pgbackrest/pgbackrest#1195]
Hi

My version of pgbackrest is 2.18.
My versio of PG server is 11.7

To speed up the wal archiving with parallelism, , i have added the parameter **archive-async=Y i**n the section global of the pgbackrest.conf file.

Without, the archiving is slowly because it's serial.

In addition of this parameter, should we add this parameter  **archive-push-queue-max**?
- Do you recommand to add it?
- What is its default value?
- How to calculate its size?  
- Is it dependent on the size of max_wal_size

Thanks for your answers.

Best regards

**Comment by pgstef** [comment]
Hi,

`archive-push-queue-max` isn't really attached to `archive-async`. It's 2 separated things.

Async archiving will populate the spool-path and use process-max to pre-archive wal segments. So when PG will request to archive it, it will already be done and answer pretty fast.

`archive-push-queue-max` is tight to the amount of wal segments you want PG to keep in case of slow or failing archiving process. It's not a hard limit for PG, it's just a way for pgBR to tell to PG to drop the archive queue and prevent your disk space to be full (and cause PG to crash). Like the documentation says about this option: "better to lose the backup than have PG go down".

So, it's not a mandatory option. It's all up to you if you want to protect your disk space. The sizing of this parameter would then need to be adjusted regarding the free space of you pg_wal disk.

**Comment by cheucheu** [comment]
Hi Stéphane,

Thank you for your answer.

I understand that the parameter archive-push-queue-max  is a way to avoid wal space saturation and is not correlated to max_wal_size.

Concretely, I have a FS with 100Go of wal.
- > If I fix this parameter at 1 Go, my space FS will be to 99 Go.   Is this OK ?


BR

**Comment by pgstef** [comment]
I wouldn't recommend to have a so small limit. Unless you have a very good monitoring system and watch for missing archives regularly. 

Have you already issued WAL space saturation ? A good start point would be to monitor the number of .ready files to know approximately what could be a good start point for that parameter...

**Comment by cheucheu** [comment]
why do you consider that the size of 1 Go is too low about our FS size ?

We have a supervision system.  We generate an alarm if the FS occupancy rate reaches 85% of use.
Do you think finally  that the parameter is of interest or not in our context?

 In my opinion, if there are files with this status (.ready), 'is that the archive command is experiencing latency but this does not mean that The FS is plenty ? Could you tell me  more ?
 
BR

**Comment by pgstef** [comment]
I don't think `archive-push-queue-max` is interesting in day-to-day usage when you never experienced a "full disk space" issue due to archiving. And it's not related to the FS size but to your usual archiving load.

.ready is saying that the file is ready to archive but not done yet. Until it gets .done, PG will keep the wal file associated to that .ready. Archiving latency is not always an issue (you might pg_restore faster than your archive_command can run for example). 

The issue is when you get too many wal files kept because your archive_command is failing. When the monitoring alarm is raised, you can still apply the `archive-push-queue-max` to unlock the archiving process and avoid saturation. 

1G is really low. Risk of missing archive is real. As mentioned, I would advice to monitor the real space taken by the archives (number of .ready) and figure out what "lowest" limit for `archive-push-queue-max` you could set without generating missing archives.

If you decide to configure `archive-push-queue-max`, you'll have to watch carefully for missing archives which could break your pitr capability or even your backups.
