### ISSUE TITLE
Multiple standby issues

### ISSUE THREAD

**Issue by jamessewell** [pgbackrest/pgbackrest#1197]
PGBackrest 2.30 from RPM
PostgreSQL 11.9 from RPM
CentOS 8.2

This config (pg2 is the localhost, 192.168.20.22)

```
[backups]
pg1-host=192.168.20.21
pg1-path=/pgs01/11/data/pg_data
pg2-path=/pgs01/11/data/pg_data
```

Works, but this config:

```
[ece]
pg1-host=192.168.20.21
pg1-path=/pgs01/11/data/pg_data
pg2-path=/pgs01/11/data/pg_data
pg3-host=192.168.20.23
pg3-path=/pgs01/11/data/pg_data
```

Fails, with:

```
[postgres@localhost ~]$ pgbackrest backup --stanza ece --log-level-console=info
WARN: unable to open log file '/var/log/pgbackrest/ece-backup.log': Permission denied
      NOTE: process will continue without log file.
2020-10-12 22:29:43.053 P00   INFO: backup command begin 2.30: --backup-standby --log-level-console=info --log-level-file=off --pg1-host=192.168.20.21 --pg3-host=192.168.20.23 --pg1-path=/pgs01/11/data/
pg_data --pg2-path=/pgs01/11/data/pg_data --pg3-path=/pgs01/11/data/pg_data --process-max=1 --repo1-path=/var/lib/pgsql/11/backups --repo1-retention-full=5 --stanza=ece --start-fast --stop-auto
WARN: unable to check pg-3: [LockAcquireError] raised from remote-0 protocol on '192.168.20.23': raised from remote-0 protocol on '192.168.20.21': unable to acquire lock on file '/var/lib/pgsql/11/backu
ps/lock/ece-backup.lock': Resource temporarily unavailable
      HINT: is another pgBackRest process running?
WARN: no prior backup exists, incr backup has been changed to full
2020-10-12 22:29:45.701 P00   INFO: execute non-exclusive pg_start_backup(): backup begins after the requested immediate checkpoint completes
2020-10-12 22:29:46.479 P00   INFO: backup start archive = 000000020000000000000012, lsn = 0/12000028
2020-10-12 22:29:46.479 P00   INFO: wait for replay on the standby to reach 0/12000028
ERROR: [050]: raised from remote-0 protocol on '192.168.20.23': raised from remote-0 protocol on '192.168.20.21': unable to acquire lock on file '/var/lib/pgsql/11/backups/lock/ece-backup.lock': Resourc
e temporarily unavailable
       HINT: is another pgBackRest process running?
2020-10-12 22:29:47.723 P00   INFO: backup command end: aborted with exception [050]
```

SSH is working correctly, the lock directory is writable and owned by postgres.

Any ideas?

Cheers,
James

**Comment by pgstef** [comment]
Hi,

At first look, it seems a permission problem with the repo configuration. Both on `/var/lib/pgsql/11/backups` and `/var/log/pgbackrest`. Can you check that?

Depending on your configuration, it might also be a [repo-host-user](https://pgbackrest.org/configuration.html#section-repository/option-repo-host-user) miss-configuration too.

It really depends on your configuration. Could you provide the complete configuration files used for each server (primary and standbys)?

Kind regards,

**Comment by jamessewell** [comment]
Hey,

All hosts are the same. I can touch files as postgres in both of those
directories.

[ece]
pg1-path=/pgs01/11/data/pg_data
pg1-host=192.168.20.24
pg2-path=/pgs01/11/data/pg_data
pg2-host=192.168.20.21
pg3-path=/pgs01/11/data/pg_data
pg3-host=192.168.20.22
pg4-path=/pgs01/11/data/pg_data
pg4-host=192.168.20.23

[global]
archive-async=y
backup-user=postgres
repo-path=/var/lib/pgsql/11/backups/
retention-full=5
start-fast=y
stop-auto=y
process-max=1

[postgres@localhost ~]$ id
uid=1001(postgres) gid=1001(postgres) groups=1001(postgres)
context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
[postgres@localhost ~]$ touch /var/lib/pgsql/11/backups/test
[postgres@localhost ~]$ touch /tmp/pgbackrest/test

**Comment by jamessewell** [comment]
Just to be clear - this is a temporary config where the repo is on one of
the database hosts (until SWIFT shows up then they will all share).

**Comment by df7cb** [comment]
I just had a similar (or maybe the same) problem: If I put pg1-host, pg1-path, pg2-host, and pg2-path into the config, `pgbackrest archive-push` will refuse to run because "archive-push command must be run on the PostgreSQL host".

Is running pgbackrest with more than one host in the config supposed to work when running *on* one of these hosts?

**Comment by pgstef** [comment]
I can reproduce the error using 

```
[ece]
pg1-path=/var/lib/pgsql/11/data
pg1-host=s1
pg2-path=/var/lib/pgsql/11/data
pg2-host=s2
pg3-path=/var/lib/pgsql/11/data
pg3-host=s3

[global]
repo1-path=/var/lib/pgsql/11/backups/
repo1-retention-full=1
start-fast=y
process-max=1
```
With simply 3 freshly installed CentOS7 servers, with password-less ssh connections between postgres users. Even with a shared repo (temporary nfs mount).

The error @df7cb raised is left when `pg*-host` isn't specified on the running host. Example, remove `pg1-host` on s1, `pg2-host` on s2,... But that's not related to the problem here.

I think the question here is where to store the backups, where to execute the backup and from which server to copy the data.

With this simple configuration, it will work to take backups from any server:

```
#s1
[ece]
pg1-path=/var/lib/pgsql/11/data

[global]
repo1-path=/var/lib/pgsql/11/backups/
repo1-retention-full=1
start-fast=y

#same for s2 and s3
[ece]
pg1-path=/var/lib/pgsql/11/data
pg1-host=s1
pg2-path=/var/lib/pgsql/11/data

[global]
repo1-path=/var/lib/pgsql/11/backups/
repo1-retention-full=1
start-fast=y
backup-standby=y
```

I think if you want to specify all the hosts, you'll need a specific "backup server". I'll try that.

**Comment by df7cb** [comment]
> The error @df7cb raised is left when `pg*-host` isn't specified on the running host. Example, remove `pg1-host` on s1, `pg2-host` on s2,... But that's not related to the problem here.

It would be nice if it was possible to use the same config file on all servers.

**Comment by dwsteele** [comment]
@jamessewell Since each of your pg* entries has a host setting you're getting double locking because pgbackrest locks locally to keep another backup process from running then connects to the pg host and attempts to take a lock there as well. Since the pg instance is local it loops back and ends up trying to create a new lock on the same host.

When the configuration system was designed for 1.0 it was typical to have a repo host so this generally wasn't an issue and our answer at that time was to have separate configs for each host. These days backing up to object stores is much more common and in that scenario people tend to run without a repo host to save maintenance and avoid a bottleneck.

We have been working on making it so the same configuration file can be used on all hosts (repo and pg) by also adding one additional option on each host that specifies which pg/repo host is "local". The idea is the main configuration would be in `/etc/pgbackrest/pgbackrest.conf` (or `/etc/pgbackrest.conf`) and the local option would be in a separate file in the `conf.d` dir, e.g. /etc/pgbackrest/conf.d/local.conf`. So in your case `local.conf` would look like (assuming pg1 is local on the host):
```
[ece]
pg1-local=y
```
We have been using this option internally for a while to make sure remotes don't loop back on themselves. There is also a similar option `repo1-local` in case a repo host is in use.

I want to stress that this option is still internal, which means we haven't yet decided on a permanent name for it. So, feel free to give it a try but there is a (small) chance that the name will change when we expose the option. I don't think the name *will* change at this point and your feedback would help us settle on our choice.

@df7cb Hopefully that answers your question as well. Feedback is appreciated.

We are currently working on multi-repo support which includes a general revamp of the configuration system. That should included exposing pg-local/repo local and generally improving support for symmetric configs in the next version.

Another possible option would be to have the remote process recognize that the lock was created by the main process and just continue without attempting to get a new lock. You'd still be pushing all your data through a socket, but it would be local so maybe not that big a deal, and the configuration would definitely be simpler. Starting a remote is not free, though, so for other commands like `archive-push` this could cause a serious performance issue. Maybe it would make sense to do it, but also WARN?

**Comment by df7cb** [comment]
@dwsteele Thanks David, that explains.

I was demonstrating pgbackrest to a customer in a workshop, but the part were we wanted to get "have primary and standby both in config and pull backup from either" working failed badly because we couldn't get it working. I saw suspicious ssh connections going back from the "other" host to the primary one, so it was somewhat clear it had problems determining what hosts are "local".

**Comment by dwsteele** [comment]
Correct, and I think the `pg-local` option is the best way to deal with this situation, otherwise we have to do probing to figure out that a remotely configured host is in fact the local host. We might do that probing as a fallback but users with CM should be able to set the option on each host pretty easily.

**Comment by jamessewell** [comment]
Amazing! Thanks!

**Comment by jamessewell** [comment]
Hmmm,

That all made sense, but no luck:

[postgres@localhost pg_data]$ ip addr | grep .23
    inet 192.168.20.23/24 brd 192.168.20.255 scope global dynamic
noprefixroute ens192
[postgres@localhost pg_data]$ cat /etc/pgbackrest.conf
[ece]
pg1-path=/pgs01/11/data/pg_data
pg1-host=192.168.20.21
pg2-path=/pgs01/11/data/pg_data
pg2-host=192.168.20.22
pg3-path=/pgs01/11/data/pg_data
pg3-host=192.168.20.23
pg3-local=y
pg4-path=/pgs01/11/data/pg_data
pg4-host=192.168.20.24

[global]
archive-async=y
backup-standby=y
backup-user=postgres
repo-path=/var/lib/pgsql/11/backups/
retention-full=5
start-fast=y
stop-auto=y
process-max=1

[postgres@localhost pg_data]$ pgbackrest backup --stanza ece
WARN: unable to check pg-2: [LockAcquireError] raised from remote-0
protocol on '192.168.20.22': raised from remote-0 protocol on
'192.168.20.21': unable to acquire lock on file '/tmp/pgbackrest/ece-bac
kup.lock': Resource temporarily unavailable
      HINT: is another pgBackRest process running?
WARN: unable to check pg-4: [LockAcquireError] raised from remote-0
protocol on '192.168.20.24': raised from remote-0 protocol on
'192.168.20.21': unable to acquire lock on file '/tmp/pgbackrest/ece-bac
kup.lock': Resource temporarily unavailable
      HINT: is another pgBackRest process running?
WARN: no prior backup exists, incr backup has been changed to full
ERROR: [050]: raised from remote-0 protocol on '192.168.20.22': raised from
remote-0 protocol on '192.168.20.21': unable to acquire lock on file
'/tmp/pgbackrest/ece-backup.lock': Resource temporarily u
navailable
       HINT: is another pgBackRest process running?
[postgres@localhost pg_data]$ echo $?
50
[postgres@localhost pg_data]$

Also, this does not work with this config either:

[ece]
pg1-path=/pgs01/11/data/pg_data
pg1-host=192.168.20.21
pg2-path=/pgs01/11/data/pg_data
pg2-host=192.168.20.22
pg3-path=/pgs01/11/data/pg_data
pg4-path=/pgs01/11/data/pg_data
pg4-host=192.168.20.24

Which I think you were saying should work (as pg3 is a socket connection)?

Cheers,
James

**Comment by jamessewell** [comment]
Hmmm,

That all made sense, but no luck:

```
[postgres@localhost pg_data]$ ip addr | grep .23
    inet 192.168.20.23/24 brd 192.168.20.255 scope global dynamic
noprefixroute ens192
[postgres@localhost pg_data]$ cat /etc/pgbackrest.conf
[ece]
pg1-path=/pgs01/11/data/pg_data
pg1-host=192.168.20.21
pg2-path=/pgs01/11/data/pg_data
pg2-host=192.168.20.22
pg3-path=/pgs01/11/data/pg_data
pg3-host=192.168.20.23
pg3-local=y
pg4-path=/pgs01/11/data/pg_data
pg4-host=192.168.20.24

[global]
archive-async=y
backup-standby=y
backup-user=postgres
repo-path=/var/lib/pgsql/11/backups/
retention-full=5
start-fast=y
stop-auto=y
process-max=1

[postgres@localhost pg_data]$ pgbackrest backup --stanza ece
WARN: unable to check pg-2: [LockAcquireError] raised from remote-0
protocol on '192.168.20.22': raised from remote-0 protocol on
'192.168.20.21': unable to acquire lock on file '/tmp/pgbackrest/ece-bac
kup.lock': Resource temporarily unavailable
      HINT: is another pgBackRest process running?
WARN: unable to check pg-4: [LockAcquireError] raised from remote-0
protocol on '192.168.20.24': raised from remote-0 protocol on
'192.168.20.21': unable to acquire lock on file '/tmp/pgbackrest/ece-bac
kup.lock': Resource temporarily unavailable
      HINT: is another pgBackRest process running?
WARN: no prior backup exists, incr backup has been changed to full
ERROR: [050]: raised from remote-0 protocol on '192.168.20.22': raised from
remote-0 protocol on '192.168.20.21': unable to acquire lock on file
'/tmp/pgbackrest/ece-backup.lock': Resource temporarily u
navailable
       HINT: is another pgBackRest process running?
[postgres@localhost pg_data]$ echo $?
50
[postgres@localhost pg_data]$
```

Also, this does not work with this config either:

```
[ece]
pg1-path=/pgs01/11/data/pg_data
pg1-host=192.168.20.21
pg2-path=/pgs01/11/data/pg_data
pg2-host=192.168.20.22
pg3-path=/pgs01/11/data/pg_data
pg4-path=/pgs01/11/data/pg_data
pg4-host=192.168.20.24
```

Which I think you were saying should work (as pg3 is a socket connection)?

*EDIT*

Here is the full config list from each server:

```
root@all (5)[f:20]$ cat /etc/pgbackrest.conf | grep pg
192.168.20.21 | CHANGED | rc=0 >>
pg1-path=/pgs01/11/data/pg_data
pg1-host=192.168.20.21
pg1-local=y
pg2-path=/pgs01/11/data/pg_data
pg2-host=192.168.20.22
pg3-path=/pgs01/11/data/pg_data
pg3-host=192.168.20.23
pg4-path=/pgs01/11/data/pg_data
pg4-host=192.168.20.24
repo-path=/var/lib/pgsql/11/backups/

192.168.20.23 | CHANGED | rc=0 >>
pg1-path=/pgs01/11/data/pg_data
pg1-host=192.168.20.21
pg2-path=/pgs01/11/data/pg_data
pg2-host=192.168.20.22
pg3-path=/pgs01/11/data/pg_data
pg3-host=192.168.20.23
pg3-local=y
pg4-path=/pgs01/11/data/pg_data
pg4-host=192.168.20.24
repo-path=/var/lib/pgsql/11/backups/

192.168.20.24 | CHANGED | rc=0 >>
pg1-path=/pgs01/11/data/pg_data
pg1-host=192.168.20.21
pg2-path=/pgs01/11/data/pg_data
pg2-host=192.168.20.22
pg3-path=/pgs01/11/data/pg_data
pg3-host=192.168.20.23
pg4-path=/pgs01/11/data/pg_data
pg4-host=192.168.20.24
pg4-local=y
repo-path=/var/lib/pgsql/11/backups/

192.168.20.22 | CHANGED | rc=0 >>
pg1-path=/pgs01/11/data/pg_data
pg1-host=192.168.20.21
pg2-path=/pgs01/11/data/pg_data
pg2-host=192.168.20.22
pg2-local=y
pg3-path=/pgs01/11/data/pg_data
pg3-host=192.168.20.23
pg4-path=/pgs01/11/data/pg_data
pg4-host=192.168.20.24
repo-path=/var/lib/pgsql/11/backups/
```


Cheers,
James

**Comment by dwsteele** [comment]
I think I see what is happening, but not why. Can we get a debug log `pgbackrest backup --stanza ece --log-level-console=debug` so we can see how the remotes are being started?

**Comment by jamessewell** [comment]
Done: 
[pgbackrest-debug.txt](https://github.com/pgbackrest/pgbackrest/files/5378065/pgbackrest-debug.txt)

**Comment by dwsteele** [comment]
Pretty much as I suspected. The `pg-local` option won't work for this more general use case. In fact it looks like it only worked for a pretty narrow use case, even less than I had intended for our internal usage.

So it looks like what will work *right now* is the asymmetric configuration we have been recommending in the past when there is no repo host.  For now I believe this is the only thing that will work.

So, your configs would need to look like the following. Basically the local host is always configured in `pg1` without a host and the other hosts are listed afterwards. The plan is to support either of your configs from above for the next release.
```
root@all (5)[f:20]$ cat /etc/pgbackrest.conf | grep pg
192.168.20.21 | CHANGED | rc=0 >>
pg1-path=/pgs01/11/data/pg_data
pg2-path=/pgs01/11/data/pg_data
pg2-host=192.168.20.22
pg3-path=/pgs01/11/data/pg_data
pg3-host=192.168.20.23
pg4-path=/pgs01/11/data/pg_data
pg4-host=192.168.20.24
repo-path=/var/lib/pgsql/11/backups/

192.168.20.23 | CHANGED | rc=0 >>
pg1-path=/pgs01/11/data/pg_data
pg2-path=/pgs01/11/data/pg_data
pg2-host=192.168.20.21
pg3-path=/pgs01/11/data/pg_data
pg3-host=192.168.20.22
pg4-path=/pgs01/11/data/pg_data
pg4-host=192.168.20.24
repo-path=/var/lib/pgsql/11/backups/

192.168.20.24 | CHANGED | rc=0 >>
pg1-path=/pgs01/11/data/pg_data
pg2-path=/pgs01/11/data/pg_data
pg2-host=192.168.20.21
pg3-path=/pgs01/11/data/pg_data
pg3-host=192.168.20.22
pg4-path=/pgs01/11/data/pg_data
pg1-host=192.168.20.23
repo-path=/var/lib/pgsql/11/backups/

192.168.20.22 | CHANGED | rc=0 >>
pg1-path=/pgs01/11/data/pg_data
pg2-path=/pgs01/11/data/pg_data
pg1-host=192.168.20.21
pg3-path=/pgs01/11/data/pg_data
pg3-host=192.168.20.23
pg4-path=/pgs01/11/data/pg_data
pg4-host=192.168.20.24
repo-path=/var/lib/pgsql/11/backups/
```

**Comment by jamessewell** [comment]
Thanks, that works perfectly for local backups.

I've also confirmed that it works when I hook it up to my remote repo (Minio / S3).
