### ISSUE TITLE
ERROR: [053]: unable to restore to path '/srv/pgsql' not owned by current user

### ISSUE THREAD

**Issue by ccavallie** [pgbackrest/pgbackrest#1198]
1. pgBackRest version: 2.29

2. PostgreSQL version: 9.4 and 11.8

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:  RH6 and RH7

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
Hello, 

I attempt to restore à backup with this command line:
pgbackrest restore --stanza="vtlpsq94003-inst01" --repo1-host="vtlbkrpsq001.retraite.lan" --repo1-host-user="usrpgbackrest" --pg1-path="/srv/pgsql/pginst01/9.4/pg_data" --set="20201012-145233F" --type=default   --link-map=pg_hba.conf=/srv/pgsql/pg_hba.conf --link-map=pg_log=/srv/logs/pgsql/pginst01/9.4/pg_log --link-map=pg_xlog=/srv/pgsql/pginst01/9.4/pg_xlog --link-map=startup.conf=/srv/pgsql/pginst01/9.4/startup.conf
WARN: unknown user 'root' in backup manifest mapped to current user
WARN: unknown group 'root' in backup manifest mapped to current group
ERROR: [053]: unable to restore to path '/srv/pgsql' not owned by current user

For security the 2 first levels of our arborescence is owned by root. 
The other solution is restore all files and transforme it after restore in symbolics links have you an another solution to bypass this error?
thanks
Christophe

**Comment by dwsteele** [comment]
I think there are two options here:

1) Make sure `/srv/pgsql` is owned by the restore user before the restore and then change the permissions afterwards.
2) Perform the restore as root.

I don't really recommend #2 (even though it should get the permissions right) because you'll end up with lock files and logs owned by root which can cause other problems. So if you do it, I would set an alternate `lock-path` and `log-path` just for the restore.

BTW -- I'm a little surprised that `postgres` will start with these permissions. The mode on `/srv/pgsql` must be `777` if root owns it?

**Comment by ccavallie** [comment]
It's not possible for us to modify the right on the filesystem /srv/pgsql (is knowinly locked by our linux system team) 
/srv is owned by root 
and 
/srv/pgsql by postgres (I correct what I said initialy)

**Comment by dwsteele** [comment]
I'm a bit skeptical that `/srv/pgsql` is owned by `postgres`. Or possibly the restore process is not being run by `postgres`?
