### ISSUE TITLE
Can I enable archive_mode=always, while ensuring only the Primary DBServer will push into pgBackRest repo?

### ISSUE THREAD

**Issue by insafk** [pgbackrest/pgbackrest#1204]
Hello,

I am using so many postgres clusters in Master-Slave setup in production. Today we are using FileSystemBackup using Linux LVMSnapshot from Slave Server for providing PITR setups upon customer requests. As per our organization policy, I have to use this model for PITR and I can not rule it out.

Now I wanted to use PGBackRest to replace the failed servers in a cluster quickly. 
In case of machine failure(disk crash something like that), today it is taking ~30 mins to apply the snapshot and replace the failed machine. With the use of PGBackRest, I can able to do that in ~5 mins.
Since I'm running in M-S setup, there is a risk of losing the whole cluster if the other machine goes down in that span of 30 mins. So using PGBackRest, we can reduce that window.

Hence to adopt this solution, I wanted to go with two backup methods(pgBackRest and FileSystemBackup-using-LVMSnapshot). 
For FileSystemBackup method, we need archive_mode=always. But pgBackRest doesn't support archive_mode=always.

I went through older git issues related to archive_mode=always, and found that pgBackRest disabled it because of the overhead in handling WALs coming from multiple sources.

So, if I modify the pgBackRest source code and remove the check for archive_mode=always. And I will ensure that only the primary server will be doing WAL archiving to pgBackRest repo (by using some scripts for archive_command and archive_command will push into pgBackRest archives only if the current machine is primary). 
Would that be fine? I mean, could this archive_mode=always break any other modules within pgBackRest?

Thanks
<sub>
      1. pgBackRest version: 2.30
2. PostgreSQL version: 11
3. Operating system/version - CentOS
</sub>

**Comment by dwsteele** [comment]
I don't believe there would be any issues, but obviously we don't test it.

The main reason we disabled it was because we don't have a way (with the current repo) to resolved race conditions between the primary and the standby. Worse, the WAL files on the primary are logically equivalent, but *not always* binary equivalent. So, if a WAL file was pushed by the primary the standby might error because it has the same segment with a different checksum.

Anyway, it's up to you to test, and be very sure the primary is the only one pushing to the repo. We might be open to adding an option that relaxes this check so you don't need to compile a custom version, but we'd need to discuss it among the team.

**Comment by insafk** [comment]
Hi David,

It would be great if there is an option to disable the check, but for now, going with a custom version seems to be the only option.

Also, we are planning to take Crunchy Data's paid support for pgBackRest before going into production. So just wanted to make sure that they will still provide support even if I make this change alone in the source code, ie., removing this archive_mode=always checking code. Any idea about that?

Thanks

**Comment by dwsteele** [comment]
I believe they would be fine with it as long as the use case makes sense and is safe. It'd probably be better to make it an option, though, to avoid custom compiles.

**Comment by insafk** [comment]
Actually we have decided to go with a different approach, since modifying pgBackRest can be risky.

We need only those WAL archives which are generated while FileSystemBackup is running, so we thought of copying these WAL archives from pgBackRest repo once the FileSystemBackup is done(by using _pgbackrest archive-get_).

Anyway, still, it would be great if an option is introduced to disable this check.

Thank you, David, for the help

**Comment by sfrost** [comment]
There's another possible approach that might make sense, which would be to introduce an option (or even just have it automatically happen if we see that archive_mode is set to always) where pgbackrest doesn't try to push to the repo when run on the standby, or perhaps have pgbackrest check and verify that the WAL has been pushed to the repo by the primary when it's being run from the replica (but not verify that the checksum matches, since we know that it might not and it's acceptable for it to not).  In this way we wouldn't be just disabling a check but making pgbackrest work with archive_mode=always.

Independently- I'm a bit concerned at what you're talking about regarding "FileSystemBackup".  There's really two ways you can do snapshot-based backups with PostgreSQL, the first is to snapshot every filesystem (the data directory, the WAL directory, all of the tablespaces, etc), all together at once, atomicly, underneath PG and then use that- but you must play forward to the end of the WAL which existed for that to be consistent, but in such case there's no need to fetch WAL from a repository or anything because all of the WAL needed for consistency must be in the snapshot or it wasn't a valid snapshot.  The other way to use snapshot-based backups is to use the snapshot as a kind of "fast copy" of all of the data files, but to do so requires that you actually go into PG and do pg_start_backup(), and do pg_stop_backup(), and grab the results of the stop backup and put that into place as the backup_label, and in that case you do need all the WAL generated between the start backup and the stop backup.

It's really not safe to use a snapshot-based method with multiple filesystems that are not all being snapshot atomicly together without doing pg_start_backup and pg_stop_backup.
