### ISSUE TITLE
Move backup repository from AWS S3 to another S3 compatible storage

### ISSUE THREAD

**Issue by luthv** [pgbackrest/pgbackrest#1220]
Is there an official guide on how to move backup repository from a currently running S3 configuration to another S3 compatible provider? I imagine the steps are something like:

- Stop all stanza with pgbackrest stop
- Copy all files from current S3 bucket to the new provider
- modify pgbackrest config to point to the new S3 provider
- start all stanza with pgbackrest start

Will this work or is there anything else that I should watch out for?

**Comment by pgstef** [comment]
Hi,

Stanza stop will indeed prevent new archives and backups. Since we rely on the files and directories, I think copying the entire repo content should do the trick. Just pay attention to the access rights.

Those steps look good to me.

Kind regards,

**Comment by luthv** [comment]
Thanks, since the repo is rather large, I was wondering if it's possible to migrate it one stanza at a time, can we have different S3 config for different stanza in one repository host?

**Comment by pgstef** [comment]
Hi,

To be honest, it's not something I've already seen or tested. Originally, `repo1-*` options needed to be configured in the `[global]` section of the configuration file. I think this requirement has been removed in the latests releases.

So, I've just tested the following config:

```
# cat /etc/pgbackrest.conf 
[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
start-fast=y
delta=y

[stanza1]
pg1-path=/var/lib/pgsql/13/stanza1
pg1-port=5432

[stanza2]
repo1-path=/var/lib/stanza2
pg1-path=/var/lib/pgsql/13/stanza2
pg1-port=5433
```

Redirecting the 2nd stanza in another repo. And it seems to work. I then think it should be possible to do the same for `repo1-s3-*` options. But it would be better to test to confirm.

Historically, I would have suggested to use a separated configuration file (1 for each repo). And it seems a bit easier/cleaner to separate things rather than to have a big (and confusing) configuration file.

**Comment by dwsteele** [comment]
Yes, you can move the stanzas one at a time and reconfigure each stanza as @pgstef has shown. It'll be a bit repetitive during the migration but it will work. Once done you can move all the repo configuration back to global.

Remember, each stanza has a directory in archive and in backup. Make sure you copy both for each stanza.
