### ISSUE TITLE
Can we make a Backup from a Delayed standby with recovery_min_apply_delay set to 4hours work ?

### ISSUE THREAD

**Issue by avinashvallarapu** [pgbackrest/pgbackrest#1222]
pgBackRest version: Latest

PostgreSQL version: 12.4

Operating system/version - Backups to S3 from Standby/Replica

Did you install pgBackRest from source or from a package? RPM

Describe the issue:

Requirement is to push backups from Standby that is delayed by 4 hours. It is failing with the following message that the standby is waiting for the replay until the latest. Is there an workaround or a way around for this today ?  

2020-10-29 16:55:32.551 P00   INFO: backup start archive = 000000010000000000000032, lsn = 0/32000028
2020-10-29 16:55:32.551 P00   INFO: wait for replay on the standby to reach 0/32000028
ERROR: [082]: timeout before standby replayed to 0/32000028 - only reached 0/2F011CB8
2020-10-29 16:55:33.856 P00   INFO: backup command end: aborted with exception [082]

**Comment by pgstef** [comment]
Hi,

Since the backup control sessions are executed on the primary server and the archives are pushed from the primary too, I don't think it's possible to have a backup on delayed standbys at this time. 

Given those restrictions, I don't really see how we could support `recovery_min_apply_delay` for now.

**Comment by sfrost** [comment]
You could potentially raise those timeouts, but, of course, then the backup wouldn't really start going until after recovery_min_apply_delay amount of time had passed. and all of the WAL generated during that time would be part of the backup which would mean it'd all have to be replayed when performing a restore which wouldn't be ideal.

We don't currently support replia-only backups, as a primary backup is better for a few different reasons (not everything going through the WAL), though this seems like it's an interesting use-case that might be worth the trade-off.

**Comment by dwsteele** [comment]
You would need to set `archive-timeout` and `db-timeout` > 4 hours, e.g. `18000`. It might work, but as Stephen says you'd have a lot of extra WAL replay during recovery.

**Comment by avinashvallarapu** [comment]
Sure, may be if there is a way to ignore the check of last replayed WAL on standby, that would be great. Especially, if the user decided to let pgBackRest apply the required WAL segments while  restore/recovery. 

Example, 

In backup.c, may be we could add a condition to ignore executing the following, if there was a parameter explicitly set. 

avoid_standby_replay_lsn_check = y
then do not execute the following ...
dbReplayWait(backupData->dbStandby, result.lsn, (TimeMSec)(cfgOptionDbl(cfgOptArchiveTimeout) * MSEC_PER_SEC));

But, i would leave this decision to you all.

**Comment by bradnicholson** [comment]
What is the actual driver for wanting to backup from a delayed standby?  The only one I can think of can be satisfied via PITR (ensuring you can restore from application/user level errors incorrectly modify data)

**Comment by sfrost** [comment]
I don't see how that would reasonably work since that WAL (and all the WAL before it) needs to be applied before we can start copying the files from the replica.

One simple thing we might consider doing is to have pgbackrest check if the replica has recovery_min_apply_delay set and, if so, don't consider that replica to be one which we can use for backup and check to see if there is another replica configured that doesn't have that set.  Possibly we could check if the value of recovery_min_apply_delay is less than our timeout, in which case it'd still work to use such a replica if you really wanted to....
