### ISSUE TITLE
How to use pgBackRest with S3 Glacier

### ISSUE THREAD

**Issue by asoltesz** [pgbackrest/pgbackrest#1230]
I didn't find info on this one, so I am asking here:

I would like to keep 6 months of my database backups with 1 full backup every month and WALs in between.

I would like to move older-than-1-month (older than the last full backup) backup files to S3 Glacier because it is much cheaper to keep them there.

Moving to Glacier means that the transfer would remove the files from the "hot" S3 bucket and transfer them to the "cold" (glacier) bucket.

Is this possible with pgBackRest-managed S3 repos? 

Will I still be able to restore the latest full backup from the "hot" S3 bucket? 

Are there files that I always have to keep in the "hot" repo?

**Comment by pgstef** [comment]
Hi,

Today, it isn't possible to transfer backups or archives from a repo to another repo using pgBR commands.

Multi-repository support is a work in progress, so this feature could come in the future but there's no defined time for it.

Doing what you describe manually could perhaps be possible but would require hacking the manifest files content, since we rely on those files to know what's in the repo. Not so simple, though.

**Comment by asoltesz** [comment]
Thanks, I will exclude this from my plans for now and only calculate with "hot" S3 storage.
