### ISSUE TITLE
Can't run pgbackrest successfuly

### ISSUE THREAD

**Issue by antkamidiv** [pgbackrest/pgbackrest#1231]
Hi!
Can't run pgbackrest successfuly. 
There is Postgres Pro Standard 11.9 installed on my CentOS 7.8 server. 
/etc/pgbackrest.conf:
[cmc]
pg1-path=/var/lib/pgpro/std-11/data
pg1-socket-path=/tmp

[global]
repo1-path=/archive/pgbackrest
repo1-retention-full=2
repo1-retention-diff=3
start-fast=y

[global:archive-push]
compress-level=3

I've tried all version from 2.15 to 2.30. 
Error is always the same when I run the command "sudo -u postgres pgbackrest --stanza=cmc --log-level-console=error stanza-create": 

2020-11-17 08:10:12.492 P00   INFO: stanza-create command begin 2.15: --pg1-path=/var/lib/pgpro/std-11/data --pg1-socket-path=/tmp --repo1-path=/archive/pgbackrest --stanza=cmc
2020-11-17 08:10:12.670 P00  ERROR: [046]: unexpected control version = 1347421260 and catalog version = 201809181
                                        HINT: is this version of PostgreSQL supported?
2020-11-17 08:10:12.672 P00   INFO: stanza-create command end: aborted with exception [046]

It's Postgresql version 11.9 that are supported. How to fix this? I have no idea.

Thanks in advance!

**Comment by pgstef** [comment]
Hi,

You mention using PostgresPro version, not community PostgreSQL. This error shows that the PostgresPro version isn't following the same control/catalog version as the community version of PostgreSQL. 

And since we support the community version, it seems that it won't work with PostgresPro version.

**Comment by antkamidiv** [comment]
Thanks for your reply. Catalog versioning is about how data and metadata store and organize in pg cluster. I'm right? So, pgbackrest can't manage this, cause it uses another way to operate the data for a reserving.

**Comment by dwsteele** [comment]
The control number is pretty different from what you might see in community Postgres, which for PG11 would be `1100`. This makes me think that the format of pg_control is slightly different (but I can't check since Postgres Pro is not open source).

We have been considering a feature that would allow the PG version to be forced, but I doubt that would work if the file formats have been changed.

**Comment by antkamidiv** [comment]
> 
> 
> The control number is pretty different from what you might see in community Postgres, which for PG11 would be `1100`. This makes me think that the format of pg_control is slightly different (but I can't check since Postgres Pro is not open source).
> 
> We have been considering a feature that would allow the PG version to be forced, but I doubt that would work if the file formats have been changed.

Thanks for the reply. It'd be great to force an ignorance of version, cause there is a non-zero chance to backup successfuly despite of different version numbers.

**Comment by dwsteele** [comment]
Well, the version number is pretty important to the behavior of pgBackRest so it would need to be set correctly. Even then, it's hard to say if the backup would be correct or not. If they have changed pg_control what else have they changed?
