### ISSUE TITLE
Documentation: can PgBackRest backup/restore multiple remote server/cluster?

### ISSUE THREAD

**Issue by 2019-05-10** [pgbackrest/pgbackrest#1240]
I read through a lot of documentation, but it never seems to be explictly stated anywhere:
it PgBackRest able to backup/restore multiple separate remote servers?

We have currently two separate virtual machines each hosting a Postgres installation with several databases.
I am looking for solution to create backups/restore for both VMs to/from a single repository.

It would be great if this was answered one way or another in the documentation ("Features" section probably), and if possible if the user guide would include examples.

**Comment by pgstef** [comment]
Hi,

That's what is called [Dedicated Repository Host](https://pgbackrest.org/user-guide.html#repo-host) in the user guides.

You might create a dedicated server and define 2 different stanzas in the configuration. Then you can run the backup commands for each stanza from that server. You won't be able to backup all the stanzas in one command but you may run multiple backup commands in // (1 per stanza defined).

In this scenario, the restore commands have to be executed on the PG hosts themselves.
I've got an [old blog post](https://pgstef.github.io/2018/01/04/introduction_to_pgbackrest.html) illustrating it. Even if it's based on an old pgBR version, I think it would still work with the current one.

I hope it's what you're looking for.
Kind regards,

**Comment by 2019-05-10** [comment]
Hi,

I've read that section, too, but it wasn't obvious to me that it could be used for more than one .. uhm.. pg-host.
Could the documentation  extend to inlcude a configuration for more than one and that also be mentioned?

This "repo1" and "pg1" is also confusing, do they mean there can beo more than one in each section? Or do the "pgX"  count up to "pg2" for the second stanza and so on?

Thanks

**Comment by pgstef** [comment]
Well, you have to understand the meaning of "stanza". 

> A stanza is the configuration for a PostgreSQL database cluster that defines where it is located, how it will be backed up, archiving options, etc. Most db servers will only have one PostgreSQL database cluster and therefore one stanza, whereas backup servers will have a stanza for every database cluster that needs to be backed up.

I don't think we'd need a doc example with multiple stanza since it's clearly stated in the stanza definition.

It will then depend on your need. Do you need to backup 2 different PostgreSQL primary cluster ? If yes, you'll have to define 2 stanza with `pg1-*` option in each. If you need to backup 1 PostgreSQL primary cluster and its standby server, you'll define 1 stanza with `pg1-*` being your primary cluster and `pg2-*` being your standby server.

There is an example of when using `pg1` and `pg2` in the [Backup from a Standby](https://pgbackrest.org/user-guide.html#standby-backup) section.

Then, the repo configuration (which is usually defined in the `[global]` section) is the place where your backups and archives will be stored. The repo configuration (`repo1-*` options) can point to a local directory or to any supported types (posix, cifs, s3, azure).

In the future, we'll have multi-repo support. For example, pushing the archives to 2 different repo locations in one command. That's why there's the `repo1`...`repoX` option. Currently, only `repo1` should be used.

Hope it help you understand the meaning of a stanza and when using pg1/pg2.

Kind regards

**Comment by pgstef** [comment]
Hi,

Here's an example on how to setup a backup server with 1 PostgreSQL cluster (1 primary, 2 streaming replication standbys): https://pgstef.github.io/2020/11/21/combining_pgbackrest_dedicated_repository_host_and_streaming_replication.html.

There you'll see the example of when `pg2` (and `pg3`) is used. To add other PostgreSQL clusters, you simply have to create multiple stanzas.

Hope this helps.
Kind regards

**Comment by dwsteele** [comment]
Multiple stanza are also mentioned in: https://pgbackrest.org/user-guide.html#quickstart/create-repository

`Most db servers will only have one Postgres database cluster and therefore one stanza, whereas backup servers will have a stanza for every database cluster that needs to be backed up.`

It would be a good enhancement to the docs to have real examples of multiple stanzas, but that's a bigger challenge than it might appear since our docs are code that must actually work. That means new pg hosts, backups, etc., and more time to render the docs.
