### ISSUE TITLE
pgbackrest backup error

### ISSUE THREAD

**Issue by yangvipguang** [pgbackrest/pgbackrest#1260]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.31.1

2. PostgreSQL version: 12.1

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:  centos 7

4. Did you install pgBackRest from source or from a package?
yes
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
both stanza-create and  check  are ok。
But backup will result error  like blow
![image](https://user-images.githubusercontent.com/11416887/102454241-aac19a80-4078-11eb-869e-70b4470a3404.png)

Tips：
I indeed  have the link：
![image](https://user-images.githubusercontent.com/11416887/102454379-e197b080-4078-11eb-8e46-83ffcf94ddb9.png)
Does the above question have anything to do with this？

**Comment by dwsteele** [comment]
Tablespaces should not be located inside the PG data directory. When you created the tablespace you got this warning `WARNING:  42P17: tablespace location should not be inside the data directory`.

Ignoring this warning means backup tools (including `pg_basebackup`) will not work correctly. Rather than produce an invalid backup, pgBackRest throws a hard error.

You'll need to move the tablespace outside the PG data directory, see http://www.databasesoup.com/2013/11/moving-tablespaces.html.

**Comment by yangvipguang** [comment]
@dwsteele   thx for your replying.
