### ISSUE TITLE
Archiving/replicating WALs + backups to S3 from a local repo [question]

### ISSUE THREAD

**Issue by asoltesz** [pgbackrest/pgbackrest#1268]
My problems / challenges are the following:

Currently, I am using a remote S3 pgBackrest repo in my PGO setup (S3-only, no local repo). As it is, I don't have a solution for the eventuality when the connection to the S3 storage breakes down and the uncompressed WAL files fill up my local filesystem. (using Kubernetes hostpath volumes, no quotas/limits are possible and I cannot use a separate partition either)  

I am considering switching to a local-only pgBackrest repo because that would at least mitigate the WAL congestion issue (because WALs get compressed when stored into the local pgBackrest repo, in my case to 1/1000 of the size for most WAL files). 

However, I still need to move the WALs + backups to the remote S3 location somehow, since the local pgBackrest repo is not on durable storage.

The User Guide doesn't seem to account for such a scenario, so my questions for the possible solution elements:

**Is it possible to configure pgBackrest to archive to S3 via the local repo like this: ?**

- Immediately drop the WAL segment after it was pushed successfully into a local repo, even if the S3 bucket is unavailable.
- When the S3 bucket becomes available, pgBackrest pushes the WALs from the local repo to S3 (automatic syncing)

**Is it possible to replicate a local repo to S3 with a third party tool?**

In case point 1) is not possible with pgBackrest:

- I configure pgBackrest to use only a local repo
- Sync the WAL + backup files periodically to S3 with a third-party tool
- After a crash, I recover directly from S3

Is there any structural difference between the S3 and local repos that would make the above fail?

**Is it possible to use the S3 repo as the "cold storage" extension of the local repo?**

- I take backups into the local storage.
- pgBackrest automatically replicates the backup to S3 in the background 
- Local repo has stricter/shorter retention than S3, e.g.: everything older than the latest full backup gets dropped from local
- Apply separate retention rules to the S3 repo when backups are replicated from local to S3 (so that S3 contains backups for 6 months, for example).

Any insight is appreciated.

------
1. pgBackRest version: 2.29

2. PostgreSQL version: 12.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 

CentOS 7 (in container)

4. Did you install pgBackRest from source or from a package?

Unsure - prepackaged into the CrunchyData PGO Container

5. Please attach the following as applicable ...

N/A

7. Describe the issue: above

**Comment by pgstef** [comment]
Hi,

Currently, if you often have issues with your S3 repo, you could perhaps use the [archive-push-queue-max](https://pgbackrest.org/configuration.html#section-archive/option-archive-push-queue-max) option, which will allow PG to drop the wals retained for archiving when the queue length is too high. This will break your PITR capability but will avoid your PG to crash due to lack of disk space.

The content of an S3 repo and a local repo is usually the same. It's just the way to reach the repo that changes, not its content.

Perhaps in the future with the multi-repo feature, we'll have the ability to transfer backups/archives from one repo to another but currently, that's not possible afaik.

You can imagine having 2 different configuration files: 1 to take backups/archives, 1 to recover. Pointing on different repos. But then, how to sync the repos is up to you. If you're creative enough, I think you could use [aws-cli](https://docs.aws.amazon.com/cli/latest/reference/s3/) to sync the local repo with your s3 bucket.

Unfortunately, at this point, I don't think it is possible to achieve what you expect only with pgBackRest.

Kind regards,

**Comment by asoltesz** [comment]
@pgstef Many thanks for the information.

I think I will go for "archive-push-queue-max" for now, since that seems the easiest to implement short term. 

Loosing PITR capability for certain periods is absolutely preferred to database outage. Mid-term, I will have to build some kind of WAL-continuity monitoring anyways (possibly with PGO's monitoring solution, it may have something for this in its pgBackrest metrics).
