### ISSUE TITLE
Monitoring when the limit is reached for --archive-push-queue-max

### ISSUE THREAD

**Issue by kikijolicoeur** [pgbackrest/pgbackrest#1296]
Hello.
1. pgBackRest version: 2.31
2. PostgreSQL version: 12.5
3. Debian 10.6 (Buster)
4. Did you install pgBackRest from source or from a package? : package

I use archive-async=y,  archive-push-queue-max=10GB 
How can I monitor if pgbackrest reaches the archive-push-queue-max. 
I read the documentation 
"pgBackRest will notify PostgreSQL that the WAL was successfully archived, then DROP IT.
A warning will be output to the Postgres log."
But I can't monitor the Postgresql log. 
Is there a lock file written in lock-path or a special information given by the info command or check command ?

Thanks you for pgbackrest !!

Best regards

Christian

**Comment by pgstef** [comment]
Hi,

Currently, the `archive-push` command returns a [warning](https://github.com/pgbackrest/pgbackrest/blob/d29855bd0bf8b957fa8c06445d22e425c443a704/src/command/archive/push/push.c#L38) and this warning goes to PG logs since PG triggers it in the `archive_command`.

AFAIK, there isn't any built-in solution (yet) to verify that you don't have any missing WAL archive in the repo (whatever the reason could be). There are some external possibilities though.

Kind regards

**Comment by kikijolicoeur** [comment]
Thank you for your prompt response. I'm going to test check_pgbackrest.
Best regards
