### ISSUE TITLE
Scheduled WAL Backups Without archive_command

### ISSUE THREAD

**Issue by gray-al** [pgbackrest/pgbackrest#1310]
I have a question about an alternative way of doing WAL backups through pgbackrest.

1. pgBackRest version:
pgBackRest 2.31

2. PostgreSQL version:
PG 10/11/12

3. Operating system/version:
RHEL 7/8

4. Did you install pgBackRest from source or from a package?
Installed from package

5. Please attach the following as applicable:
    - N/A - I can upload if they'd be helpful

7. Describe the issue:
 We recently started using Rubrik for our backup software provider.  For Postgres, Rubrik uses an immutable snapshot backup strategy where the backup mount is only writable and available when the backup is being taken.  This means the backup process will roughly be:  run the backup script, unlock the filesystem, we take our pgbackrest backup using the rubrik filesystem as a destination, and then end the backup which locks the filesystem.  After this Rubrik takes a snapshot of that filesystem with the new backup files.  
 This works fine with full or incremental backups because they're scheduled relatively infrequent compared to WAL file creation. We're having trouble with pgbackrest and continuous WAL archiving.  We first tried setting the PG archive_command parameter to empty but this breaks pgbackrest's full/incremental backups.  Having archive_command unlock the filesystem, copy the wal file, and end the backup is going to be too much Rubrik overhead to do for every single log that gets written.  Instead we're thinking we could do a scheduled log backup: have archive_command do nothing and periodically run a log backup script that does a `pgbackrest ... archive-push` for each available WAL.  
 After reading Issue 759 and some of the warnings about disabling checks, risk of losing WALs, etc.. I'm hesitant to get too creative to get this working.  

 If we set archive_command to something that does nothing but meets the "must contain pgbackrest" requirement (ex: `archive_command='#pgbackrest'`) do we run the risk of not having pgbackrest's checks or other functionality?

 In a sandbox database I've confirmed that I'm able to get successful full backups and successful archive-push backups when using `archive_command='#pgbackrest'`. With this approach I could have an hourly job unlock my Rubrik filesystem, get a list of what logs are available for backup, run archive-push backups for each log, and then finish the backup and put the filesystem back in read only mode.  This would help avoid overwhelming rubrik with too many snapshots.  This hourly WAL backup would be in addition to a scheduled daily full. 
 Since this isn't a real or especially busy environment I'm looking for some feedback if I'm jeopardizing my backup quality/consistency using pgbackrest this way. 
 
I'm also interested if there are other suggestions for WAL backups through pgbackrest that aren't immediately kicked off via archive_command.

**Comment by pgstef** [comment]
Hi,

The question here is what do you really want to achieve and then, ask yourself if you use the good tool for it.

To achieve point in time recovery, PG relies on [continuous archiving](https://www.postgresql.org/docs/current/continuous-archiving.html). This can be achieved with the `archive_command` or with `pg_receivewal` (which we don't support currently).

Now, the question is what are your recovery point and time objectives (RPO/RTO). You'll need the WAL segments generated during the backup (so a working `archive_command`) at least. Between your backups, if PG can't push the archives, it will have to keep it in its `pg_wal` directory. Do you know what happens if the `pg_wal` directory gets too big and fills up your disk space? Well,... PG will panic and stop. So you definitively don't want to do that.

Since `archive_command` change only requires a PG config reload, I would suggest you to set it to '/bin/true' between your backups. 

The steps would be:
- set a correct `archive_command`
- run check command to verify it's working
- take your backup
- set `archive_command` to  '/bin/true'

And then, take 1 full per day, and as many incr (or diff) in between. That should work. Even if it's not really a "supported" or "advised" use-case. Be aware that you won't be able to recover data to any point "between" your backups since you break the PITR capability.

The risk of missing 1 wal file is pretty high with your approach. If you really want PITR capability, you should have a backup storage reachable all the time ;-)

**Comment by dwsteele** [comment]
Your biggest issue is you are either going to lose WAL or have constant errors in your postgres log. The simplest thing would be to set:
```
archive_command=/bin/false
```
until the volume is available. Then set archive_command correctly and do the backup and hope async archiving can catch up before the backup fails. In this case you'll see a lot of errors in the postgres log due to archive command "failing".

If you do something creative like this you'll need to monitor and test to make sure your solution is working.

But I tend to agree with @pgstef. This might be the time to ask yourself if Rubrik is the right storage choice when it doesn't seem to make any provision for continuous archiving. The more code and procedures you add on top of pgbackrest the more likely you are to end up with a nightmare restore scenario.
