### ISSUE TITLE
pgbackrest lock path is created with drwxr-x---, which effectively bans multiple users access

### ISSUE THREAD

**Issue by kozlowski9ld** [pgbackrest/pgbackrest#1312]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.31

2. PostgreSQL version:
9.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu 16, Ubuntu 18 (no problem on Centos 7)

4. Did you install pgBackRest from source or from a package?
package

7. Describe the issue:
On a freshly installed pgbackrest, I run `pgbackrest info` as user1. A side effect of this is that  '/tmp/pgbackrest' directory is created; the access rights there are `drwxr-x---`. When I later try to run `pgbackrest backup` as user2, I'm getting:

```
ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/starfish-backup.lock': Permission denied
HINT: does the user running pgBackRest have permissions on the '/tmp/pgbackrest/starfish-backup.lock' file?
```

When I run `pgbackrest info` as user2 it does not fail, however it shows:
```
status: error (no valid backups, backup/expire running)
```
When executed as user1, the message is:
```
status: error (no valid backups)
```

Setting '/tmp/pgbackrest' access rights manually to `drwxrwxrwx` fixes the problem.

**Comment by pgstef** [comment]
Hi,

I don't really see why this would be different on CentOS, since the [rpm](https://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob;f=rpm/redhat/master/common/pgbackrest/master/pgbackrest.spec;h=d633db51ce0e95fdb969ba4c5ab1f370eaded683;hb=HEAD) doesn't create the lock path. Debian [packages](https://salsa.debian.org/postgresql/pgbackrest/-/blob/master/debian/pgbackrest.dirs) doesn't seem to create it either.

`STORAGE_MODE_PATH_DEFAULT` is indeed **750**.

Adding `.mode = 0777` to [storagePathCreateP](https://github.com/pgbackrest/pgbackrest/blob/master/src/common/lock.c#L84) should probably fix your issue even though this path might be created at several places I think (like the stop file,...).

Maybe the others will have some concerns about security to open this path to world. I admit I'd prefer leave it like that if you have a manual fix for your specific use-case (using multiple system users doesn't really seem widely spread).

But I'm curious now. What's your actual use-case/setup for this multi-users env?

**Comment by kozlowski9ld** [comment]
I have found the problem in the testing env, but I can see the following use-case too:
`pgbackrest` itself may be running on a single account. But there may be several admins, who run `pgbackrest info` diagnostics. Since the default lock-path is in `/tmp`, it may get cleaned up, and then whoever runs `pgbackrest info` first sets the access rights to the path.
It's rather easy to get it worked around I admit - but what was happening was not obvious at first.

**Comment by gozdal** [comment]
Maybe the `umask` differs? I wonder if `/tmp/pgbackrest` should be the default place to create lock files. 
If it is a single lock file and nothing more maybe it should be directly under `/tmp`? This would avoid the problem of creating a directory with some unknown permissions.
Another option would be to use `/run/lock` although I am not sure if it is available in all OSes.

**Comment by pgstef** [comment]
[lock path](https://pgbackrest.org/configuration.html#section-general/option-lock-path) is indeed `/tmp/pgbackrest` by default but you can change it pretty easily.

I could try to setup some poc changing the default path mode to 777 but I think it would be reasonable to adjust the initial use-case to create a shared directory for allowed users and then set the lock-path option.

**Comment by dwsteele** [comment]
The user is welcome to pre-create and/or adjust the location of the path. If the path already exists we won't remove or recreate.

> If it is a single lock file and nothing more maybe it should be directly under /tmp?

There are a number of possible lock/stop files so we feel a directory is most appropriate.

> pgbackrest itself may be running on a single account. But there may be several admins, who run pgbackrest info diagnostics. 

In this case the admin should be in the same group as the pgbackrest user. The info (and restore and archive-get) command does not take a lock so there's no need for that user to have write permissions.

**Comment by kozlowski9ld** [comment]
The info certainly creates the lock-path directory.
Isn't it by the means of taking the lock?
https://github.com/pgbackrest/pgbackrest/blob/c2c702c09d4ac3ea858d0450695a789c999b99da/src/command/info/info.c#L481

**Comment by pgstef** [comment]
Any command needing a lock or a stop file could create the path **if not there yet**. First triggered, first to create it. 
That's certainly why David mentioned that the user is welcome to pre-create and/or adjust the location using the `lock-path` option.

**Comment by kozlowski9ld** [comment]
Maybe the info should be checking for the existence of the lock-dir, and if not there, return "no backup" without taking the lock?

**Comment by pgstef** [comment]
> Maybe the info should be checking for the existence of the lock-dir, and if not there, return "no backup" without taking the lock?

That assumption would not be accurate at all. Furthermore, the only way of checking if a backup is running locally is to try to acquire the lock. That's why this line exists. 

> The info is an operation which is aimed at reading things only, so the less side effects it has, the better.

I respectfully disagree. It is aimed at giving information about the backups and archives. And the information about running processes is very useful, even more when you use the info command for monitoring purposes.

I don't find invasive to simply create a lock file in a temp directory. Even more if you can change its location easily and create it yourself with permissions you want. Don't forget that the user running the info command will need complete read permissions on your backups and archives. Even if your repo is encrypted, it won't be for the user running the info command. And that's much more invasive than creating a simple lock file...

**Comment by dwsteele** [comment]
> Maybe the info should be checking for the existence of the lock-dir, and if not there, return "no backup" without taking the lock?

If the directory was missing you could assume there is no backup running, but it would seem to have limited utility since this dir will be created early on and have a long lifetime. It would be better to check the lock file and it if is missing don't attempt the lock.

Overall I agree that checking locks in the temp dir is OK for the info command to do. The info command *does not write* to the repo and that's the important part, I believe.

**Comment by kozlowski9ld** [comment]
There's another scenario of a similar nature that I've run into: if an admin tries to manually run `pgbackrest expire` from his account, he might not be able to do that due to access rights on `backup.info` file, which has `-rw-r-----`, if it was created from a different account.
There are two "maybes" which come to my mind:
- maybe the access rights could be loosened, so the users from the same group could have write access to paths like `backup.info` file or the lock path
- it seems that it may be particularly harmful, if some `pgbackrest` command is run from the `root` account - so maybe `pgbackrest` should be preventing that and always fail in such case with no side effects at all.

**Comment by glimpsi** [comment]
From the pgbackrest documentation i see that neutral-umask=y is the default and means that "The lock and log directories set the directory and file mode to 0770 and 0660 respectively."  However, the lock directory /tmp/pgbackrest in our environment is set to 750 instead of 770 by pgbackrest, although we are running with the default neutral-umask=y

**Comment by dwsteele** [comment]
I think it is OK to require users who prefer special permissions to create the lock directory in advance. Loosening permissions can have unintended consequences.
