### ISSUE TITLE
expire - [oldest] archives not deleted

### ISSUE THREAD

**Issue by devops93** [pgbackrest/pgbackrest#1349]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.32

2. PostgreSQL version: EDB Advanced Server 10.16

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Debian 9 - Stretch

4. Did you install pgBackRest from source or from a package? : packages

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

The archive files are not deleted with the expire command (for the requested full backup and oldest archives). So I have to delete them **manually** to get more free space on the disk.
After the expire command all the archives before 000000010000083300000047 had to be deleted (start archive of 20210228-003001F remaining full backup).

I also noticed some root owner log files ! (pgadmin user account normaly).

[dry-run.txt](https://github.com/pgbackrest/pgbackrest/files/6211226/dry-run.txt)
[kargo10-expire.log](https://github.com/pgbackrest/pgbackrest/files/6211227/kargo10-expire.log)
[ls-archives.txt](https://github.com/pgbackrest/pgbackrest/files/6211228/ls-archives.txt)
[ls-backup.txt](https://github.com/pgbackrest/pgbackrest/files/6211229/ls-backup.txt)
[pgbackrest.txt](https://github.com/pgbackrest/pgbackrest/files/6211255/pgbackrest.txt)

**Comment by cmwshang** [comment]
Your repo retentions are:
repo1-retention-full-type=count
repo1-retention-full=6

In the documentation, https://pgbackrest.org/command.html#command-expire 

> When run by the user, expiration will occur as defined by the retention settings for each configured repository. Expiration can also be limited by the user to a specific backup set with the --set option. It should be noted that the archive retention schedule will be checked and performed any time the expire command is run.

And under the Expire Command --set option:

> WARNING Use this option with extreme caution — it will permanently remove all backups and archives not required to make a backup consistent from the pgBackRest repository for the specified backup set. This process may negate the ability to perform PITR. If --repo-retention-full and/or --repo-retention-archive options are configured, then it is recommended that you override these options by setting their values to the maximum while performing adhoc expiration.

And then in the  Archive Retention Option section under the Expire Command:

> 6.4.11 Archive Retention Option (--repo-retention-archive)
Number of backups worth of continuous WAL to retain.
NOTE: WAL segments required to make a backup consistent are always retained until the backup is expired regardless of how this option is configured.
If this value is not set and repo-retention-full-type is count (default), then the archive to expire will default to the repo-retention-full (or repo-retention-diff) value corresponding to the repo-retention-archive-type if set to full (or diff). This will ensure that WAL is only expired for backups that are already expired. If repo-retention-full-type is time, then this value will default to removing archives that are earlier than the oldest full backup retained after satisfying the repo-retention-full setting.

However, I admit that the Expire Command --set option description could be a little clearer with regard to the retention options so I'll see if we can come up with some better wording.

So what is happening in your case is that --repo1-retention-archive is being set (correctly) to --repo1-retention-full, which is 6. So you have to have 6 backups of type Full before archive expiration will occur which is why you're not seeing any archives get expired because you're forcing an adhoc expiration when you have expiration rules set up. If you only want to keep 4 full backups, you would not have to keep forcing an adhoc expiration - just change your retention settings (which you can do on the command line rather than force an adhoc expiration) so that --repo1-retention-full=4 and that backup set 20210228-003001F would have expired automatically (along with the early archives) when backup 20210324-220857F was created or if you ran `expire --repo1-retention-full=4` instead of the adhoc expire. Or you can use time-based retention to, say, keep all Full backups that are a month old or less, see section "6.4.15 Full Retention Type Option (--repo-retention-full-type)" under the command reference for more details on that.

**Comment by devops93** [comment]
Hi,

Thanks for the tip : expire --repo1-retention-full=4
I have the expected result.

I thought it was not useful to keep WALs whithout the associated backups

Bye

**Comment by dwsteele** [comment]
> I thought it was not useful to keep WALs whithout the associated backups

It may be useful if you have replicas that require older WAL to complete replay. That's why we don't start expiring WAL until retention is met, so there is a healthy amount of WAL for replicas.

**Comment by devops93** [comment]
Thanks David
