### ISSUE TITLE
Regression in check command wrt. multi-repository changes

### ISSUE THREAD

**Issue by anse1** [pgbackrest/pgbackrest#1366]
Hi,

one of our customers reported a regression wrt. the check command on a standby-only-stanza: Previously, the check command was successful in this case and after upgrading to 2.32 it reports "ERROR: [027]: primary database not found".

It seems to me that it is related to commit f32eb9b94ec, whose message indicates that this behavioral change would be unintended.

Details how to reproduce below.

regards,
Andreas

Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.32
2. PostgreSQL version: 10
3. Operating system/version: any
4. Did you install pgBackRest from source or from a package?
```
$ apt-cache policy pgbackrest
pgbackrest:
  Installed: 2.10-1
  Candidate: 2.32-1.pgdg100+1  <--- problematic upgrade
```
5. Please attach the following as applicable:

```
[global]
repo1-path=/var/lib/pgbackrest
process-max=4
compress-level=6
resume=n
repo1-retention-full=2
[standby10]
pg1-path=/var/lib/postgresql/10/standby
pg1-port=5436
```

7. Describe the issue:

```
$ sudo -u postgres pgbackrest --stanza=standby10 --log-level-console=info check
2021-04-12 18:44:47.996 P00   INFO: check command begin 2.10: --compress-level=6 --log-level-console=info --pg1-path=/var/lib/postgresql/10/standby --pg1-port=5436 --repo1-path=/var/lib/pgbackrest --stanza=standby10
2021-04-12 18:44:48.839 P00   INFO: switch wal cannot be performed on the standby, all other checks passed successfully
2021-04-12 18:44:48.841 P00   INFO: check command end: completed successfully (847ms)
$ echo $?
0
$ sudo apt-get install pgbackrest=2.32-1.pgdg100+1
Unpacking pgbackrest (2.32-1.pgdg100+1) over (2.10-1) ...
$ sudo -u postgres pgbackrest --stanza=standby10 --log-level-console=info check
2021-04-12 18:45:31.261 P00   INFO: check command begin 2.32: --exec-id=8166-e596c600 --log-level-console=info --pg1-path=/var/lib/postgresql/10/standby --pg1-port=5436 --repo1-path=/var/lib/pgbackrest --stanza=standby10
ERROR: [027]: primary database not found
       HINT: check indexed pg-path/pg-host configurations
2021-04-12 18:45:31.868 P00   INFO: check command end: aborted with exception [027]
 -> 27
```

**Comment by cmwshang** [comment]
The check command has been enhanced since 2.10. What is happening here is that you have a repo on your standby and the configuration is not indicating where the primary is that the repo needs. We do not recommend having your repository on your standby, however, you should be able to resolve this by adding pg2-* options so that the repo knows where the primary is located, which is a requirement for backups.

**Comment by anse1** [comment]
I suppose their use case is that backups into this machine's
repository are to be taken only after a promote while the check
commands are monitored regardless of the instance's role.  It's the
behavioral change of the check command that is not documented wrt. the
release notes that caught them by surprise.

If you say this stricter checking - while undocumented - is an
intended change, I will pass it on that they either need to change
their configuration or stop invoking the check command on standby
servers along with the pgbackrest upgrade.

thanks,
Andreas

**Comment by pgstef** [comment]
IMHO they shouldn't use the check command for monitoring purpose anyway. On a primary server, this will force a new archive to be generated. There's no point at invoking it on a standby server alone since, as @cmwshang mentioned, the backup command wouldn't work without adding the primary location.

So the bigger question is more about what they are trying to achieve using the check command and replace that with a more accurate solution...

**Comment by cmwshang** [comment]
The issue that the check command caught was valid and is the purpose of the check command. As far as the documentation, we do not detail every item that the check command checks, just its purpose, and we currently have no plans to implement that at this time, therefore, we are closing this issue.
