### ISSUE TITLE
Is it possible restore from pgbackrest repo filesystem backup

### ISSUE THREAD

**Issue by fatihmtekin** [pgbackrest/pgbackrest#1378]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.30

2. PostgreSQL version:12.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL 7.7 2 nodes patroni cluster( 1 primary 1 standby), pgbackrest repository host = standby node

4. Did you install pgBackRest from source or from a package? from package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the PostgreSQL log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue: How can I restore from pgbackrest repository's filesystem backup? For example, my pgbackrest full backup retention is 7 days. Also, I am backing up pgbackrest repository files ( all archive, all backup files) to another backup unit. If I need a restore that is older than 7 days, how do I do this with the pgbackrest repository files restored from the backup unit? Is it possible? 

Thanks in advance.

**Comment by pgstef** [comment]
Hi,

First of all, I'd like to react to **pgbackrest repository host = standby node**. It's not supposed to work like that and furthermore, it is very **not recommended** to store your backups locally on db hosts.

That being said, regarding your question, I would say it completely depends on your filesystem backup method.
If you can restore your snapshot to another local directory, then use a separate configuration file to point to that repo and use it to restore an old backup. Using 2 repositories inside the same config file is possible since 2.33 with the multi-repo feature but as soon as you'd add `repo2*` options, your primary server would send WAL archives to that second repo too. That's why I would recommend to create a new configuration file to point to the restored snapshot.

But as said, again, that's not really related to pgBackRest itself but more to your filesystem backup method/strategy.

**Comment by dwsteele** [comment]
If you use multi-repo functionality to bring in the recovered backup repo, I would recommend configuring it only on the command line (e.g. `--repo2-path=/restored-repo`) when doing the restore. That way `archive-get` will know which settings to use (since `restore` writes `restore_command`, but `archive-push` will read from the standard config file and not try and push to the added repo.

The advantage of using multi-repo in this scenario is that you'll have access to the newer WAL in repo1 so if the WALs overlap between `repo1` (your current repo) and `repo2` (the one you recovered from filesystem backup) then you be able to play forward to the current time from a backup in `repo2`.

**Comment by fatihmtekin** [comment]
Actually, I meant that my filesystem backup method is sent all repo files (archive and backup directories) via scp command to the destination server, then gunzip all files and start the database. I tried that method, but I had a "could not locate a valid checkpoint record" error.

Thanks a lot.

**Comment by pgstef** [comment]
> Actually, I meant that my filesystem backup method is sent all repo files (archive and backup directories) via scp command to the destination server, then gunzip all files and start the database. I tried that method, but I had a "could not locate a valid checkpoint record" error.

That's because pgBackRest updates some restored files (e.g. configure `restore_command` and recovery targets...) to allow PG a proper recovery. That error is usually seen when WAL archives are missing.

**Comment by fatihmtekin** [comment]
Thank you so much Stefan. I am really appreciate for your help.
