### ISSUE TITLE
Will deleting incremental backup makes PITR impossible?

### ISSUE THREAD

**Issue by bioflash** [pgbackrest/pgbackrest#1393]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.32
2. PostgreSQL version:

9.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

Redhat

4. Did you install pgBackRest from source or from a package?
From rpm package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    
[global]
repo1-path=/var/pgbackrest_repo
repo1-retention-full=7
repo1-retention-full-type=time
compress-type=zst

[my-stanza]
pg1-path=/var/lib/pgsql/9.6/data

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

Suppose we take 1 full backup and some incremental backup

1st full backup --> change1 --> 1st incremental backup --> change2 --> set restore_point1

If we expire 1st incremental backup, could we still use 1st full backup as base to PITR restore to restore_point1.
Though we see this warning when expiring the incremental backup 
`WARN: expiring latest backup repo1: 20210409-034944F_20210409-042645I - the ability to perform point-in-time-recovery (PITR) may be affected`

We can restore to restore_point1 from 1st full backup without problem. Could we say that expiring incremental backup won't break PITR. Just postgresql takes more time to recover since it need to replay more WAL archive to reach the target time?

**Comment by pgstef** [comment]
Hi,

The explanation for that message can be found in the comments of the source command [here](https://github.com/pgbackrest/pgbackrest/blob/2bfebff2ec73b0af6d937f303fbb9b8a0b8ee649/src/command/expire/expire.c#L138).

You're right to say that you should be able to recover from the full backup but taking much time since more WAL archive has to be replayed. However, if you miss 1 WAL archive, the chain will be broken and you could not be able to recover to the point in time you'd want...

Monitoring/checking the WAL archive chain to be sure none is missing would be one way to verify that PITR capability, but at the end, the only reasonable answer is to comply to Schrödinger law of backup: **_"The condition of any backup is unknown until a restore is attempted."_**.

Hope this answers your question,
Kind regards

**Comment by bioflash** [comment]
Thanks for your promptly reply
