### ISSUE TITLE
archive command failed with exit code 45 after Primary crashed abruptly

### ISSUE THREAD

**Issue by aogb** [pgbackrest/pgbackrest#1399]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

pgBackRest version:
2.33

PostgreSQL version:
12.6

Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: I do have all the servers mentioned with same same OS/version on all.
RHEL 7.8

Did you install pgBackRest from source or from a package?
Package

Please attach the following as applicable:

pgbackrest.conf file(s)
repository host server
[demo]
pg1-host=pgdb
pg1-path=/pgdata1/postgres/data
[global]
repo1-path=/u01/pgbackrest
repo1-retention-full-type=time
repo1-retention-full=3
start-fast=y

database server
[demo]
pg1-path=/pgdata1/postgres/data

[global]
log-level-file=detail
repo1-host=backup-repo

standby server
None
- postgresql.conf settings applicable to pgBackRest (archive_command, archive_mode, listen_addresses, max_wal_senders, wal_level, port)

listen_addresses = '*'
max_wal_senders = 10
wal_keep_segments = 100
max_replication_slots = 10
wal_level = 'replica'
hot_standby = on
archive_mode = on
archive_command = 'pgbackrest --stanza=demo archive-push %p'
shared_preload_libraries = 'repmgr,pg_stat_statements'

- errors in the postgresql log file before or during the time you experienced the issue
- log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
Describe the issue:

The primary server crashed abruptly and it took sometime for me to bring it backup. Now i am getting this in my log archive command failed with exit code 45 already exists in the repo1 archive with a different checksum.

Saw a post that talked about deleting all the archives in the repo. Do i just change to the archive directory in the repo and remove or are there other solutions out there?

**Comment by pgstef** [comment]
A proper backup recovery imply a timeline switch. Since the timeline is part of the WALfile name, you shouldn't get duplicates after a restore. In general, I tend to recommend no removing anything from the repo unless you know what you are doing.

Unfortunately, you don't provide a lot of information to understand what your problem exactly is nor where it would come from.

The question is more "The primary server crashed abruptly and it took sometime for me to bring it backup". Did you get the information about "why" it crashed ? What do you mean by "crash" also.. And what did you do to bring it up...
