### ISSUE TITLE
warning: file has timestamp in the future has timestamp in the future, enabling delta checksum

### ISSUE THREAD

**Issue by 1schmnkS** [pgbackrest/pgbackrest#1401]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.33

2. PostgreSQL version: 12.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL7

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue: just installed and configured pgbackrest on one of our pg servers. When performing the 1st full backup I got the warning message **"file 'base/20142/108188' has timestamp in the future, enabling delta checksum"**. Could you pls elaborate on the exact meaning and consequences of this warning? 2 subsequent differential backups had the exact same issue. 

Thank you + KR

**Comment by dwsteele** [comment]
`base/20142/108188` has a timestamp in the future relative to the system clock, which should not be possible. Make sure your system clock is correct and you may need to touch that file to fix the timestamp.

The question is -- how did that happen? There may be more, since we only warn on the first file found.

**Comment by 1schmnkS** [comment]
Hello. system clock seems fine to me.

`
**[postgres]$ date +%T ; stat 108188 ; pgbackrest --stanza=xxxx --type=diff backup**

06:34:11

  File: ‘108188’
  Size: 841949184       Blocks: 1650920    IO Block: 65536  regular file
Device: 29h/41d Inode: 3604047302  Links: 1
Access: (0600/-rw-------)  Uid: (   26/postgres)   Gid: (   26/postgres)
Access: 2021-05-18 03:00:47.836970000 +0200
Modify: 2021-05-18 06:32:19.365080000 +0200
Change: 2021-05-18 06:32:19.365080000 +0200
 Birth: -

2021-05-18 06:34:11.830 P00   INFO: backup command begin 2.33: --compress-type=lz4 --exec-id=65514-be3b131b --log-level-console=info --log-level-file=info --log-level-stderr=warn --pg1-path=/data/postgres/TXAP1 --pg1-port=5432 --process-max=4 --repo1-path=/data/postgres_bkp --repo1-retention-diff=1 --repo1-retention-full=7 --repo1-retention-full-type=time --stanza=TXAP1 --start-fast --stop-auto --type=diff
2021-05-18 06:34:12.663 P00   INFO: last backup label = 20210517-124116F, version = 2.33
2021-05-18 06:34:12.663 P00   INFO: execute non-exclusive pg_start_backup(): backup begins after the requested immediate checkpoint completes
2021-05-18 06:34:14.168 P00   INFO: backup start archive = 000000010000002E00000001, lsn = 2E/10000028
WARN: file 'base/20142/108188' has timestamp in the future, enabling delta checksum
2021-05-18 06:34:16.999 P04   INFO: backup file /data/postgres/TXAP1/base/20142/108201 (164.8MB, 4%) checksum 0f563a026864c12068e35c17b68cd8088df8ee73
`
this is a little bit unsettling. what might be the consequences in case a restore needs to be done?

**Comment by dwsteele** [comment]
> what might be the consequences in case a restore needs to be done?

None from this warning. The delta backup is the safest form of backup and we enable it automatically when the timestamps look unreliable. You can also enable it manually with `delta=y`. That would shut up this warning but delta backups are slower (because every file needs to be checksummed) so that is not ideal.

But something is definitely wrong here. The time we use for comparison here is coming from Postgres so I wonder if something is off there. 

Can you attach an affected backup manifest so we can look at the raw data?

**Comment by 1schmnkS** [comment]
Hello. Sure thing ... see latest backup.manifest in the attachment.
`[postgres]$ date +%T ; psql -c "select current_timestamp"

06:48:08

       current_timestamp
-------------------------------
 2021-05-19 06:48:08.867143+02
(1 row)`

 Thanks 4 your time. 

[backup.zip](https://github.com/pgbackrest/pgbackrest/files/6505901/backup.zip)

**Comment by dwsteele** [comment]
After a quick inspection I see 29 files in the manifest that are in the future with respect to the copy time.

Copy time is calculated after the manifest has been built by waiting for the remainder of the current second and then capturing the time. It should always be later than any file modified time.

We put in this check to catch systems that are behaving badly, and it sure looks like that is what is happening here. It could be a bug, but I don't believe we've never seen this warning in the field and the check has been there for years.

Is there anything unusual about this system? Is it virtualized?

**Comment by 1schmnkS** [comment]
Yes, this is a virtualized box, but so are all systems I deployed pgbackrest on in the past. Good question anyway. The one difference I spotted: this is the first system that uses nfs-attached storage for both the database and the backups. No idea if and how this could make a difference, since this isn't a very exotic way to do things. Do you have any ideas on how to find out wether this is the right direction to dig further? 

```

[root]# cat /etc/fstab

... :/pgdata_dev       /data/postgres nfs rw,sync,hard,intr 0 0
... :/pgbackup_dev     /data/postgres_bkp nfs rw,sync,hard,intr 0 0

```

**Comment by pgstef** [comment]
Hi,

I don't believe nfs is really an issue. You might check options given the PG [docs](https://www.postgresql.org/docs/current/creating-cluster.html#CREATING-CLUSTER-FILESYSTEM) though.

What virtualization technology do you use? I often saw time drifts induced by guest add-ons (like vmware or virtualbox tools) used to sync time with the host. You might want to try to disable those time syncs and use a ntp service instead to confirm that idea...

Kind regards

**Comment by dwsteele** [comment]
> this is the first system that uses nfs-attached storage for both the database and the backups

That could certainly be it, but you would not be the first pgBackRest user to run PostgreSQL on NFS.

From the pgBackRest side, I'm not sure what else we can do. I'm confident that our handling of timestamps is accurate and this definitely seems to be a case of time skew, likely caused by clock differences between the PG host and the NFS server.

I think this is something you'll need to chase down with your IT department, but cases like this are exactly what the delta option (https://pgbackrest.org/configuration.html#section-general/option-delta) was designed for. When delta is enabled pgBackRest will use checksums to decide which files to copy and you won't see these warnings.

**Comment by 1schmnkS** [comment]
Thanks for all your useful comments and inputs. Instead of going down the rabbit-hole with the linux and nas guys I've configured the delta=y option and decided to call it a day. the database isn't that big so longer backup times won't hurt anyone.
