### ISSUE TITLE
What version of postgresql-devel package to use when building from source for multiple PostgreSQL versions?

### ISSUE THREAD

**Issue by cloud-account** [pgbackrest/pgbackrest#1403]
Hello,

https://pgbackrest.org/user-guide-centos8.html#build gives an example for RHEL/CentOS systems:

>sudo yum install make gcc postgresql10-devel \\
>       openssl-devel libxml2-devel lz4-devel libzstd-devel bzip2-devel

What version of postgresql-devel packade do I have to use when building for multiple PostgreSQL versions (e.g. 10, 11, 12, 13)?
Can I use the newest version (13)? Should I build a separate pgbackrest version for each PostgreSQL server version?

Regards

**Comment by dwsteele** [comment]
It is common practice to build with the most recent version of PostgreSQL but the APIs we use have been available since 8.4. You do not need to build a separate version of pgBackRest per version of PostgreSQL.

Please note that packages are available at yum.postgresql.org and it is best to use them when possible.

**Comment by cloud-account** [comment]
Thank you.
