### ISSUE TITLE
Invalid page checksums found in file /u01/pgdata/../xxx01/base/xx80/xx311.1 at pages xx1072-xx3215

### ISSUE THREAD

**Issue by ksonupg** [pgbackrest/pgbackrest#1404]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.33dev

2. PostgreSQL version: 13.1

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL 7.9

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

Getting below warning during executing command "pgbackrest --stanza=xxxS01 --log-level-console=warn --db-port=5432 backup --type=full --pg1-socket-path=/tmp > /u00/app/postgres/admin/xxxS01/log/pgbackrest_bck_full_`date +\%Y\%m\%d_\%H\%M\%S`.log"

What could be the exact issue and how we can fix this?

Warning Log -
WARN: invalid page checksums found in file /u01/pgdata/13/xxxS01/base/xxx80/28311.1 at pages xxx072-xxx215
WARN: invalid page checksums found in file /u01/pgdata/13/xxxS01/base/xxx80/28311.2 at pages xxx144-xxx739
WARN: invalid page checksums found in file /u01/pgdata/13/xxxS01/pg_tblspc/xxx95/PG_xx_202007201/12351977/59573.1 at pages 131073-393217
WARN: invalid page checksums found in file /u01/pgdata/13/xxxS01/pg_tblspc/xxx95/PG_xx_202007201/12351977/58983.2 at pages 262145-524288
WARN: invalid page checksums found in file /u01/pgdata/13/xxxS01/pg_tblspc/xxx95/PG_xx_202007201/12351977/58983.1 at pages 131073-393214
WARN: invalid page checksums found in file /u01/pgdata/13/xxxS01/pg_tblspc/xxx95/PG_xx_202007201/12351977/55892.1 at pages 131073-393214
WARN: invalid page checksums found in file /u01/pgdata/13/xxxS01/pg_tblspc/xxx95/PG_xx_202007201/12351977/54332.4 at pages 524289-786432

**Comment by dwsteele** [comment]
First, run pg_checksums (https://www.postgresql.org/docs/13/app-pgchecksums.html) to be sure this is not a false positive. That seems unlikely, but it is best to check.

If pg_checksums gives the same result you have two main options. Before you do either of them you should check the storage and make sure there are no issues there, otherwise you could wind up in the same situation after taking action.

1) Restore from an older backup. If the corruption was due to storage, this should fix it.
2) If the relations in question are indexes you can rebuild them and avoid having to do a restore.

Please let us know the results of pg_checksums. It could be different because pages may be overwritten without being read in some cases and of course the corruption could get worse. If pg_checksums reports *no* corruption we'd definitely like to know.

**Comment by ksonupg** [comment]
Thanks @dwsteele for prompt response but this is a production cluster hence I am afraid to make it down as it mentioned as mandatory.
`The` server must be shut down cleanly before running pg_checksums`

**Comment by dwsteele** [comment]
> this is a production cluster hence I am afraid to make it down as it mentioned as mandatory.

You may not have much choice in the end, but for an online cluster you can also try `pg_dump` on the affected tables and see how that goes. See https://www.2ndquadrant.com/en/blog/postgresql-filename-to-table/ for information on identifying a table from the relfilenode.

Note that postgres will stop on the *first* error in a relation so you won't get a complete list of bad pages per relation.

**Comment by pgstef** [comment]
Make sure you won't lose any data due to some corruption might worth the downtime. In such cases, having a standby server might help (check corruption there and switch-over if needed).

Here are a few other interesting resources about this topic imho:
- https://wiki.postgresql.org/wiki/Corruption
- http://rhaas.blogspot.com/2014/05/troubleshooting-database-corruption.html
- https://pgconf.ru/en/2021/288356
