### ISSUE TITLE
Permission stop File

### ISSUE THREAD

**Issue by wildhi** [pgbackrest/pgbackrest#1412]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.33

2. PostgreSQL version: 10,11,12,13

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: SUSE Linux Enterprise Server 12 SP5

4. Did you install pgBackRest from source or from a package? Source Code

7. Describe the issue:

How can i manage the Permissions for the stop File at Building the pgbackrest exec file ?`
I need Permission for the stop file in /tmp/pgbackrest/all.stop for monitor it on icinga. Normal only the user add the stop file are authorized, but we need other user permissions. 
My Workaround is to change the File (STORAGE_MODE_FILE_DEFAULT = 0644) https://github.com/pgbackrest/pgbackrest/blob/45a4e801ed52f60f27c73eacaf63ff4b483ab352/src/command/control/stop.c#L40
But i think it´s nice to add this for reading other to standard or add a parameter to use this at building pgbackrest.

**Comment by pgstef** [comment]
Hi,

I don't really know what to think about your request. I agree there's room for improvement in the docs regarding monitoring but forcing users to compile when they need monitoring doesn't seems really fun. Mainly because we tend to recommend using PGDG packages when possible over building from sources.

And to be precise, `STORAGE_MODE_FILE_DEFAULT` is defined [here](https://github.com/pgbackrest/pgbackrest/blob/45a4e801ed52f60f27c73eacaf63ff4b483ab352/src/storage/storage.intern.h#L22). Changing it could have some side effects.

Do you only check the stop file inside your monitoring ? I mean there are a lot of other things you could watch. Often even running `pgbackrest info` command itself. 

This sounds more like a system config. Admins / monitoring users could be in the same group as the pgbackrest user. That's what I do with [check_pgbackrest](https://github.com/pgstef/check_pgbackrest) too. I create a dedicated system user accessed by ssh (for icinga) and add it to the postgres/pgbackrest group...

**Comment by dwsteele** [comment]
Or just precreate the lock path. We don't change the permissions if the path already exists.

**Comment by pgstef** [comment]
> Or just precreate the lock path. We don't change the permissions if the path already exists.

I'm not sure it would be enough. With 0640, the external user won't probably be able to read the file, so not even checking it exists (since can't read its attributes).

**Comment by dwsteele** [comment]
If dir mode is 750 and file mode is 640 you can see if the file exists, but not read it. Since stop files are empty this seems like it would be enough.

**Comment by pgstef** [comment]
Hm, my bad, I don't know why my last quick test didn't work.

Precreating the spool path with **755** should indeed work for the icinga user:

```bash
# spool path 700 / stop file 640
$ ls -l /var/spool/ |grep pgbackrest
drwx------.  2 postgres postgres   6 Apr  6 10:50 pgbackrest
$ ls -l /var/spool/pgbackrest/
-rw-r-----. 1 postgres postgres 0 May 25 10:02 640-test-file
$ sudo -u icinga ls /var/spool/pgbackrest/640-test-file
ls: cannot access /var/spool/pgbackrest/640-test-file: Permission denied

# spool path 755
$ ls -l /var/spool/ |grep pgbackrest
drwxr-xr-x.  2 postgres postgres  27 May 25 10:02 pgbackrest
$ sudo -u icinga ls -l /var/spool/pgbackrest/640-test-file
-rw-r-----. 1 postgres postgres 0 May 25 10:02 /var/spool/pgbackrest/640-test-file
```

For this test at least, it seems enough indeed.

**Comment by wildhi** [comment]
Okay. thanks.
I have solved with Permissions for the icinga User. We configure the pgBackRest to our hosts with Ansible and there I change the permissions.
Thanks!
