### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by internetuser2008** [pgbackrest/pgbackrest#1428]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.32

2. PostgreSQL version: 12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 16 & 18

4. Did you install pgBackRest from source or from a package? pkg

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
Please allow the version on the server and version on the Postgres host to be slightly different. 

A central pgbackrest repository runs on Ubuntu 18 and Postgres server runs on Ubuntu 16. Constantly have to fight to keep the server and repository server versions the same.  Currently xenial is one version behind. 
```
 pgbackrest --stanza=server0112 info
ERROR: [039]: expected value '2.32' for greeting key 'version' but got '2.33'
       HINT: is the same version of pgBackRest installed on the local and remote host?
```

**Comment by pgstef** [comment]
Hi,

Unfortunately, we don't control the package releases. Those are provided by the PGDG packagers. You can contact them on https://www.postgresql.org/list/pgsql-pkg-debian/ to get more details about their release policy.

Sorry for the inconvenience.
Kind Regards,

**Comment by dwsteele** [comment]
Ubuntu 16 is EOL so there won't be any more packages built for it. You'll need to stick to 2.32 for both systems if you want to use the packages from apt.p.o.

We would definitely like to be able to allow the remote to be a few versions back, but we add functionality to the remote so often that it would only work occasionally. For now if you want to use a remote the versions must match.

**Comment by SemiNomadic** [comment]
😄  This has been a massive, bleeding thorn in my side for _years_.  So for what it's worth, my $0.02 on this open issue...

It's specifically _because_ pgbackrest does not have control over the package releases that it DESPERATELY needs to be able to handle at least a minor version mismatch between the repo server and the PG server being backed up.

Not letting the remote version be > repo version is understandable.

But that said, the remote should be allowed to be <= repo version.

For example...
- you're handed a shiny new server
- you can only install the latest & greatest package from PGDG on it
- this package is not available for any of your older servers
- you can now either
-- A) install an older version from source on just this _one_ server, thus making it the black sheep of the group requiring manual maintenance
-- B) rewrite your Ansible playbooks to remove the packages from all servers, and install pgbackrest from source (also via Ansible, which is no fun IMHO) on all of them

If the worst I had to do was upgrade the repo server to >= PG server being backed up, life is good 👍 

Or imagine "someone" updated the packages on one or more of the db servers unbeknownst to you.  Fun times ahead as the failed backup and wal archiving alerts begin coming in (probably in the middle of the night, right? lol). Now you have to roll through either of those A/B choices above in the middle of the night—once you figure out the issue is a `pgbackrest` version mismatch—i in order to get things working again.

Does this improvement have any kind of priority for the project?  I ask, because—no joke—it is the single most commiserated and bitched about issue I know of amongst lovers of `pgbackrest`, such as myself 😉 

Thanks!

**Comment by dwsteele** [comment]
> Not letting the remote version be > repo version is understandable.

It's not that simple, unfortunately since the communication is two-way. So, if the pg host was > repo host you would not be able to do backups from the repo host, you would be able to archive. That doesn't seem like a good solution.

The solution is to have a versioned API, and we are working in that direction, but I can't say when it will happen. It's a pretty massive effort to do it right because the remote does a *lot*, basically anything pgbackrest can do. So it will require a lot of cross-version testing and we simply don't have the resources to implement that at this time.

**Comment by SemiNomadic** [comment]
@dwsteele  —

Thanks for the reply!

Right, I didn't think about the mismatch when writing back to the repo.  That makes sense.

But all-in-all it is super encouraging to hear that this is a "thing", and will arrive "some day".
