### ISSUE TITLE
Adding HINT when timeout-waiting-for-replica-to-catch-up error for disable backup-standby 

### ISSUE THREAD

**Issue by leigh-downs** [pgbackrest/pgbackrest#1434]
Suggesting adding a HINT when getting the timeout-waiting-for-replica-to-catch-up error:

`ERROR: [082]: timeout before standby replayed to 0/9D000028 - only reached 0/1D000000`

Change to:

```
ERROR: [082]: timeout before standby replayed to 0/9D000028 - only reached 0/1D000000 ... HINT: if the standby isn't working correctly, disable backup-standby by setting backup-standby=n in pgbackrest.conf and attempt a new backup
```

**Comment by pgstef** [comment]
Hm, we'd then basically suggest "if your standby server can't keep up, take backup from primary". But the user might prefer to find a way to speed up the wal replay, increase the timeout, or take a backup in another time when there will be less activity on the server...

Long story short, I'm not really fan/in favor of that HINT but perhaps @dwsteele will have another idea about this..

**Comment by sfrost** [comment]
Agreed that there might be other options besides disabling backup-standby, but to figure those out we have to have some idea as to why the replica isn't catching up to where the primary is at, whereas the suggested hint is very likely to result in a successful backup regardless of the issue with the standby.  That there is some issue with the standby is pretty clear from the original message, I would think, but people might not get why that's relevant.  Adding the hint makes it clear that the replica matters because backup-standby is enabled.  All-in-all, it seems like a good thing to draw attention to when this happens.

**Comment by dwsteele** [comment]
I think two hints here might be appropriate. Perhaps:
```
HINT: is replication running and current on the standby?
HINT: disable the 'backup-standby' option to make a backup from the primary.
```

**Comment by dwsteele** [comment]
Or:
```
HINT: is replication running and current on the standby?
HINT: disable the 'backup-standby' option to backup directly from the primary.
```

**Comment by dwsteele** [comment]
Committed at b7ef12a7.
