### ISSUE TITLE
Automatically create data directory

### ISSUE THREAD

**Issue by cbandy** [pgbackrest/pgbackrest#1445]
pgBackRest version: 2.33

I use `pgbackrest restore` for a variety of tasks&sup1; and have found that I always run the command as `install -d -m 0700 "${data_directory}" && pgbackrest restore …`. I would prefer that `pgbackrest restore` creates the data directory according to `pg-path` in `pgbackrest.conf` so there is just one command and one configuration I need to maintain.

&sup1; PITR, cloning a cluster to move data, and preparing standbys for log-shipping and streaming replication.

---

https://github.com/pgbackrest/pgbackrest/blob/39c1c1012013f456e951fc149b0f88cbc5dcbcc0/src/command/restore/restore.c#L62-L65

The upstream tools `initdb` and `pg_basebackup` create their data directory, but I've never needed or used the `--allow-group-access` flag.

**Comment by pgstef** [comment]
Hi,

I've got a small [poc](https://github.com/pgstef/pgbackrest/tree/sf-restore-creates-pgdata) for this.

PR is not created yet because, as it would be a behavior change, I'm wondering if we'd need to add an extra option or not...

I guess creating with default 0700 mode would be safe enough and users who want to change ownership/permissions will have to create the dir in advance.

**Comment by dwsteele** [comment]
We have the perms for PGDATA stored in the manifest so I think we should create the directory with them.

I'm fine with this enhancement -- but it will only work so long as the restoring user has permission to create the directory. So, I think we need a message to let the user know that we are trying to create the directory on their behalf. That way, if an error happens there is some context for the error. Otherwise we'll be getting bug reports for it.

**Comment by dwsteele** [comment]
So, in the POC, we should WARN in advance. Also, we are going to create the data directory I think we should try to create directories for symlinks as well.

**Comment by pgstef** [comment]
> So, in the POC, we should WARN in advance.

Just updated the [poc](https://github.com/pgstef/pgbackrest/commit/6362c5a783f73fa3a0a512d64df1b7d15a2d1d4b) to WARN before.

> We have the perms for PGDATA stored in the manifest so I think we should create the directory with them.
> Also, we are going to create the data directory I think we should try to create directories for symlinks as well.

At this point (1), the current poc is just a "simple" patch to create the pg1-path with default 0700 mode rather than throwing an error. The logic is placed in `restorePathValidate` and at that time we don't know which backup set will be restored yet. 

If we want to go further and get the info from the manifest for pg_data perms and links (2), I believe we'd have to move the creation logic to `restoreManifestMap` then (which might complicate the patch a little bit).

@dwsteele : Am I right regarding the option 2 ? Do you prefer to go that way (so I'd have to create a new patch following that road) or is option 1 enough ?

I tend to see option 1 as a "quick win" for this enhancement request, but I perhaps miss the bigger picture if there are user requests for the links creation too :-)

**Comment by dwsteele** [comment]
It might be enough just to remove the check in `restorePathValidate()`. The way I read it all paths will be created at restore.c line 1150 if they don't exist. This might be some leftover cruft from the Perl migration.

**Comment by pgstef** [comment]
> It might be enough just to remove the check in `restorePathValidate()`. The way I read it all paths will be created at restore.c line 1150 if they don't exist. This might be some leftover cruft from the Perl migration.

I wasn't sure it would apply to PGDATA too, but after testing it, you're right (as always...). I prepared the PR #1454 to remove that requirement then...

**Comment by dwsteele** [comment]
Haha, not always...

During the migration we were trying not to change the behavior as much as possible to make it easier to verify the functionality. We obviously meant to remove this check but just never got to it.
