### ISSUE TITLE
Feature request - ability to specify SSH key for remote SSH stanza

### ISSUE THREAD

**Issue by fmbiete** [pgbackrest/pgbackrest#1448]
Our setup looks like this:

DEV server -> DEV stanza
PROD server -> PROD stanza

Sometimes we need to perform a refresh of DEV with PROD and we are leveraging pgbackrest to do this quickly:
In DEV server we connect to PROD stanza and we restore the desired backup.
```
--repo1-host=<prod server> --repo1-host-user=<prod postgres user>
```

Would it be possible to add an option so that we can specify an SSH key in this situation instead of always using the default?
Something like
```
--repo1-host-sshkey=/home/dev/.ssh/refresh_prod_rsa
```
That would allow us to do this operation without having to momentarily change the default key of the user

**Comment by pgstef** [comment]
Hi,

Wouldn't you be able to do it using `~/.ssh/config` ?

Example:
```ini
Host prod
    HostName <prod server>
    User <prod postgres user>
    IdentityFile /home/dev/.ssh/refresh_prod_rsa
```

**Comment by dwsteele** [comment]
It looks there are a number of ways to deal with this outside of pgbackrest. Anyway, seems like the dev server should have a dev key that the prod repo host recognizes rather than placing the prod key on dev. If you need to revoke a key you'd need to revoke it in prod as well, which isn't very good.

While the feature would be fairly easy to implement, I don't think it is is useful enough to justify the additional tests.

**Comment by fmbiete** [comment]
One of my requirements was to avoid that dev box permanent access to the prod sever. I could copy the key, add the block in ssh/config and remove it after... Not ideal, but it would be good enough

**Comment by dwsteele** [comment]
I see what you are saying, but if the dev box has a key that is recognized by prod, then it pretty much does have permanent access. If the dev box has it's own key, then it can be revoked from the prod side. That seems better to me overall.

You can also use ssh to limit which commands can be run, e.g. `pgbackrest restore`.
