### ISSUE TITLE
Error caused by checkpoint LSN between primary and standby

### ISSUE THREAD

**Issue by fatihmtekin** [pgbackrest/pgbackrest#1450]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:pgBackRest 2.30

2. PostgreSQL version: 12.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL 7.9 - Patroni cluster with 3-nodes

4. Did you install pgBackRest from source or from a package? from package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - [global]
repo1-path=/nfsbackup/oxygen
repo1-retention-full=4
process-max=16
log-level-file=detail
archive-async=y
backup-standby=y
lock-path=/nfsbackup/oxygen/lock
delta=y
spool-path=/backup/pgbackrest/spool
[global:archive-push]
compress-level=3
process-max=12
archive-push-queue-max=300GB

[oxygen]
pg1-host=172.202.52.11
pg1-host-user=postgres
pg1-path=/pgdata/data
pg1-port=5432
pg2-host-user=postgres
pg2-path=/pgdata/data
pg2-port=5432
recovery-option=standby_mode=on
recovery-option=primary_conninfo=host=172.202.52.11 user=replicator passfile=/pgdata/.pgpass port=5432 sslmode=prefer application_name=oxygen02 gssencmode=prefer
recovery-option=recovery_target_timeline=latest
start-fast=y

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue: My pgBackRest backup process was working flawlessly until now. But, I noticed today that you got an error.
My backup script runs on the standby node. (backup-standby=y)

-------------------PROCESS START-------------------
2021-07-06 05:41:01.889 P00   INFO: backup command begin 2.30: --archive-timeout=60 --backup-standby --delta --lock-path=/nfsbackup/oxygen/lock --log-level-console=info --log-level-file=detail --pg1-host=172.202.52.11 --pg1-host-user=postgres --pg1-path=/pgdata/data --pg2-path=/pgdata/data --pg1-port=5432 --pg2-port=5432 --process-max=16 --repo1-path=/nfsbackup/oxygen --repo1-retention-full=4 --stanza=oxygen --start-fast --type=full
2021-07-06 05:41:03.549 P00   INFO: execute non-exclusive pg_start_backup(): backup begins after the requested immediate checkpoint completes
2021-07-06 05:41:09.260 P00   INFO: backup start archive = 00000034000052180000006B, lsn = 5218/6B002620
2021-07-06 05:41:09.260 P00   INFO: wait for replay on the standby to reach 5218/6B002620
2021-07-06 05:41:14.868 P00  ERROR: [082]: the checkpoint lsn 5218/5E35BBA8 is less than the target lsn 5218/6B002620 even though the replay lsn is 5218/6C847D90
2021-07-06 05:41:14.969 P00   INFO: backup command end: aborted with exception [082]
 
I don't understand why you get an error right away.  Why doesn't it wait to replay?

**Comment by pgstef** [comment]
Hi,

First short remark, you could probably get rid of `recovery-option=standby_mode=on` (setting no longer valid after PG 12) by using `restore --type=standby`. And `recovery-option=recovery_target_timeline=latest` is the default value after PG 12 (or using `--target-timeline=latest`). Also `pg1-port=5432` is not needed since you use `pg1-host`, `pg2-host-user` should probably be `pg2-user` (postgres being its default value) given `pg2-host` is not defined.

That being said, if I understand correctly the [dbReplayWait](https://github.com/pgbackrest/pgbackrest/blob/62e8d97af03e7628d5710b17aad1cc31f83d7e69/src/db/db.c#L588) function, the data from the primary have been replayed (replay lsn) but didn't make it to the pg_data on disk yet (checkpoint lsn).

I agree, the ERROR message isn't really clear about that behavior. We could probably add a HINT or perhaps add a loop to wait the checkpoint lsn reach the target, as it's done for the replay lsn...

Kind Regards

**Comment by fatihmtekin** [comment]
Hi Stefan,
Thank you so much for your crucial knowledges. I changed the conf as you specified. I removed unnecessary or invalid parameters.

**Comment by dwsteele** [comment]
We have seen this happen at least once before in the wild. It seems that updates to pg_control can lag `pg_last_wal_replay_lsn()` so a loop is needed. We let it go before since it was just once (and transient) but now I think we should have a look.

I'm going to reopen this issue and mark it as an improvement.

**Comment by dwsteele** [comment]
Add a card for this issue (https://github.com/pgbackrest/pgbackrest/projects/2#card-64554287) so we'll close it again and comment when we add the loop.

**Comment by dwsteele** [comment]
@fatihmtekin PR #1460, which fixes this issue, is ready to commit. How would you like your name to appear in the release notes?

**Comment by fatihmtekin** [comment]
@dwsteele 
Thanks a lot for your fixes. My name can appear as "fatih mencutekin".
Thank you again.

**Comment by jw1u1** [comment]
We faced the same Error message in 2.36:
2022-02-24 19:07:00.049 P00   INFO: backup command begin 2.36:
2022-02-24 19:07:17.309 P00   INFO: wait for replay on the standby to reach EABB/D00888C8
2022-02-24 19:09:04.297 P00  ERROR: [082]: timeout before standby checkpoint lsn reached EABB/D00888C8 - only reached EABA/A772D470

**Comment by dwsteele** [comment]
Please don't comment on closed issues.

It is likely that your standby is lagging. You can increase `archive-timeout` but you'll want to check if your standby is replicating first.
