### ISSUE TITLE
Archive WAL Files retention outside of repository

### ISSUE THREAD

**Issue by moindba** [pgbackrest/pgbackrest#1493]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.33
2. PostgreSQL version:
11.12
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS 7.4
4. Did you install pgBackRest from source or from a package?
Package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
As part of Archive WAL file retention policy we need to keep 7 days of archive wal files in a separate directory, but while using pgBackrest archive wal files are kept inside the repository. Our aim to keep the archive wal files in separate directory using archive_command = 'cp %p <<pathofarchdir>>/%f'  while using pgbackrest.

is this possible to use above archive_commad while taking backups from pgbackrest tool ?

**Comment by pgstef** [comment]
Hi,

Imho, there's no point to define a time retention period for WAL archives. Because WAL files without any related backup would be useless. Same if the backup is older than your time retention, you'd broke the WAL chain. That's way better to keep the archives needed for your backups / PITR capabilities. If you really need to keep less archives than backups, you can have a look to the `--repo-retention-archive-type` option.

Cp is usually not reliable enough imho too. Because you don't check that the archives doesn't exist already, nor it's fsynced to disk, nor its checksum,... You'd also lose a lot of features if you don't use the same tool for backups and archives.

I'm not sure it would/should be possible anyway. If you really want an external copy, simply add a cron task that will look to the archives repo and copy the latest ones over to your other directory. That way, you wouldn't block your PG archiving process in case that extra copy isn't working. Or simply add both commands in `archive_command = 'pgbackrest ... && cp ...'`. PG archiver would then be blocked if any of the 2 commands fail.

Kind Regards

**Comment by dwsteele** [comment]
You can set `archive-check=n` to use your own `archive_command`.

But as @pgstef noted, using cp as an archive_command is very prone to error, and if WAL expiration is not tied to backup expiration you are likely to have useless backups in your repository. Storing WAL archives locally is also a really bad idea. If the host dies you lose all your backups (WAL is required for recovery).

You may want to ask yourself where this policy came from and is it a good idea?

**Comment by moindba** [comment]
Hello All,

In pgbackrest repository i can see that archive wal files are in .gz format. how can i have the archive wal files without encryption and compression in normal form what we have without pgbackrest.

Currently I can see the archive files as 000000010000000000000038-c78781ebfbd572fbbde07da83b983b02f6aeedfe.gz  in pgbackrest repository, instead of this can i have archive wal like this 000000010000000000000038

So do let me know how can i have archive wal files as 0000000100000000000000**.




Thanks and Best Regards,

Moin Akther
PostgreSQL DBA
Email: ***@***.***
Mobile:+91 7702234217
             :+91 8977863138

________________________________

**Comment by pgstef** [comment]
If you encrypted your repo (using `repo-cipher-type`), the easiest way would be to use the [repo-get](https://pgbackrest.org/command.html#command-repo-get) command and pipe it to `gzip -d`. 

If you didn't encrypted your repo, simply copy the file and `gunzip` it.

The `c78781ebfbd572fbbde07da83b983b02f6aeedfe` part in your `000000010000000000000038-c78781ebfbd572fbbde07da83b983b02f6aeedfe.gz` example is just a checksum. Rename your file and you'll be fine.

Example:
```bash
$ pgbackrest repo-get archive/STANZA/13-1/0000000100000000/000000010000000000000006-3004475a76a57b3c34a682b086131e6a07a9250f.gz|gzip -d > 000000010000000000000006

$ pg_waldump 000000010000000000000006
...
```
