### ISSUE TITLE
Protecting backups against malicious operations

### ISSUE THREAD

**Issue by siepkes** [pgbackrest/pgbackrest#1494]
Let me start out by thanking you folks for creating such a nice piece of PostgreSQL backup software!

With ransomware and such on the rise (basically the monetization of criminal IT activities) I was hoping I could use retention policies to guard my backup data from being deleted by an attacker. However I stumbled across #1439 in which it is outlined that it is not possible to use a retention policy of a object storage provider (such as GCS, AWS S3, etc.).

Is there at this point any way or storage backend (so not necessarily object storage) in which one can create a setup where backups can only be appended by pgbackrest?

**Comment by levkk** [comment]
Sounds like a job for a copy-on-write system which S3 can achieve with [file versioning](https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html). I think most object storage solutions will have what you need.

**Comment by siepkes** [comment]
@levkk Thanks for the suggestions! However as I stated in my post disabling S3 delete does not work with pgbackrest (outlined in #1439 ). I don't think versioning alone is going to help one against a malicious operator because they can simply delete the object in S3 including all previous versions. 

I also don't really see how ZFS is going to be much help here. Aside from wanting to have the backups off-site, if the machine gets root-ed ZFS snapshots can easily be destroyed.

**Comment by dwsteele** [comment]
> I don't think versioning alone is going to help one against a malicious operator because they can simply delete the object in S3 including all previous versions.

Are you sure? I thought there was a way to prevent deleting prior versions. Even so, I'm not sure how pgBackRest would look at a "snapshot" or if this is even something that can be set on the bucket.

We have been thinking about this a lot recently and in general we've decided that we would like to have our own versioning rather than rely on any particular vendor solution. This has been the plan for a while because it will also allow us to do "lockless" writes to the repo.

One thing to do might be to create a new repo each week with a single full backup and no expiration. Then mark it write-only and continue to accumulate WAL in the repo for the next week. Multi repo could be used to access several repos to do a restore depending on how far in the past you needed to go.

**Comment by dwsteele** [comment]
We have added a card for this feature to the repo v6 project: https://github.com/pgbackrest/pgbackrest/projects/8#card-64556418
