### ISSUE TITLE
Retention option for incremental backups

### ISSUE THREAD

**Issue by ktosiek** [pgbackrest/pgbackrest#1503]
I want to implement a retention policy that keeps daily backups with PITR for 2 weeks, weekly backups for 6 weeks, and 1 monthly backup for 6 months.
I'm trying to configure it by setting full backup retention to ~6 months, diff backup retention to 6 (they will be made weekly), and archive retention to 14 incremental backups.

The problem is, I understand from the documentation that I'll still keep the incremental backups made on top of all the full/differential backups. Is there some better way to build such retention policy? I'd rather avoid writing a dedicated tool based on `expire --set=...`.

**Comment by pgstef** [comment]
Hi,

There isn't any retention setting for incremental backups because they always expire with the backup they refer to. They are cumulative. So removing the oldest incremental would remove the newest too. 

Have you considered using weekly full and daily diff instead ? That would allow you not to keep "every day" backup, but only 2 or 3 diff per week. At the end, as long as you get 1 backup and all the archives, you'll be able to recover. Using an older backup will also allow to recover, just a bit slower. It really depends on your WAL activity I guess.

Otherwise, indeed, `expire --set` the 1st incremental of the week you want to "clean" should work. I guess it would expire all the incremental between 2 differential.
