### ISSUE TITLE
[Feature Request] Add time-based logging for Restore processes

### ISSUE THREAD

**Issue by tomswartz07** [pgbackrest/pgbackrest#1507]
Hi there:

I'd like to request a feature enhancement for the `restore` function which would add additional timestamps to indicate the time of the latest files being replayed into the restore, at the request of a customer client.

## Background

Often, when there are restores being performed on very large (≥1TB) db's, it can. understandably, take some time to complete if infrastructure or network conditions are not ideal. Percentage complete output is sometimes useful, but not always indicative of how far along it may be.

One common way to see 'how close to the target time' the restore is currently running is to compare the filenames listed in the pgbackrest restore log, look up the mtime/atime of the file in the filesystem, and then compare it to the target restore time.
This will then give a 'time based' estimate, rather than a percentage completion, which may be a bit more intuitive for some users.

## Example
This is to say, for example:
- The goal is PITR to 30 Aug 2021, 13:55:00 EDT
- pgBackRest is restoring `/var/lib/postgresql/11/main/base/1/3502` and logs that filename in the `stanza-restore.log` file.
- Running an `ls -liah` on the backup dir to identify that file, with its timestamp, you can see that file is for Aug 27, 16:12:00 EDT
- This means that the recovery process has "3 days of WAL" remaining to process. The `info` level stdout may say the restore at this point is 50% complete.
- User reviewing the output can then know that there are 5 days (two weekend days) of WAL left to process, and communicate that info, with the understanding that pgBackRest may proceed to report 'percent completion' increase rapidly.
>"Ah, just Friday and the weekend's worth of data left to process"

## Suggested Possible Implementation

This type of logging, while potentially useful, can and probably should be tagged for more 'verbose' logging schemes, `DETAIL`, perhaps. Obviously the concern with enabling it on the less verbose or default logging levels would be confusion around the processes, and ensuring that users allow pgBackRest to complete the full restore action properly.

It appears that you're already logging mtime of the files, but only in cases where `--force` is used;
https://github.com/pgbackrest/pgbackrest/blob/master/src/command/restore/restore.c#L2035

It may be possible to have a similar function that logs the mtime of the file separately, along with the filename, similar to:
https://github.com/pgbackrest/pgbackrest/blob/master/src/command/restore/restore.c#L2024

I'd be happy to attempt a PR with a change, but I'll defer to the maintainers for the proper/ideal location for this item to be captured and logged.

**Comment by pgstef** [comment]
Hi,

My first thoughts about this request is that it wouldn't be accurate nor achieving what you expect. Simply because pgBackRest doesn't restore any WAL archive. That's up to PostgreSQL itself.

Imagine you have a full backup with `timestamp start/stop: 2021-09-06 10:02:40 / 2021-09-06 15:07:43`. And you request PITR until `2021-09-09 08:20:00`. It means pgBackRest will restore files with mtime no later then `2021-09-06 15:07:43` and set the `recovery_target_time` in PostgreSQL recovery settings. So PostgreSQL will try to recover all the wal archives until that point in time.

The maximum time you'd be able to log is the timestamp stop of the backup set to restore. Adding `file->timestamp` just before [checksum](https://github.com/pgbackrest/pgbackrest/blob/f4e1babf6b4ce7087ace8221cac7cadb51488f0e/src/command/restore/restore.c#L2058) wouldn't be that hard I guess but at some point, I doubt this info would really be valuable...

**Comment by dwsteele** [comment]
The WAL to recover is determined by the backup start LSN/time -- it is not related to the individual file timestamps. So if I'm recovering from a backup started on midnight FEB-01 and doing PITR to midnight FEB-03, then 2 days of WAL need to be replayed, regardless of the file timestamps.

How about just adding the backup starting time to this message:
```
P00   INFO: repo2: restore backup set 20161219-212741F_20161219-212918I starting at 2016-12-19 21:29:18
```
The start time is right there in backup label, but this would be much easier to read.

**Comment by tomswartz07** [comment]
Thanks David, I think that would cover this type of use case that was discussed with us.

**Comment by dwsteele** [comment]
Closing since a PR has been created for this feature. @tomswartz07, please review #1518.
