### ISSUE TITLE
pgBackrest S3 restore fails with invalid type

### ISSUE THREAD

**Issue by echel0n** [pgbackrest/pgbackrest#1509]
Attempting to restore a recent backup using pgBackRest and Postgresql Operator v4.7.0 I get back the following error below:
```
ERROR: [099]: raised from local-1 protocol: invalid type at '[;z=1Gxŧ*'}1_vy!yՁN4b0a1eY:#pVJ*V*V*#Ǒ!#g+U..05`_hz4$Uq$BU_jc+Z'}yY2gקu1tuY8nґP\O}\?-J2&䦡:!'
```

**Comment by echel0n** [comment]
OK, I was able to restore the backup, however, I had to exec into the bootstrap container, delete everything inside /pgdata folder and retry the restore, took me 3 times to finally get it to fully perform the restore.

**Comment by pgstef** [comment]
Hi,

Error 99 is a [JsonFormatError](https://github.com/pgbackrest/pgbackrest/blob/c38d6926d6c9aa01b895a28e66fc0aa6965350a3/src/common/error.auto.c#L82). This format is used in a lot of places.

Given you don't provide any information useful to reproduce the issue (logs, config file, pgbr exact command used, does this happen to each restore or only "sometimes", what did you do between a successful restore and a failed one,...), unfortunately, I don't really see how we could guess what happened here.

It would probably be interesting to report this behavior to postgres-operator though. If cleaning the target pg-data helps, it worth knowing how this folder was created (even if I don't immediately see how a messy pgdata could lead to a json format error...).

For a first restore (or bootstrap as you call it), it's usually recommended to restore on a clean target (empty directory) anyway. The `--delta` option is mostly interesting to re-sync old standbys or only restore files modified since the backup. 

Regards

**Comment by echel0n** [comment]
first restore fails, exec into bootstrap container and rm -fr /pgdata/*, 2nd restore works.
I have a ticket open with postgres-operator repo as well.

**Comment by echel0n** [comment]
I'll close this out here and continue over at postgres-operator, thanks!
