### ISSUE TITLE
Is it possible to have repo and hot standby on the same node?

### ISSUE THREAD

**Issue by bhola05** [pgbackrest/pgbackrest#1517]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.34

2. PostgreSQL version: 11.12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: CentOS 7.9

4. Did you install pgBackRest from source or from a package? Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
I am trying to use 2 nodes:
- Node A as primary node.
- Node B as standby + REPO node.

Is it possible to make standby node as REPO node as well?

My configuration looks like this right now:

**Primary node - pgbackrest.conf**
```
[global]
repo1-host=NodeB
repo1-host-user=postgres
repo1-path=/PGDATA/wal_archive
repo1-retention-full=1

[testdb]
pg1-path=/PGDATA/datadg/data
```

**Node B (standby and REPO) - recovery.conf**
```
restore_command = 'pgbackrest --stanza=testdb archive-get %f %p'
recovery_target_timeline = 'latest'
standby_mode = 'on'
```

**Node B (standby and REPO) - pgbackrest.conf**
```
[global]
repo1-path=/PGDATA/wal_archive
repo1-retention-full=1

[testdb]
pg1-path=/PGDATA/datadg/data
```

The above works okay for Node B to act as a REPO and a standby as well. But the problem happens when I want to take `backup`. Because `backup` requires `pg1-host`. As soon as I put that, and say `pg1-host=NodeA`, it no more works as standby.

```
[global]
repo1-path=/PGDATA/wal_archive
repo1-retention-full=1

[testdb]
pg1-host=NodeA
pg1-path=/PGDATA/datadg/data
```

Is there any way to do it? I tried using 2 stanzas on the Primary node, but realized that data wouldn't be sent to both.

**Comment by pgstef** [comment]
Hi,

Possible, I guess it is. But imho, it shouldn't be recommended, nor supported. One of the most important rule is "never keep your backups next to your PG data". That's why you should have a dedicated backup server or a shared backup storage (nfs, s3,...).

On your primary node, `repo1-path` and `repo1-retention-full` aren't used and may be removed (given you defined `repo1-host` and backups are taken from that repo host).

In theory, changing nodeB config like this should work for taking backups:
```ini
[testdb]
pg1-path=/PGDATA/datadg/data
pg2-host=NodeA
pg2-path=/PGDATA/datadg/data
```
You could even add `backup-standby=y` if you want to copy data directly from the standby PG. I've not tested it but I guess it should work for the `restore_command` too.

That also means you'll have to change the configs in case of fail-over/switch-over. Using a shared storage would really be easier.

Kind regards,
