### ISSUE TITLE
pgbackrest for large databases

### ISSUE THREAD

**Issue by fvannee** [pgbackrest/pgbackrest#1595]
I wanted to start this thread for some questions about using pgbackrest for very large databases, let's say 70+ TB, which also have a high WAL rate, 50-70MB/s. These type of databases are usually historical analytics databases, which are mostly INSERT-only so old data is rarely modified, but new data is inserted all the time. We have a case like this.
Having experience with pgbackrest on smaller databases, I think pgbackrest works very well in cases even up to several TB. I was wondering if some optimizations are possible for larger databases.

First question: the documentation suggests that when doing an incremental backup, it verifies whether or not it needs to include a file in the backup using checksums. In order to do this, it needs to compute the checksum of the file on the database host. Is is feasible to have an option here to look at file timestamp here instead, to avoid having to do file IO for the whole database for incremental backups where likely >95% of the data didn't change?

Second question: backups for large databases can take a significant amount of time, during which WAL is accumulated. This WAL needs to be replayed after a restore before it's in a consistent state. The longer these backups take, the longer the WAL replay takes after a restore as it may be necessary to replay hundreds of GB of WAL.
For this reason, currently when we are creating a new replica from the primary, we are using a script with rsync in several stages. We could use pg_basebackup to create a replica, but it'd take several days, during which so much WAL is accumulated that it'd take even longer to replay this. So instead, we do this roughly as follows:
- rsync the data directory first (could call this sequentially twice or three times even, each rsync run will get faster as less has changed in the meantime)
- call pg_start_backup and start pg_receivewal
- rsync data dir again, comparing timestamps - this is now very fast as it's sort of an "incremental backup" compared to the last rsync that was run.
- pg_stop_backup
In order to get to a consistent state we only need the WAL that was generated during the last rsync.

We are not interested in all WAL. We explicitly don't want WAL archiving to the repo host to be on all the time. For other databases, we use the conditional WAL archiving check for this that tests if the pgbackrest lock file is currently present.

I was wondering if a procedure like I described would make sense if it is supported in pgbackrest for regular backups. So a two-step approach in creating a backup:
- copy all files first (in the case of an incremental backup, only copy the files that have changed since the last backup of course) -- possibly repeat this several times
- pg_start_backup (and indicate in some way, perhaps a less hacky way than via the .lock file, that WAL archiving should start)
- copy all files that have changed, comparing timestamps
- pg_stop_backup

With this, it's possible to create a backup where you barely need any WAL replay after a restore. (Obviously, a full restore would still take a decent amount of time as it needs to copy all data)

What are your general thoughts on such a feature?

**Comment by dwsteele** [comment]
> First question: the documentation suggests that when doing an incremental backup, it verifies whether or not it needs to include a file in the backup using checksums.

By default timestamps are used for diff/incr backups. Checksums are only used when `--delta` is specified.

> currently when we are creating a new replica from the primary, we are using a script with rsync in several stages

It is not safe to use rsync for backup in this manner unless the second rsync specifies `--checksum`. Here's why: If postgres modifies a file during the same second that rsync builds the manifest and copies it, the change will not be seen by the second rsync. On a small, busy database I can reproduce this about 70% of the time. Larger databases may be less vulnerable because of the time it takes to build the manifest, but that's not a chance I'd take.

We have found that the clog is particularly vulnerable to this issue since the clog segments do not change size, which might clue rsync that something was changed. The result is that committed transactions may be lost. Any type of corruption is possible, but this is one that came up a lot in testing.

In pgBackRest, we solve this problem by waiting the remainder of the current second after building the manifest before copying anything. That way any changes by Postgres in the same second will be copied and any subsequent changes will update the timestamp. See https://github.com/pgbackrest/pgbackrest/blob/release/2.36/src/command/backup/backup.c#L287.

> I was wondering if a procedure like I described would make sense if it is supported in pgbackrest for regular backups. So a two-step approach in creating a backup:

We have been considering this feature for a few years. See https://github.com/pgbackrest/pgbackrest/projects/2#card-36304273.

**Comment by fvannee** [comment]
Thank you for your response.

> It is not safe to use rsync for backup in this manner unless the second rsync specifies --checksum. Here's why: If postgres modifies a file during the same second that rsync builds the manifest and copies it, the change will not be seen by the second rsync. On a small, busy database I can reproduce this about 70% of the time. Larger databases may be less vulnerable because of the time it takes to build the manifest, but that's not a chance I'd take.

This is probably the behavior of rsync that is discussed here: https://bugzilla.samba.org/show_bug.cgi?id=11521
Am I correct that using rsync >= 3.1.3 ( https://download.samba.org/pub/rsync/NEWS#3.1.3 ) with the appropiate filesystem that supports subseconds and the appropiate rsync option to consider subsecond resolution would solve this?

Why does pgbackrest also implement this extra 1 second sleep though. Is it to support filesystems that don't have the subsecond resolution? Or does pgbackrest, when building its diff manifest, also not consider subsecond resolution? When looking in the `manifest.backup` file for pgbackrest, it seems the latter is the case, as the `timestamp` field there seems to be in second-resolution.

> We have been considering this feature for a few years. See https://github.com/pgbackrest/pgbackrest/projects/2#card-36304273.

Nice, I'll have a look.

**Comment by dwsteele** [comment]
> Am I correct that using rsync >= 3.1.3 with the appropiate filesystem that supports subseconds and the appropiate rsync option to consider subsecond resolution would solve this?

I don't know since I haven't tried to break it. I wasn't aware that they had finally addressed this issue until just now. My production systems (Ubuntu 18.04) don't have this version so most others probably don't as well. It would certainly make it much harder, but not impossible, to hit the issue.

> Why does pgbackrest also implement this extra 1 second sleep though. Is it to support filesystems that don't have the subsecond resolution?

Yes. It's easier to have one solution that works for all file systems rather than switch. We sleep for the *remainder* of the current second so the delay is rarely a full second.

We implemented this method in 2013 and of course technology has moved on so we continue to evaluate. In the next manifest version we may at least store ms precision. One issue is I don't see any Posix-standard way to get ms precision file timestamps. Poking at the rsync code could provide some answers.

**Comment by fvannee** [comment]
> One issue is I don't see any Posix-standard way to get ms precision file timestamps. Poking at the rsync code could provide some answers.

These are the fields used by rsync for nanoseconds:
https://github.com/WayneD/rsync/blob/master/rsync.h#L427

**Comment by dwsteele** [comment]
We have a card for the suggested feature in this issue, so closing.
