### ISSUE TITLE
--archive-copy option doesn't backup timeline history files (e.g 00000004.history)

### ISSUE THREAD

**Issue by abubakarm94** [pgbackrest/pgbackrest#1598]
1. pgBackRest version: pgBackRest 2.36
2. Postgres version: postgres (PostgreSQL) 14.1

Description: 

Currently, --archive_copy does not backup the timeline history files, which causes an issue when timelines have changed and you'll like to use the wal files to achieve consistency rather than recovery.conf/recovery.signal. 

When archive-copy is enabled, pgbackrest should backup the timeline history files as well in other to fully support the use-case described here in the docs

```
11.1.15 Type Option (--type)
none - no recovery.conf file is written so PostgreSQL will attempt to achieve consistency using WAL segments present in pg_xlog/pg_wal. Provide the required WAL segments or use the archive-copy setting to include them with the backup.
```

Steps to replicate:
1. Create an HA cluster (primary and secondary)
2. Force a timeline switch at least twice (e.g when there is a failover between primary and secondary)
3. Perform a backup during pgbackrest with --archive-copy option enabled (e.g pgbackrest backup --stanza=${BACKUP_STANZA_NAME} --type=full --archive-copy)
4. Perform a restore of the backup that was executed on step 3
a. Make sure --type is none or remove the recovery.conf/recovery.signal file after restore the primary
b. Once the primary is up and running, start up the secondary, take note that the secondary instance is not able to come up because of missing timeline files
```
ERROR Failed to request TIMELINE_HISTORY: ERROR:  could not open file "pg_wal/00000002.history": No such file or directory ```

**Comment by pgstef** [comment]
Hi,

First of all, in a "HA" cluster, why wouldn't you want to use the PG `restore_command`? When combined with a PITR setup, archives are a very good safety-net for your streaming replication... Even dedicated HA tools like Patroni offers a way to specify recovery settings like the restore_command to use to bootstrap the cluster.

Imho, archive-copy is there to make a self-consistent backup. So only wal archives generated during the backup should be copied. And it would seem very strange to have a timeline switch during the backup. 

All the timeline switches that happened before the backup shouldn't be needed since all the wals are now referring to the current timeline. Restoring the "self-contained" backup to start your primary will cause a new timeline switch (and generate a new history file). So that history file wouldn't be known at the backup time and couldn't be copied in it. Restoring the "self-contained" backup again to create a standby will then miss that last history file at least. 

So, even coping all previously existing history files inside the backup directory itself wouldn't, imo, solve your problem. A new backup taken once your primary is correctly setup would probably solve your problem and be a good idea (on a production system) anyway...

The best answer should be to use the `restore_command` though. That's why it exists. 

Kind Regards

**Comment by dwsteele** [comment]
Agreed. The purpose of `archive-copy` is to copy WAL generated during the backup to make the backup self-sufficient (so it can be backed up to tape, for example). No timeline files are generated during a backup so there are none to copy. `restore_command` is the solution.
