### ISSUE TITLE
feature request: also report min/max archive creation times in info command

### ISSUE THREAD

**Issue by ikzelf** [pgbackrest/pgbackrest#1625]
The info command already reports the min and max wall numbers. It would be very nice to also get the creation times of the specified archives. This gives a better insight into our recovery options.

**Comment by dwsteele** [comment]
We have considered this, but we'd need to use the timestamps on the files in the repo since we don't store the timestamp in metadata. That means this information would change if the file timestamps change.

We are planning to store metadata about the WAL in a future release and at that time we'll expose the timestamps.

**Comment by ikzelf** [comment]
Thanks for the update, can't wait to see it pop up.
