### ISSUE TITLE
Security concerns with documented Dedicated Repository Host solution

### ISSUE THREAD

**Issue by yennor** [pgbackrest/pgbackrest#1627]
I've been following the guide on https://pgbackrest.org/user-guide.htm for the Dedicated host repository.
There the database server gets ssh access to the repository and with the paramater
`command="/usr/bin/pgbackrest ${SSH_ORIGINAL_COMMAND#* }"`
It is only allowed to execute the command pgbackrest. But with any parameter
There my security concern is, that if the database host is compromised, an attacker could execute on the backup host the command
`pgbackrest stanza-delete --force`
and then we've not only lost the database, but also the backups from it.
is there a way to avoid that?
For example pg_probackup has the agent parameter. So you set ssh to only be allowed to execute 
`pg_probackup agent`
which only receives data for the backup.
Does pgbackrest offer a similar parameter?

**Comment by pgstef** [comment]
Hi,

I'm don't understand your remark about pgprobackup but that's not really the point.

pgBackRest needs RW access to the repo for a lot of commands, not only stanza-delete. And that's the case when using dedicated repo hosts or directly attached storage (cloud, nfs,..). Theoretically, the attacker could simply drop all your databases and take a new backup which would expire everything else.

Perhaps the best approach here would be to secure your db hosts and regularly export the content of your repo to a "cold" storage somewhere safe ? (like the old-school tape backup systems...)

Hope this helps,
Kind regards

**Comment by yennor** [comment]
the remark with pgprobackup was about, that it has a single parameter "agent", which opens a process which only receives data for the backups. Like that you can restrict the allowed command to be executed over ssh to exactly this one. Like that an attacker can not execute any other command/parameters to delete or alter your backups.

**Comment by dwsteele** [comment]
We pass parameters to our "remote" process so just running `pgbackrest remote` is not going to work, I think, even if we put the command first, which we don't currently. SSH command is just not very flexible. We might be able to get something like that working, but it seems moot, because...

1) You can run stanza-delete from the pg host and delete the stanza just as easily. No need to do run anything directly on the remote host. So perhaps that's a security issue but not one that SSH will help with.

2) You can use TLS (https://pgbackrest.org/user-guide-rhel.html#repo-host/setup-tls) instead of SSH and avoid the remote execution issue, though no 1 still applies.

In general @pgstef is right. The best thing to do is copy backups to a read-only medium that is not vulnerable to these sorts of attacks. Even if we improved this on SSH it would not work on systems that write directly to S3, for example.

**Comment by yennor** [comment]
I see.
So right now it basically is necessary to make a backup of your db backup server.
Most backup programms provide out of that reason a client server architecture. Where the client can not do anything else, than starting a backup and sending data...
Obviously, if you directly attach storage like S3, then you need to do a separate backup of that storage.

**Comment by dwsteele** [comment]
You'll need separate, secured backups in *every* case. What if they break into the repo host instead of the pg host? Or hop over with an SSH bug, or somebody accidentally runs stanza-delete, or, or...

Major enterprises I have dealt with make a weekly full backup with `archive-copy` and then copy that backup from the repo to tape or an object store that does not allow deletes.

Don't get me wrong -- you have good points. But there are so many ways things can go wrong that I think there is little choice but to have secondary backups for your data, if you care about it.

**Comment by bradnicholson** [comment]
Long term - support for WORM is the ideal solution to this problem.

**Comment by dwsteele** [comment]
That's a lot more challenging than you might think. The main thing is that failed backups last for the entire retention because there is no way to resume or remove them. What I want is a way to mark backups read only when they are done but I don't see any good way to do that.

Another challenge is making `info` fast since it will be much harder to summarize.

However, we know this is something we'll need to support going forward. Just not quite sure how to go forward. :) Certainly there will need to be some concessions vs how things work now.

**Comment by yennor** [comment]
Of course you need more than one valid backup. I mainly wanted to know, if pgbackrest supports something like that. Since for me it wasn't completely clear from the documentation.
My main point is that at the moment, the backups made with pgbackrest are a bit better, than copying the data to an attached usb drive or similar. It helps against hardware failure, and accidentally changing data. But it doesn't count as a backup in the case of a break in. If you count it as a real backup and only make a second weekly backup to a read only storage somewhere, you almost guaranteed will loose up to a week's work in case of a break in...
Maybe it would be good to mention that in the guide.

**Comment by bradnicholson** [comment]
> That's a lot more challenging than you might think. The main thing is that failed backups last for the entire retention because there is no way to resume or remove them. What I want is a way to mark backups read only when they are done but I don't see any good way to do that.

Honestly,  I don't think that is all that terrible, because: 

> Certainly there will need to be some concessions vs how things work now.

100%. As long as those tradeoffs are reasonable and clearly documented - I'd fully expect that. And WORM potentially using  a lot more storage is a tradeoff I'd see as acceptable. Most people I encounter that want this type of protection also want to keep years worth of backups (due to regulatory requirements) - storage isn't really a concern.

I think that multi-repo support also adds a dimension to this. You can do your regular backups to standard repo and backup to WORM at a lower cadence.

**Comment by dwsteele** [comment]
> What I want is a way to mark backups read only when they are done but I don't see any good way to do that.

I wonder if there is a way to "save" these backups by just writing new files when something has changed and keeping the files that still match. Something to consider.

> storage isn't really a concern

I'm still waiting for somebody to tell me this. :) 

Recently ransomware has become a major concern and this is another reason why we need this type of functionality.
