### ISSUE TITLE
Archive WAL files in pgbackrest repository without .gz format

### ISSUE THREAD

**Issue by moindba** [pgbackrest/pgbackrest#1663]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.37

2. PostgreSQL version:
11.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHEL 7.6

4. Did you install pgBackRest from source or from a package?
Install From RPM Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[global]
repo1-path=/u02/bkp
repo1-retention-full = 2
repo1-retention-full-type = count
repo1-retention-diff = 7
repo1-retention-archive = 7
process-max = 2
log-level-console = info
#log-level-console = warnings
#log-level-console = error
#log-level-console = detail
log-level-file = info
#log-level-file = warnings
#log-level-file = error
log-path=/u02/pgbackrest_logs
start-fast = y
delta = y
#backup-standby = y

[pg1]
pg1-path=/u03/postgres/data
#pg1-port=5432
#pg1-host=192.168.1.100
#pg1-user=postgres
#pg2-path=/u03/postgres/data
#pg2-port=5432
#pg2-host=192.168.1.101
#pg2-user=postgres    

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
    
postgres=# show archive_mode;
 archive_mode
--------------
 on
(1 row)

postgres=# show archive_command;
             archive_command
-----------------------------------------
 pgbackrest --stanza=pg1 archive-push %p

7. Describe the issue:

/u02/bkp/archive/pg1/11-1/0000000300000041

000000030000004100000062-178015de48625778e037e18c45ee9411a54f565c.gz 

In the archive repository i have noticed that archive WAL are getting in with some random value along with .gz format, as per our requirement we need the archive wal files as a default format (Example: 000000030000004100000062)  without any .gz, like how we get the WAL files in pg_wal the same way we want in archive repository.

Kindly help us how we can get the Archive WAL files in normal form same as pg_wal in pgBackRest Archive Respository directory ?

Is there any values we need to mention /etc/pgbackrest.conf file ?

**Comment by pgstef** [comment]
Hi,

The `.gz` part

**Comment by pgstef** [comment]
Hi,

The `gz` part comes from the compress-type option and can be removed if you disable compression.
But the remaining suffix is the SHA1 checksum that we use to verify file integrity. There is no way to omit it.

Kind regards

**Comment by moindba** [comment]
If my pgBackRest Repository destination is full, then how can remove ONLY Archive WAL files older than last 2days or 3days WITHOUT taking any new backup from pgbackrest ?

**Comment by pgstef** [comment]
After a new successful backup, the `expire` command is triggered automatically. That means you can run that `expire` command manually whenever you want. You can change your retention settings and run that command. 

There are some retention settings regarding the [archives](https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-archive). Those options will allow to keep less wal archives between the backups so you don't break your backups consistency but only your PITR capability between them.

Regarding the archives generated after your last successful backup, that's not possible to expire them with pgBackRest. There's no time retention setting for the archives because they should always be referring to a backup.

Usually the answer to "repository full" are: move to another storage, add storage to current repo or keep less backups.
