### ISSUE TITLE
archive-get, possible to use wildcards?

### ISSUE THREAD

**Issue by mattbunter** [pgbackrest/pgbackrest#1670]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.36
2. PostgreSQL version:
12
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS Linux release 7.6.1810 (Core)
4. Did you install pgBackRest from source or from a package?
Package

7. Describe the issue:
Need a solution for 38000 wals to restore to a certain directory (for a standby to catch up).
archive_get doesn't seem to like wildcards so we haven't been able to get these 38000 restored.

Is there a work-around? Besides creating a script with 38000 lines of archive-get?

**Comment by pgstef** [comment]
Hi,

The `archive-get` command (just like `archive-push`) is not there to run manually. It's meant to be called by PG itself.
 
What do you mean by `for a standby to catch up` ? If the streaming replication is lagging too far, you can set `restore_command`. PG will then fetch all the archives from the repo directly.

Given the amount of archives to restore, you could speed up the recovery using multiple processes (`process-max` combined with `archive-async=y` and `archive-get-queue-max`).

Kind Regards

**Comment by mattbunter** [comment]
Pgbackrest isn't on the standby, our primary feeds two standbys. We backup on the primary. Once we get them restored we need to copy these WALs from the primary to one of the standbys so that it can catch up. 

Is there a specific method to (just) restore WALs to the pg_wal directory?

**Comment by pgstef** [comment]
> Once we get them restored we need to copy these WALs from the primary to one of the standbys so that it can catch up.

Not only to catch-up the primary. Archives are there for the backup consistency too.

> Is there a specific method to (just) restore WALs to the pg_wal directory?

No, that's the `archive-get` command and it's meant to be used by PG itself.

If you restore a backup on your standby, you'll probably need to install pgBackRest there to use the restore command anyway. Using `--type=standby`, the restore command will also prepare PG `restore_command` for you.

So the "method" you're expecting (and probably the fastest way to achieve this) is to configure pgBackRest on the standbys to use **restore** and **archive-get** there. You even won't need the disk space for _38000_ wals locally since PG should be able to remove/recycle the wals used for the recovery along the way.

Regards,
