### ISSUE TITLE
IMDSv2 support?

### ISSUE THREAD

**Issue by nunopi** [pgbackrest/pgbackrest#1685]
Hi,
First of all, I just wanted to say thanks for this great pg backup open-source tool!

I have a question:
I'm working on sending pgbackrest backups to S3 in an AWS environment that has IMDSv2 enabled. ([AWS official documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html))

I was wondering if pgbackrest supports this? 
Is there any specific configuration that has to be done in order to get the credentials from this endpoint?

Thanks!

**Comment by dwsteele** [comment]
> First of all, I just wanted to say thanks for this great pg backup open-source tool!

Thank you!

> I'm working on sending pgbackrest backups to S3 in an AWS environment that has IMDSv2 enabled.

Do you mean *only* IMDSv2? pgBackRest does not support IMDSv2 yet so that's not going to work.

Clearly we need to do this update. I think the question is should we *require* IMDSv2 or allow some sort of soft failback. While IMDSv2 should be available on all AWS instances, I wonder if any third-party implementations have IMDSv1 but not IMDSv2 support.

One thing we could do is add a new `auto2` option that requires IMDSv2 while the current `auto` will use it when available. I'd rather not add that sort of complexity if we can avoid it, though.

Would you be willing to test this feature if we implement it?

**Comment by nunopi** [comment]
Thanks for clarifying! 
Yes, I mean only IMDSv2. The environment I'm working on doesn't allow IMDSv1.
I'd be happy with assisting in testing this feature, please let me know how can I help.
Yesterday I had a quick test to see if I could make it work:
[imdsv2.txt](https://github.com/pgbackrest/pgbackrest/files/8221765/imdsv2.txt)

(Please note that I'm not a C developer and there's probably issues with this patch since I've simply copy pasted functions I found and modified them to retrieve the IMDSv2 token. Also this doesn't handle falling back to IMDSv1)

**Comment by nunopi** [comment]
Yes, it does work in the limited testing I've performed. I did it in an EC2 environment that only allows IMDSv2 auth and was able to interact with the configured S3 bucket.
I've submitted a PR here: https://github.com/pgbackrest/pgbackrest/pull/1691

**Comment by dwsteele** [comment]
OK, I'll close this issue since we have a PR to work on.

How would you like your name to appear in the release notes?
