### ISSUE TITLE
primary database not found error on standby with s3 repo

### ISSUE THREAD

**Issue by fixed77** [pgbackrest/pgbackrest#1703]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.37

2. PostgreSQL version: 14.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 20.04

4. Did you install pgBackRest from source or from a package? Package

5. Please attach the following as applicable:
 - `pgbackrest.conf` 
[main]
pg1-path=/var/lib/postgresql/14/main
pg1-socket-path=/var/run/postgresql
pg1-port=5432

[global]
archive-async=y
process-max=4
log-level-file=detail
log-level-console=info
log-path=/var/log/pgbackrest
repo1-type=posix
repo1-host=backup
repo1-host-user=postgres
repo2-type=s3
repo2-storage-host=s3.cloudian
repo2-path=/
repo2-retention-full=2
repo2-s3-bucket=backup-bucket
repo2-s3-endpoint=s3.cloudian
repo2-s3-region=nord1
repo2-s3-key=xxx
repo2-s3-key-secret=xxx
repo2-cipher-pass=xxx
repo2-cipher-type=aes-256-cbc

- postgresql.conf settings applicable to pgBackRest (archive_command, archive_mode, listen_addresses, max_wal_senders, wal_level, port)
listen_addresses = '*'
max_wal_senders = 10
wal_keep_segments = 100
wal_level = 'replica'
hot_standby = on
archive_mode = on
archive_command = 'pgbackrest --stanza=main archive-push %p'

7. Describe the issue:

If I run check command on standby node with only posix repo pgbackrest detect that node is standby:
2022-03-25 10:11:44.334 P00   INFO: check repo1 (standby)
2022-03-25 10:11:45.202 P00   INFO: switch wal not performed because this is a standby
2022-03-25 10:11:45.302 P00   INFO: check command end: completed successfully (1577ms)

if i add s3 repo to config and run check i get error:
ERROR: [027]: primary database not found
       HINT: check indexed pg-path/pg-host configurations
2022-03-25 10:13:53.983 P00   INFO: check command end: aborted with exception [027]

**Comment by dwsteele** [comment]
The primary must be configured in order to make a backup. See https://pgbackrest.org/user-guide.html#standby-backup and https://blog.crunchydata.com/blog/pgbackrest-performing-backups-on-a-standby-cluster.

**Comment by fixed77** [comment]
Shouldn't the behavior be the same?

**Comment by pgstef** [comment]
> Shouldn't the behavior be the same?

Your repo1 config is using a repo host, so it expects that the backup will be run/triggered from there and you'd only need to push archives from the local PG to that repo host. (so it doesn't need any interaction between the standby and the primary)

Your repo2 is a "directly attached storage", so it expects to take a backup from the local server. We can take backups from standbys but need to reach the primary (shortly said, for the backup control session mostly). That's why the primary must be configured too.

So, you're in fact mixing 2 different use-cases (dedicated backup server vs. directly attached storage).
