### ISSUE TITLE
Does pgBackRest employ continuous archiving or streaming in some way?

### ISSUE THREAD

**Issue by x-yuri** [pgbackrest/pgbackrest#1716]
I'm mainly concerned in minimizing RPO (amount of data that can be lost) without running a replica. From the user guide it seems like the only option to minimize RPO is to make backups more frequently. I mean [Barman][a] can supposedly make use of the pg's streaming protocol and achieve RPO close to 0 without running a replica. This seems to be unavailable with pgBackRest, right?

On the other hand I can see that pgBackRest is using the `archive_command` option. Can you elaborate on how it's used? Does pgBackRest additionally archive the WAL files (continuous archiving), and as such maximum RPO = 1 WAL file?

[a]: https://docs.pgbarman.org/release/2.19/

**Comment by MichaelDBA** [comment]
Seems to be at least that good, down to the last archived WAL.

**Comment by pgstef** [comment]
Hi,

Any live backup (taken with pg_basebackup or 3rd party tools using pg_start/stop_backup) requires WAL archives for consistency: at least those generated during the backup.

Past that consistency point, and as long as you have them all, you can replay the WAL archives generated between your backups to get what is called "Point-in-time recovery".

There are 2 ways to get those archives. Using pg_receivewal or using archive_command. pg_receivewal combined with synchronous replication can probably achieve something like RPO close to 0. But that comes with some caveats and performance penalty. Barman is indeed able to use both methods, while pgBackRest only relies on `archive_command` (using the [archive-push](https://pgbackrest.org/command.html#command-archive-push) sub-command). 

With archive-push being able to asynchronously use multi-processes, you can usually achieve a higher archiving throughput than with pg_receivewal. That's also why pgBackRest relies on archive_command rather than pg_receivewal.

See the [user guide](https://pgbackrest.org/user-guide.html#quickstart/configure-archiving) for some examples.

> Can you elaborate on how it's used?

PG triggers the archive_command using the pgBackRest archive-push sub-command which will push WAL archives to the repo. When you restore a backup, WAL archives are fetched from the repo and replayed by PG.

> Does pgBackRest additionally archive the WAL files (continuous archiving), and as such maximum RPO = 1 WAL file?

PG does indeed push continuously WAL archives using pgBackRest archive-push. So, usually and as long as your archiving system is working properly, maximum data loss should indeed be 1 WAL file.

Kind Regards

**Comment by dwsteele** [comment]
You can also use `archive_timeout` to force archiving when there has been activity but not enough to fill a WAL segment.

**Comment by x-yuri** [comment]
I see. I somehow had an impression that pgBackRest allows only making "snapshots." Which is why seeing WAL files confused me. Although indeed a base backup is not... usable? without the WAL files produced while taking the backup. For some reason.

> With archive-push being able to asynchronously use multi-processes, you can usually achieve a higher archiving throughput than with pg_receivewal.

Isn't `pg_receivewal` about streaming log records as they're created? Well, I'm not particularly sure it's `pg_receivewal`. But I thought there was a way to stream records as they come not waiting for a WAL file to be filled up. Without running a standby. Or not?

Also, you say:

> pg_receivewal combined with synchronous replication can probably achieve something like RPO close to 0.

Which can be read as, "synchronous replication affects the way `pg_receivewal` works." The way I understand it, synchronous replication itself reduces RPO to 0 (or close). What `pg_receivewal` has to do with it?

**Comment by pgstef** [comment]
> I see. I somehow had an impression that pgBackRest allows only making "snapshots." Which is why seeing WAL files confused me. Although indeed a base backup is not... usable? without the WAL files produced while taking the backup. For some reason.

"For some reason" -> because Postgres. You should understand how Postgres handles data modifications to understand why you need the wals for the backup consistency. Basically said, all the modifications will first go into the wal files and then, asynchronously, Postgres will write those modifications into the data files. So, during your backup, the data files are still being modified. To be able to bring the data into a consistent state, the recovery process needs to replay the wal files generated during the copy. So you reach the "consistency" point at the backup stop time. 

> Isn't `pg_receivewal` about streaming log records as they're created? Well, I'm not particularly sure it's `pg_receivewal`. But I thought there was a way to stream records as they come not waiting for a WAL file to be filled up. Without running a standby. Or not?

`pg_receivewal` is indeed about fetching the wal archives via streaming replication while they are being generated. But then it depends on how long it takes to fill up the 16MB. If you are only generating, let's say, 1 WAL archive per hour, sure, pg_receivewal will get if faster. But if your db is under heavy write load, generating plenty of wals per minute, pgBackRest async archive-push will usually be faster than pg_receivewal.

> Which can be read as, "synchronous replication affects the way `pg_receivewal` works." The way I understand it, synchronous replication itself reduces RPO to 0 (or close). What `pg_receivewal` has to do with it?

pg_receivewal is using the streaming replication protocol. So the replication mode (synchronous or asynchronous) is directly affecting pg_receivewal.

Anyway, all this discussion is about Postgres knowledge and shouldn't happen here.

Regards
