### ISSUE TITLE
Running pgbackrest restore with --type=none creates a recovery.signal file 

### ISSUE THREAD

**Issue by abubakarm94** [pgbackrest/pgbackrest#1756]
### Description
Looking at the [docs](https://pgbackrest.org/command.html#command-restore/category-command/option-type), it is my understanding that when pgbackrest restore command is executed with --type set to none, a recovery.conf (pg 11) or recovery.signal file (pg 12,13,14) should have not been created. However, in Postgres 12, 13, and 14, the recovery.signal file is still created, leaving the server unable to start up with the following error. The same issue does not exist in Postgres 11, the recovery.conf file is not created. 
```
FATAL:  must specify restore_command when standby mode is not enabled
```

### Version details and command 
1. pgBackRest version: `2.38`

2. PostgreSQL version: `Postgres 12 ,13, 14`

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: `Ubuntu 18.04.6 LTS`

4. Pgbackrest restore command:
```
pgbackrest restore --config=/etc/pgbackrest/pgbackrest.conf --delta --set=20220520-134013F --stanza=<stanza> --type=none
```

**Comment by dwsteele** [comment]
We should test this before making a code change. So, do a backup with `archive-copy`, do the restore, remove `recovery.signal` and make sure it comes up as a primary with a timeline switch. Seems like we should add an integration test for this as well, so we don't get surprised later by behavioral changes.

**Comment by abubakarm94** [comment]
Hi @dwsteele, I could be wrong but I'm not certain that a timeline switch is desirable in this case. Since the goal of --type=none is for Postgres to use the files present in the pg_wal directory for consistency, from Postgres' perspective, this should be no different than a shutdown and start up? 
I tested it on my end and Postgres was able to come up as a primary without needing to perform a timeline switch

**Comment by pgstef** [comment]
> ```
> 2022-05-23 18:27:39.530 UTC [1667] FATAL:  requested timeline 2 is not a child of this server's history
> 2022-05-23 18:27:39.530 UTC [1667] DETAIL:  Latest checkpoint is at 0/5000060 on timeline 1, but in the history of the requested timeline, the server forked off from that timeline at 0/3000088.
> ```

That's because the TL switch occurs in a path before backup 2. So in this case, you should use `recovery_target_timeline=current` rather than latest (which is the default). With that setting and the 00000002.history file present, the recovery should end up with a new timeline switch -> 3.

**Comment by pgstef** [comment]
> We should test this before making a code change. So, do a backup with `archive-copy`, do the restore, remove `recovery.signal` and make sure it comes up as a primary with a timeline switch. Seems like we should add an integration test for this as well, so we don't get surprised later by behavioral changes.

I quickly tested it on PG14:
- backup with archive-copy
- restore --type=none, remove recovery.signal --> no timeline switch
- restore --type=none, with recovery.signal --> PG recovery doesn't even start

In our [current](https://github.com/pgbackrest/pgbackrest/blob/main/test/src/module/command/restoreTest.c#L1882) tests, we're expecting that the recovery.signal exists even if the [doc](https://github.com/pgbackrest/pgbackrest/blob/main/src/build/help/help.xml#L2073) says something else.

When the recovery.signal exists but there's no restore_command (which is the point of restore --type=none imho), PG fails to [validate the recovery parameters](https://github.com/postgres/postgres/blob/master/src/backend/access/transam/xlogrecovery.c#L1070).

If we don't want to accept recovery without TL switch, perhaps we should remove the `--type=none` option?
Or open a discussion in PG community to use recovery.signal without restore_command to kinda enforce a TL switch for each restore type possible?

Writing an integration test for the current situation, so we don't get surprised later by behavioral changes, sounds like a good idea indeed. Where should we put it? In `restoreTest.c` or in `RealAllTest.pm`?

**Comment by swati-nair** [comment]
Hi @pgstef, I tried setting  `recovery_target_timeline=current` in the pgbackrest restore command as below and follow the steps provided by @abubakarm94 :

`pgbackrest restore --config=/etc/pgbackrest/pgbackrest.conf --delta --set=20220601-235926F --stanza=<stanza-name> --target-timeline=current`

If I set target-timeline, then I need to set `--type` to one out of these: ('default', 'lsn', 'name', 'standby', 'time', 'xid'). But, we can't use any of these types since we want to restore to a particular backup set and not do a PITR or have a restore point specified. So, I tried running it with the `default` type.

The issue here is that the default type reads until the end of the archive stream, which includes the transactions after the specified backup set. Even though the restore worked (with proper timeline switching), the data that was restored wasn't as expected, it included subsequent transactions.

Could you advise on what would be the correct way (if it's at all possible) to configure the `recovery-target-timeline` to current and to restore to the backup set provided in the `--set` option?

**Comment by pgstef** [comment]
Hi,

> Could you advise on what would be the correct way (if it's at all possible) to configure the `recovery-target-timeline` to current and to restore to the backup set provided in the `--set` option?

This is a totally different use-case. When you want to restore a specific backup set and not restore the archived wal stream, you don't need to play with timeline options, you simply need to use `--type=immediate` to recover only until the database becomes consistent.

**Comment by tirelibirefe** [comment]
> Hi,
> 
> > Could you advise on what would be the correct way (if it's at all possible) to configure the `recovery-target-timeline` to current and to restore to the backup set provided in the `--set` option?
> 
> This is a totally different use-case. When you want to restore a specific backup set and not restore the archived wal stream, you don't need to play with timeline options, you simply need to use `--type=immediate` to recover only until the database becomes consistent.

Hello,
Have you ever tried to restore from a specific backup by using `--type=immediate` option?

It doesn't work as described.

Thanks & Regards

**Comment by pgstef** [comment]
Hi,

> Hello, Have you ever tried to restore from a specific backup by using `--type=immediate` option?
> 
> It doesn't work as described. pgbackrest ignores `--type=immediate `and restores the latest backup.

Well, I actually used it several times yes and just re-tested it with the following simple use-case:

```bash
$ pgbackrest --stanza=ro8pg backup --type=full
$ psql -c "CREATE TABLE test (c1 text);"
$ psql -c "INSERT INTO test VALUES ('step 1');"
$ psql -c "SELECT pg_switch_wal();"

$ pgbackrest --stanza=ro8pg backup --type=full
$ psql -c "INSERT INTO test VALUES ('step 2');"
$ psql -c "SELECT pg_switch_wal();"

$ pgbackrest --stanza=ro8pg backup --type=full
$ psql -c "INSERT INTO test VALUES ('step 3');"
$ psql -c "SELECT pg_switch_wal();"

$ pgbackrest info
...
wal archive min/max (14): 000000010000000000000010/000000010000000000000017

full backup: 20220610-084911F
    timestamp start/stop: 2022-06-10 08:49:11 / 2022-06-10 08:49:14
    wal start/stop: 000000010000000000000010 / 000000010000000000000010
    database size: 25.2MB, database backup size: 25.2MB
    repo1: backup set size: 3.2MB, backup size: 3.2MB

full backup: 20220610-085056F
    timestamp start/stop: 2022-06-10 08:50:56 / 2022-06-10 08:50:59
    wal start/stop: 000000010000000000000012 / 000000010000000000000013
    database size: 25.2MB, database backup size: 25.2MB
    repo1: backup set size: 3.2MB, backup size: 3.2MB

full backup: 20220610-085152F
    timestamp start/stop: 2022-06-10 08:51:52 / 2022-06-10 08:51:55
    wal start/stop: 000000010000000000000016 / 000000010000000000000016
    database size: 25.2MB, database backup size: 25.2MB
    repo1: backup set size: 3.2MB, backup size: 3.2MB
```

So, `20220610-084911F` doesn't contain the table.
`20220610-085056F` contains the table with 'step 1'.
`20220610-085152F` contains the table with 'step 1' and 'step 2'. 
If replaying the entire archives stream, we should have 'step 3' too (contained in 000000010000000000000017).

Stop the cluster and restore `20220610-085056F`:

```bash
$ psql -c "SELECT * FROM test;"
   c1   
--------
 step 1
 step 2
 step 3
(3 rows)

$ sudo systemctl stop postgresql-14
$ sudo rm -rf /var/lib/pgsql/14/main/data/
$ pgbackrest --stanza=ro8pg restore --type=immediate --set=20220610-085056F
...
INFO: repo1: restore backup set 20220610-085056F, recovery will start at 2022-06-10 08:50:56
INFO: write updated /var/lib/pgsql/14/main/data/postgresql.auto.conf

$ cat /var/lib/pgsql/14/main/data/postgresql.auto.conf
# Recovery settings generated by pgBackRest restore on 2022-06-10 08:58:18
restore_command = 'pgbackrest --stanza=ro8pg archive-get %f "%p"'
recovery_target = 'immediate'
```

From PG logs:
```
LOG:  consistent recovery state reached at 0/13000088
LOG:  database system is ready to accept read-only connections
LOG:  recovery stopping after reaching consistency
LOG:  pausing at the end of recovery
HINT:  Execute pg_wal_replay_resume() to promote.
```

And guess what? It worked:

```bash
psql -c "SELECT * FROM test;"
   c1   
--------
 step 1
(1 row)
```

pgBackRest only restores the files and prepares the configuration so PG can actually perform the recovery. It is important to understand recovery targets and timelines in PG itself.
The `--type=immediate` will only configure PG `recovery_target = 'immediate'`. I don't see why it couldn't use the backup set specified with `--set`.

If you encounter an issue with this `--set=... --type=immediate` use-case, please open a new issue with the details of your config/test rather than commenting on closed (or unrelated) issues.

Thanks & Kind Regards
