### ISSUE TITLE
Issue during performing PITR on a Streaming Replication setup

### ISSUE THREAD

**Issue by muhammadali54321** [pgbackrest/pgbackrest#1772]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

2.39

2. PostgreSQL version:

Postgresql 14.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

I have primary database A and standby database B and a Backup server C
Operating system: Centos 7

5. Did you install pgBackRest from source or from a package?

Source

6. Please attach the following as applicable:
 
Standby server logs

![image](https://user-images.githubusercontent.com/58175928/172501761-ecac3f33-dd0b-4325-8e2b-a6c3abb8370b.png)

7. Describe the issue:

PITR successfully works on primary. I followed the steps below which are a part of issue 
Scenario is that I have dropped a table which I want to recover.

https://github.com/pgbackrest/pgbackrest/issues/891

Steps: 
*) lets say my timeline at that time was 24.
*) Shutdown standby(so it doesn't get promoted) B and primary A
*) Set archive_command on primary A to false (note that this will cause archiving errors in the log) => Before PITR
*) Perform PITR on primary A(repeat until you have the right PIT).
*) Set archive_command on primary A to false again as old postgresql.conf will be restored after PITR
*) Start PostgreSQL and let it recover and after recovery, run pg_Wal_Replay_resume() on primary to promote it => This works successfully and I got the PIT and its sets new timeline to 25.
*) after above steps, set archive_command to "'pgbackrest --stanza=main archive-push %p' " to start archiving
-----------------------------------------------------------------------

*) Delta restore standby B from the same backup with --target-timeline=latest

I performed above using the following command on standby B
 pgbackrest --stanza=main --target-timeline=latest  restore --log-level-console=detail --delta
 
After this, I created standby.signal and added primary_conn_info inside postgresql.auto.conf to start it as a standby after recovery

 It takes me to original state where the table was dropped

Timeline on Server A is 25
Timeline on server B is 24.

and I can't even rejoin it using pg_rewind. Am I doing something wrong?

**Comment by pgstef** [comment]
Hi,

> Am I doing something wrong?

Unfortunately, yes. In streaming replication, you can't have 2 promoted clusters running at the same time.
Why are you blocking the primary archive command ? The all point of PITR is to use archives and timelines.

You could:

1. stop the standby
2. PITR restore your primary to a specific recovery target
- don't touch the archive_command
- promote your restored primary once it reached the target you expected
3. delta restore your standby server using `--type=standby`

Since you're above PG 12, the recovery_target_timeline is set to latest by default. So your restored standby will follow the latest WAL archives stream (the one generated by your PITR restore at step 2). The standby will then be on the same timeline as the primary and as soon as it replayed all the archives following the new path, it should try to connect to the primary using Streaming Replication (the --type=standby will create the standby.signal which should prevent the promotion).

But that's not a "pgBackRest specific behavior", it's a PG generic knowledge.

Hope it helps,
Kind Regards

**Comment by muhammadali54321** [comment]
Hello @pgstef 

As per your recommendation, I followed the steps.

Current timeline is 30. Take full backup using pgbackrest.
drop table A and table B
Now I want to recover table B using PITR.

1: Stop standby and primary server
2: run PITR on primary server where I recovered table B. = All good and after promotion, timeline is switched to 31
3: Go on standby and run the following command

pgbackrest --stanza=main --type=standby  restore --log-level-console=detail --delta

4: standby.signal is created and inside postgresql.auto.conf, there was no primary _conn_info added so I added it manually to connect with primary.
5: start standby and by checking the logs, it is started and recovering from archives.
6: After getting consistent state, I checked and couldn't recover table B on standby using --type=standby.

I also got this error that **highest timeline 30 of the primary is behind recovery timeline 31** on standby.

Can you please help with this.

**Comment by pgstef** [comment]
Also, a "good practice" is to take a new backup after a successful recovery. In theory, resync the old standby with replaying the wal archives will work, but restoring from a new backup (full or incr) would be faster.
