### ISSUE TITLE
backup_issues

### ISSUE THREAD

**Issue by SzhiH** [pgbackrest/pgbackrest#1777]
I run the backup through the ctonjob of k8s. When only one full or incremental backup is run, it can succeed. Once the two plans are all run, an error will be reported in the backup, as follows:

ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/main-backup.lock': Resource temporarily unavailable
       HINT: is another pgBackRest process running?
2022-06-09 08:10:13.785 P00   INFO: backup command end: aborted with exception [050]

**Comment by pgstef** [comment]
Hi,

> Once the two plans are all run

What do you mean by that?

The error is simply because 2 backup commands can't be run at the same time for the same stanza (and you wouldn't need to do it anyway).

**Comment by pgstef** [comment]
Is the 2nd one starting while the 1st one is still running ?
The lock file is there to prevent 2 backups to run simultaneously

**Comment by SzhiH** [comment]
Check whether the log backup is successful

**Comment by SzhiH** [comment]
Maybe I have a problem with my operation. Maybe there is a time conflict

**Comment by pgstef** [comment]
The error is pretty clear: `unable to acquire lock on file '/tmp/pgbackrest/main-backup.lock': Resource temporarily unavailable`.
The backup process can't get the lock. You now have to find out why.

It can be because 2 backups are running simultaneously (which is something you shouldn't need anyway) or it can be a system resource issue too.

**Comment by SzhiH** [comment]
ok， thank you
