### ISSUE TITLE
GPDB support

### ISSUE THREAD

**Issue by andr-sokolov** [pgbackrest/pgbackrest#1801]
Hi,
PostgreSQL has forks, one of which is GPDB (https://github.com/greenplum-db/gpdb). I would like pgbackrest to work with GPDB too. Are you going to implement support for PostgreSQL forks in pgbackrest? Are there any ideas how to implement? If my colleagues and I prepare a PR to support GPDB, will it be merged?

**Comment by andr-sokolov** [comment]
@woblerr , welcome.  https://github.com/arenadata/pgbackrest/pull/6 This patch is not ready to be in upstream, but it seems to be working. I want to rewrite it.

**Comment by dwsteele** [comment]
The way we have been planning to handle forks is by adding a `--pg-version` option (or something like that) to stanza-create that would force pgpackrest to accept the fork as version 10, 11, or whatever. In that case we would expect the fork to act exactly like Postgres does for that version.

**Comment by Stolb27** [comment]
I suggest removing the fork-version property, the forkVersion field and the FORK_VERSION macro. Since the pgTablespaceId function will be in interface, the PostgreSQL version and the fork name are enough to output a string of the desired format. In addition, the path in forks may have a different format.

**Comment by dwsteele** [comment]
Closing since there is now a PR under discussion.
