### ISSUE TITLE
Missing configure archiving on the pg-primary in the "Dedicated Repository Host" section of the documentation

### ISSUE THREAD

**Issue by silenius** [pgbackrest/pgbackrest#1802]
Hello,

Unless I misunderstood something there is an oversight in the "Dedicated Repository Host" section of the User Guide in the documentation regarding the archiving configuration on the `pg-primary`.

Something like:

_Backing up a running PostgreSQL cluster requires WAL archiving to be enabled on the pg-primary:_

```
archive_command = 'pgbackrest --stanza=demo archive-push %p'
archive_mode = on
max_wal_senders = 3
wal_level = replica 
```

**Comment by pgstef** [comment]
To be fair, a few points could be seen as missing compared to the quick start. The [configure-archiving](https://pgbackrest.org/user-guide.html#quickstart/configure-archiving) part is there (such as retention, encryption,...). 

The user-guide is a kind of step-by-step run-book. Each section being "the next step". We could probably add some loop links to let the user "think" to have a look in the previous sections but I don't think we should repeat everything here :thinking:

**Comment by dwsteele** [comment]
Yes, the user guide is meant to be followed sequentially. The PG primary is setup in the quickstart and so that's where the setup directions are. The repo-host section reconfigures the primary but does not change the Postgres configuration.

However, a link seems appropriate here so done in https://github.com/pgbackrest/pgbackrest/pull/1809. Please have a look.
