### ISSUE TITLE
[question] behavior of pgBackRest 

### ISSUE THREAD

**Issue by Dboy-Even** [pgbackrest/pgbackrest#1821]
Hi,

I would like some light on how pgBackRest works. I am currently trying to deploy it in my enterprise, but there's a behavior I don't understand.

### setup
pgbackrest runs on a virtual machine, with its main storage being a glusterfs mount point.
Pgbackrest is set up in TLS mode.

### FYI

1. pgBackRest version:
- 2.40 (2.37 was also tested with the same behavior)

2. PostgreSQL version:
- 13.5 (mostly) and 14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
- debian (11.4 and 11.2)

5. Did you install pgBackRest from source or from a package?- build from source
- source (build on debian 11.4)

### behavior

Backup seems to run and transfer perfectly (at first). I'm having transfer speed of up to 200MB/sec with an average around 130.
But, when it seems all the data is transferred. The backup process continues for much longer!

```
full backup: 20220720-183548F
            timestamp start/stop: 2022-07-20 18:35:48 / 2022-07-20 21:51:36
            wal start/stop: 000000010000004100000096 / 00000001000000410000009C
            database size: 159.8GB, database backup size: 159.8GB
            repo1: backup set size: 37.2GB, backup size: 37.2GB
```
Is the resulting backup, but according to my self monitoring :P (pfsense bandwidth usage on the network) that quantity of data would have been transferred in around 20-40 minutes.
Yet, at around 19h20, no visible data were being transferred !

Of course, I wasn't there during all the process, but it doesn't seems any data were exchanged (less than 1MB/sec)

Could you shed some light on what happens during the backup ?
I believe it something like :
- transfer the database files
  - would there be checksum / metadata being transferred/checked afterward that could play badly with gluster?
- synchronize the wals
- apply retention policy

I'll provide information as best as I can, but I didn't set any detailed logs (set to default).

Thank you for your time,
regards,
Even

**Comment by dwsteele** [comment]
No way to tell with logs. Even the default level file log for the backup would be helpful.

At a guess, your archiving is running slowly and the backup is waiting for it to finish. You have not provided a config so not much I can say about that. If you want archiving to run faster, see https://pgbackrest.org/user-guide.html#async-archiving.

**Comment by Dboy-Even** [comment]
Hi,

Thank you for your help !
Took some time, but here's everything :

### config
```
[preprod]
pg1-path=/var/lib/postgresql/13/main
pg1-host=postgres-server
pg1-host-cert-file=<path to postgres-server.crt>
pg1-host-key-file=<path to postgres-server.key>
pg1-host-ca-file=<path to ca.crt>
pg1-host-user=postgres
pg1-host-type=tls
pg1-host-port=<pg1 tls port>

[global]
compress-level=3
compress-type=lz4
process-max=4
start-fast=y
spool-path=/var/spool/pgbackrest
archive-async=y
archive-get-queue-max=1G

repo1-cipher-pass=<encry key>
repo1-cipher-type=<encry methode>
repo1-path=/storage
repo1-retention-full=2
repo1-retention-diff=5
repo1-retention-archive-type=full
repo1-retention-archive=1

tls-server-address=*
tls-server-port=<repo tls port>
tls-server-cert-file=<path to pgbackrest.crt>
tls-server-key-file=<path to pgbackrest.key>
tls-server-ca-file=<path to ca.crt>
tls-server-auth=postgres-server=dev
```

As you can see, I put in place 'archive-async' as you advised, sadly, I don't think the problem's here

### log

backup started at 2022-07-22 17:26

at 17h50 it was at 99.00% (file size were around 1.1MB)
at 19h36, it was at 99.90% (8Kb) ...
at 19h59, it was at 99.99%

backup finished at 20:48

It seems that all those little files (around 40K smaller than 1MB) takes a huge amount of time.
Is there any means of doing this faster ?
- max-process is set to 4
- archive-async is on

here's the log file (it's an xz archive and not a zip 5.1/175M) :
[dev-backup_debug.log.zip](https://github.com/pgbackrest/pgbackrest/files/9197427/dev-backup_debug.log.zip)

Thanks again for your time.

**Comment by pgstef** [comment]
Hi,

First of all, `pg1-host=postgres-server` means you are on a repo-host. But you didn't provide the pg host config.
The archiving process is done on the pg host, so the archive-async thing should be configured there (and logs for the archive-push command will be found in the PG logs).

Given the logs, I don't think your problem comes from the archiving system anyway:

```
2022-07-22 17:26:26.903 P00   INFO: execute non-exclusive pg_start_backup(): backup begins after the requested immediate checkpoint completes
2022-07-22 17:26:27.543 P00   INFO: backup start archive = 0000000100000041000000B6, lsn = 41/B6000028
2022-07-22 17:26:27.543 P00   INFO: check archive for prior segment 0000000100000041000000B5
2022-07-22 17:26:38.397 P00   INFO: backup '20220722-162424F' cannot be resumed: resume is disabled
2022-07-22 20:48:28.776 P00   INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
2022-07-22 20:48:29.023 P00   INFO: backup stop archive = 0000000100000041000000B9, lsn = 41/B99666B8
2022-07-22 20:48:29.788 P00   INFO: check archive for segment(s) 0000000100000041000000B6:0000000100000041000000B9
2022-07-22 20:48:31.441 P00   INFO: new backup label = 20220722-172626F
2022-07-22 20:49:56.307 P00   INFO: full backup size = 159.8GB, file total = 151375
2022-07-22 20:49:56.312 P00   INFO: backup command end: completed successfully (12211336ms)
```

Clearly the most time is spent on copying files. pgBackRest relies on PG physical backup method (and continuous wal archiving). While archive-async might speed up the archive_command, the backup command will need to copy every data file. It can be compressed and encrypted. Max-process will define the number of files treated in //. Network bandwidth, cpu usage for compression, read or write IO could slow you you down but the problem here is probably the number of small (or empty) files in your db.

Looking at the `...DETAIL: backup file postgres-server...` log lines, we can see that 50 minutes are needed to transfer 99% of your database and the remaining time is used to transfer more than 150.000 small files (< 1MB). Something meaningful from the logs too is the number of files to handle that are 16KB, 8KB or 0KB. As an example, it takes 48 minutes to simply create the empty files "`(0B, 100.00%)`". You should probably have a look at the [file bundling](https://pgbackrest.org/user-guide.html#backup/bundle) feature which might help reduce the time taken to handle the small files.

Kind Regards

**Comment by Dboy-Even** [comment]
Hi,

Sorry, Should have replied sooner.
File bundling was exactly what I needed! Reduced the backup from 2h30 min to 17 min!

Thank you for your time and dedication, that's amazing work !

regards,
Even
