### ISSUE TITLE
pgbackrest throw warning `20220415-051530F_20220721-002602I of same type exists -- remove invalid files and resume` 

### ISSUE THREAD

**Issue by Bhautik0110** [pgbackrest/pgbackrest#1822]
`pgbackrest` throw below-mentioned warning after postgresql restart. Below I mentioned the full log.

```
time="2022-07-22T01:03:11Z" level=info msg="crunchy-pgbackrest starts"
time="2022-07-22T01:03:11Z" level=info msg="debug flag set to false"
time="2022-07-22T01:03:11Z" level=info msg="backrest backup command requested"
time="2022-07-22T01:03:11Z" level=info msg="command to execute is [pgbackrest backup --stanza=db --repo=1 --type=incr]"
time="2022-07-22T01:05:45Z" level=info msg="output=[]"
time="2022-07-22T01:05:45Z" level=info msg="stderr=[WARN: a timeline switch has occurred since the 20220415-051530F_20220720-002532I backup, enabling delta checksum\n      HINT: this is normal after restoring from backup or promoting a standby.\nWARN: resumable backup 20220415-051530F_20220721-002602I of same type exists -- remove invalid files and resume\n]"
time="2022-07-22T01:05:45Z" level=info msg="crunchy-pgbackrest ends"
```
What files do I need to remove / Do I need to take any full backup?

**Comment by dwsteele** [comment]
Warnings are never fatal so there should not be anything for you to do.

The first warning lets you know that checksums will be during the backup because a timeline switch was detected. In this case timestamps are not reliable.

The second warning lets you know that a prior failed backup and is being resumed. As long as there is no error after this you should be fine.

Is the `20220415-051530F_20220721-002602I` backup now in the info output?

**Comment by Bhautik0110** [comment]
Done, automatically handled by `pgbackrest`. and warning is gone. Thanks.
