### ISSUE TITLE
restore to irrelavant server

### ISSUE THREAD

**Issue by mencutekin** [pgbackrest/pgbackrest#1834]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.37

2. PostgreSQL version: 14.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL 8.4

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

I have 2 node patroni cluster and I want to restore my pgbackrest backup to irrelevant server in order to restore testing. I added my environment config below.

![resim](https://user-images.githubusercontent.com/91777324/183854255-2cbb04ce-1792-458d-ad7a-77498efe8dc0.png)

I have taken backup from standby node successfully, and I want to restore this backup to a server (10.40.12.250). I can restore this backup on the same server, but I want to restore for another server.

How can I perform this operation? 

Thank you so much for your help.

**Comment by robinportigliatti** [comment]
Hello,

Please copy and paste your configuration files.

Best regars,

**Comment by pgstef** [comment]
> How can I perform this operation? 

That's a pretty common operation. Trying to restore a backup regularly on a test server is indeed usually a good idea.

The first step would be to be able to reach the repo from the test server. It it obviously recommended to only give a read only access to avoid messing with the production data. (A successful recovery would trigger a timeline switch and push new WAL archives to the repo.)

It seems that you're using a NFS storage, so that would be easy to (RO) mount it on the test server too.

Then, you simply can setup a basic pgbackrest local configuration on the test server and use the restore command. Using the `--archive-mode=off` option to disable the archiving on the test cluster is also a good practice (so it doesn't push anything to the production repo).

Btw, using the NFS storage for lock and spool path isn't recommended and could lead to some unexpected issues. Having the spool path next to the pg_wal directory (same disks) usually speeds up PG recovery. But that's not the topic of this issue ;-)

Have a nice day,
Kind regards

**Comment by mencutekin** [comment]
Thank you so much Stefan for your valuable answer and warning.
