### ISSUE TITLE
ERROR: [029]: repo2: unable to find child 'NextContinuationToken':0 in node 'ListBucketResult'

### ISSUE THREAD

**Issue by ymtvs** [pgbackrest/pgbackrest#1880]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.41

2. PostgreSQL version: 14 and 13

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: centos 7 

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
```
[test-14]
pg1-host=host1
pg1-host-user=postgres
pg1-path=/pgsql-data
pg1-port=5432
pg2-host=host2
pg2-host-user=postgres
pg2-path=/pgsql-data
pg2-port=5432
pg3-host=host3
pg3-host-user=postgres
pg3-path=/pgsql-data
pg3-port=5432
repo2-path=/pgbackrest-backups
repo2-s3-bucket=pgbackrest-backups
repo2-s3-endpoint=endpoint.com
repo2-s3-port=6780
repo2-s3-key=ket
repo2-s3-key-secret=key-secret
repo2-s3-region=default
repo2-type=s3
repo2-s3-uri-style=path
repo2-retention-full=5
backup-standby=y
process-max=4
compress=y
repo1-retention-full=1
start-fast=y
stop-auto=y
resume=y
```
6. Describe the issue:

We are using two repositories. But s3(using OpenStack object storage) does not delete expired backups. Also this problem started when we upgrade to 2.40 .

```
2022-09-21 15:37:54.985 P00   INFO: expire command begin 2.41: --exec-id=11337-88ae6cd2 --log-level-console=detail --log-level-file=detail --repo=2 --repo1-path=/pgsql-backup --repo2-path=/pgbackrest-backups --repo1-retention-full=1 --repo2-retention-full=15 --repo2-s3-bucket=oms-pgbackrest-backups --repo2-s3-endpoint=endpoint.com --repo2-s3-key=<redacted> --repo2-s3-key-secret=<redacted> --repo2-s3-region=default --repo2-s3-uri-style=path --repo2-storage-port=6780 --repo2-type=s3 --stanza=test-14
2022-09-21 15:37:58.634 P00   INFO: repo2: remove expired backup 20220914-010150F
ERROR: [029]: repo2: unable to find child 'NextContinuationToken':0 in node 'ListBucketResult'
ERROR: [104]: expire command encountered 1 error(s), check the log file for details
2022-09-21 15:37:58.751 P00 DETAIL: statistics: {"http.client":{"total":2},"http.request":{"total":33},"http.session":{"total":2},"socket.client":{"total":2},"socket.session":{"total":2},"tls.client":{"total":2},"tls.session":{"total":2}}
2022-09-21 15:37:58.751 P00   INFO: expire command end: aborted with exception [104]
```

**Comment by dwsteele** [comment]
This is only checked when `IsTruncated=y` (https://github.com/pgbackrest/pgbackrest/blob/main/src/storage/s3/storage.c#L694), so it is likely that something is wrong with OpenStack's implementation. My guess is that it is ignoring our request for list v2 and is returning v1 format, which we do not support since it has been deprecated for many years. See https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html.

**Comment by ymtvs** [comment]
Thank you for the quick response. But this problem started when I upgraded pgbackrest v2.38 to v2.40. So I downgraded from V2.41 to V2.38, and V2.39 expired run successfully.

**Comment by pgstef** [comment]
Well, that's in the 2.40 release notes: [Use S3 IsTruncated flag to determine list continuation.](https://github.com/pgbackrest/pgbackrest/commit/845d82f6825d4101e6a465a435ef056ff6ec15a2).

And as David mentioned, that's how the API v2 works.

Regards

**Comment by dwsteele** [comment]
Yes, the API is very specific about this -- if IsTruncated=y then the NextContinuationToken must exist. Prior to 2.40 We just checked NextContinuationToken, which caused problems with other S3 clones that sent a blank NextContinuationToken when IsTruncated=n. As far as I can see that is also a violation of the spec, but we decided it was reasonable to add a check for IsTruncated=y before looking at NextContinuationToken, since the field exists for that purpose. Also, that's what boto3 does.

It's a bit of a balancing act since S3 clones tend to implement the API slightly differently. Our goal is the follow the S3 spec as closely as possible.

In this case, if it worked before, then it looks like your clone is setting IsTruncated incorrectly which would appear to be a bug in your clone.

**Comment by cbandy** [comment]
I don't know if this is the right place to look in OpenStack, but the following code might not be setting `NextContinuationToken` when `is_truncated`. 🤷🏻 

https://opendev.org/openstack/swift/src/tag/2.30.0/swift/common/middleware/s3api/controllers/bucket.py#L236-L242

**Comment by dwsteele** [comment]
Yeah, sure seems like it should error if one of these does not succeed. If `IsTruncated=true` then `NextContinuationToken` should always be set.

**Comment by dwsteele** [comment]
From the relevant S3 API docs: https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html
```
NextContinuationToken is sent when isTruncated is true, which means there are more keys in the bucket that can be listed.
```

**Comment by sfrost** [comment]
Agreed that, in this case, it's a bug in openstack which needs to be fixed because it's a much clearer violation of the spec and just plain wrong in what it is returning.
