### ISSUE TITLE
to setup multi repo, I need to recreate the stanza again? 

### ISSUE THREAD

**Issue by jianheMark** [pgbackrest/pgbackrest#1884]
This slide [0] introduce the multi repository feature. Now I want try multi repo feature.
related post: https://github.com/pgbackrest/pgbackrest/issues/965

Follow through the guide.html, first it's only single repo, then multi repo.
But multi repo explanations (https://pgbackrest.org/user-guide.html#multi-repo) only just 4 paragraphs.

I already created an stanza pg15_3 with single repo. 
If I just add repo2 under [global], pgbackrest check will fail. to a little bit of cautiously, want to confirm the following question. 

1. Do I need recreate the same name(pgsql15_3) stanza again? like `sudo -u postgres pgbackrest --stanza=pgsql15_3 --log-level-console=info stanza-create`

2. Previous single repo backup command is `sudo  -u jian pgbackrest --type=diff  --stanza=pgsql15_3 --log-level-console=info backup` So I need to add `--repo=repo2`? 
3. I guess if  point 2 is true, then I guess it will apply to restore. 

[0]: https://pgstef.github.io/talks/en/20220324_pgDayParis_Using-multiple-backup-repositories-with-pgBackRest.pdf

**Comment by pgstef** [comment]
Hi,

The `stanza-create` command initialize the repository. So when you add a new one, you need to re-run the `stanza-create` command again indeed. 

The `backup` command works per repository. So you should indeed add the `--repo` option.
When you don't specify `--repo`, the highest priority will be used by default (1 > 2 > ...). But we clearly advise to use `--repo=1` and `--repo=2` in your backup commands so that you exactly know before launching the command where the backup will land.

That also means that if you ask for a `diff` backup in repo2, that diff backup will be based on the last full backup in repo2, not in repo1. Both repositories are completely separated.

That also applies to the `restore` command yes. If you want to restore a specific backup set, you should specify from which repository you want to restore it.

Kind Regards
