### ISSUE TITLE
Custom Protocol spec

### ISSUE THREAD

**Issue by whisper-bye** [pgbackrest/pgbackrest#1904]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.40

2. PostgreSQL version: 14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: linux

4. Did you install pgBackRest from source or from a package? yes

I want to create a tool to remotely control a pgbackrest service through the custom protocol, Is there a protocol specification for reference?

**Comment by dwsteele** [comment]
We will not publish the spec for the binary protocol since it can change with every release. The protocol only implements primitives anyway so it would not be useful, i.e. you can't request a backup via the protocol but you can copy or remove a file.

We are planning to implement an endpoint for our TLS server that will allow you to do anything you would do from the command line, but that work is not currently scheduled.
