### ISSUE TITLE
Storing Backup and wal on different partition

### ISSUE THREAD

**Issue by Chets19c** [pgbackrest/pgbackrest#1914]
Hi, we are facing iops bottleneck at backup server... We are using the latest version of pg_backrest on CentOS 7.

Im trying to figure out from last few weeks if it's possible to define config in such way so that I can be able to store wal and backup on different partition in a same repo.. 

i.e i want to store backup in location /mnt/pg_wal
And backup inside /backup/pg_bkp

is there anyway i can achieve the above given requirement?

Any help would be appreciated..
Thanks

**Comment by pgstef** [comment]
> i.e i want to store backup in location /mnt/pg_wal
> And backup inside /backup/pg_bkp

Not sure to understand what's the question here. You can indeed store data/pg_wal on another partition. But there isn't any easy way to split your repo content (archive -  backup) into different location.

First of all because without the wal archives, the backups aren't consistent, so that's a risk (that could be mitigated by using the archive-copy option). And then, while wal archives are pushed all day long, backups are only pulled when you schedule/trigger it. I'm not sure why splitting those 2 folders would solve your iops issue.

Probably you can split those folder by using symlinks in your repo1-path. Something like this:
```bash
$ ls -l /var/lib/pgbackrest/
... archive -> /mnt/disk1/archive
... backup -> /mnt/disk2/backup
```
Creating the symlinks or mount points before running the stanza-create command could probably work, but I wouldn't really recommend doing it unless you know exactly what you are doing.

Kind Regards

**Comment by dwsteele** [comment]
> Creating the symlinks or mount points before running the stanza-create command could probably work

I have done this before and also put the mount points directly in `repo-path`. But I have not tested this recently so be sure you test before committing to production.
