### ISSUE TITLE
Archive ERROR[045]  after standby promote

### ISSUE THREAD

**Issue by jiangshuai1995** [pgbackrest/pgbackrest#1915]
### ERROR OUTPUTS
```
2022-11-01 14:30:43.851 P00   INFO: push 1 WAL file(s) to archive: 000000010000000000000055
2022-11-01 14:30:44.201 P01   WARN: could not push WAL file '000000010000000000000055' to the archive (will be retried): [45] raised from local-1 protocol: WAL file '000000010000000000000055' already exists in the repo1 archive with a different checksum
2022-11-01 14:30:44.201 P00   INFO: archive-push:async command end: completed successfully (356ms)
```

### Version
pgbackrest 2.39 
postgresql 9.6 

### DESC

archive_mode = on

I have a primary and two standby,  when I promote one of standbys ,  I noticed I was missing a **.done** file[000000010000000000000055.done]

```
[root@PG-xhjegke6ud pg_xlog]# ls -al

-rw-------  1 postgres postgres 16777216 Nov  1 10:25 000000010000000000000054
-rw-------  1 postgres postgres 16777216 Nov  1 10:25 000000010000000000000055
-rw-------  1 postgres postgres 16777216 Nov  1 10:27 000000010000000000000056.partial
-rw-------  1 postgres postgres       42 Nov  1 10:27 00000002.history
-rw-------  1 postgres postgres 16777216 Nov  1 10:27 000000020000000000000056
-rw-------  1 postgres postgres 16777216 Nov  1 10:28 000000020000000000000057
-rw-------  1 postgres postgres 16777216 Nov  1 10:28 000000020000000000000058
-rw-------  1 postgres postgres      338 Nov  1 10:28 000000020000000000000058.00000028.backup
-rw-------  1 postgres postgres 16777216 Nov  1 10:32 000000020000000000000059

[root@PG-xhjegke6ud archive_status]# ls -al

-rw------- 1 postgres postgres    0 Nov  1 10:25 000000010000000000000054.done
-rw------- 1 postgres postgres    0 Nov  1 10:27 000000010000000000000056.partial.done
-rw------- 1 postgres postgres    0 Nov  1 10:27 00000002.history.done
-rw------- 1 postgres postgres    0 Nov  1 10:27 000000020000000000000056.done
-rw------- 1 postgres postgres    0 Nov  1 10:28 000000020000000000000057.done
-rw------- 1 postgres postgres    0 Nov  1 10:28 000000020000000000000058.00000028.backup.done
-rw------- 1 postgres postgres    0 Nov  1 10:28 000000020000000000000058.done
-rw------- 1 postgres postgres    0 Nov  1 10:32 000000020000000000000059.done
``` 

When I reboot [systemctl restart postgres], the error appears.
Sure enough, a file appeared 
```
-rw------- 1 postgres postgres    0 Nov  1 14:27 000000010000000000000055.ready
```

This is not a coincidence, I think many people have encountered this problem
[#584](https://github.com/pgbackrest/pgbackrest/issues/584)

Although I do not think this is the problem of **pgbackrest**, but the problem of **postgres**
I still want more people to discuss this issue, Why is the **done** file not generated on the original standby?

Looking forward to everyone's reply!    

If someone can't reproduce after restart, I suggest to change the configuration and restart the database service again.

**Comment by jiangshuai1995** [comment]
Perhaps I've found the problem.

https://www.postgresql.org/message-id/CAEC-+VH5PrQyrVHZU-t55xfzUwhZ=XSFGtt6M13Aai8rqNMkcQ@mail.gmail.com

> It seems you agree that segment created during pg_basebackup with stream
mode, which is not marked with .done extension, would be attempted to be
archived again.

**Comment by dwsteele** [comment]
This certainly does seem to be an issue with Postgres. Do you know if this was fixed in newer versions? Since 9.6 has been EOL for a year there's not chance of a fix for that version.

**Comment by jimmyyih** [comment]
I recently hit something similar where a promoted standby (PG9.4.26) would show WAL archiving checksum error from pgbackrest.  When comparing the WAL segment files between the old primary, the archive, and the promoted standby, I found that the WAL dumps matched but the file padding did not (compared hexdumps).  Testing the same scenario with PG12, the WAL segment files were all padded the same so pgbackrest just correctly returned a warning (file exists but checksums match) and moved along.

It seems like the issue was accidentally fixed in PG11 with commit https://github.com/postgres/postgres/commit/4a33bb59dfc33566f04e18ab5e1f90b8e7461052.  So now the last WAL segment file from pg_basebackup's receiver matches with the primary's WAL segment file that contains the BACKUP_END and switch record.

**Comment by jimmyyih** [comment]
The reason why there's a missing `000000010000000000000055.done` file is most likely because pg_basebackup WAL receiver got cut off early and didn't have a "complete" WAL segment file to mark as done whereas `000000010000000000000054` has a done file because the pg_basebackup WAL receiver got it fully and marked it as done to prevent it from being archived.  That's what I observed at least on my test setup.

**Comment by dwsteele** [comment]
I think @jimmyyih's analysis here is correct, so closing.
