### ISSUE TITLE
Determining how many WAL files need to be applied after restore?

### ISSUE THREAD

**Issue by RonJohn2** [pgbackrest/pgbackrest#1928]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.07 (It's going away soon.)

2. PostgreSQL version:
9.6.24

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHEL 6.10

4. Did you install pgBackRest from source or from a package?
Postgresql community package.

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
`pgbackrest restore` successfully restored an instance, then I ran `pg_ctl start -D /path/to/data`, knowing that `recovery.conf` would apply a lot of WAL files.  Where do I look to see how many need to (or still need to) be applied?

**Comment by pgstef** [comment]
Look at PG logs to watch the recovery process (which WAL is currently replayed). If you don't specify a recovery target, all WAL archives found in the repo will be replayed (unless one is missing).

So I'd say you can calculate the amount of WAL archives between the "WAL stop" of your backup set and the "wal archive max" (newest archive found in the repo) reported by the info command.

**Comment by RonJohn2** [comment]
> Look at PG logs to watch the recovery process (which WAL is currently replayed). If you don't specify a recovery target, all WAL archives found in the repo will be replayed (unless one is missing).

My restore command specified `--set=XXXXXXX`.  Why didn't pgbackrest add a clause to `restore.conf` to stop when all of the relevant WAL files were restored?

**Comment by pgstef** [comment]
Because pgBackRest can't guess what you have in mind. Defining the recovery targets is up to you.

If you simply want to restore a backup set and only replay the WAL entries needed for the consistency, you need to add `--type=immediate`. See the [--type](https://pgbackrest.org/command.html#command-restore/category-command/option-type) option for more details about the default behavior.

**Comment by RonJohn2** [comment]
> Because pgBackRest can't guess what you have in mind. Defining the recovery targets is up to you.

With every other RDBMS, when you restore a specific backup set, it's understood that the instance will be functional as of the time of the backup set.

As a follow-on, I noticed when using `--set=XXXXX -type=immediate` that the database has data as of **the end of** the backup job, whereas other RDBMS backup/restore systems (including pg_dump/pg_retore) bring the database to the **start of** the backup job.

This makes sense when I think about it, but implies that `--type=time "--target=<some timestamp>"` is a better way to do it.

**Comment by pgstef** [comment]
> With every other RDBMS, when you restore a specific backup set, it's understood that the instance will be functional as of the time of the backup set.

That's not how PG physical backup works. And pg_dump isn't a real backup imo, it's a logical export of your data. 

When you are copying the data files while PG is running, those data files are modified and can't be consistent if you don't replay the wal entries generated during your copy. That's why a PG physical backup is only consistent at the stop time.

Also, it's the PG default behavior to replay all the wal archives stream when performing a recovery. No matter if the data files are 1 day old or 1 month old.

pgBackRest is only there to help you send data files to your backup space and restore those files when needed. PG is responsible for the recovery, and it has no idea where the data files come from. So it's up to you to determine your recovery targets. pgBackRest can help changing the config files only if you tell it what you want to achieve.

> This makes sense when I think about it, but implies that `--type=time "--target=<some timestamp>"` is a better way to do it.

Not in PG. The recovery target should always be past the backup stop location. If you want to target a timestamp right between your backup start / stop time, you'll need an older backup set.

A lot have changed in PG recovery settings since 9.6 anyway.
