### ISSUE TITLE
Question: Interpretation of "pgbackrest info" output

### ISSUE THREAD

**Issue by mzwettler2** [pgbackrest/pgbackrest#1973]
```
sh-4.4$ pgbackrest info
stanza: db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (13): 0000000B0000010B000000C1/0000000C000001110000000A

        full backup: 20221222-230004F
            timestamp start/stop: 2022-12-22 23:00:04 / 2022-12-23 01:32:17
            wal start/stop: 0000000B0000010B000000C1 / 0000000B0000010C0000005C
            database size: 46.3GB, database backup size: 46.3GB
            repo1: backup set size: 17.6GB, backup size: 17.6GB
```

Questions:

1. wal archive min/max describes min + max WAL existing in the repo.
2. full backup - timestamp start/stop describes the start + stop time of the backup run. there is no relation to the data status.
3. full backup - wal start/stop describes that these wals are needed to get the full backup consistent. That means the full backup above would be consistent by applying WALs 0000000B0000010B000000C1 until 0000000B0000010C0000005C.

Correct?

**Comment by dwsteele** [comment]
This looks right but I don't know what `there is no relation to the data status` means. The backup end time in particular is important because any PITR for the backup needs to be strictly *after* that time.

All of this is explained in more detail in https://pgbackrest.org/user-guide.html#quickstart/backup-info.
