### ISSUE TITLE
Question on deleting all incremental backups, but keeping corresponding full or differential backups

### ISSUE THREAD

**Issue by neiaberau** [pgbackrest/pgbackrest#2025]
I have generic question: 
As per documentation, differential and incremental backups will always be expired when the backup they depend on is expired.
I also understand that a removal of a single incremental breaks the backup. However, is there a reason that there is no option to delete all incremental backups belonging to a full or differential backup, but not the corresponding full or differential backup?
(or have I not found it or misunderstood something?)

I try to make a simple example why this might be useful:
monthly full
daily incremental 
weekly differential
3 months of full backups kept

If I understood the manual correctly, by keeping the last 5 differential I would over time remove all differentials and corresponding incremental of former months backup, i.e only keeping full and first week of incremental on full but not the other incremental and differential backups of previous backups  (PITR is still possible although very slow I guess having to apply almost a full month of archives)
Other than simply buying more disks, I can see a case that I want to keep all weekly differentials, but remove all existing incremental of previous months, so at most having to apply a full week of archives.

**Comment by pgstef** [comment]
Hi,

In your case, I agree the incremental in the week after the full might be removed. But that's because you're mixing all backup types. Why don't you simply take a differential backup right after your full ? That will be a small and fast one, and all the incremental in the week after should then expire when that differential will expire. 

Anyway, retention policy is always a bit touchy and should be tested carefully ;-)

Kind Regards
