### ISSUE TITLE
2.45 fails to build on bionic/ppc64el

### ISSUE THREAD

**Issue by mbanck** [pgbackrest/pgbackrest#2035]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.45

2. PostgreSQL version: n/a

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 18.04 LTS (bionic)

4. Did you install pgBackRest from source or from a package? Trying to build the .deb package

6. Please attach the following as applicable: n/a

7. Describe the issue:

When trying to build the 2.45 Debian/Ubuntu packages, we see the following build error in the new block-incremental code:

```
19:44:28 gcc  -g -O3 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -Wall -Wextra -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-clobbered -O2 -Wdate-time -D_FORTIFY_SOURCE=2 -D_POSIX_C_SOURCE=200809L -I. -I/usr/include/postgresql -I/usr/include/libxml2 -I. -I. -c -o .build/common/crypto/xxhash.o common/crypto/xxhash.c -MMD -MP -MF .build/common/crypto/xxhash.dep
19:44:28 In file included from common/crypto/xxhash.c:17:0:
19:44:28 ./common/crypto/xxhash.vendor.c.inc: In function ‘XXH3_accumulate_512_vsx’:
19:44:28 ./common/crypto/xxhash.vendor.c.inc:4148:9: error: invalid parameter combination for AltiVec intrinsic __builtin_vec_ld
19:44:28          xxh_u64x2 acc_vec        = vec_xl(0, xacc + 2 * i);
19:44:28          ^~~~~~~~~
19:44:28 ./common/crypto/xxhash.vendor.c.inc:4158:9: error: invalid parameter combination for AltiVec intrinsic __builtin_vec_st
19:44:28          vec_xst(acc_vec, 0, xacc + 2 * i);
19:44:28          ^~~~~~~
19:44:28 Makefile:291: recipe for target '.build/common/crypto/xxhash.o' failed
19:44:28 make[2]: *** [.build/common/crypto/xxhash.o] Error 1
19:44:28 make[2]: Leaving directory '/<<PKGBUILDDIR>>/src'
```

The full log is here, I hope it is accessible: https://pgdgbuild.dus.dg-i.net/job/pgbackrest-binaries/110/architecture=ppc64el,distribution=bionic/console

**Comment by dwsteele** [comment]
I have confirmed this issue. We only regularly test ppc64le on 20.04 which works fine.

Not quite sure what to do here. This is due to a bug in GCC12 but they have worked around it recently in the xxHash project here https://github.com/Cyan4973/xxHash/commit/ad63946825f89c69ffac3861d8156fb2f10b5e17. The current release is pretty old and this commit sits in top of a large amount of refactoring in HEAD, so I'm pretty doubtful it can be applied safely to the release version we are using. I'll give it a try, but even if it does apply, I'd worry about making random changes to the hash function which could have unintended consequences. We could update to the version in HEAD, but not too satisfied with that, either.

Is the build on Debian 10 working OK? I think that is the next oldest version after 18.04 expires in April.

**Comment by dwsteele** [comment]
I did try to apply the xxHash patch that seems to fix this issue but I was not successful. There has been too much churn in the 15 months since the last release.

I was able to get a few tests through, but now Github actions has gone into a scheduled brownout for Ubuntu 18.04 since they are removing it in a few days.

**Comment by mbanck** [comment]
> Is the build on Debian 10 working OK? I think that is the next oldest version after 18.04 expires in April.

Yes, buster is fine; it has gcc-8 whereas bionic has gcc-7.4, maybe due to that.

**Comment by dwsteele** [comment]
> Yes, buster is fine; it has gcc-8 whereas bionic has gcc-7.4, maybe due to that.

Well, that's good at least. Honestly I'm not inclined to spend time working on an issue for a version that will be EOL in a month. Especially since the only fixes I can think of might be destabilizing.

Any chance we can make 2.44 the last release for 18.04? The major new feature in 2.45 is the block incremental beta and that won't end up in 18.04 anyway. There were no significant bug fixes.

**Comment by dwsteele** [comment]
Sounds like a plan to me. Thanks!
