### ISSUE TITLE
support archive_library

### ISSUE THREAD

**Issue by franchb** [pgbackrest/pgbackrest#2043]
PostgreSQL 15 can now do WAL archiving using loadable modules:

- https://git.postgresql.org/gitweb/?p=postgresql.git;h=5ef1eefd7
- https://www.postgresql.org/message-id/20220202224433.GA1036711@nathanxps13

There is a basic example in https://github.com/postgres/postgres/tree/master/contrib/basic_archive .

Were there any solutions for using such a function?

**Comment by dwsteele** [comment]
We are planning to support this feature, but in our experience the bottleneck is primarily compression and transfer since we have already optimized archiving with an async process and a fast notification process. For those reasons is it not currently a priority.

If you have a use case where executing `archive_command` appears to be the bottleneck, we'd certainly like to see it.
