### ISSUE TITLE
pgbackrest restore bug 

### ISSUE THREAD

**Issue by Tiago-Anastacio** [pgbackrest/pgbackrest#2062]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.44

2. PostgreSQL version: 13.7

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:  SUSE 15.3 two database servers (primary/ standby ) and 2 repository hosts set in TLS way

4. Did you install pgBackRest from source or from a package? community package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s) attached done
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - archive_mode = 'True' 
    - archive_command = '/usr/bin/pgbackrest archive-push %p'  
    - wal_level = 'logical'
    - max_wal_senders = '20' 
    - listen_addresses = '*'
    - errors in the postgresql log file before or during the time you experienced the issue : no errors

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue: pgbackrest restore --type=none creates recovery.signal file. Documentation states: https://pgbackrest.org/command.html#command-restore   
"none - no recovery.conf file is written so PostgreSQL will attem
[pgbackrest_hostpostgres_conf.log](https://github.com/pgbackrest/pgbackrest/files/11429697/pgbackrest_hostpostgres_conf.log)
pt to achieve consistency using WAL segments present in pg_xlog/pg_wal. Provide the required WAL segments or use the archive-copy setting to include them with the backup"

Thank you

[pgbackrest_host.conf.log](https://github.com/pgbackrest/pgbackrest/files/11429621/pgbackrest_host.conf.log)
[pgbackrest_hostpostgres_conf.log](https://github.com/pgbackrest/pgbackrest/files/11429623/pgbackrest_hostpostgres_conf.log)

**Comment by dwsteele** [comment]
Not exactly a bug, I think. We did this on purpose because I'm pretty sure at one point postgres would error if there was a backup_label but not recovery.signal. That doesn't seem to be the case any more, so we might be able to make this change.

To test this I built a PG12 and PG15 env (PG15 shown here):
```
pgbackrest/doc/doc.pl --out=html --include=user-guide --pre --no-cache --var=host-mem-limit=n --require=/quickstart/check-configuration
```
I modified backup.c before backupProcess() to make it wait a while:
```
        LOG_INFO("SLEEPING NOW!!!");
        sleepMSec(300 * 1000);
```
Then ran the backup:
```
docker exec -it -u postgres doc-pg-primary pgbackrest --stanza=demo backup --no-resume --type=full --repo1-retention-full=1 --log-level-console=info --log-timestamp --repo1-bundle=y --start-fast --compress-type=lz4 --archive-copy
```
And in parallel ran pgbench:
```
docker exec -it -u postgres doc-pg-primary /usr/lib/postgresql/15/bin/pgbench -i -s 2000
```
When the backup was done restored with type=none and removed recovery.signal:
```
docker exec -it -u postgres doc-pg-primary pg_ctlcluster 15 demo stop
docker exec -it -u postgres doc-pg-primary pgbackrest --stanza=demo restore --delta --type=none
docker exec -it -u postgres doc-pg-primary rm /var/lib/postgresql/15/demo/recovery.signal
```
Check LSN start in backup_label:
```
docker exec -it -u postgres doc-pg-primary cat /var/lib/postgresql/15/demo/backup_label

START WAL LOCATION: 0/3000028 (file 000000010000000000000003)
CHECKPOINT LOCATION: 0/3000060
BACKUP METHOD: streamed
BACKUP FROM: primary
START TIME: 2023-05-14 07:40:19 UTC
LABEL: pgBackRest backup started at 2023-05-14 07:40:19.067599+00
START TIMELINE: 1
```
And the last checkpoint location (we want to make sure this is way after the backup start LSN):
```
docker exec -it -u postgres doc-pg-primary /usr/lib/postgresql/15/bin/pg_controldata -D /var/lib/postgresql/15/demo

Latest checkpoint's REDO location:    5/F1080060
```
Start and check the log after recovery is complete:
```
docker exec -it -u postgres doc-pg-primary rm -f /var/log/postgresql/postgresql-15-demo.log
docker exec -it -u postgres doc-pg-primary pg_ctlcluster 15 demo start
docker exec -it -u postgres doc-pg-primary tail -f /var/log/postgresql/postgresql-15-demo.log

...
LOG:  database system was interrupted; last known up at 2023-05-14 07:43:23 UTC
LOG:  redo starts at 0/3000028
...
LOG:  consistent recovery state reached at 6/2849F98
LOG:  redo done at 6/2849F98 system usage: CPU: user: 17.82 s, system: 38.78 s, elapsed: 76.48 s
```
So it definitely appears to be getting the redo location from `backup_label` even when recovery.signal is not present.

Thoughts, @sfrost, @pgstef?

**Comment by dwsteele** [comment]
One thing to note, though, is that `type=none` restores should be avoided. The reason is that this recovery method does not switch the timeline, so there may be conflicts in the repository when postgres tries to re-archive a WAL segment that has already been archived.

**Comment by sfrost** [comment]
Seems like we should probably work to make the behavior consistent with recovery.conf not being there in older versions to newer versions that don't have a recovery.conf.  If that means not having a recovery.signal, and things otherwise match up with how things worked before, then seems alright to do.

**Comment by dwsteele** [comment]
> If that means not having a recovery.signal...

I agree in general, but I remember the way we have it currently was based on some hard lessons we learned at the time. Of course, the change in PG12 was a bit problematic and spawned a bunch of fixes. So, it is worth trying to track down when this worked again (assuming I did not imagine it) or should we just alter the code to match the current reality?

I'm kind of leaning towards the latter.

**Comment by pgstef** [comment]
Hi,

> We did this on purpose because I'm pretty sure at one point postgres would error if there was a backup_label but not recovery.signal. That doesn't seem to be the case any more, so we might be able to make this change.

I can remember we had an issue with this at some point but not really remember the details. I also confirmed the same behavior with PG 12 -> 15 :

```
$ /usr/pgsql-12/bin/pg_controldata -D /var/lib/pgsql/12/main/data/
Latest checkpoint's REDO location:    1/5D08F378
$ cat /var/lib/pgsql/12/main/data/backup_label
START WAL LOCATION: 1/24F2BF58 (file 000000020000000100000024)
CHECKPOINT LOCATION: 1/26839B10

$ rm -rf recovery.signal
# systemctl start postgresql-12

# logs
LOG:  redo starts at 1/24F2BF58
LOG:  consistent recovery state reached at 1/7BE06568
LOG:  redo done at 1/7BE06568
```

```
$ /usr/pgsql-15/bin/pg_controldata -D /var/lib/pgsql/15/main/data/
Latest checkpoint's REDO location:    1/8A0E4248

$ cat /var/lib/pgsql/15/main/data/backup_label
START WAL LOCATION: 1/66663118 (file 000000030000000100000066)
CHECKPOINT LOCATION: 1/66F2AAD8

$ rm -rf recovery.signal
# systemctl start postgresql-15

# logs
LOG:  redo starts at 1/66663118
LOG:  consistent recovery state reached at 1/A982CCE8
LOG:  redo done at 1/A982CCE8 ...
```

> Thoughts, @sfrost, @pgstef?

Leaving the AS IS situation also means you get `FATAL:  must specify restore_command when standby mode is not enabled` since we have the `recovery.signal` but no `restore_command`.

So I'd be in favor to not create the .signal anymore to make the behavior consistent with < 12.

> One thing to note, though, is that `type=none` restores should be avoided. The reason is that this recovery method does not switch the timeline, so there may be conflicts in the repository when postgres tries to re-archive a WAL segment that has already been archived.

That's also why I don't like that either. But why does PG allows that in the first place? I mean now that we don't have exclusive backups anymore, if we have a backup_label, it's not a simple crash recovery but a entire backup recovery.

If you simply want a consistent backup, you might better use `--type=immediate` anyway :man_shrugging:.

Completely removing `--type=none` would probably be too much but since the doc is currently not up-to-date and we'd have to change it, we could also make it very clear there that this option is "dangerous" regarding the timeline switch?

**Comment by dwsteele** [comment]
> I can remember we had an issue with this at some point but not really remember the details.

Same here. We never updated the behavior, though, so whatever it was we found it before the initial commit. But there were so many bug fixes for this after PG12 it must have been cleaned up by one of those.

> Completely removing --type=none would probably be too much

Yes. There are still some valid use cases for this -- but like a lot of tools it can be dangerous.

> we could also make it very clear there that this option is "dangerous" regarding the timeline switch?

Yeah, at least we can do that. I'll work up a separate patch for that. We are in feature freeze right now but doc updates are always fair game.
