### ISSUE TITLE
Does cloud storage retention policy mess with pgbackrest?

### ISSUE THREAD

**Issue by ThommyH** [pgbackrest/pgbackrest#2086]
We have many postgres clusters backed up by pgbackrest, which are coming and going.
However, we are often left with backups in cloud storage which we have to delete manually once the postgres clusters are gone. One solution could be using retention policies to lets say 90d, so old files automatically get deleted.
Since I see pgbackrest creating backup history files and so on, which are not updated after they have been created, I wonder if such a retention time policy would mess with pgbackrest internals.
Unfortunately I wasnt able to find that out in the official pgbackrest documentation.

**Comment by dwsteele** [comment]
We changed pgBackRest to all long-lived metadata files with each backup in 2.41 (3b5df1e0).

Storage retention policies are still not ideal (.e.g. we might try to restore a backup that is in backup.info but only partially exists in storage) and right now we don't test this case.

If you do this I would recommend that your storage retention policy be longer than pgBackRest's retention. That solves the problem of expiring old data without affecting the validity of the contents of backup.info.

But ultimately since we are not testing this scenario you use storage retention policies at your risk. You might be better off generating an alert for repos that have not been written to in N number of days.
