### ISSUE TITLE
Question - repo1-block and repo1-bundle

### ISSUE THREAD

**Issue by robinportigliatti** [pgbackrest/pgbackrest#2119]
Hello,

With the new version of pgbackrest 2.46, 2 very useful new parameters have appeared:
```
repo1-bundle=y
repo1-block=y
```

If I have already FULL and DIFF backups do I risk anything by activating these two parameters ?

Robin,

**Comment by dwsteele** [comment]
The `repo-bundle` option has been around for over a year and is very stable. `repo-block` is brand new and we have found a few issues which will be fixed in the next release. Hard to hit issues, but issues nonetheless.

The main thing you risk is losing compatibility with older versions of pgBackRest.
