### ISSUE TITLE
How do I add a remote repo to an existing local server?

### ISSUE THREAD

**Issue by alex-immersive** [pgbackrest/pgbackrest#2138]
1. pgBackRest version: 2.47
2. PostgreSQL version: 15
3. Operating system/version:
Local: ubuntu
RemoteRepo: ubuntu

I have a local machine running postgres and and have configured a local repo/archiving. I've made backups and this works as expected.

I'm attempting to extend this config and add a remote repo. I've been following the instructions here: https://pgbackrest.org/user-guide.html#repo-host

I've setup pgbackrest on the new instance, setup ssh + keys. I'm using the user `postgres` on both instances (I'm aware this is frowned upon).

Next I updated the config files:
Local:
```
[timeseries]
pg1-path=/mnt/nvme/pgdata

[global]
repo1-path=/mnt/nvme/pgbackrest
repo1-retention-full=2
start-fast=y
process-max=2
buffer-size=8MiB

repo2-type=posix
repo2-path=/var/lib/pgbackrest
repo2-host=REMOTE_HOST
repo2-host-user=postgres
```

REMOTE:
```
[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
start-fast=y

[timeseries]
pg1-host=DATABASE_HOST
pg1-host-user=postgres
pg1-path=/mnt/nvme/pgdata
```

I then attempt to create and check the stanza on the remote host:
```
postgres@localhost:~$ pgbackrest --stanza=timeseries stanza-create
postgres@localhost:~$ pgbackrest --stanza=timeseries check
ERROR: [082]: WAL segment 00000001000000E80000006E was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
```

What am I missing here?

**Comment by alex-immersive** [comment]
Additionally, after i've fixed the configuration, what steps should I take so that I can make a backup on the remote repo? Does archiving automatically begin on the remote repo? Do I need to restart any services? etc etc

**Comment by pgstef** [comment]
Hi,

Try to remove `repo2-type=posix` and `repo2-path=/var/lib/pgbackrest` from the pg host config. And use `repo2-path=/var/lib/pgbackrest` and `repo2-retention-full=2` on the repo host. (Afaik the repo indexes should match)

Once done, if the stanza-create cmd has run successfully on the repo host, you should be able to at least run `pgbackrest info --repo=2` from the pg host.

As soon as another repo is added to the configuration, `archive-push` will detect it and try to push archives there. (The archive_command will fail until both repos are working)

Have you looked at what the error message says regarding archiving `HINT: check the PostgreSQL server log for errors.`?
The check cmd fail because archive-push probably fails (or don't push to the accurate repo) so you need to look at the error message in the PG logs and fix it. (Running the check cmd from the pg host might also be a good idea)

Once archiving is working, to take a backup, run `pgbackrest --stanza=timeseries backup --repo=2` from the repo host.

Hope this helps,
Kind Regards

**Comment by alex-immersive** [comment]
This has helped - thanks.
