### ISSUE TITLE
Procedure to backup on the Standby, no downtime, no impact on PG instance

### ISSUE THREAD

**Issue by mattbunter** [pgbackrest/pgbackrest#2146]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.44

3. PostgreSQL version:
12.7
4. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS Linux release 7.9
5. Did you install pgBackRest from source or from a package?
RPM
6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[global]
repo1-path=/var/lib/pgbackrest
log-level-console=info
log-level-file=info
start-fast=y
process-max=5
repo1-retention-full=4
repo1-s3-bucket=dcmppg
repo1-s3-endpoint=s3.cls.fr
repo1-s3-port=9443
repo1-s3-uri-style=path
repo1-s3-key=blahblahblah
repo1-s3-key-secret=tototototototototototototo
repo1-s3-region=FR
repo1-type=s3
repo1-s3-verify-tls=y

[dcmppg]
pg1-path=/data/12

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
archive_command = 'pgbackrest --stanza=dcmppg  archive-push %p'
archive_mode=on
listen_addresses='*'
max_wal_senders=10
wal_level='replica'

    - errors in the postgresql log file before or during the time you experienced the issue
    NONE
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
    

7. Describe the issue:
We seek the best practice and/or approved procedure to change our backups to run on the standby of a large, always active database.
Any suggestions/gotchas that have been seen would be appreciated since we want to do this without downtime or impact on the running PG instance.
Thank you in advance.

**Comment by pgstef** [comment]
Hi,

> 7\. We seek the best practice and/or approved procedure to change our backups to run on the standby of a large, always active database.
>         Any suggestions/gotchas that have been seen would be appreciated since we want to do this without downtime or impact on the running PG instance.

The backup from standby is described in the [user guide](https://pgbackrest.org/user-guide.html#standby-backup) and is pretty easy to achieve without downtime imo. The central point is having a shared repository (which is already the case with your S3 bucket). Since the WAL archives will always come from the primary and will be pushed to that central repository, you don't need to change anything there.

The backup command started on a standby server (with the backup-standby option) will open a connection to the primary for the backup control (mostly start/stop backup + check the standby replication lag) and copy the data from the standby cluster. 
That means the standby server will need an access (ssh or tls) to the primary server and you'll simply define multiple `pg*` options in the stanza configuration : that's what pg options indexing is made for.

Obviously, it would be good to replicate the setup on your primary in case of a failover. 
Choosing how to trigger the backup command will also be important. Something like this is usually helpful: 
```
[ `psql -At -d postgres -c "select pg_is_in_recovery();"` = 't' ] && pgbackrest backup --stanza=dcmppg --backup-standby --type=full
```

You'll find lots of example in old issues or even on various blog posts.

Kind Regards

**Comment by Jhiliano** [comment]
@pgstef  I tested standby backup on a cluster with 2 hosts and i noticed that pgbackrest **fails archiving when pg-host isn't primary** (I suppose this behaviour is there on purpose for performance issue).

On the demo (https://pgbackrest.org/user-guide.html#standby-backup) we have the current **stanza** configuration

```toml
[demo]
pg1-host=pg-primary
pg1-path=/var/lib/postgresql/12/demo
pg2-host=pg-standby
pg2-path=/var/lib/postgresql/12/demo
```

And i can see 2 issues here : 

- i suppose pg-primary will ssh to himself to perfom any action which is not realy great
- _pg-primary_ and _pg-standby_ can be swapped (on switchover/failover scenario for example) and in this case the archive_command should fail (so also backups).

In order to resolve these issues i made a configuration symmetrical between each host (in this example i have got (node1 and node2):

- primary configuration (stanza part) 

```toml
# Stanza
[demo]
# Hosts

## - localhost
pg1-path = /var/lib/postgresql/12/demo

## - the other host
pg2-host = node2
pg2-path = /var/lib/postgresql/12/demo
```

- standby configuration (stanza part) 

```toml
# Stanza
[demo]
# Hosts

## - localhost
pg1-path = /var/lib/postgresql/12/demo

## - the other host
pg2-host = node1
pg2-path = /var/lib/postgresql/12/demo
```

I wonder if this is the right thing to do, and if that so, maybe adding a comment on documentation about this could be helpful

**Comment by pgstef** [comment]
Hi,

> I wonder if this is the right thing to do, and if that so, maybe adding a comment on the documentation about this could be helpful

Yes, this is the right thing to do. The user-guide describes how to take a backup from a standby server when using a dedicated backup server (aka repository-host), which is usually the easiest way to do it when dealing with multiple PG hosts (and even more in case of automated failover).

When only pg-hosts options are defined, it means to pgBackRest that there's no cluster running locally, so it considers itself as a repository host (backup server) and the archive_command isn't supposed to run on a backup server.
That's why you get the `ERROR: [072]: archive-push command must be run on the PostgreSQL host` message.

Unfortunately, the docs are used by the CI tests and can't cover each and every situation. (It wouldn't be logical to mention the "without backup server" configuration in the "with backup server" section)

However, the documentation states clearly:
> A stanza is the configuration for a PostgreSQL database cluster that defines where it is located, how it will be backed up, archiving options, etc. Most db servers will only have one PostgreSQL database cluster and therefore one stanza, whereas backup servers will have a stanza for every database cluster that needs to be backed up.

So that's how you dealt with it in the stanza section: pg1-path pointing to your local cluster + pg2-host/pg2-path pointing to the other node. Perfect.

A quick search would have showed you a few old blog posts illustrating this behavior:
- https://www.crunchydata.com/blog/pgbackrest-performing-backups-on-a-standby-cluster
- https://pgstef.github.io/2020/09/04/combining_pgbackrest_and_streaming_replication.html

Those are old, yes, but the pg option indexing and backup from standby hasn't changed since then :-)

Kind Regards
