### ISSUE TITLE
Issue with symbolic links on NFS mount

### ISSUE THREAD

**Issue by goran-kuzmanovic** [pgbackrest/pgbackrest#2148]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.38
2. PostgreSQL version: 13.7

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL 8.6

4. Did you install pgBackRest from source or from a package? RPM package from Percona repositories

5. Please attach the following as applicable: N/A (can provide later if necessary)

7. Describe the issue:

Apologies upfront is this is the wrong way to raise this. I'm currently backup and restore solution for our Postgres clusters (hosted on premise) and the challenge is around where we will be storing backups. Current attempt is to use Amazon S3 with Amazon Storage Gateway. I'm aware that pgBackRest can use S3 directly (which would probably solve my problems), but at the moment this is not an option due to security settings between our on-prem and AWS, hence the usage of storage gateway. 
While using gateway, we create a file share of type "NFS" and mount it to Postgres cluster nodes. That all works fine, but I stumbled upon issue similar, if not same, as described here -  [#592](https://github.com/pgbackrest/pgbackrest/issues/592). Storage Gateway doesn't support symbolic links, so I changed repo-type to "cifs" and that seems to be working fine.

Now, to the problem. Considering the age of that issue (early 2019) where it was already not considered a good practice to use cifs, due to it being obsolete, what are my options ? Should I even consider using it or try to steer away from AWS Storage Gateway altogether (due to said limitation) ? 
I assume something like `repo1-link=n` wasn't implemented, which I believe would help here.

Any feedback would be of great help. Thanks in advance!

**Comment by pgstef** [comment]
Hi,

First of all, 2.38 is really old (March 2022). You should definitely consider to use the latest release.

> it was already not considered a good practice to use cifs, due to it being obsolete

Where did you see it is mentioned as obsolete? It is "just" not a great plan because it disables directory fsyncs as well as symlinks.

> I assume something like repo1-link=n wasn't implemented

This very specific feature hasn't been implemented because there are better options to use and it hasn't really be needed since then.

> While using gateway, we create a file share of type "NFS" and mount it to Postgres cluster nodes

Even if we had the disable-link feature, are you sure that Amazon Storage Gateway is posix compliant ?
There are a few consideration to verify when an NFS mount is used as a posix repository: the same rules apply to pgBackRest as described in the PostgreSQL documentation [Creating a Database Cluster - File Systems](https://www.postgresql.org/docs/current/creating-cluster.html#CREATING-CLUSTER-FILESYSTEM).

> what are my options ?

First of all, maybe asking your Amazon or vendor support? Is Amazon Storage Gateway posix compliant and why symlinks don't work with it?

You could also use any other supported/recommended repo-types (s3, azure, gcs) or use a repo-host (dedicated backup server) or even sftp.
Lots of options with the latest release to be fair.

Using repo-type=cifs is probably the "easiest" possibility, but it has its drawbacks (no directory fsync).

**Comment by goran-kuzmanovic** [comment]
Hi,

Thank you for your prompt answer and many valid points made.

> Where did you see it is mentioned as obsolete? It is "just" not a great plan because it disables directory fsyncs as well as symlinks.

Mainly in some (not all) articles explaining CIFS, but fair point. On that issue, comments were referring to NFS v2 being ancient/obsolete, not CIFS, true.

> Even if we had the disable-link feature, are you sure that Amazon Storage Gateway is posix compliant ?
There are a few consideration to verify when an NFS mount is used as a posix repository: the same rules apply to pgBackRest as described in the PostgreSQL documentation [Creating a Database Cluster - File Systems](https://www.postgresql.org/docs/current/creating-cluster.html#CREATING-CLUSTER-FILESYSTEM).

What I can say is it does satisfy this requirement listed on the link you've provided: "The only firm requirement for using NFS with PostgreSQL is that the file system is mounted using the hard option". Then again, there is this limitation regarding symbolic links, so probably not fully. As you suggested, I'll check with vendor support to get that part clarified. Symlinks won't work on it as they are not supported, as per: https://aws.amazon.com/storagegateway/faqs/ ("Q: What file system operations are supported by Amazon S3 File Gateway?"). I'll look more into other recommended repo-types and whether we can use them on-prem in our current way of working (which was the limitation that initiated this thread anyways).

Nevertheless, thank you for your help, no further info needed.
