### ISSUE TITLE
How we can perform WAL replay after EBS snapshot restoration?

### ISSUE THREAD

**Issue by Tekchanddagar** [pgbackrest/pgbackrest#2166]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.45

2. PostgreSQL version: 15.X

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 22.04

4. Did you install pgBackRest from source or from a package? Source

5. Describe the issue: We are using pgbackrest for psql backup (full and diffrential + WAL) and its working as fine. But some of the database size is growing recently and size is around (3TB). 

So the full backup and diffrential backup are taking lot of time now and these DB are creating too many WAL. So whenever we are performing DB backup restoration activity to test backup integrity its taking lot of time.

Yesterday I was reading one article regarding about  DB backup and how we can make it faster. Please find the link for same:
[https://www.timescale.com/blog/making-postgresql-backups-100x-faster-via-ebs-snapshots-and-pgbackrest/](url)

But I am unable to understand one point. When we restore the EBS snapshot which can be consider as full backup but from there I want to go at latest state or say at some point in time. Then how we will perform the WAL replay with EBS snapshot.

As far as I know using pgbackrest we can restore lastest backup or particular backup which we want to retsore and it will perform WAL replay automatically.

But in case of EBS snapshot restoration how it will know which WAL need to replay?

Can you please help me here so I can test in my environment?

**Comment by pgstef** [comment]
Hi,

First of all, that article was written by "[Grant Godeke](https://www.timescale.com/blog/author/grant/) and [James Blackwood-Sewell](https://www.timescale.com/blog/author/james-blackwood-sewell/)". Given the pgBackRest project doesn't officially support this kind of feature, you might ask them directly...

What I get from quickly reading it: 

> we still rely on pgBackRest to do our WAL management

You have to know that WAL archives are expired based on the oldest backups in the repository. So if you don't take backups with pgBackRest but only storage snapshots, you'll have to clean-up the WAL archives yourself.

> it will perform WAL replay automatically

pgBackRest doesn't perform any recovery. It restores the data files and prepare PG configuration to let PG do the actual recovery (creating the recovery signal and at least adding the restore_command). Usually storage snapshots don't produce consistent backups unless you manually perform all the steps needed for PG physical backups and recovery. To be able to do that, you need to know exactly how PG works.

> these DB are creating too many WAL

I don't see how switching from full/diff/incr backups to storage snapshots without using pgBackRest anymore for the backup/restore will help you with that specific WAL archiving issue... Most certainly when the article you linked specifically mention they are only using pgBackRest for WAL archives.

Depending on your environment and backup space, there are some configuration settings you can change/activate to speed-up the process (repo bundle, asynchronous archiving, compression types,...). But given you didn't provided the initial configuration you used, we can't really give any recommendation.

Ultimately, generating a high WAL activity will impact your archiving system and backups, but also the PG behavior itself. It might be good to investigate what generates those WAL entries and see if you could optimize that too first.

Kind Regards

**Comment by Tekchanddagar** [comment]
@pgstef , Thank You for quick response.


> pgBackRest doesn't perform any recovery.

Yes, we need to define `restore_command` in our config and I forgot to mention this.

> I don't see how switching from full/diff/incr backups to storage snapshots without using pgBackRest anymore for the backup/restore will help you with that specific WAL archiving issue

No, we don't want to switch from pgbackrest. We want to use both EBS snapshot and pgbackrest for full/diff backup  and WAL archive.

Just want to know if we restore any EBS snapshot than how we can perform WAL replay (which are store on S3 bucket using pgbackrest)?

Thank You

**Comment by pgstef** [comment]
> Just want to know if we restore any EBS snapshot than how we can perform WAL replay (which are store on S3 bucket using pgbackrest)?

You'll have to make sure that you followed all the steps to have a consistent PG physical backup and then perform all the steps to prepare the PG recovery (make sure you have the backup_label, ...). That's a PG knowledge, nothing to do with pgBackRest.
In your recovery process, you'll have to set the restore_command to use pgBackRest archive-get to let PG fetch the archives from your repo. But nothing guarantees PG will perform its recovery starting at the good location unless you took the backup correctly.

You'll basically have to do everything by yourself. So you'll have to learn more about PG physical backups and recovery management.

And to be clear, it won't solve your archive recovery "taking too much time" problem.

**Comment by sfrost** [comment]
Note that when you take a snapshot, it's absolutely essential that *all* of the WAL which was written out at the time the snapshot was taken is replayed, which would obviously include WAL that hasn't yet been archived at the moment the snapshot is taken ... if that's not done, then you'll end up with very hard to detect corruption.  The article referenced doesn't discuss how this is managed or how they ensure that this is the case, which is concerning as it's absolutely critical to be sure that the resulting system is consistent.

There also isn't any mention of the fact that the snapshot must absolutely be taken atomically across the entire database system in order for it to be consistent- that is, *everything* must be on the same volume which is being snapshotted.  If the WAL is on a separate volume, you can't simply issue a snapshot for the data volume and the WAL volume because those snapshots won't be taken at the exact same moment and that will, again, lead to very hard to detect corruption.  The same is also true if multiple tablespaces are used across different volumes.  None of these complications are discussed even though knowing how all of this is handled is absolutely critical to ensuring that the resulting system won't end up with latent and hard to detect corruption.

The earlier points made in the article regarding storage system failure seem to miss out on the possibility that, by using a snapshot, and therefore a COW system, whereby unmodified data only exists in one place, that should there be a failure with that storage, all of the snapshots are suddenly invalid.  Such arrangements shouldn't be properly considered backups.

Also, as it relates to the cost of performing a backup due to i/o resources ... having a primary system and a replica point to largely the same storage blocks, wherever they are stored, is introducing a hidden cost in terms of access to those blocks.  Perhaps the higher level throttling performed by the cloud architecture ends up essentially hiding that in some instances (that is, the storage is fast, the higher levels throttle, but do so based on the configured IOPS, such that there's a pseudo increase in IOPS because there's now another access channel..), but this won't be the case in those particularly high throughput systems where the true storage access speed is being reached.

Lastly, for all the concern about the length of time required for full backups and for WAL replay... it should almost never be the case that the length of time of the full backup truly matters- you should simply take an incremental after the full backup and that'll minimize the amount of WAL replay required when restoring that incremental backup (to the point that we've actually discussed just implementing that as an automatic step...).  Further, using pgBackRest delta restore, the actual restore time is also able to be minimized- it just requires a bit of planning ahead of time (perform a restore to the new replica- on entirely independent storage which won't interfere with the primary's operation, ahead of time and then do a delta-restore when you need to do the restore), but that's not really news when you're talking about large-scale systems.
