### ISSUE TITLE
minor documentation errors

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#217]
Just thought Id create an issue to document some documentation errors...

In the pgbackrest User Guide, in the replication section under "Hot Standby", you specify the backup host as "backup", not "db-master", which should be used in this example, i.e., slave is db-standby
backup-host=backup
should be:
backup-host=db-master

In the Command Reference Guide, you show some parameters with an associated value when the parameter name suffices
your example -> example: start-fast=y
should be just the parameter name --> --start-fast
Same fix for parameter, --archive-check, and probably other toggle parms

**Comment by dwsteele** [comment]
In the replication example the backup host is definitely _backup_.  This follows from the "dedicated backup host" section.  As it says in the intro, the guide is meant to be read from start to finish so if you skip around things may not be as clear, and of course there are lots of alternate configurations.  Every example in the guide is run in docker containers as the guide is built so I feel pretty confident about their correctness (though the text is another matter).

The examples are generally show as option=setting because the vast majority of users put options on pg_backrest.conf.  Examples are show as --option usually for cmd line only settings.

It looks like you are using all cmd line options (which is totally fine) but this is not common usage.

**Comment by MichaelDBA** [comment]
Thanks for the elaboration.  

In my case, the backup was the where the master was, but I see your point about "backup" meaning where the pgbackrest repo is installed and that could be anywhere not just on the master like in my case.

Also thanks for the elaboration about parms requiring values in pgbackrest.conf, but not on the command line.  Perhaps that should be noted somewhere about this distinction.

Again, thanks for your speedy responses my issues.
