### ISSUE TITLE
Pgbackrest expires backups when repo1-retention-full-type=count but doesn't work when repo1-retention-full-type=time

### ISSUE THREAD

**Issue by cyberioio** [pgbackrest/pgbackrest#2171]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.47
2. PostgreSQL version:
15.1
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Red Hat Enterprise Linux release 8.6 (Ootpa)
4. Did you install pgBackRest from source or from a package?
package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/12535360/pgbackrest.conf.txt)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
[postgresql.conf.txt](https://github.com/pgbackrest/pgbackrest/files/12535362/postgresql.conf.txt)

    - errors in the postgresql log file before or during the time you experienced the issue
No error in the postgresql.log file

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
[pgbackrest_backup_expire_logs.txt](https://github.com/pgbackrest/pgbackrest/files/12535361/pgbackrest_backup_expire_logs.txt)
[STANZA-expire.log](https://github.com/pgbackrest/pgbackrest/files/12535364/STANZA-expire.log)

7. Describe the issue:
The pgbackrest backup command works fine and expires old backups when repo1-retention-full-type=count.
But it doesn't work when repo1-retention-full-type=time ...
I don't know why because there is no error in log files
On the other hand, "pgbackrest expires ..." manually command works fine when repo1-retention-full-type=time 
Thanks in advance for your feedback

**Comment by pgstef** [comment]
Hi,

The time expire appears to work as documented to me.

> If set to time then full backups older than repo-retention-full will be removed from the repository if there is at least one backup that is equal to or greater than the repo-retention-full setting

Based on your logs, I see:
```
# --repo1-retention-full=3 --repo1-retention-full-type=time
2023-09-06 07:57:10.006 P00   INFO: new backup label = 20230906-075544F

# --repo1-retention-full=3 --repo1-retention-full-type=count
2023-09-06 10:12:59.026 P00   INFO: new backup label = 20230906-101135F
2023-09-06 10:12:59.374 P00   INFO: repo1: expire full backup 20230831-085130F
2023-09-06 10:12:59.383 P00   INFO: repo1: expire full backup 20230903-174213F
2023-09-06 10:12:59.393 P00   INFO: repo1: expire full backup 20230904-083639F
```

Having the info output before running the expire might help you see why it doesn't expire anything.

So:
- 31/08 08:51
- 03/09 17:42
- 04/09 08:36
- ...
- 06/09 07:55
- 06/09 10:12

On `06/09 07:55`, the expire command need to keep at least 1 full backup that meets the retention period (so > than 3 days). So it needs to keep 1 backup prior to `03/09 07:55` --> that's why the `31/08 08:51` is kept.

When you run the expire manually *later*, the time retention is calculated at the time you actually run the command. So if you run it `06/09 18:00`, the `03/09 17:42` would meet the criteria and `31/08 08:51` would have been removed.

Time-based retention is bit more tricky to apprehend but works correctly.

Kind Regards

**Comment by cyberioio** [comment]
OK, thanks for your answer.
I didn't really understand how the purge cleared with --repo1-retention-full-type=time.
Now it's clear for me, thanks.
Issue closed.
