### ISSUE TITLE
Where's the cool pgbackrest diagram?

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#218]
Unless I haven't looked in the right place, I cannot find a nice diagram of pgbackrest that shows stuff like process flow, etc.

**Comment by dwsteele** [comment]
Heh, that's because there isn't one.

It sounds like a good idea, just hasn't been a priority.  Also, the documentation is currently rendered into 5 formats (html, pdf, cmd-line help, man, and text) so ideally I would like something that displays in all of them, though I would settle for html and pdf.

**Comment by dwsteele** [comment]
This issue has been added to the backlog on the wiki as it is not likely to be addressed soon.
