### ISSUE TITLE
checksums in non-standard pg_control files

### ISSUE THREAD

**Issue by markwort** [pgbackrest/pgbackrest#2199]
Hey,

since pgbackrest 2.48 we see the following behaviour, on PostgreSQL databases running a forked version of PostgreSQL, which adds additional fields to the pg_control file:

```
ERROR: [026]: calculated pg_control checksum does not match expected value
HINT: calculated 0x8a5867f4 but expected value is 0x91583e01
HINT: is pg_control corrupt?
HINT: does pg_control have a different layout than expected?
```

Obviously this is due to the newly added checksum verification for pg_control, as introduced here for 2.48 : https://github.com/pgbackrest/pgbackrest/commit/f42d927d2dcd58cf5a80d68eaf6888bcf2c67a4b 

Now, as a workaround, we discovered - from the discussion on that pull request - that setting
`pg-version-force` in the configuration section for the stanza fixes this.
The code in question then goes about searching the actual position of the checksum in the file, instead of stricly relying on the offset that is applicable to vanilla PG.

https://github.com/pgbackrest/pgbackrest/blob/af4621894a20ca0333726d459e2e6409bd4ee1e0/src/postgres/interface.c#L246-L254

So, while we can see, and appreciate, that forks where already considered when adding this checksum verification feature, we do wonder if setting `pg-version-force` is the appropriate fix for this.
I understand that it is a development configurable, not necessarily intended for production use, and it's not documented anywhere.
Also, it seems to change a bunch of other behaviour as well.

I wonder if it might make sense to add a specific toggle just to allow this advancing of the checksum offset to take place, without all of the other implications of `pg-version-force`.

Best regards
Julian

**Comment by dwsteele** [comment]
> we do wonder if setting pg-version-force is the appropriate fix for this.

It is.

> I understand that it is a development configurable, not necessarily intended for production use, and it's not documented anywhere.

Yes -- we left this internal for now because only fork maintainers should be using/recommending it. Our plan is to create a new "maintainers" configuration section with the three maintainer options that we already have and put appropriate caveats around it. We're planning to get the documentation updated appropriately in the next (November) release.

BTW -- you can get docs from the command line if you know the name of the internal option.

> Also, it seems to change a bunch of other behaviour as well.

Yes -- and these changes are required. Even more so going forward.

> I wonder if it might make sense to add a specific toggle just to allow this advancing of the checksum offset to take place, without all of the other implications of pg-version-force.

We don't believe this is the best course. Ultimately pgBackRest is a community focused project. We do our best to support forks but the onus to test those forks must fall to the maintainers and users of that fork. In general, users don't/won't even inform us of the fork they are using.

**Comment by markwort** [comment]
Thanks, this answers all my questions for the moment.

I understand that pgBackRest puts compatibility with PostgreSQL first and foremost, and cannot fix any issues with forks.
It's certainly appreciated that such forks are considered when adding certain features.

You're only receiving this question and not a bug report, because we already handled the user's complaint in this case. :)

Assuming you're already tracking a task for documenting these "maintainer" options, we can close this ticket if you want to.

**Comment by dwsteele** [comment]
I have created PR #2202 to document the maintainer options. Feel free to have a look.
