### ISSUE TITLE
using spool to queue WAL files before copying to external storage

### ISSUE THREAD

**Issue by segasai** [pgbackrest/pgbackrest#2230]
Hi, 

Thanks for the great software!

I have question/suggestion: 

I am encountering the situation where I am backing up a tens-of-TB-sized database to a reasonably slow external NFS store, so the backup takes a few days. When doing that I encountered an issue when some changes were done to the DB, leading to hundreds of GB of WAL (which in the end lead to DB shutdown, because the WAL partition became full as pgbackrest couldn't keep up with copying the WAL files to remote storage).

At first I thought that archive_async would fix the issue, but I can see that if the network is already saturated, the WALs will still accumulate till  archive-push-queue-max is reached, which would not crash the DB, but would invalidate the backup. 

So the question I have is whether 
* It would be useful to implement in pgbackrest queuing of WAL files at the spool location before copying. Assuming that spool has more space (and is local FS, so it's cheap to copy), that would be safer than accumulating the files at the pg_wal (which may be limited in size). At first I thought that's what pgbackrest does when I saw the spool option, but  then I saw that only the .ok files are stored there, not the WAL files.
* If that's not an option, is there anything else I could do to in my case to prevent backup invalidation if the WAL generated is larger than WAL partition and the copying over the network can't keep up. 

Thanks in advance, 
        Sergey

PS Just in case I'm running pgbackrest 2.47 with PG14.10 on Linux.

**Comment by sfrost** [comment]
A few questions/comments on this ...

- Have you considered reducing the parallel workers for the backup, to avoid the network being saturated, so that the WAL is able to be archived?
- If the network isn't able to handle the rate of WAL generation with a reduced number of parallel workers performing the backup, then I seriously think you are in a potentially untenable situation as any hiccup on the network will end up with a WAL backlog that might be unrecoverable and results in a DB crash due to WAL volume filling up.  You should seriously consider if this design is really acceptable.
- How much of the database (heap files, in particular...) is changing during the backup?  We are currently investigating a feature to allow pgbackrest to copy most of the database heap files *before* doing backup start, then starting the backup and going back and checking if we need to re-copy any of the files we already copied.  If most of the database is unchanged then this will significantly reduce the amount of time between start backup and stop backup and therefore reduce the amount of WAL that is required for a given backup to be valid.  While this doesn't really help with your situation on the backup side, we expect it to be useful for reducing restore times (where the 'restore time' includes WAL replay to get back to a consistent state), which is why I'm curious and wanted to ask about this.
- Overall, I'm not against a feature in the form that you're suggesting, though I'm not fully convinced of the use-case yet either.

**Comment by dwsteele** [comment]
> It would be useful to implement in pgbackrest queuing of WAL files at the spool location before copying.

We used to do this but changed the implementation because of the additional load it placed on the host. Also, it looked to Postgres like WAL had been archived, but in fact it was still just sitting on host storage.

Aside from improving your performance, the main thing you can do is add space to the pg_wal volume.

> We are currently investigating a feature to allow pgbackrest to copy most of the database heap files before doing backup start

I don't think this would help. The same WAL would be generated during the backup even if it would not needed to make the backup consistent. If anything, the new method uses slightly more I/O, which would make the situation worse.

**Comment by sfrost** [comment]
> > * Have you considered reducing the parallel workers for the backup, to avoid the network being saturated, so that the WAL is able to be archived?
> 
> The reason for using so many workers is because the DB is so large and the backup takes so long, so I chose to saturate the CPU and use the maximum compression possible and ensure the bandwidth is fully saturated.

Hopefully you're using zstd..?

Is there a reason why it's an issue that the backup takes a long time?  Generally speaking, we don't care too much about how long a full backup takes, what matters is restore time, and it's best to go ahead and take an incremental right after a full, if you full takes a long time, as that will minimize the restore time by reducing the amount of WAL that has to be replayed.

> > * If the network isn't able to handle the rate of WAL generation with a reduced number of parallel workers performing the backup, then I seriously think you are in a potentially untenable situation as any hiccup on the network will end up with a WAL backlog that might be unrecoverable and results in a DB crash due to WAL volume filling up.  You should seriously consider if this design is really acceptable.
> 
> Unfortunately my DB is mostly read-only, but in this case there was an update and I encountered the issue. Previously I used pitrery to do the backup and I din't have the issue, because I was saving WAL locally first before sending it to the network in the end.

In theory you could have a local pgbackrest repo that you back up to and then just copy to the NFS mount, but as noted before, that means you're at risk of losing whatever backups and WAL are only in the local repo should something happen.

> > * How much of the database (heap files, in particular...) is changing during the backup?  We are currently investigating a feature to allow pgbackrest to copy most of the database heap files _before_ doing backup start, then starting the backup and going back and checking if we need to re-copy any of the files we already copied.  If most of the database is unchanged then this will significantly reduce the amount of time between start backup and stop backup and therefore reduce the amount of WAL that is required for a given backup to be valid.  While this doesn't really help with your situation on the backup side, we expect it to be useful for reducing restore times (where the 'restore time' includes WAL replay to get back to a consistent state), which is why I'm curious and wanted to ask about this.
> 
> In my case the percentage change is maybe 1%, but because the whole DB is ~100Tb, that's still quite a a abit. It would be definitely worth for me to first copy the heap files before the main backup

Right, does sound that way.  You can effectively do what we're imagining the feature doing by taking an incremental right after your full backup.  Again, this isn't going to help with the current issue you're running into where the WAL volume is filling up because archiving isn't going fast enough, but it might make you more comfortable with reducing the parallel workers for the backup to allow archiving to keep up knowing that the incremental will go a whole bunch faster than the full and so you won't end up having to do a restore that's replaying many TBs of WAL.

As always, strongly recommend that you do test your restore process regularly and see how long it takes given a system this large and plan accordingly.

**Comment by segasai** [comment]
> > > * Have you considered reducing the parallel workers for the backup, to avoid the network being saturated, so that the WAL is able to be archived?
> > 
> > 
> > The reason for using so many workers is because the DB is so large and the backup takes so long, so I chose to saturate the CPU and use the maximum compression possible and ensure the bandwidth is fully saturated.
> 
> Hopefully you're using zstd..?

I am using lz4 which should be fine I believe speed-wise. 


> 
> Is there a reason why it's an issue that the backup takes a long time? Generally speaking, we don't care too much about how long a full backup takes, what matters is restore time, and it's best to go ahead and take an incremental right after a full, if you full takes a long time, as that will minimize the restore time by reducing the amount of WAL that has to be replayed.
> 

The reason the DB size is 130 Tb. When compressed in a backup it takes ~ 70Tb, but even transfer of that at 100Mbytes/s would take 8 days. 

It is not a big issue for me as I do need to do that often, as the DB is mostly static. And TBH I don't care about restore time either, I can tolerate a week of downtime. 
My use-case is fairly atypical obviously. 

At this point I didn't yet manage to make pg_backrest incremental backup work, I was hoping that would speed things up (I need to investigate it). But at 


> > > * If the network isn't able to handle the rate of WAL generation with a reduced number of parallel workers performing the backup, then I seriously think you are in a potentially untenable situation as any hiccup on the network will end up with a WAL backlog that might be unrecoverable and results in a DB crash due to WAL volume filling up.  You should seriously consider if this design is really acceptable.
> > 
> > 
> > Unfortunately my DB is mostly read-only, but in this case there was an update and I encountered the issue. Previously I used pitrery to do the backup and I din't have the issue, because I was saving WAL locally first before sending it to the network in the end.
> 
> In theory you could have a local pgbackrest repo that you back up to and then just copy to the NFS mount, but as noted before, that means you're at risk of losing whatever backups and WAL are only in the local repo should something happen.

Yes that would work. (unfortunately I don't have enough space to do that in practice, I do for the WAL though) 

> 
> > > * How much of the database (heap files, in particular...) is changing during the backup?  We are currently investigating a feature to allow pgbackrest to copy most of the database heap files _before_ doing backup start, then starting the backup and going back and checking if we need to re-copy any of the files we already copied.  If most of the database is unchanged then this will significantly reduce the amount of time between start backup and stop backup and therefore reduce the amount of WAL that is required for a given backup to be valid.  While this doesn't really help with your situation on the backup side, we expect it to be useful for reducing restore times (where the 'restore time' includes WAL replay to get back to a consistent state), which is why I'm curious and wanted to ask about this.
> > 
> > 
> > In my case the percentage change is maybe 1%, but because the whole DB is ~100Tb, that's still quite a a abit. It would be definitely worth for me to first copy the heap files before the main backup
> 
> Right, does sound that way. You can effectively do what we're imagining the feature doing by taking an incremental right after your full backup. Again, this isn't going to help with the current issue you're running into where the WAL volume is filling up because archiving isn't going fast enough, but it might make you more comfortable with reducing the parallel workers for the backup to allow archiving to keep up knowing that the incremental will go a whole bunch faster than the full and so you won't end up having to do a restore that's replaying many TBs of WAL.
> 
> As always, strongly recommend that you do test your restore process regularly and see how long it takes given a system this large and plan accordingly.

Thanks for responses.

It seems that my requirements are a bit niche here, and my suggestion was not very useful. 
I'll close the issue.

**Comment by sfrost** [comment]
> > > > * Have you considered reducing the parallel workers for the backup, to avoid the network being saturated, so that the WAL is able to be archived?
> > > 
> > > 
> > > The reason for using so many workers is because the DB is so large and the backup takes so long, so I chose to saturate the CPU and use the maximum compression possible and ensure the bandwidth is fully saturated.
> > 
> > 
> > Hopefully you're using zstd..?
> 
> I am using lz4 which should be fine I believe speed-wise.

Sure ... but it doesn't compress as well as zstd and if the issue is the network is too slow then using more CPU to do more compression might help as it would reduce the amount of data having to be sent across the network.

> > Is there a reason why it's an issue that the backup takes a long time? Generally speaking, we don't care too much about how long a full backup takes, what matters is restore time, and it's best to go ahead and take an incremental right after a full, if you full takes a long time, as that will minimize the restore time by reducing the amount of WAL that has to be replayed.
> 
> The reason the DB size is 130 Tb. When compressed in a backup it takes ~ 70Tb, but even transfer of that at 100Mbytes/s would take 8 days.

That's not really saying why it's an issue that the backup takes a long time, just saying that it does...

> It is not a big issue for me as I do need to do that often, as the DB is mostly static. And TBH I don't care about restore time either, I can tolerate a week of downtime. My use-case is fairly atypical obviously.

If the restore would involve this same network then the restore time seems likely to be over a week...  Perhaps even two weeks of downtime is still fine for your use-case, but if not you'll want to consider investing in a faster network.

> At this point I didn't yet manage to make pg_backrest incremental backup work, I was hoping that would speed things up (I need to investigate it).

With a mostly static database, a pgbackrest incremental backup should be very fast, and small.

> > > > * If the network isn't able to handle the rate of WAL generation with a reduced number of parallel workers performing the backup, then I seriously think you are in a potentially untenable situation as any hiccup on the network will end up with a WAL backlog that might be unrecoverable and results in a DB crash due to WAL volume filling up.  You should seriously consider if this design is really acceptable.
> > > 
> > > 
> > > Unfortunately my DB is mostly read-only, but in this case there was an update and I encountered the issue. Previously I used pitrery to do the backup and I din't have the issue, because I was saving WAL locally first before sending it to the network in the end.
> > 
> > 
> > In theory you could have a local pgbackrest repo that you back up to and then just copy to the NFS mount, but as noted before, that means you're at risk of losing whatever backups and WAL are only in the local repo should something happen.
> 
> Yes that would work. (unfortunately I don't have enough space to do that in practice, I do for the WAL though)

Given that it's mostly read-only, I have to admit that I'm a bit surprised that the network is getting so saturated and so little is being given to the WAL archiving to make it fall so far behind.  "Mostly read-only" and "generating so much WAL that I run out of space / the limited network bandwidth isn't enough to keep up with archiving" aren't really making sense together.  Also, using zstd to reduce the size of the backup and then reducing the parallel workers down such that the network isn't completely saturated and the WAL is able to be archived would hopefully make the backup only take a little while longer to run.

> > > > * How much of the database (heap files, in particular...) is changing during the backup?  We are currently investigating a feature to allow pgbackrest to copy most of the database heap files _before_ doing backup start, then starting the backup and going back and checking if we need to re-copy any of the files we already copied.  If most of the database is unchanged then this will significantly reduce the amount of time between start backup and stop backup and therefore reduce the amount of WAL that is required for a given backup to be valid.  While this doesn't really help with your situation on the backup side, we expect it to be useful for reducing restore times (where the 'restore time' includes WAL replay to get back to a consistent state), which is why I'm curious and wanted to ask about this.
> > > 
> > > 
> > > In my case the percentage change is maybe 1%, but because the whole DB is ~100Tb, that's still quite a a abit. It would be definitely worth for me to first copy the heap files before the main backup
> > 
> > 
> > Right, does sound that way. You can effectively do what we're imagining the feature doing by taking an incremental right after your full backup. Again, this isn't going to help with the current issue you're running into where the WAL volume is filling up because archiving isn't going fast enough, but it might make you more comfortable with reducing the parallel workers for the backup to allow archiving to keep up knowing that the incremental will go a whole bunch faster than the full and so you won't end up having to do a restore that's replaying many TBs of WAL.
> > As always, strongly recommend that you do test your restore process regularly and see how long it takes given a system this large and plan accordingly.
> 
> Thanks for responses.
> 
> It seems that my requirements are a bit niche here, and my suggestion was not very useful. I'll close the issue.

Perhaps a bit niche but we'd still like to have pgbackrest work.  I appreciate that it's a bit of additional effort but I do suspect that your case could be handled by pgbackrest with a bit of additional configuration and without having to queue up all of the WAL and have the remote archive end up falling far behind (meaning potentially a lot of data loss if the primary system ended up going completely offline too...).

As an interesting feature idea- perhaps we could make pgbackrest able to detect when WAL archiving isn't keeping up during a backup and throttle back automatically on the backup side until WAL archiving has caught up...

**Comment by segasai** [comment]
> > 
> > I am using lz4 which should be fine I believe speed-wise.
> 
> Sure ... but it doesn't compress as well as zstd and if the issue is the network is too slow then using more CPU to do more compression might help as it would reduce the amount of data having to be sent across the network.

Thank you, I will give zstd a try. 

> 
> > > Is there a reason why it's an issue that the backup takes a long time? Generally speaking, we don't care too much about how long a full backup takes, what matters is restore time, and it's best to go ahead and take an incremental right after a full, if you full takes a long time, as that will minimize the restore time by reducing the amount of WAL that has to be replayed.
> > 
> > 
> > The reason the DB size is 130 Tb. When compressed in a backup it takes ~ 70Tb, but even transfer of that at 100Mbytes/s would take 8 days.
> 
> That's not really saying why it's an issue that the backup takes a long time, just saying that it does...
> 
> > It is not a big issue for me as I do need to do that often, as the DB is mostly static. And TBH I don't care about restore time either, I can tolerate a week of downtime. My use-case is fairly atypical obviously.
> 
> If the restore would involve this same network then the restore time seems likely to be over a week... Perhaps even two weeks of downtime is still fine for your use-case, but if not you'll want to consider investing in a faster network.
> 
> > At this point I didn't yet manage to make pg_backrest incremental backup work, I was hoping that would speed things up (I need to investigate it).
> 
> With a mostly static database, a pgbackrest incremental backup should be very fast, and small.

It is maybe my lack of trying/understanding. I remember a few times I tried, I got the impression (from looking at the actual files/speed of the backup) pgbackrest does the full backup irrespective of 'diff' option, but I clearly misunderstand something.



> > > > 
> > > > Unfortunately my DB is mostly read-only, but in this case there was an update and I encountered the issue. Previously I used pitrery to do the backup and I din't have the issue, because I was saving WAL locally first before sending it to the network in the end.
> > > 
> > > 
> > > In theory you could have a local pgbackrest repo that you back up to and then just copy to the NFS mount, but as noted before, that means you're at risk of losing whatever backups and WAL are only in the local repo should something happen.
> > 
> > 
> > Yes that would work. (unfortunately I don't have enough space to do that in practice, I do for the WAL though)
> 
> Given that it's mostly read-only, I have to admit that I'm a bit surprised that the network is getting so saturated and so little is being given to the WAL archiving to make it fall so far behind. "Mostly read-only" and "generating so much WAL that I run out of space / the limited network bandwidth isn't enough to keep up with archiving" aren't really making sense together. Also, using zstd to reduce the size of the backup and then reducing the parallel workers down such that the network isn't completely saturated and the WAL is able to be archived would hopefully make the backup only take a little while longer to run.

I agree it is a bit weird, but it's mostly read only, but occasionally(rarely) a user may create a  table or something, and that could easily be 200GB or so (which is tiny wrt the size of the whole DB, but what brought down my DB recently when I was backing up) 


> > It seems that my requirements are a bit niche here, and my suggestion was not very useful. I'll close the issue.
> 
> Perhaps a bit niche but we'd still like to have pgbackrest work. I appreciate that it's a bit of additional effort but I do suspect that your case could be handled by pgbackrest with a bit of additional configuration and without having to queue up all of the WAL and have the remote archive end up falling far behind (meaning potentially a lot of data loss if the primary system ended up going completely offline too...).

Yes, thank you I will try to play more configuration.
