### ISSUE TITLE
Archive wal with streaming archiving to ensure RPO = 0

### ISSUE THREAD

**Issue by anayrat** [pgbackrest/pgbackrest#2233]
Hello,
Currently, wal archiving is done thank to `archive_command`. Even if we can change `archive_timeout` there is no way to ensure we don't lost any transaction (RPO=0).

Sometimes, we want to ensure, no transactions are lost. And only a synchronous streaming archiving can offer that.
I know it can be very expensive regarding performance, but sometimes, you prefer performance penalty and ensure you warranty RPO=0.

Only Barman can offer that, it could be a good improvement in pgBackRest to add this functionality. Users can choose between :

- Very fast (asynchronous) archiving thanks to current async archiving.
- Use streaming archiving. Maybe with synchronous (and performance penalty) to ensure RPO=0

Regards,

**Comment by sfrost** [comment]
PG can offer what you're asking for by simply having a sync streaming replica.  If this is your requirement, then you should absolutely have a sync streaming replica that addresses this need.  We don't have any plans to write a whole bunch of additional code to deal with the streaming replication system in PG for what is ultimately a very poor design choice to try and use a tool like pg_receivewal or similar to fake having a proper sync replica.

**Comment by anayrat** [comment]
Thanks for your answer. We can use pg_receivewal with pgbackrest ? Maybe I missed it ?

My use case is very simple : "We want backup with RPO=0".

**Comment by sfrost** [comment]
Nothing prevents you from using pg_receivewal if you want and you could even push that WAL into pgbackrest if you want to using regular archive-push, but again, if this is a requirement, you should have a real PG sync replica (or probably more than one replica with at least one providing sync...).  Don't push partial WAL segments into the pgbackrest repo though.

**Comment by dwsteele** [comment]
> I don't see the point with sync replica. You can completely choose to have an RTO of 4H by restoring a backup and an RPO of 0 because you don't want to lose a transaction.

Sure, you can, but a sync replica seems more efficient for this case, both in terms of performance during normal operation and for recovery.

Having said that, I can definitely see the advantage of an RPO=0 backup for certain use cases. But I'm not sure it is a strong enough use case to justify the development effort, at least not at this time.

**Comment by sfrost** [comment]
> * start synchronous pg_receivewal
> * Put the wal in a spool folder
> * Take each complete wal, calculate checksum, compress the file and move it in pgbackrest's archive folder

No, I was suggesting you could start pg_receivewal, have the WAL go into a spool folder, and then loop over that folder and just call 'pgbackrest archive-push' on WAL files which are the compete (and therefore are exactly 16MB in size).  I definitely do NOT recommend copying things directly into the pgbackrest repo.

Or, really, you could just run pg_receivewal and have it spool into a directory and then just periodically clean it up, perhaps having whatever script that does that check that a given WAL is in the pgbackrest repo first before removing it.

The most difficult and potentially buggy part of all of this would be on the restore side, really, since you'd have to adjust the restore command to check for a WAL file being in this other spool area if pgbackrest doesn't find it.  Certainly not impossible but would be annoying.  All of this hand-hacking is strongly discouraged though and, again, a much, much better design would be to have a sync replica for this use-case.  Simply having a sync replica would give address this use-case and is much better tested than any of the other approaches and much less likely to lead to a surprise somewhere along the way.

> I don't see the point with sync replica. You can completely choose to have an RTO of 4H by restoring a backup and an RPO of 0 because you don't want to lose a transaction.

I agree that this is a valid use-case but the much, much, much more tested and proven and understood approach for it is simply having a sync replica, which then provides other advantages.  Either way you need to have a separate system, running another service that has to be monitored and maintained.

> That's what Barman propose : https://docs.pgbarman.org/release/3.9.0/#wal-streaming

That doesn't make it a good idea.

In terms of what pgbackrest might be able to do to make this easier, without a huge amount of additional code- we could possibly consider allowing partial WAL to be archived, such that you wouldn't have to deal with scripting around the restore command.  That opens up the question about how often you'd want to do that though as it wouldn't be cheap and you'd still have the issue of having some delay between the WAL getting pulled down by pg_receivewal and it getting into the pgbackrest repo.

I suppose another possibility would be for pgbackrest to support a pg_receivewal spool dir where pgbackrest archive-get would check for WAL that isn't in the repo yet and maybe even support archiving into the pgbackrest repo from the spool dir, cleaning it up once the WAL has made it into the repo.  Seems like it would still be a fair bit of code and maybe not less than just writing the code to pull from the PG server directly using the replication protocol, and this approach would end up being pretty limited in terms of what would be supported- you'd have to have a separate server where this is all happening and couldn't have pgbackrest just pushing from the primary system to some remote object store, though even if we made that work somehow, I'm not sure the performance of it would be acceptable- do you really want to wait on s3 to accept the most recent WAL before allowing a transaction to finish being committed?

**Comment by dwsteele** [comment]
> Seems like it would still be a fair bit of code and maybe not less than just writing the code to pull from the PG server directly using the replication protocol

If we were to do this, we'd definitely want to do it directly via the protocol.
