### ISSUE TITLE
The problem of conflicting timelines

### ISSUE THREAD

**Issue by booven** [pgbackrest/pgbackrest#2283]
Hi, When I use pgbackrest to restore to another instance, there is an issue with timeline conflicts if there are wal logs inside the other instance repository.
For example, the current backup set wal log is 00000025000000190000001A, then after cross-instance recovery the next wal log will start from 00000026000000190000001A, and when I use this backup set again for cross-instance recovery, the wal log will still start from 00000025000000190000001A. The wal log will still start from 00000025000000190000001A, which will lead to wal log conflict problem and cannot be archived.
Using the upgrade command can solve part of the scenario, pgbackrest will create a new folder for storing wal logs, but if the same backup set is used repeatedly for cross-instance recovery, the wal log conflict issue still occurs, is there any way to avoid the issue, or is there a command that pgbackrest can force the switch the archive folder. switch the archive folder.
Thank you very much!

**Comment by pgstef** [comment]
Hi,

> When I use pgbackrest to restore to another instance, there is an issue with timeline conflicts if there are wal logs inside the other instance repository.

What other instance repository? Can you provide an example and configurations used?

> For example, the current backup set wal log is 00000025000000190000001A, then after cross-instance recovery the next wal log will start from 00000026000000190000001A, and when I use this backup set again for cross-instance recovery, the wal log will still start from 00000025000000190000001A. 
> The wal log will still start from 00000025000000190000001A, which will lead to wal log conflict problem and cannot be archived.

What conflict exactly? I mean if you had a timeline switch already, PG would find `00000026.history` in the archives directory and pick 00000027 as a new timeline id.
Recovery and timelines are something handled by PG, not by pgBackRest by the way. And that's the all point of timelines: figure out which data have been written after a recovery.

> Using the upgrade command can solve part of the scenario, pgbackrest will create a new folder for storing wal logs, but if the same backup set is used repeatedly for cross-instance recovery, the wal log conflict issue still occurs, is there any way to avoid the issue, or is there a command that pgbackrest can force the switch the archive folder. switch the archive folder.

What do you call **cross-instance recovery**? Because you shouldn't have 2 PG primary clusters pushing backups/wal archives to the same stanza.
If it's just a test server, then the recovered test cluster shouldn't push anything to the main repo and you could very well erase it with a fresh restore.

To give you a real example:

```
wal archive min/max (16): 000000010000000000000005/00000001000000000000000E

full backup: 20240213-093658F
    timestamp start/stop: 2024-02-13 09:36:58+00 / 2024-02-13 09:37:01+00
    wal start/stop: 000000010000000000000005 / 000000010000000000000006
    database size: 22.2MB, database backup size: 22.2MB
    repo1: backup set size: 3.0MB, backup size: 3.0MB
```

If you don't specify any recovery setting, the default PG behavior will be to recover the data to the consistency point by replaying 000000010000000000000005 + 000000010000000000000006, replay all the data it can from 000000010000000000000007 -> 00000001000000000000000E and then once the recovery has ended and the recovered server promoted, a timeline switch will occur -> 00000002000000000000000F.
If this is the new primary of the cluster/stanza, then PG will try to push `00000002.history` and 00000002000000000000000F to the repo.
Then you generate some data and have like 000000020000000000000010, 000000020000000000000011 and 000000020000000000000012 in the repo.
If you restore that backup set again, PG will follow the latest timeline before switching to a new one, and therefore will need the info from `00000002.history`.
Basically, PG would recovery the data to the consistency point by replaying 000000010000000000000005 + 000000010000000000000006, then find out the swith point of the 00000002 timeline and try to replay all the wal entries from 000000010000000000000007 -> 00000001000000000000000E until that switch point, and then replay all the wal entries from the 00000002 timeline (00000002000000000000000F -> 000000020000000000000012) and finally set a new 00000003 timeline at the end of the recovery. 
So no conflict if you have done things correctly thanks to the history files.

And as mentioned above, if it's a test server, just disable archiving (`resotre --archive-mode=off`) so you'd be able to restore/recover from scratch every time without polluting your main respository.

However, it is very hard to tell what you're doing wrong since you don't provide any real example nor configuration.

Regards,

**Comment by booven** [comment]
Hi,  I'm honored to receive your reply message, and I'm sorry I'm just now seeing the message.
I see what you mean, PG will determine the timeline for the next wal log based on the .history file.
My problem is that there are now two instances bound to pgbackrest and running right now, they both have their own repositories, demo1 and demo2, and I would like to restore demo2's instances through demo1's backup set. The pgbackrest.conf  is shown below:
```
[demo1] 
pg1-path=/app/pg/demo2/data
pg1-port=xxxx
pg1-user=xxxx
````
Where **/app/pg/demo2/data** is the data directory of the corresponding instance of demo2, and the archive_command is set to demo2 after recovery .I achieve cross-instance recovery in this way.
```
archive_command = 'pgbackrest --stanza=demo2 archive-push %p'
```
Borrowing from your example.
```
wal archive min/max (16): 000000010000000000000005/00000001000000000000000E

full backup: 20240213-093658F
    timestamp start/stop: 2024-02-13 09:36:58+00 / 2024-02-13 09:37:01+00
    wal start/stop: 000000010000000000000005 / 000000010000000000000006
    database size: 22.2MB, database backup size: 22.2MB
    repo1: backup set size: 3.0MB, backup size: 3.0MB
```
suppose the archive file in demo1 is as follows:
```
000000010000000000000005
000000010000000000000006
...
00000001000000000000000E
00000001.history
```
The archive file in demo2 is as follows:
```
00000002000000000000000E
00000002000000000000000F
000000020000000000000010
00000002.history
```
With my configuration file above, the timeline that the recovered instance relies on is the **.history** in demo1, which may conflict with the wal log file that has been archived in demo2, so I hope to avoid that issue.
```
ERROR: [045]: raised from local-1 protocol: WAL file '00000002000000000000000F' already exists in the repo1 archive with a different checksum
```
If there is a problem with this configuration, or any other solution, please advise.
Looking forward to your reply.

**Comment by pgstef** [comment]
> If there is a problem with this configuration, or any other solution, please advise.

It ain't going to work imho. That's not meant to work like that.
Erasing demo2 with demo1 restore will create a totally new cluster. So it can't co-exist with the previous demo2 cluster backups/archives. You're basically experiencing split-brains situations -> 2 primary clusters living at the same time.

**Comment by booven** [comment]
> It ain't going to work imho. That's not meant to work like that.

Is there any other way to restore another pgbackrest bound  (with stanza repository)  instance from demo1's backup set?

**Comment by booven** [comment]
This approach does cause a lot of problems and I will try something else.

Thanks a lot for your reply.
