### ISSUE TITLE
Make use of GCS batch requests to speed up expiry

### ISSUE THREAD

**Issue by franciscoreinolds** [pgbackrest/pgbackrest#2309]
Hi,

One of our databases' backups was in a pretty weird state, where it backed up quickly (15m) but spent a lot longer expiring archived files (+7h) from our GCS repo.

Enabling `repo-bundle` did massively improve the situation (down to 2h30 of expiration), but it still seems odd. I looked at the `expire` code, and from what I could understand, the [removal is issued per file](https://github.com/pgbackrest/pgbackrest/blob/main/src/command/expire/expire.c#L711-L726), which would incur a lot of overhead.

I don't know about Azure or S3, but GCS makes it possible to [batch](https://cloud.google.com/storage/docs/batch) operations, among which, `deletes`.

This might be an interesting opportunity to massively speed up this operation with not too much cost (unsure of how complex refactoring the code would be to accommodate this).

Curious to hear your thoughts about it!

**Comment by dwsteele** [comment]
> and from what I could understand, the [removal is issued per file](https://github.com/pgbackrest/pgbackrest/blob/main/src/command/expire/expire.c#L711-L726)

This only happens for the last partially full WAL dir, but could certainly stand to be improved. However, I doubt it is your issue.

> I don't know about Azure or S3, but GCS makes it possible to [batch](https://cloud.google.com/storage/docs/batch) operations

We have batch deletes for S3 but GCS and Azure require multipart request/response which we have not implemented yet. I've created project cards for this work (https://github.com/pgbackrest/pgbackrest/projects/2#card-92166945, https://github.com/pgbackrest/pgbackrest/projects/2#card-92166953).

Not exactly sure when we can get to this but having cards will at least bump the visibility. With performance this bad we should be able to give it some priority.

**Comment by dwsteele** [comment]
Batch delete for GCS was implemented in 76bcb740b6.

**Comment by dtseiler** [comment]
Great to see this is (hopefully) fixed. We've had similar issues where the full backup would finish but then the expiration would take an extremely long time. This past weekend we had a few Monday morning incrementals skipped because the Sunday morning post-backup expiration was still going. One expiration alone took over 28 hours. We just moved to GCS from Azure in March and it's been noticable in my head but I hadn't taken the time to do any forensic investigation.

We'll look to upgrade to 2.52 ASAP.

**Comment by dwsteele** [comment]
> We just moved to GCS from Azure in March and it's been noticable in my head

Interesting since Azure works the same way. I have a batch delete for Azure in progress but it was giving me some problems and I have not gotten back to it yet. I do wonder if the performance of GCS delete changed recently which made this more of an issue or if there has just been more uptake of GCS.

**Comment by dtseiler** [comment]
Up until now I could only say that it "felt" like it took longer to do the expirations (we had to expire a lot after the initial cutover since we had just been transferring the entire repo). But with Azure it didn't seem like things took extraordinarily long. Certainly not 28 hours. I'm happy to try to capture anything you'd like to see. Our full backups run Sat night and incr the other nights of the week.

**Comment by dwsteele** [comment]
> I'm happy to try to capture anything you'd like to see.

It'd certainly be nice to see a comparison of how long it takes to expire using an older version vs 2.52 -- but I already know it is much faster since I tested it.

Are you using file bundling? That also helps a lot.

**Comment by dtseiler** [comment]
I'm not familiar with file bundling in this context, is that a pgBackrest feature? I'll do some digging tomorrow. But I'll assume we aren't using it.

**Comment by dwsteele** [comment]
See https://pgbackrest.org/user-guide.html#backup/bundle.

**Comment by dtseiler** [comment]
Oh wow that sounds like a really nice feature for cloud storage like this. I'll plan to start trialing that in our lower environments.

**Comment by dtseiler** [comment]
@dwsteele I just wanted to double-check: Is anything required to enable the batch expiration/deletion for GCS? Or will be done automatically? I didn't see anything in the user guide either way.

**Comment by dwsteele** [comment]
> Is anything required to enable the batch expiration/deletion for GCS? Or will be done automatically?

It is automatic.
