### ISSUE TITLE
pgbackrest info takes long time

### ISSUE THREAD

**Issue by glushakov** [pgbackrest/pgbackrest#2351]
1. pgBackRest version: 2.51
2. PostgreSQL version: 15.5
3. Operating system/version AlmaLinux 9
4. Did you install pgBackRest from source or from a package?  - package from PGDG

Hi.
Thanks for the great tool!
We use pgbackrest with s3 (minio) storage. Some clusters store in stanza millions of WAL segments (according to the retention policy).
On such clusters, the "pgbackrest info" command takes quite a long time to execute (sometimes up to 2 minutes).
I'm guessing this has to do with gathering real information about WAL segment boundaries?
Maybe there a way to optimize this query?

**Comment by vidierr** [comment]
It's related to S3 storage.
I had this when I was using S3 storage and since I migrated to NFS it's almost instantaneous.
The info command should read all files, including wals.

**Comment by glushakov** [comment]
It may be possible to add a parameter that will not scan WAL when used. 
For monitoring, it is important to have information about a successful backup and it is not very convenient when the data takes so long to be returned.
Another option is to have the data cached in a metafile that will be updated periodically. But I'm not sure about the possibility of this solution.

**Comment by pgstef** [comment]
> It may be possible to add a parameter that will not scan WAL when used. 

That wouldn't make sense imo. Backups without WAL archives are totally useless. And here, only the oldest and the newest are searched, not scanning the entire archives repo...

> For monitoring, it is important to have information about a successful backup and it is not very convenient when the data takes so long to be returned.

So it is to have the archives info. And I personally don't find "up to 2 minutes" a monitoring problem. You're not taking backups every 5 minutes, but usually once a day. So you shouldn't run the monitoring query every minute anyway.
And it's slow because of your storage, not because of the tool.

If you are really concerned about your monitoring, are you even checking that all the required WAL archives are still in the repo after the backup was taken? That will take significantly longer, even more on object stores.

I don't want to start another debate but just as David mentioned already, I don't see what we could do about your GH issue.

**Comment by glushakov** [comment]
I understand your point.
I just wanted to highlight a potential problem that arises when using s3 storage.
For example, on the same cluster there is a problem when deleting backups after the expiration date, and I had to raise io-timeout.
For now, our current solution is to raise timeouts and increase the size of WAL segments.

**Comment by dwsteele** [comment]
Even given the number of WAL segments, this seems unusually slow. Four million WAL segments would only be 15625 paths to list. My guess is Minio is not very fast at summarizing, or the storage is slow, or there's less-than-ideal config.
