### ISSUE TITLE
Suggestion: take advantage of "remote copy" APIs on storage backends supporting them

### ISSUE THREAD

**Issue by tsutsu** [pgbackrest/pgbackrest#2355]
Right now, there is a key trade-off in pgBackRest configuration, between use of `diff` and `incr` backups. `incr` backups are (often much) faster to make than `diff` backups; but pgBackRest can't expire old `incr` backups (after the latest `full` or `diff` backup), because they all reference files from previous `incr` backups.

But what if the advantages of `diff` and `incr` modes could be combined (for at least some storage backends)?

S3-compatible object-store APIs support a "remote copy" (`CopyFile`) API call. This call, given the URL of an existing object, exposes that same object's data under a new key (with, optionally, different object metadata associated with it.) Objects are immutable, so internally to these object-stores, this "remote copy" is done simply by adding a new metadata to the bucket that references the existing object data content-hash key. This means that such "remote copies" complete in O(1) time. Their semantics can be thought of as being more akin to a "remote hard-link" or "remote copy-on-write clone" operation, than anything like a file copy. (Though, like a file copy, and unlike a hard-link/clone, any additional copies of an object *are* considered to take up additional billable storage in the buckets they're in.)

If pgBackRest took advantage of this "remote copy" operation for backends that have it, I can see several useful (and previously possible-in-theory, but impractical) features, being made practical:
- acceleration of `full` backups (other than the first backup of a fresh stanza.) This would be an option for `full` backups, to allow them to use the logic of `incr`-mode backups to upload only modified files/blocks (and so have the speed of an `incr` backup), but which would end up "filling out" the rest of the backup (by remote-copying unchanged files referenced by the manifest into the backup's directory) — making it into a standalone `full` backup as intended.
- the addition of an explicit `compact` or `backup:convert-to-full` operation, which could convert an arbitrary existing `diff` or `incr` backup into a `full` backup, by discovering any pointers to previous backups in the manifest, remote-copying those into the backup dir, and rewriting the manifest to point to the now-local objects. (This could also be done without affecting the existing source backup, by doing a remote-copy of _all_ objects referenced from the source backup manifest into a fresh backup dir, and then generating a new manifest referencing all of those objects, resulting in a new "dense" version of the backup being created alongside the existing "sparse" backup.)
- the addition of an explicit `copy` operation, that allows one or all backups + segments under one stanza to be remote-copied into another stanza (note that the S3-compatible `CopyFile` operation allows cross-bucket copies!)
- (bit of a stretch, but fun to think about:) the addition of an explicit `relocate-stanza` operation, that could allow a stanza's bucket or prefix to be changed — with the archiving destination temporarily being updated to an intermediate "write to `$old`, then remote-copy to `$new`" state; the backup destination being updated to `$new`; existing backups and archives in `$old` being remote-copied to `$new` (with configured expire rules used to filter out would-have-expired backups + segments); archiving updated to just write to `$new`; and `$old` purged. (Adding this would probably require the ability of stanzas to have multiple sub-locations as config entries.)

It seems to me that, with such features in place, there'd be no reason for someone using an object-store storage backend to ever choose the `diff` backup strategy — they'd instead either:
- use frequent `incr` backups + less-frequent accelerated `full` backups
- use frequent `incr` backups and periodically convert the latest `incr` backup to a `full` backup
- always use accelerated `full` backups

**Comment by dwsteele** [comment]
> S3-compatible object-store APIs support a "remote copy" (CopyFile) API call. 

This is feature we have been looking at -- and more generally the ability to copy unchanged data from prior backups rather than needing to recompress/reencrypt it.

> This would be an option for full backups, to allow them to use the logic of incr-mode backups to upload only modified files/blocks (and so have the speed of an incr backup)

I doubt we would do this. Block incremental chains can get quite long and they affect restore performance. What we *can* do is reconstruct files from the repo that have not changed since the last backup (even if the last backup was not full). But we'd store them as if they had been made from a full backup.

> the addition of an explicit compact or backup:convert-to-full operation

We would only do this if some portion of the full backup is rechecked each time. Otherwise an issue (e.g. a bug in an older version of pgBackRest) could be propagated forever.

> the addition of an explicit relocate-stanza operation

Interesting idea. It wouldn't be as efficient if the remote copy command is not available, but would still be handy for users to have a built-in way to do it. I'd say something like this would be pretty far down on our list of priorities, though.

> there'd be no reason for someone using an object-store storage backend to ever choose the diff backup strategy

I'd still use it. The reason is that 3 diff backups are still often smaller than 6 incr backup. I prefer to have three days of daily backups. Most PITR situations are resolved in three days, and if not then the appropriate full is sufficient. Diff backups are just easier to expire since they only have one dependency.
