### ISSUE TITLE
Backing up to machine with test database

### ISSUE THREAD

**Issue by step21** [pgbackrest/pgbackrest#2356]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.37

2. PostgreSQL version: 14.11

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
* DB: Ubuntu Linux 22.04.3 LTS
* Repo/Test DB: Ubuntu Linux 22.04.3 LTS

6. Did you install pgBackRest from source or from a package?

package

7. Please attach the following as applicable:
pgbackrest.conf of repo/test db   
 ``` 
 [global]
process-max=4

[test_backup]
pg1-path=/var/lib/postgresql/14/main
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
repo1-cipher-pass=<>
repo1-cipher-type=aes-256-cbc

[main_backup]
#pg1-path=/var/lib/postgresql/14/prod_backup
pg1-path=/var/lib/postgresql/14/main
pg2-host=db
pg2-host-user=postgres
repo2-path=/var/lib/pgbackrest_remote
repo2-retention-full=2
repo2-cipher-pass=<>
repo2-cipher-type=aes-256-cbc

[global:archive-push]
compress-level=3
 ```

main db config:
```
[global]
process-max=4
start-fast=y

[main_backup]
pg1-path=/var/lib/postgresql/14/main
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
repo1-retention-diff=23
repo1-cipher-pass=<>
repo1-cipher-type=aes-256-cbc
repo2-host=test
repo2-host-user=postgres
repo2-cipher-pass=<>
repo2-cipher-type=aes-256-cbc
repo2-path=/var/lib/pgbackrest_remote

[global:archive-push]
compress-level=3
```

```
# (on the repo host)
sudo -u postgres pgbackrest --stanza=main_backup --log-level-console=info backup
2024-05-22 00:03:16.845 P00   INFO: backup command begin 2.37: --exec-id=2119880-a038dd50 --log-level-console=info --pg1-host=db --pg1-host-user=postgres --pg1-path=/var/lib/postgresql/14/main --process-max=4 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/var/lib/pgbackrest_remote --repo1-retention-full=2 --stanza=main_backup
WARN: no prior backup exists, incr backup has been changed to full
2024-05-22 00:03:18.051 P00   INFO: execute non-exclusive pg_start_backup(): backup begins after the next regular checkpoint completes
2024-05-22 00:03:19.657 P00   INFO: backup start archive = 000000010000000C000000E8, lsn = C/E8000028
2024-05-22 00:03:19.657 P00   INFO: check archive for prior segment 000000010000000C000000E7
ERROR: [082]: WAL segment 000000010000000C000000E7 was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
2024-05-22 00:04:19.758 P00   INFO: backup command end: aborted with exception [082]
```
2024-05-22 00:26:12.035 UTC [2690330] LOG:  archive command failed with exit code 104
2024-05-22 00:26:12.035 UTC [2690330] DETAIL:  The failed archive command was: pgbackrest --stanza=main_backup archive-push pg_wal/000000010000000B00000060
ERROR: [104]: archive-push command encountered error(s):
       repo2: [FileMissingError] unable to load info file '/var/lib/pgbackrest_remote/archive/main_backup/archive.info' or '/var/lib/pgbackrest_remote/archive/main_backup/archive.info.copy':
       FileMissingError: raised from remote-0 ssh protocol on 'test': unable to open missing file '/var/lib/pgbackrest_remote/archive/main_backup/archive.info' for read
       FileMissingError: raised from remote-0 ssh protocol on 'test': unable to open missing file '/var/lib/pgbackrest_remote/archive/main_backup/archive.info.copy' for read
       HINT: archive.info cannot be opened but is required to push/get WAL segments.
       HINT: is archive_command configured correctly in postgresql.conf?
       HINT: has a stanza-create been performed?
       HINT: use --no-archive-check to disable archive checks during backup if you have an alternate archiving scheme.
```
In this case, this is probably pg1-path missing from the repo host. However when I had it, there was another issue, and espcially also the issue that the repo number must be the same on repo host, than it is on the db host, no? As otherwise it complains that it cannot find it, if called repo2 on test, and repo1 on prod.


8. Describe the issue:

scenario: prod and test, both set up with pgbackrest. Before they were each backing up their own db, to their own machine.
As a next step, I wanted to backup the prod db to a separate db on the test machine, but NOT as a replication, only as a backup. With the option to restore to prod or to the test machine for updating testing data. By now, the machines do have a connection, and stanzas are created, but there's always something not working, so maybe this is not supported? or more likely, I am messing sth up with how repo and pg and their numbers go together.

So I'd like to know if the scenario I want to use is supported, and if yes, why isn't it working. I guess part of the confusion is that when one one machine there is repoX, the remote machine should be name similary. But then somehow pg1-path f.e. has to be there, despite everything else being repo2 etc? I think I am likely misunderstanding some kind of terminology or how things fit together, however while the docs were very helpful, for this they haven't helped so far. I omit further log files as there was nothing relevant I think.

**Comment by pgstef** [comment]
Hi,

The repo nb should match between the db host and the repo host. And you should put the repo config in the global section. 

> however while the docs were very helpful, for this they haven't helped so far

That's because you're mixing a lot a concepts that shouldn't be used like that. A repository host should be a dedicated backup server, it shouldn't have a db running on it. That backup server can be used to centralize multiple stanzas into the same place. And mixing up the stanza names will make it more complicated for you to restore the prod backup on the test server.

With a local repo and a remote repo on your main db, you'll also over-complicate things by changing the place where the backup command has to run. And storing the backups locally on the same db host is the best way to lose everything in case of a disaster. 

Don't forget that multi-repo for the same stanza should have the same data. If you restore on the cluster B, a backup from cluster A, the recovery will try to apply WALs from the B stanza and that will just mess everything up.

What you can do is to keep it simple on your production server, by pushing your backups/archives to one of the available [repo types](https://pgbackrest.org/configuration.html#section-repository/option-repo-type). Then, on the test server, setup your backups with the same stanza name and use a local repo if you really want to. Finally, when you want to restore a backup from prod to test, just point the repository target of the test server to the production one (ideally with RO access so you don't mess up with production data, and using the `stop` command before the restore to prevent the restored cluster to push archives or backups to the wrong repo). Once the recovery has ended, switch back to your test repo, trigger the `start` command and take a new backup.

Since this question (of imo misusing repo hosts, and how to restore a production backup onto a test server) comes regularly, I should probably write a blog post about it to show a working example.

**Comment by step21** [comment]
Thanks for your very helpful answer. I know that this is not ideal, but the idea by others was like "let's test it like that first, we can make a dedicated machine later" and I know it wasn't ideal, but couldn't push back that much. I'll try to just get it on dedicated host.
Regarding repo-types - so far I haven't had a repo type and just used ssh. Would it be better to use sftp? In any case, thanks a lot already for your help! 🌟

**Comment by pgstef** [comment]
If you're aiming at a dedicated backup server, then ssh or tls it is. If you want to push backups/archives from the db host to a shared/central location, then you can use of the repository types available: in that case, sftp is an option, nfs share/mount is another.
