### ISSUE TITLE
Pgbackrest 

### ISSUE THREAD

**Issue by waqas7pk** [pgbackrest/pgbackrest#2362]
select lsn::text as lsn,
pg_catalog.pg_walfile_name(lsn)::text as wal_segment_name
from pg_catalog.pg_backup_start('pgBackRest backup started at ' || current_timestamp, false) as lsn

I want alter such query while starting backup

Which file need to be altered???

How to change this in already installed pgbackrest from official website

**Comment by pgstef** [comment]
Duplicates [this](https://github.com/pgbackrest/pgbackrest/issues/2336#issuecomment-2132823446) comment.

> How to change this in already installed pgbackrest from official website

You can't. If you modify the sources, you'll need to compile and install your own binaries. 

> Which file need to be altered???

[This](https://github.com/pgbackrest/pgbackrest/blob/main/src/db/db.c#L339) one, first. And then investigate the impact at every place where this helper is used. That's definitely something we wouldn't support imo since this query returns the important information needed for the backup.

> I want alter such query while starting backup

Why? What are you trying to achieve exactly?

Regards

**Comment by waqas7pk** [comment]
while executing this from dbeaver 


select lsn::text as lsn,
              pg_catalog.pg_walfile_name(lsn)::text as wal_segment_name
         from pg_catalog.pg_backup_start('pgBackRest backup started at ' || current_timestamp, false) as lsn

we faced

SQL Error [22007]: ERROR: invalid input syntax for type timestamp with time zone: "pgBackRest backup started at "
  Position: 141

**Comment by pgstef** [comment]
Why do you want to execute this in dbeaver? It is automatically run by the pgBackRest backup command. You shouldn't play with that manually... You shouldn't have to fix this if you use the latest pgBackRest release and community PostgreSQL.

**Comment by waqas7pk** [comment]
just to verify the execution of query and try to apply workaround if above query execute from dbeaver definitly its execute by pgbackrest

**Comment by pgstef** [comment]
You wouldn't need a workaround unless the backup command fails. In such cases you would have an error message and you could open a new issue for potentially helping fix a real problem.

**Comment by waqas7pk** [comment]
So what is your suggestion?

**Comment by pgstef** [comment]
I don't have any suggestion since you didn't reported any error with pgBackRest...

Don't try to use the sql queries in your own without any context. Just use the software and if you get errors while using it, follow the proper issue template to submit the error including context (config files, error message,...).

**Comment by dwsteele** [comment]
As we said in #2336 you need to follow up with the agedb devs to find out why this query does not work. We're not going to blindly make changes to pgBackRest in hopes it will work with a certain fork of Postgres.

If you would like to make the changes yourself you can find the relevant code here: https://github.com/pgbackrest/pgbackrest/blob/release/2.52/src/db/db.c#L340.
