### ISSUE TITLE
Schema level backup using Pgbackrest

### ISSUE THREAD

**Issue by jahnavisana2812** [pgbackrest/pgbackrest#2368]
Hi,
Is it possible to perform a schema-level backup using pgBackRest? Specifically, I am interested in understanding if pgBackRest has built-in capabilities to back up individual schemas within a PostgreSQL database, rather than backing up the entire database. If it does not support this directly, what are the recommended best practices or workarounds to achieve schema-level backups while still utilizing pgBackRest's features for reliability and efficiency? Additionally, how can I integrate these schema-level backups into a comprehensive backup strategy that leverages pgBackRest for full database and incremental backups?
Thank you,
Sana Jahnavi

**Comment by pgstef** [comment]
Hi,

All databases in a single cluster (and schemas in those databases) should be considered one unit for the purposes of backup and restore. This is a limitation of PostgreSQL.

>  file system backups only work for complete backup and restoration of an entire database cluster

There's no recommended best practices or workarounds to achieve schema-level, since this isn't very meaningful imo. If the data across the schemas are tight together, they should be saved/restored together. If they're isolated, then spiting them into various databases or even separated clusters would make sense. But that's an app consideration.

From the backup/restore point-of-view, the entire cluster should be handled. Then, if you only need to recover 1 schema, you still can restore the cluster (possibly even only one specific db thanks to the `--db-include` option) and then extract the data you wanted from that recovery target with pg_dump. But this requires some business/app logic knowledge more than a DB administration expertise tbh.

See [PG docs](https://www.postgresql.org/docs/current/continuous-archiving.html) for more details.

Regards
