### ISSUE TITLE
Pgbackrest INCR Backups Consuming Too Much Disk

### ISSUE THREAD

**Issue by abdullahergin** [pgbackrest/pgbackrest#2375]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: `2.51`

2. PostgreSQL version: `13.3`

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: `Ubuntu 20.04`

4. Did you install pgBackRest from source or from a package? repo;  
`sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list' wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -`

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
```
    - - archive_mode = on
     - archive_command = 'pgbackrest --stanza=my_stanza archive-push %p'
     - listen_addresses = *
     - max_wal_senders = 10 
     - wal_level = replica
     - port = 5433
```
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

I have a configuration where I take backups on a standby server. In case of any problems in the database, I was asked to be able to restore to 15 minutes ago. So I set up the setup as follows;
Full backup one day a week,
Diff backup once a day,
Incr backup every 15 minutes every day.

But I think there is a problem with the setup. First of all, is it necessary to take a backup every 15 minutes to go back to 15 minutes ago, or is it enough for me to take a full backup once a week and 1 incr backup once a day to go back to 15 minutes ago?

My configs are as follows;

Conf;
```
pg-backup;

[global]
repo1-path=/mnt/dbbackup
repo1-retention-full=2
process-max=2
start-fast=y
log-level-console=info
log-level-file=info
backup-standby=y

[global:archive-push]
compress-type=zst
compress-level=3

[my_stanza]
pg1-host=primary_hostname
pg1-path=/data
pg1-port=5433
pg2-host=standby_hostname
pg2-path=/data
pg2-port=5433
```
```
pg-primary;
[global]
log-level-file=info
repo1-host=backup_hostname
start-fast=y
archive-async = y
process-max = 2
spool-path = /var/spool/pgbackrest

[global:archive-get]
process-max=4

[global:archive-push]
process-max=4


[my_stanza]
pg1-path=/data
pg1-port=5433
```

```
pg-standby
[global]
log-level-file=info
repo1-host=backup_hostname
start-fast=y
process-max = 2
spool-path = /var/spool/pgbackrest

[my_stanza]
pg1-path=/data
pg1-port=5433
```

I don't know if there is a problem with the script I installed or with my pgbackrest config files.

In addition, I tried to install the block incr structure of pgbackrest from the previous topic, but it had no effect: [link](https://pgbackrest.org/user-guide.html#backup/block)

I set this parameter on both primary and standby server but it had no effect;

Last full backup and reference incr backups;
```
8.9G    20240613-110729F
1.2G    20240613-110729F_20240613-111503I
5.1G    20240613-110729F_20240613-113003I
4.2G    20240613-110729F_20240613-114504I
4.2G    20240613-110729F_20240613-120004I
```

Total size of incr backups taken with the previous full backup reference;
```
4.0G    20240604-172054F_20240613-103004I
6.9G    20240604-172054F_20240613-104504I
4.0G    20240604-172054F_20240613-110004I
739G    total
```
**The size of my database cluster is only 12 GB**

What I need to do?

Thanks.

**Comment by pgstef** [comment]
Hi,

> I have a configuration where I take backups on a standby server. In case of any problems in the database, I was asked to be able to restore to 15 minutes ago. So I set up the setup as follows; Full backup one day a week, Diff backup once a day, Incr backup every 15 minutes every day.
> 
> But I think there is a problem with the setup. First of all, is it necessary to take a backup every 15 minutes to go back to 15 minutes ago, or is it enough for me to take a full backup once a week and 1 incr backup once a day to go back to 15 minutes ago?

No, you don't need an incremental backup every 15 minutes. With the WAL archives you should be able to recover up until the latest archive generated. But that has nothing to do with pgBackRest, that's PostgreSQL PITR basics. See [continuous archiving documentation](https://www.postgresql.org/docs/current/continuous-archiving.html).

`log-level-file=info` you should raise that to detail, which would be helpful for you to learn what's going on during the backup command.

The info command would be helpful too I guess. The given configuration doesn't show that you used the block-level incremental backup. By default, every data file that has been modified since the latest backup will be copied in the incremental backup. And by default, it is based on file modification time. If you got some clock screw-ups between your hosts, that can be a problem. With block incremental correctly setup, you'll only copy the parts of the files that were modified (the blocks, not the entire file), so it can reduce the disk space. And if you're unsure about the clock/time, just use `delta=y` for the backup command, this will use the checksums.

See this nice blog post to understand what is block-level: https://www.crunchydata.com/blog/pgbackrest-file-bundling-and-block-incremental-backup



> What I need to do?

There's not much more we can do to help you. David already gave you the answer in your other issue. IMHO, you should also read a bit more about PostgreSQL write-ahead-logs to learn how all this is working.

Regards
