### ISSUE TITLE
feature request: archive-push-queue-max monitoring

### ISSUE THREAD

**Issue by jw1u1** [pgbackrest/pgbackrest#2390]
If archive-push-queue-max kicks in, a warning message is logged in the postgres log.
It would be helpful to have this information in the pgbackrest info output.
If this occurs during a full-backup, the backup process should be canceled.

**Comment by dwsteele** [comment]
> It would be helpful to have this information in the pgbackrest info output.

That seems useful but not sure how we'd go about implementing in. Lock files won't work here and I'm not too excited about storing transient state in the repo.

Probably we'd implement something like this with gap detection (if we did it at all), which we already have a project card for: https://github.com/orgs/pgbackrest/projects/3/views/1?filterQuery=ar&pane=issue&itemId=66662979. The problem there is it is extremely IO intensive so we have never implemented it in info -- for that you need verify.

> If this occurs during a full-backup, the backup process should be canceled.

Again, useful, but there would be a lot of implementation behind it, mostly because the backup process generally does not run on the same host as archive-push so the question would be how do they communicate.

What would be more likely is that we'd monitor the WAL during the backup to make sure it advances. Right now we check at the beginning and the end. This would be better anyway because it would detect any disruption in archiving, no matter the cause. I have created a project card for this (https://github.com/orgs/pgbackrest/projects/3/views/1?filterQuery=archiv&pane=issue&itemId=69197297) but put it in the backlog since it it not something we are planning to look at anytime soon.
