### ISSUE TITLE
WAL summarizer in pg 17  and incremental backups in pgbackrest ?

### ISSUE THREAD

**Issue by zejeanmi** [pgbackrest/pgbackrest#2405]
Hello
As you know, the new WAL summarizer that should be introduced in upcoming Postgres 17 will allow incremental backup with pg_combinebackup.
Will PgBackrest rely on / switch to this new feature in future versions to implement incremental backups ?
Thank you !

**Comment by dwsteele** [comment]
We already support page-level (we call it block-level) incremental since v2.46 and it works for all versions of PostgreSQL supported by pgBackRest (>= 9.4), see https://pgbackrest.org/user-guide.html#backup/block.

We are planning to use the WAL summarizer to help us pick more optimal block sizes and cross-check timestamps but we are waiting for it to be a bit more stable. Also, the WAL summarizer output uses a lot of memory and is not the best fit for large databases with a lot of changes. We have some ideas on how to make that more efficient but have not had time to pursue it yet.

**Comment by zejeanmi** [comment]
Thank you
