### ISSUE TITLE
PITR Failing

### ISSUE THREAD

**Issue by BabaTataKaka** [pgbackrest/pgbackrest#2433]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
   2.53.1

3. PostgreSQL version:
   16.3
4. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
ubuntu 22.04
5. Did you install pgBackRest from source or from a package?
  package
6. Please attach the following as applicable:
 **pgbackrest.conf** 

```
[global]

log-level-file=detail

log-level-console=info

log-path=/var/log/pgbackrest

repo1-type=posix

repo1-path=/var/lib/pgbackrest

repo1-retention-full=4

repo1-retention-archive=4

start-fast=y

stop-auto=y

resume=n

link-all=y

archive-check=y

archive-copy=n

backup-standby=y


# Include stanzas configuration files

include-path = /etc/pgbackrest/conf.d

```

  **postgresql.conf**

```
archive_command = 'pgbackrest --stanza=postgres-cluster archive-push %p'

archive_mode = 'True'

archive_timeout = '1800s'

listen_addresses = 'pg-2.server.ta,127.0.0.1'

max_wal_senders = '10'

port = '5432'

wal_level = 'logical'

# recovery.conf

primary_conninfo = 'user=replicator host=pg-1.server.ta port=5432 sslmode=verify-full sslcert=/etc/postgresql/certs/tls.crt sslkey=/etc/postgresql/certs/pkc8.key sslrootcert=/etc/ssl/certs/ca-certificates.crt application_name=svr117 gssencmode=prefer channel_binding=prefer'

primary_slot_name = 'svr117'
```

7. Describe the issue:

Here what i did :
1-Deployed the cluster.
2-Entered data in DB
3-Ran backup from pgbackrest server
4- Deleted data from DB
5- Ran point_in_time_recovery.

The restore is successfully on the master only.

**Postgres master logs:**
```
2024-07-31 13:55:13 UTC [34061-4] x.x.x.x(38560) replicator@[unknown] ERROR:  requested starting point 0/8000000 on timeline 1 is not in this server&apos;s history
2024-07-31 13:55:13 UTC [34061-5] x.x.x.x(38560) replicator@[unknown] DETAIL:  This server&apos;s history forked from timeline 1 at 0/7000170.
2024-07-31 13:55:13 UTC [34061-6] x.x.x.x(38560) replicator@[unknown] STATEMENT:  START_REPLICATION SLOT &quot;svr002&quot; 0/8000000 TIMELINE 1

```
**Postgres replicas logs:**
```
2024-07-31 14:10:23 UTC [31599-1]  FATAL:  could not start WAL streaming: ERROR:  requested starting point 0/8000000 on timeline 1 is not in this server's history
	DETAIL:  This server's history forked from timeline 1 at 0/7000170.
```

This is from a PITR from an existing cluster. Looks like its working when restoring from a new cluster. Looks like a problem wit the timeline but not sure why. There is no error in the pgbackrest logs on both the master and replicas.

**Comment by pgstef** [comment]
> There is no error in the pgbackrest logs on both the master and replicas.

Because there's no problem from the restore point-of-view. That's a PostgreSQL error which most probably comes from a process misunderstanding.

> Looks like a problem with the timeline but not sure why.

The primary created a new timeline when it reached the recovery target. So the standby needs to be reconstructed and switch timeline at the same point as your primary, but not perform PITR on the standby.

> The restore is successfully on the ~~master~~ primary only.

What steps did you follow to reconstruct your standby server exactly?

> ERROR:  requested starting point 0/8000000 on timeline 1 is not in this server's history
> 	DETAIL:  This server's history forked from timeline 1 at 0/7000170.

Usually you recover the primary with the time (or another) recovery target and once it has been recovered, restore the standby without the recovery target (so PG will replay everything it needs to catch-up with the primary).
It's even easier to take a new backup after the primary has been recovered and use that to reconstruct the standby (less data to replay during the recovery process).

pgBackRest only handles the restore process which is restoring the backup files from the backup repository to your database server. Then PostgreSQL performs the recovery based on the settings you provided.

Kind Regards

**Comment by BabaTataKaka** [comment]
> > There is no error in the pgbackrest logs on both the master and replicas.
> 
> Because there's no problem from the restore point-of-view. That's a PostgreSQL error which most probably comes from a process misunderstanding.
> 
> > Looks like a problem with the timeline but not sure why.
> 
> The primary created a new timeline when it reached the recovery target. So the standby needs to be reconstructed and switch timeline at the same point as your primary, but not perform PITR on the standby.
> 
> > The restore is successfully on the ~master~ primary only.
> 
> What steps did you follow to reconstruct your standby server exactly?
> 
> > ERROR:  requested starting point 0/8000000 on timeline 1 is not in this server's history
> > DETAIL:  This server's history forked from timeline 1 at 0/7000170.
> 
> Usually you recover the primary with the time (or another) recovery target and once it has been recovered, restore the standby without the recovery target (so PG will replay everything it needs to catch-up with the primary). It's even easier to take a new backup after the primary has been recovered and use that to reconstruct the standby (less data to replay during the recovery process).
> 
> pgBackRest only handles the restore process which is restoring the backup files from the backup repository to your database server. Then PostgreSQL performs the recovery based on the settings you provided.
> 
> Kind Regards

HI, thanks for your reply.

I'm using the following ansible playbook to performer the backup and restore:

https://github.com/vitabaks/postgresql_cluster

I opened a ticket regarding the same issue.

Not sure if that answer your question about the replicas reconstruction but here the command that is run for the postgres recovery on replicas(same as master):

`
"/usr/lib/postgresql/16/bin"/pg_ctl start -D /var/lib/postgresql/16/postgres-cluster" -o '-c hot_standby=off' -w -t 1800"`

Looks, like the restore command is also run on the replicas which contradict your statement about not running the PITR on the replica and only on the master. I'm confused.

One thing I noted in the backup logs on the pgbackrest server is that it looks like it backup the master and one of the replicas but not the second replicas. Is that normal?

Also I'm using patroni for HA. I know its not pgbackrest but I found the following lines interesting:
```
2024-08-30 13:07:07,406 WARNING: Postgresql is not running.

2024-08-30 13:07:07,406 INFO: Lock owner: svr116; I am svr5118

2024-08-30 13:07:07,408 INFO: pg_controldata:

  pg_control version number: 1300

  Catalog version number: 202307071

  Database system identifier: 7408648673377205663

  Database cluster state: shut down in recovery

  pg_control last modified: Fri Aug 30 13:06:44 2024

  Latest checkpoint location: 0/6000060

  Latest checkpoint's REDO location: 0/6000028

  Latest checkpoint's REDO WAL file: 000000010000000000000006

  Latest checkpoint's TimeLineID: 1

  Latest checkpoint's PrevTimeLineID: 1

  Latest checkpoint's full_page_writes: on

  Latest checkpoint's NextXID: 0:753

  Latest checkpoint's NextOID: 24576

  Latest checkpoint's NextMultiXactId: 1

  Latest checkpoint's NextMultiOffset: 0

  Latest checkpoint's oldestXID: 723

  Latest checkpoint's oldestXID's DB: 1

  Latest checkpoint's oldestActiveXID: 753

  Latest checkpoint's oldestMultiXid: 1

  Latest checkpoint's oldestMulti's DB: 1

  Latest checkpoint's oldestCommitTsXid: 0

  Latest checkpoint's newestCommitTsXid: 0

  Time of latest checkpoint: Thu Aug 29 20:06:04 2024

  Fake LSN counter for unlogged rels: 0/3E8

  Minimum recovery ending location: 0/7000170

  Min recovery ending loc's timeline: 1

  Backup start location: 0/0

  Backup end location: 0/0

  End-of-backup record required: no

  wal_level setting: logical

  wal_log_hints setting: on

  max_connections setting: 600

  max_worker_processes setting: 24

  max_wal_senders setting: 10

  max_prepared_xacts setting: 0

  max_locks_per_xact setting: 512

  track_commit_timestamp setting: off

  Maximum data alignment: 8

  Database block size: 8192

  Blocks per segment of large relation: 131072

  WAL block size: 8192

  Bytes per WAL segment: 16777216

  Maximum length of identifiers: 64

  Maximum columns in an index: 32

  Maximum size of a TOAST chunk: 1996

  Size of a large-object chunk: 2048

  Date/time type storage: 64-bit integers

  Float8 argument passing: by value

  Data page checksum version: 1

  Mock authentication nonce: d9cf6b46f85851c95a4d777fb793ed9ff43b291763f6f0cf7f932b991e967f95



2024-08-30 13:07:07,409 INFO: Lock owner: svr116; I am svr118

2024-08-30 13:07:07,419 INFO: Local timeline=1 lsn=0/7000170

2024-08-30 13:07:07,574 INFO: primary_timeline=3

2024-08-30 13:07:07,574 DEBUG: primary: history=1	0/7000170	before 2024-08-29 20:08:33.325189+00





2	0/70032D8	no recovery target specified



2024-08-30 13:07:07,575 INFO: primary: history=1	0/7000170	before 2024-08-29 20:08:33.325189+00

2	0/70032D8	no recovery target specified

2024-08-30 13:07:07,575 INFO: Lock owner: svr116; I am svr118

2024-08-30 13:07:07,576 INFO: starting as a secondary

2024-08-30 13:07:07,596 DEBUG: Starting postgres: /usr/lib/postgresql/16/bin/postgres -D /var/lib/postgresql/16/main --config-file=/etc/postgresql/16/main/postgresql.conf --listen_addresses=pg-3.ll,127.0.0.1 --port=5432 --cluster_name=postgres-cluster --wal_level=logical --hot_standby=True --max_connections=600 --max_wal_senders=10 --max_prepared_transactions=0 --max_locks_per_transaction=512 --track_commit_timestamp=off --max_replication_slots=10 --max_worker_processes=24 --wal_log_hints=True

2024-08-30 13:07:07,981 INFO: postmaster pid=166440

2024-08-30 13:07:08,066 INFO: establishing a new patroni heartbeat connection to postgres

2024-08-30 13:07:08,067 DEBUG: API thread: 10.136.16.57 - - "OPTIONS /replica?lag=100MB HTTP/1.0" 503 - latency: 0.955 ms

2024-08-30 13:07:08,392 INFO: establishing a new patroni heartbeat connection to postgres

2024-08-30 13:07:08,403 INFO: establishing a new patroni restapi connection to postgres
```

**Comment by pgstef** [comment]
> Not sure if that answer your question about the replicas reconstruction but here the command that is run for the postgres recovery on replicas(same as master):
> 
> ` "/usr/lib/postgresql/16/bin"/pg_ctl start -D /var/lib/postgresql/16/postgres-cluster" -o '-c hot_standby=off' -w -t 1800"`

That's the command to start Postgres, not to re-sync a standby server.

> Looks, like the restore command is also run on the replicas which contradict your statement about not running the PITR on the replica and only on the master. I'm confused.

I don't know the rationale behind those scripts but I wrote down how a Point-in-time Recovery should be performed in a streaming replication environment -> perform the recovery on the primary to the specific recovery target, then re-sync your standbys. You have several ways of working to re-sync the standby: it can be a copy from scratch (using i.e. pg_basebackup) or using a regular backup restore (without a recovery target, i.e. using the `--type=standby` restore option). In most cases, it is faster to restore from backup but also easier to first take a backup of the recovered primary before re-sync the standbys (which would be safer and reduce the amount of WAL data to replay). 

> One thing I noted in the backup logs on the pgbackrest server is that it looks like it backup the master and one of the replicas but not the second replicas. Is that normal?

I don't understand that statement. You shouldn't take multiple backups. Or you aim at the primary, or you aim at the standbys. If you take a backup from standby, the backup command will pick the first one in the list and backup the data files from that one. But there's no point to take a backup from standby if you also take backups from the primary.
And the backup from standby is an hybrid backup: the backup control session (pg_backup_start/stop) will be done against the primary, then most of the data files will be copied from the standby, and finally some specific files will be copied from the primary. 

> Also I'm using patroni for HA.

Then you should follow Patroni best-practices. Perform PITR on the primary and use Patroni to re-sync the standbys after you took a new backup of the primary.

All these questions are more about Postgres streaming replication management and disaster recovery, rather than specifically tight to pgBackRest itself. I'm not really sure what we could do to help you further tbh.
