### ISSUE TITLE
ERROR: [082]: WAL segment 00000001000XXX was not archived before the 60000ms timeout

### ISSUE THREAD

**Issue by franko108** [pgbackrest/pgbackrest#2451]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.53

2. PostgreSQL version:14.13, with timescale extension v.2.7.0

3. Operating system/version - ubuntu 22.04.5 LTS server. 64 CPU  AMD EPYC 7502P, 256 GB RAM

4. Did you install pgBackRest from source or from a package?   
Both, from the package is v.2.49, then compiled v.2.53

5. Please attach the following as applicable:
  `pgbackrest.conf` file(s):       
  ```
[global]
repo-path=/BACKUP/pg/pgbackrest
process-max=5
start-fast=y
repo1-retention-full=1
repo1-retention-diff=4
repo1-cipher-pass=xxxxyyyy
repo1-cipher-type=aes-256-cbc
repo1-retention-history=7

[global:archive-push]
compress-level=8

[db-primary]
db-path=/var/lib/postgresql/14/main/
```

  - postgresql.conf settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`):  
 ```
archive_mode = on
archive_command = 'pgbackrest --stanza=db-primary archive-push %p'
#listen_addresses  # no settings
max_wal_senders = 3
wal_keep_size = 1024MB
max_wal_size = 6GB
min_wal_size = 64MB
wal_buffers = 16MB
checkpoint_completion_target = 0.8
wal_level = replica
port = 5432
``` 
  
Errors in the postgresql log file before or during the time you experienced the issue:    
  `2024-09-23 07:16:41.505 UTC [419068] postgres@postgres WARNING:  aborting backup due to backend exiting before pg_stop_backup was called`   

log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`):  

```
-------------------PROCESS START-------------------
2024-09-23 07:15:35.167 P00   INFO: backup command begin 2.53.1: --exec-id=419067-35122ce3 --log-level-console=detail --pg1-path=/var/lib/postgresql/14/main/ --process-max=5 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/BAC
KUP/pg/pgbackrest --repo1-retention-diff=4 --repo1-retention-full=1 --repo1-retention-history=7 --stanza=db-primary --start-fast --type=full
2024-09-23 07:15:35.875 P00   INFO: execute non-exclusive backup start: backup begins after the requested immediate checkpoint completes
2024-09-23 07:15:41.477 P00   INFO: backup start archive = 0000000100044C5F00000051, lsn = 44C5F/512D0C58
2024-09-23 07:15:41.477 P00   INFO: check archive for prior segment 0000000100044C5F0000004C
2024-09-23 07:16:41.501 P00  ERROR: [082]: WAL segment 0000000100044C5F0000004C was not archived before the 60000ms timeout
                                    HINT: check the archive_command to ensure that all options are correct (especially --stanza).
                                    HINT: check the PostgreSQL server log for errors.
                                    HINT: run the 'start' command if the stanza was previously stopped.
2024-09-23 07:16:41.501 P00   INFO: backup command end: aborted with exception [082]
```  

7. Describe the issue:   
Database is big, 2 Tb.   
I had this setup working for months, occasionally failed with the same error, but now I can't perform backups anymore, always the same error. I tried to increase and decrease `min_wal_size` , `checkpoint_completion_target`, but always the same error.   
Also tried to disable setting: `start-fast=y`, no changes.    
Stop then start the stanza didn't help here.   
I've seen several issues here with very similar problems, and I don't understand what is their solution.   
This is  the zabbix monitor db, quite busy, but the server load isn't big, as this is big server. Also, no oom noticed.

Let me know if you need more details, thank you.

**Comment by pgstef** [comment]
Hi,

First of all, `repo-path` should be `repo1-path` and `db-path` (which has been deprecated long ago) should be `pg1-path`.

> Both, from the package is v.2.49, then compiled v.2.53

Definitively, if you can, stick with the PGDG packages: they are compiled with all the dependencies needed.

> I tried to increase and decrease min_wal_size , checkpoint_completion_target, but always the same error.
> Also tried to disable setting: start-fast=y, no changes.

Those settings have an effect on the `pg_start_backup()` PostgreSQL internal function. The idea is to request for an immediate checkpoint or wait for the next regular one triggered by PostgreSQL itself (with checkpoint_timeout or max_wal_size). What is does is making sure PostgreSQL will write in its data files all the modified buffers so we're not copying "old" data files.

Although, it doesn't seem to be your problem. The `ERROR: [082]: WAL segment 0000000100044C5F0000004C was not archived before the 60000ms timeout` means that the PostgreSQL archive_command is not working or not fast enough (within the archive-timeout period - 60s by default). You could check that with the following query:
```sql
SELECT pg_walfile_name(pg_current_wal_lsn()), last_archived_wal FROM pg_stat_archiver;
```

The user-guide has a [performance tuning](https://pgbackrest.org/user-guide.html#quickstart/performance-tuning) section which could help.

```ini
[global:archive-push]
compress-level=8
```

By default, the compress type is `gz` (with default compress-level = 6), which is already slow. What you made is to make it even slower.
What we'd recommend here is to remove that configuration and use `compress-type=zst` globally (and don't touch the default compression level).
Zstandard does compress very good and is really a lot faster than gzip.

The other thing you can try is to enable [asynchronous archiving](https://pgbackrest.org/user-guide.html#async-archiving). The idea is to use multiple asynchronous processes (you already set `process-max=5`) for the archive-push command too. You then need to set `archive-async=y` and make sure that your PostgreSQL system user (running the archive_command) can write to the spool-path (by default `/var/spool/pgbackrest`).

> I've seen several issues here with very similar problems, and I don't understand what is their solution.

It's usually because they're trying to take backups while archiving isn't pushing to the same repository or because the archiving is too slow (which is potentially your issue too).

Kind Regards

**Comment by franko108** [comment]
Nice, thanks a lot for such a quick and detailed answer!  
It already looks much better as the current full backup is being running.    

I've added into `[global]` section:  
```
archive-async=y
spool-path=/var/spool/pgbackrest
```

and into ` [global:archive-push]`:  
```
compress-type=zst
```     
(or `compress-type` makes more sense into `[global]` section)?   
Also, I commented `compress-level`, as you suggested.

---

While here, just to clarify usage of `archive-get`, if I understand correctly, it is used for restore process.   
Manual states, it can go into postgresql.conf:  
`restore_command = 'pgbackrest --stanza=db-primary archive-get %f "%p"'`   

and what to put into pgbackrest.conf?   
I see example as:   
```
[global:archive-get]
process-max=2
```
There is already defined `process-max` in the `[global]` section.

This is a standalone server.

**Comment by pgstef** [comment]
> or compress-type makes more sense into [global] section

Yes, `compress-type` should be used globally since it applies to all commands.

> there is already defined process-max in the [global] section

So, the idea to set `process-max` globally is to apply it to all commands. As you've enabled async archiving, that setting will also apply to `archive-push` and `archive-get`, not to backup and restore only. If you want to adjust the number of processes (or another specific setting) per command, then the `[global:command]` section makes sense, otherwise you can simply remove the `[global:archive-push]` and `[global:archive-get]` sections.

**Comment by franko108** [comment]
Good, thanks a lot for help. It looks all better now.  
I think we can close this question.
