### ISSUE TITLE
question on timezone with pgBackRest PITR

### ISSUE THREAD

**Issue by mzwettler2** [pgbackrest/pgbackrest#2452]
The Postgres instance is running on timezone CEST (parameter timezone = 'Europe/Zurich') which is UTC+2.

The underlying Linux OS (K8s container) is running on timezone UTC.

Backups are done with pgBackRest.

With PITR we will have to use target timezone CEST (--target=2024-09-19 17:00:00+02") although OS is running on UTC.

Agreed?

**Comment by dwsteele** [comment]
It is always best to specify a timezone offset and using the database timezone makes the most sense. However, you can specify the time in any timezone you want, for instance this `--target=2024-09-19 15:00:00+00` is equivalent to the above.

If you don't specify a timezone offset in your timestamp then pgBackRest will use the *system* timezone to search for a backup while Postgres will use *its* timezone to do recovery. Ideally we'd get the timezone from Postgres but since it is not running during the restore that's not possible (or at least it is very complicated!)

**Comment by mzwettler2** [comment]
So, best practice is to always specify the database timezone offset in the timestamp to be on the safe side.

Anyway. If i understand you correctly, pgbackrest would choose a backup based on UTC time if i don't specify a timezone offset in the timestamp. postgres itself, however, would restore based on CEST time in following because it uses “its” timezone offset again. so it wouldn't really matter whether the timestamp contains the correct timezone offset, would it?

**Comment by dwsteele** [comment]
> so it wouldn't really matter whether the timestamp contains the correct timezone offset as long as this is a positive offset, would it?

It matters. Let's say you wanted to restore to `2024-09-24 12:00:00` in CEST. If you don't specify an offset this will be interpreted as `2024-09-24 12:00:00+00` by pgBackRest but `2024-09-24 12:00:00+02` by Postgres. Since that recovery target is two hours before the time interpreted by pgBackRest, you might not get a backup that is capable of recovering to that point. Or you might, depending on the frequency of your backups and the target time.

To be safe, always specify the offset.

**Comment by mzwettler2** [comment]
argh. yes. 12:00:00+02 = 10:00:00+00. 

so, negative timestamp offsets would not matter.
