### ISSUE TITLE
Why C lang, why not Go lang?

### ISSUE THREAD

**Issue by dhanuj247** [pgbackrest/pgbackrest#2471]
Why did you choose C lang instead of Go lang for development of pgbackrest?

**Comment by dwsteele** [comment]
Simple -- PostgreSQL is written in C and this allows us to easily borrow code and data structures. Since Postgres is written in C we also know that we have a pool of hackers with experience in Postgres and C. With Go, not so much.

Anyway, if I were to pick a modern language it would certainly be Rust not Go.
