### ISSUE TITLE
Backup from standby - 3 node cluster

### ISSUE THREAD

**Issue by uspen** [pgbackrest/pgbackrest#248]
Hi!

I have 3-node test cluster and pgbackrest v1.06. Then i perform backup, its fail. If and only if master is db3-host. My conf:

>db1-host=192.168.56.11
db1-path=/data/pgsql
db1-user=postgres
db2-host=192.168.56.12
db2-path=/data/pgsql
db2-user=postgres
db3-host=192.168.56.13
db3-path=/data/pgsql
db3-user=postgres

**Comment by dwsteele** [comment]
pgBackRest will only backup from a single standby so you should only have db1 and db2 configured.  One should be the master and one the replica in any order.  We plan to improve this in the very near future so that you can configure multiple standbys and pgBackRest will use the first one it finds for the backup.

Further on we plan to allow backup from multiple replicas simultaneously.

**Comment by uspen** [comment]
Thank you!
