### ISSUE TITLE
Restoring on a test server fails because of insufficient parameter settings

### ISSUE THREAD

**Issue by Jahrenski** [pgbackrest/pgbackrest#2480]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 
pgBackRest 2.54.0

2. PostgreSQL version:
Main server : 16.1
Test server : 16.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu 22.04.5 LTS

4. Did you install pgBackRest from source or from a package?
from apt get package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

```
[demo]
    pg1-path=/demo/bd
    pg1-user=postgres
    
    [global]
    repo1-retention-full=4
    repo1-type=s3
    repo1-path=/demo/backup
    repo1-s3-region=ca-central-1
    repo1-s3-endpoint=<redacted>
    repo1-s3-bucket=<redacted>
    repo1-s3-key=<redacted>
    repo1-s3-key-secret=<redacted>
    repo1-cipher-pass=<redacted>
    repo1-cipher-type=aes-256-cbc
    repo1-storage-upload-chunk-size=8MiB
    archive-async = y
    
    start-fast=y
    delta=y
    
    buffer-size=8MiB
    compress-type=zst
    compress-level=1
    compress-level-network=0
    process-max=3
    
    log-level-console=info
    log-level-file=debug
```

    
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    Config on the main server : 

```
archive_command = 'pgbackrest --stanza=demo archive-push %p'
archive_mode = 'on'
max_wal_senders = '3'
wal_level = 'replica'
listen_addresses = '*'

```

Config on the test server : 
```
restore_command = 'pgbackrest --stanza=demo archive-get %f "%p"'
archive_mode = 'off'
max_wal_senders = '3'
wal_level = 'replica'
listen_addresses = '*'
```

7. Describe the issue:
I'm trying to understand why I can't seem to fetch a backup made from a server onto a test server.
I tried many ways without success.

At first I tried restoring using : 
`sudo -u postgres pgbackrest --stanza=demo  restore `

This would fail because of multiple timelines.
```
2024-11-04 12:00:16.598 P00   INFO: archive-get command end: completed successfully (1418ms)
2024-11-04 12:00:16.609 EST [11713] LOG:  restored log file "000000010000001C0000001F" from archive
2024-11-04 12:00:17.309 EST [11713] FATAL:  requested timeline 3 is not a child of this server's history
2024-11-04 12:00:17.309 EST [11713] DETAIL:  Latest checkpoint is at 0/DEAD on timeline 1, but in the history of the requested timeline, the server forked off from that timeline at 1B/B6FFFFF8.
```

I then tried : 
`sudo -u postgres pgbackrest --stanza=demo --archive-mode=off  restore `

This would fail because it also restores the main server's postgresql.auto.conf which resets the archive_mode to on and also generates timeline errors.

Finally, I tried with preserve : 
`sudo -u postgres pgbackrest --stanza=demo --archive-mode=off --type=preserve restore 
`
This fails saying my setting of max_connection = 100 differs from the setting in the main server of 103.
```
2024-11-04 12:05:07.646 EST [12837] FATAL:  recovery aborted because of insufficient parameter settings
2024-11-04 12:05:07.646 EST [12837] DETAIL:  max_connections = 100 is a lower setting than on the primary server, where its value was 103.
```

My question is, how can I restore a backup from any server onto my test machine without having to match the pgtune settings and without the risk of pushing test data into the repo backend ?
And also, can this be caused by a minor PG version difference between main and test servers? (16.1 vs 16.4)

**Comment by pgstef** [comment]
> At first I tried restoring using : `sudo -u postgres pgbackrest --stanza=demo restore `
> 
> This would fail because of multiple timelines.

Multiple timelines shouldn't be a problem. When you want to restore the latest backup and replay up until the latest WAL in the repository, the default restore type is what needs to be used. 
In the latest PG versions, the `recovery_target_timeline` is set to latest by default. So PG would try to recover up until the latest timeline found in the archives.
The `requested timeline 3 is not a child of this server's history` (which is a PG error, not one from pgBackRest) usually means that something is wrong with your repository content (probably a test server pushed some archives to the production repository). It could be interesting to get the info command output and check on what timeline is your production server. That's also why usually it is best to only have a RO access to the production repository.

> DETAIL:  Latest checkpoint is at 0/DEAD on timeline 1

This error message also indicates that something is wrong with your restore process. See the comments of the `0/DEAD` in the [code](https://github.com/pgbackrest/pgbackrest/blob/main/src/postgres/interface.h#L90): `This will prevent PostgreSQL from starting if backup_label is not present`. The backup_label should be in the backup and not touched after the restore, since it is important for PG recovery.

If you messed up with the repository content somehow, obviously you should fix it, but using `--target-timeline=current` could potentially help PG recovery to stay on the timeline of the backup set.

> I then tried : `sudo -u postgres pgbackrest --stanza=demo --archive-mode=off restore`
> 
> This would fail because it also restores the main server's postgresql.auto.conf which resets the archive_mode to on and also generates timeline errors.

Fail? This shouldn't fail. During the restore process, pgBackRest would create the restore_command and other recovery settings according to the restore command options into `postgresql.auto.conf`. This is quite common practice to use `--archive-mode=off` to turn off archiving on the restored test cluster. It wouldn't reset archive_mode to on.

> Finally, I tried with preserve : `sudo -u postgres pgbackrest --stanza=demo --archive-mode=off --type=preserve restore ` This fails saying my setting of max_connection = 100 differs from the setting in the main server of 103.

`--type=preserve` would keep the same `postgresql.auto.conf` as in the backup set (so pgBackRest wouldn't write restore_command). Given that you defined `archive_mode = 'off'` (hopefully in the main /etc/postgresql configuration), using `--archive-mode=preserve` (which is the default) or not using this option should just work.

> My question is, how can I restore a backup from any server onto my test machine without having to match the pgtune settings and without the risk of pushing test data into the repo backend ? 

As mentioned previously, RO access would be the safest. `archive_mode` to off is also good, but not likely enough.

> The settings of some parameters determine the size of shared memory for tracking transaction IDs, locks, and prepared transactions. These shared memory structures must be no smaller on a standby than on the primary in order to ensure that the standby does not run out of shared memory during recovery. For example, if the primary had used a prepared transaction but the standby had not allocated any shared memory for tracking prepared transactions, then recovery could not continue until the standby's configuration is changed. The parameters affected are: max_connections, max_prepared_transactions, max_locks_per_transaction, max_wal_senders, max_worker_processes.

There's nothing we can do about those parameters. It's a PG recovery limitation for the size of the shared memory. You can change it after the recovery if you want but for the recovery the shared memory should not be smaller.

> And also, can this be caused by a minor PG version difference between main and test servers? (16.1 vs 16.4)

Likely not. There are lots of important fixes but nothing regarding recovery behavior AFAIK: https://why-upgrade.depesz.com/show?from=16.1&to=16.4

**Comment by pgstef** [comment]
> Alright I think I understand the concept here for timelines and the default settings. Would using type=immediate always make sure the test server is using the right timeline in this case?

`--type=immediate` would only replay up until the backup consistency point, not further. Using the `recovery_target_timeline='current'` would fit your need imho.

> here's the result of the info command from the test server : I see 000000030000001B000000B6 in the max value, but never mentions 3 in the actual backups pushed to repo.

Definitely something (probably test restored) pushed bad timelines in your repo (if your primary is still on 1st timeline). You should look at it and clean up the repo.

> EDIT: I read more about this and basically this is a pure postgresql issue and not a pgbackrest one at this point. If you set big enough values for : max_connections, max_prepared_transactions, max_locks_per_transaction, max_wal_senders, and max_worker_processes
> 
> The recovery process will manage to replay the wals to a consistant level and start. Then you can change these values to something befitting your test server better.

That's exactly what I wrote in my latest message. You need to pay attention to those settings for the recovery. You can change it afterwards if you really need it indeed.

> Thank you @pgstef you have been a great help!

You're welcome. I guess we can close the issue then ?
