### ISSUE TITLE
Any plan to support PG 17.2 ?

### ISSUE THREAD

**Issue by jasonchenTJ** [pgbackrest/pgbackrest#2494]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
INFRA [postgres@dc02psqldbuat04 roles]# pgbackrest --version
pgBackRest 2.52

2. PostgreSQL version:
psql (PostgreSQL) 17.2

4. Describe the issue:
INFRA [postgres@dc02psqldbuat04 roles]# pgbackrest --stanza=prod7970 --log-level-console=info stanza-create
2024-11-25 17:38:38.485 P00   INFO: stanza-create command begin 2.52: --buffer-size=8MiB --exec-id=85117-3b83d518 --log-level-console=info --pg1-path=/data/prod7970/data --pg1-port=7970 --pg1-socket-path=/tmp --repo1-cipher-type=none --repo1-path=/data/backup --stanza=prod7970
WARN: unable to check pg1: [VersionNotSupportedError] unexpected control version = 1700 and catalog version = 202406281
      HINT: is this version of PostgreSQL supported?
ERROR: [056]: unable to find primary cluster - cannot proceed
       HINT: are all available clusters in recovery?

**Comment by pgstef** [comment]
Hi,

We already answered about PG 17 compatibility in [this issue](https://github.com/pgbackrest/pgbackrest/issues/2465).

> pgBackRest 2.52

Long story short: `2.52` was released before PostgreSQL 17 was actually released and hackers have bumped the catalog version since then. `2.54.0` is fully compliant with PostgreSQL 17.

Before opening an issue, it is usually best to try the latest version available and see if the problem still occurs, as we tend to recommend using latest versions anyway.

@dwsteele Maybe we should adjust the release notes on the website to note "initial support or beta support" for 2.52 and alpha/final support in 2.54.0 so people aim to use 2.54.0 with PG 17?

Kind Regards

**Comment by dwsteele** [comment]
@pgstef:
> Maybe we should adjust the release notes on the website to note "initial support or beta support" for 2.52 and alpha/final support in 2.54.0 so people aim to use 2.54.0 with PG 17?

Good idea. Done in 4af42d93b2a02, but I used 2.53.1 because that's the version that works with 17 GA. The updates in 2.54.0 were just to finalize the catalog version.

**Comment by jasonchenTJ** [comment]
@pgstef @dwsteele  Thank you Both! will try 2.54.0.
