### ISSUE TITLE
Backup of config file

### ISSUE THREAD

**Issue by blogh** [pgbackrest/pgbackrest#252]
Hi,

My client as a directory for config files (`postgresql.conf`, `pg_hba.conf` and `pg_ident.conf`) and one for the data storage.

They start the cluster with :  pg_ctl start -D CONFIG_DIR -w 

And they set the guc `data_directory` to the cluster directory.

My problem is that the backups don't include these files.
I tried to set it up differently with the gucs: `hba_file` / `ident_file`. But couldn't make it work.

Did I miss something ? 

Benoit

** This tool is getting better all the time, Many thanks.

**Comment by dwsteele** [comment]
You didn't miss anything.  pgBackRest only copied files in, or linked from, the $PGDATA directory.  If you really want to copy the config files you'll need a link from $PGDATA, perhaps $PGDATA/pg_config or something like that.

By default pgBackRest does not restore links for safety, so you would need to use --link or --link-all when restoring.  This is a good thing since replicas often have different configs.

For the record, I backup configs with normal system backups or create them dynamically with CM tools so the the above is not something I really recommend, but it will probably do the trick.
