### ISSUE TITLE
Failover/switchover increases incremental backup size almost to a full backup size

### ISSUE THREAD

**Issue by zdravhub** [pgbackrest/pgbackrest#284]
Hi there,

We use pgBackRest for incremental backup of synchronous replication cluster. Automatic failover is configured with Virtual IP in Pacemaker. After failover, the standby node becomes master and although it is synchronized with the former master, the next incremental backup is almost with the size of a full backup. Is it possible after a switchover, the incremental backup size not to be with the size of a full backup?

Thanks in advance,
Zdravko

**Comment by dwsteele** [comment]
Hi Zdravko,

Even though a standby might be logically the same, it will not necessarily be physically the same.  This is because hint bits, free space, and btree page splits (among other things) can be replayed or updated differently.  This depends a lot on your version, too.

Actually, I would recommend taking a full backup after a failover.  It's possible that files with the same timestamp on the standby do not match the data on the master.

We've discussed a feature to force a full on any timeline switch, though it's possible to failover without a timeline switch.  Does your failover include a timeline switch (i.e. does it use promote?)
