### ISSUE TITLE
Backup fails: 2 duplicate files found

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#307]
My pgbackrest backup fails and here are the last few info lines:
```
pgbackrest --type=full --stanza=model   backup log-level-file=info --log-level-console=info

2017-01-13 08:12:06.378 P00   INFO: execute exclusive pg_stop_backup() and wait for all WAL segments to archive
2017-01-13 08:12:08.494 P00   INFO: backup stop archive = 0000000500002A620000006B, lsn = 2A62/6B000DD0
ASSERT [100]: 2 duplicate files found for 00002A620000006B
2017-01-13 08:12:12.121 P00   INFO: backup command end: aborted with exception [100]
```
These files are in the pg_xlog directory:
```
-rw------- 1 postgres postgres 16777216 Jan 13 08:12 0000000500002A620000006B
-rw------- 1 postgres postgres          344 Jan 13 08:12 0000000500002A620000006B.00000028.backup
```
But they were generated during the backup by the date it appears.

**Comment by dwsteele** [comment]
The duplicates refer to the archive, so there are two files with the name *00002A620000006B-* in the archive.  They are probably on different timelines.  If you can find the files and send me the first 64 bytes of each I'll have a look.

However, this usually happens when archive files are manually copied or `archive.info` is removed to "manually" upgrade a cluster to a new major version of PostgreSQL.  Once the WAL from multiple clusters is mixed there's not much pgBackRest can do except throw errors when it sees duplicates.

**Comment by MichaelDBA** [comment]
hmmm, I think it is a bug on my part, trying to get fancy and change stanza targets when backups already exist for another previous location using that same stanza.

Thanks for the info that pointed me in the right direction.
