### ISSUE TITLE
how can i tell if a backup is running?

### ISSUE THREAD

**Issue by sandrotosi** [pgbackrest/pgbackrest#330]
Hello,
we have our monitoring system configured to warn us if the backup is older than a given threshold. but sometimes it takes longer than expected, and anyway, as the db grows, the backup time will increase and we'd have to periodically increase the threshold as well, so we would like to improve that.

We would like to extend that monitoring logic to not warn if the backup is older and a backup is running. but, how can i tell if a backup is running?

i was hoping something in `pgbackrest info` output would say that, but it only contains completed backups. i would rather not parse the logs. is the only way left checking the currently running processes?

thanks!

**Comment by dwsteele** [comment]
Currently there is no way to know except to check the process list, which would probably be fragile.  Another way would be to test if a backup lock exists and is locked, e.g. $LOCK_PATH/$STANZA_backup.lock.  I can't guarantee that those locks won't be renamed over time but you could give it a try.

For my 2c I don't think you should be so eager to check for new backups.  Checking that WAL is current is arguably more important and that is in the json info output.

**Comment by sandrotosi** [comment]
we setup this platform during the gitlab "backup" issue, so we'd rather be over-paranoid and check everything :)

how can i tell that `wal archive min/max: 000000010000086700000077 / 000000010000087E000000C2` is current? i guess i should check on the master instance if the last generated WAL is equal to the max reported in that line? that would also mean that the WAL files are archived, not necessarily that a backup was taken, and successful, correct?

**Comment by dwsteele** [comment]
When it comes to backups paranoia is generally a good thing.

Yes, the best thing to do is compare to the database.  Timestamps are not a great indicator because a quiet database may not generate WAL very often.

Yes, this indicates only that WAL logging is working.  However, if you have a backup and your WAL archive is up to date, then you should be good.  The only question is how long it will take to replay the WAL.  That's where diff/incr backups come in.
