### ISSUE TITLE
pgbackrest info doesn't show running backups

### ISSUE THREAD

**Issue by marcinbarczynski** [pgbackrest/pgbackrest#345]
I set up a backup schedule in crontab, and expected that running backup is also included in the output of `pgbackrest info`. Unfortunately, it's not. This means that I have to consult pgbackrest log file to check if backup is progressing.

**Comment by dwsteele** [comment]
We are planning to do this at some point, but it's not a big priority.

Whether or not a backup is running is lot less important than the last backup that completed.  That's what you really want to be monitoring.

**Comment by obernhard** [comment]
For sure, knowing that your backup has completed successfully is what you really want to monitor. However, from a production perspective it's also vital to know what your system is doing. what could really help (because i didn't see it yet in any backup tool) is a dedicated database catalog in which you can check your backup history for any database, as well as archived wals / Timelines and of course the current backup status (in progress, completed successfull / warning / errors).

**Comment by dwsteele** [comment]
Agreed, and we would to do it at some point.  It's just not at the top of the list right now.

During the backup backrest maintains a connection to the cluster.  So you could also look for that connection.  The app name will be "pgBackRest [backup]".

**Comment by dwsteele** [comment]
This has been added to the backlog.  Thanks!

**Comment by RonJohn2** [comment]
Was this added to v1.24?  (I don't see it in v2.07.)

**Comment by dwsteele** [comment]
No, it was added to the backlog.  We're getting more requests for it, though, so it is getting towards the top.

**Comment by dwsteele** [comment]
This feature has been committed at 1c1a7104604 for v2.27.
