### ISSUE TITLE
64bit only?

### ISSUE THREAD

**Issue by jungle-boogie** [pgbackrest/pgbackrest#350]
Hi All,

I understand this is 2017 and not the year 2000, which means everyone should already be running 64bit everywhere - especially on database servers.

That said, my postgres databases run on a raspberry pi for Freeswitch. I compile both of the projects from git master source a few times a month. I'd like to use pgbackrest between the pi and a i386 FreeBSD build, also with postgresql running on git master.

With that said, what kinds of trouble will I have if pgbackrest is used? Understandably I won't be able do parallel backups, but the databases are very, very small anyway.

> Note that only 64-bit distributions are currently supported due to 64-bit operations in the Perl code.

http://www.pgbackrest.org/user-guide.html

Thanks!

**Comment by jungle-boogie** [comment]
FreeBSD:
This is perl 5, version 24, subversion 1 (v5.24.1) built for i386-freebsd-thread-multi-64int

raspberry pi:
This is perl 5, version 20, subversion 2 (v5.20.2) built for arm-linux-gnueabihf-thread-multi-64int
(with 92 registered patches, see perl -V for more detail)

Is this okay?

**Comment by dwsteele** [comment]
Well, the main issue is that 64-bit ints are used to read the PG system indentifier so almost everything will blow up if 64-bit ints are not supported in your Perl.  64-bit in support is available in i386 perl but it is a compile-time option that not all distros specify.

According to this (https://buildd.debian.org/status/package.php?p=pgbackrest) pgBackRest happily builds and tests on several 32-bit architectures, but since I don't test any myself I don't want to make any guarantees.

**Comment by jungle-boogie** [comment]
Looks like freebsd has this compile time option enabled for packages:
`PERL_64BITINT=on: Use 64 bit integers (on i386)`
https://www.freshports.org/lang/perl5.24/

And since it looks like `pgbackrest` is build on various arm architectures for debian, I think i might be out of the woods!

> I don't want to make any guarantees.

Absolutely understood.
