### ISSUE TITLE
Exclude pg_xlog in delta mode

### ISSUE THREAD

**Issue by LaetitiaLoxo** [pgbackrest/pgbackrest#353]
Hi,

I think it would be a good idea to exclude the pg_xlog directory when we restore a cluster. That way, WALs that haven't been archived but that could contain committed data won't be erased and the recovery will take them by default.

Moreover, you could maybe indicate in your documentation to save the pg_xlog before each restore operation ?

Regards,

Arkhena

**Comment by dwsteele** [comment]
It's an interesting idea.  I can see how it might be useful in some cases but there are also times when it would be a very bad thing to do.  In a recovery situation the local WAL may not represent the true timeline - and replaying it would cause silent corruption.

Also, I don't think this would play very nicely with the `recovery_command` and be hard for the user to manage reliably in practice.

I will give it some thought, though.

**Comment by LaetitiaLoxo** [comment]
Sure, I didn't think about the wrong timeline case.

Maybe we could add it as an option ?

**Comment by dwsteele** [comment]
It could be an option, but I don't think it would be very clear when it should be used -- so it probably wouldn't be used.

I think it would generally be best to fail over to a streaming replica or set archive_timeout to something very small.  Mucking about with the WAL manually can have unexpected consequences.

**Comment by dwsteele** [comment]
I thought about this a bit.  If a `recovery_command` is specified, then PG won't use anything in `pg_xlog` -- it will always call the `recovery_command`.

That being the case I don't see how useful this option would be.  The user can always move WAL if they have a very special situation.  In general though, it is best and safest to get WAL from the archive.

**Comment by LaetitiaLoxo** [comment]
I disagree...
If you look at documentation (and also at the code in xlog.c), you will find that WALs in archive folder are prefered to pg_xlog but if a WAL is only present in the pg_xlog directory it will be taken into account while recovering.

> WAL segments that cannot be found in the archive will be sought in pg_xlog/; this allows use of recent un-archived segments.
From [https://www.postgresql.org/docs/current/static/continuous-archiving.html](https://www.postgresql.org/docs/current/static/continuous-archiving.html)

When you're crash recovering you need those WALs. They contain you're last committed transactions (that of course you don't want to loose). Even if it's only a few, I think it needs considering keeping them.

**Comment by dwsteele** [comment]
Whoops, you are correct.  I somehow transformed "will always try recovery_command first" in my mind to "will only use recovery command".

Even so, I'm not convinced.  This option supposes that there is *unarchived* WAL that needs to be used during the restore and that's not a good thing.  After the restore, Postgres may recycle those WAL files and they will be gone forever (I need to look more closely at how Postgres handles WAL segments from a prior timeline).  What if the restore was not successful?  Now there's no way to get back to that point in time.

I think the focus should be on how to get those WAL into the archive rather than working around the problem.  Even if you must work around, I still think copying the WAL to another location is the safest thing to do, rather than consuming the only copy of the WAL in place.

**Comment by LaetitiaLoxo** [comment]
> I think the focus should be on how to get those WAL into the archive rather than working around the problem.

I agree. Maybe that's the solution. Be sure to archive all unarchived segments before restoring. Can we do that ?

**Comment by dwsteele** [comment]
Yes - but it's going to be a bit tricky.  Since the cluster is down during a restore information about the current WAL position would need to come from pg_control.  PostgreSQL pre-creates WAL segments so just looking at the existing files could be very misleading.

Maybe it would be easier to scan the LSNs in the WAL files.  Recycled files will have LSNs in the past so that would be pretty easy to detect.

In theory we could archive everything and let PostgreSQL sort it out, but I'm afraid that PG might not understand when it starts getting WAL segments with old LSNs via `restore_command`.  Seems like it should work but would definitely require some research and testing.

**Comment by LaetitiaLoxo** [comment]
I wasn't sure current LSN was in pg_control file. So here's what I did:

- Show current LSN
- Make some transactions (created a table and added some rows)
- Show current LSN
- Crash the PostgreSQL server (stop --m immediate)
- Use pg_controldata to inspect pg_control file

I couldn't find current LSN in it. I'm pretty confident pg_controldata displays pg_control infos as the data provided match the pg_control.h structure...

So we can't find that piece of information in pg_control file.

I will perform some test to see how pg_xlogdump is handling recycled WALs...

**Comment by dwsteele** [comment]
You are correct about pg_control.  So, how does PG handle WAL with past LSNs?

This came up on `pgsql-hackers` recently and apparently it can cause problems, but they aren't unique to this situation and maybe not something we have to worry about for the moment.

I'm very tempted just to archive all WAL found on a restore.  This will only work well if the timeline is always switched after the restore but that seems like a reasonable requirement.

**Comment by LaetitiaLoxo** [comment]
I think this is the right path... Event if it's not as elegant as I would want a solution to be...

**Comment by dwsteele** [comment]
I've thought about this some more and I'm not too comfortable with this feature.  I think the user should either use `archive-push` to move WAL to the archive or just manually make a copy of the files.

The important part is that another copy of the files is made so Postgres does not do recovery on the only copy.  So, just ignoring the directory as originally proposed seems dangerous and automatically archiving WAL during a restore seems counter-intuitive.

I'm going to close this issue but if you come up with any new ideas feel free to comment.

**Comment by LaetitiaLoxo** [comment]
I'm okay with that solution. It's elegant without adding complexity.I  like it!
