### ISSUE TITLE
Support config includes

### ISSUE THREAD

**Issue by ChristophBerg** [pgbackrest/pgbackrest#365]
Hi,
it would be nice if I could drop config snippets into /etc/pgbackrest.d/ and have them included from the main config, e.g. via "include /etc/pgbackrest.d/*.conf".
That way I could add new clusters to be backed up without having to edit the main config file.
Thanks for considering!

**Comment by dwsteele** [comment]
We've been thinking about doing this for a while.  It became less urgent after we made the config file "flatter" in 1.0, but there's obviously a need.

We'll discuss and see where this falls in terms of priorities.

**Comment by dwsteele** [comment]
I have added this to the backlog.  We are currently moving the config functionality into C to provide a C-only path for time-critical operations.  I would rather add this when that work is complete for 2.0.

**Comment by disco-stu** [comment]
I would like to reopen this issue. 2.0 is now out.
Do you have any concrete plans for supporting config includes?

IMHO: Support of includes would simplify some use cases such as managing pgbackrest with config management systems like ansible, puppet, salt, etc. At the current state one has to "mess" around with that *one* config file. Includes would support a much cleaner way to deploy configs for new clusters.

**Comment by dwsteele** [comment]
Yes, agreed.  We are currently targeting this feature for 2.01 unless that turns out to be a bug release.

**Comment by disco-stu** [comment]
Great! Thanks!

**Comment by dwsteele** [comment]
Hi All,

OK, looks like there have been two requested implementations:

1) The one that Michael suggested originally: #75 
2) And this one.

It seems like 1 would be a little easier with CM tools (puppet, ansible, etc), but 2 is a bit more flexible.  I suppose we could just default `pgbackrest.conf` to `include /etc/pgbackrest.d/*.conf` if it is not present.  This does kind of break the ini format that we use, though.  Maybe something like:
```
[general]
config-include=/etc/pgbackrest.d
```
This could then be used at the command line as well.  What I'd like to do is:

1) check for pgbackrest.conf, if exists load it.
2) check for pgbackrest.d, if exists load all files and append

If `--config` is specified then ignore the default includes dir, if `--config-include` is specified ignore the default config.  If both are specified, use both, if neither then use the defaults for both.

Or -- we could overload `--config`.  If it's a file, load it.  If it's a directory then load all the files in the directory and cat them together before parsing.

Also, it's not clear how precedence would be handled.  I think the simplest thing would be to combine the files and treat them as if they had been a single file.  This is different from how Postgres does things, but we have a hierarchy to handle overrides intelligently,  i.e., options in the stanza section override options in the general section.

We also need to make sure this does not affect any existing config files.  We don't want any breakage.

Adding @sfrost because I'm sure he'll have some input.

Thoughts?

**Comment by ChristophBerg** [comment]
Please require all to-be-included files from a directory to have a certain extension like *.conf, or else backup files from vi/cms/whatever will really hurt.

**Comment by dwsteele** [comment]
Here is what we are planning to implement.

A new option `config-path` will be added with a default of `/etc/pgbackrest.d`.  The `config` option default will remain the same.

There are four ways the configs can be loaded:

- `config` and `config-path` are default.  In this case, the config file will be loaded, if it exists, and *.conf files in the config path will be appended, if they exist.
- `config` is specified.  Only the specified config file will be loaded.
- `config-path` is specified.  Only *.conf files in the config path will be loaded.
- `config` and `config-path` are specified.  Just like #1, except with the user-specified values.

Once the files are concatenated they will be passed to the ini parser just as if they were one big file.  Order doesn't matter in pgBackRest configs, but there is precedence based on sections.  The order is:

- `[<stanza>:<command>]`
- `[<stanza>]`
- `[global:<command>]`
- `[global]`

Note that it will not be possible to specify `config-path` inside the configuration file, at least in this first implementation.  Doing so would require multiple passes over the configuration, cycle detection, etc.  Config parsing is critical path for all commands and we want to keep it as fast as possible.

Any comments?

**Comment by cmwshang** [comment]
config-path makes me think it is the location of the config file itself. Maybe config-include-path? I know that's long - maybe config-incl-path? Someone else might have a suggestion - or we just document the heck out of it to clearly indicate it is the path to the config includes and not the main config...

**Comment by disco-stu** [comment]
Maybe "config-include-directory"? Naming the option *directory* should make thinks more clear.

If the files are concatenated based on there section they describe, what if a include file doesn't contain any section identifier? E.g. global.conf contains [global], stanza1.conf contains [stanza1], and foobar.conf doesn't contain a section at all? One possible solution could be to reject *.conf files that doesn't contain a section. However, that would require further validation of included files.

**Comment by dwsteele** [comment]
We use "path" everywhere else so I think `config-include-path` is more consistent.

Hmmm, you are correct about included files without a section.  I think we'll need to do (at least) some minimal testing on them to make sure they contain a section.

**Comment by dwsteele** [comment]
This has been committed at 27aa5f756e32e8e17135.

We adjusted the rules a bit and also added the `config-path` option to allow all current and future config files to be moved to a new location.  Have a look at the docs:

Reference: https://github.com/pgbackrest/pgbackrest/commit/27aa5f756e32e8e1713588695b86451fde2e5b02#diff-90308a99d5c36b74eb70165b2fa4f20fL758
User Guide: https://github.com/pgbackrest/pgbackrest/commit/27aa5f756e32e8e1713588695b86451fde2e5b02#diff-a62458990193106959efca32e11bc8efR431

We have also changed the default location of the base config file to `/etc/pgbackrest/pgbackrest.conf`.  The old location is checked by default as long as there is no file in the new location.  I'm not sure what we should do in the packages.  We certainly don't want to create a sample file in the new location if the user is just upgrading.

It should be a couple weeks until the next release, so if you have any comments then we'd like to hear them before that.
