### ISSUE TITLE
WAL extraction to specified directory

### ISSUE THREAD

**Issue by LaetitiaLoxo** [pgbackrest/pgbackrest#366]
Hi,

Here is a functionnality suggestion: to be able to extract archived WAL to a specified directory (not necessarily in PGDATA).

Why would someone extract WAL in another directory ? Simply if you want to PITR if a user did a horrible mistake in production (say as send a DELETE query without the WHERE clause) and need to "go back in time". You need to be able to use pg_xlogdump to find when you want to stop your PITR and you can't do that when your WAL are archived...

I had to use this code (not so hard, but could be handy to have a simple extract command in pgbackrest):

```
cp /var/lib/pgbackrest/archive/main/9.6-1/0000000100000001/* /tmp/WAL
cp /var/lib/pgbackrest/archive/main/9.6-1/0000000100000002/* /tmp/WAL
cp /var/lib/pgbackrest/archive/main/9.6-1/0000000100000003/* /tmp/WAL
cd /tmp/WAL
rm *.backup
gunzip *
rename 's/^(.{24}).*/$1/' *
```

Here are the options I suggest:
--backup <backupId>: All WAL taken since that backup
--dir <directory>: Were to extract WAL -> Must be empty

I can help write the code if you need...

Regards,

Lætitia

**Comment by dwsteele** [comment]
It seems like this functionality could be added to the `archive-get` command.  The `--set` option would be used instead of `--backup` (to conform with the `restore` command) and the path could be passed as a parameter, which would better match how `archive-get` works now.

I can definitely see the usefulness of this feature, though I can't prioritize it right now.  If you want to take a stab at it, feel free, but I would wait until after the 1.19 release as there are a lot of changes coming to how storage works.

**Comment by dwsteele** [comment]
It seems to me you could use the `db-path` option to achieve this goal.  You would still need to create the `pg_xlog` sub-directory but that seems like a minor issue.

What do you think?

**Comment by LaetitiaLoxo** [comment]
Yes, that should do it. I will try this as soon as I can.

**Comment by dwsteele** [comment]
I'm going to close this for now - let me know if you run into any problems with my suggestion.
