### ISSUE TITLE
Different Linux and PostgreSQL usernames

### ISSUE THREAD

**Issue by Stibila** [pgbackrest/pgbackrest#381]
Currently --db-user is used for ssh login and login to database. I'm running db where Linux username does not match PostgreSQL username an thus pgBackRest is unable to create stanza.
It would be useful to use --ssh-user (or something like that) alongside with --db-user as I don't fancy an idea of creating another PostgreSQL user just for backups.

**Comment by sfrost** [comment]
To perform a backup, the pgbackrest process must be able to access all of the files in the PG data directory.  PostgreSQL currently requires mode 700 on the PG data directory and therefore only the user who owns the database is able to perform a backup and therefore it's not really sensible to have those two be different values (if they were, the other Linux user wouldn't be able to actually perform the backup).

We are working with the PostgreSQL community to change PostgreSQL to, optionally, allow group read access to the PG data directory, so that the backup could be performed as a different user, but those changes won't be in PG until at least PostgreSQL 11 (scheduled to be released in September of 2018), at which point we'll update pgbackrest also to support this.

I hope that helps to clarify the situation.  I realize that you might have a different username for the user who owns the PG data directory from the actual user you have in PG, and we might consider adding support for that, but it's a pretty uncommon case and we'd have to think about how that might complicate the future capability we're trying to work towards where the backup is performed by a user who has only read-only access.

**Comment by dwsteele** [comment]
I added this to the backlog a while back (#171) but there never seemed to be enough need to implement it.  This option would require additional tests and has security implications that make it harder than it looks.

I agree with Stephen that this is an unusual use case and since there's a workaround I'm not eager to make this change without considering the implications for future features.
