### ISSUE TITLE
Resolving system-id not matching?

### ISSUE THREAD

**Issue by tdavis** [pgbackrest/pgbackrest#383]
I'm now getting an error `WAL segment system-id <number> does not match archive system-id <other number>`. I haven't changed the archive command or otherwise done anything interesting to the cluster lately. This started popping up in the middle of a alter table statement that I had running and now persists through postgres restarts.

**Comment by dwsteele** [comment]
This is usually caused by an incorrect stanza being specified.  If you haven't changed anything then it's a bit puzzling.  Maybe something happened on the repo side?

Could you check the id returned by `pg_controldata` against the data in `<repo-path>/archive/<stanza>/archive.info`?  It would be more helpful if you attached the output from both.

**Comment by tdavis** [comment]
pg_controldata differs from the one in the info file (the former matches `<number>` above)

**Comment by dwsteele** [comment]
Is there more than one db in the history section?

**Comment by tdavis** [comment]
Nope, just the single mismatched one.

**Comment by dwsteele** [comment]
I would look at the actual WAL segments in the repo and see if they match up with the WAL stream from your database.  The system ID is also recorded in the `backup.manifest` file in each backup directory and the `<repo-path>/backup/<stanza>/backup.info` file.
