### ISSUE TITLE
archive.info : backrest-version not update in 1.20

### ISSUE THREAD

**Issue by blogh** [pgbackrest/pgbackrest#385]
Hi,

I did some upgrades from pgbackrest from 1.06 to 1.20.

I notice that: 
- the "backrest-version" version of archive.info is not updated. 
- then "backrest-version" version of"backup.info" is updated.

I suppose it's because archive.info is not re-written that often.
I realize this is far from critical. I just wanted to throw it out there just in case it was not intended.

Benoit
NB: Thx for the awesome tool. process-max is so awesome now.

**Comment by dwsteele** [comment]
This is correct - the backrest version is only updated when the file is updated and `archive.info` is only updated on stanza-upgrade.  It's just informational, anyway.  The important number is `backrest-format` and that hasn't changed since 1.0.

If you were on 1.06 you should see performance improvements across the board, but the new multi-processing code introduced in 1.07 is definitely the most obvious one.  Glad you like it!
