### ISSUE TITLE
Add a export backup function.

### ISSUE THREAD

**Issue by blogh** [pgbackrest/pgbackrest#386]
Hi,

We use pgbackrest for our backups and are very happy with it. 
We have more and more cases of client asking to restore their production backups on another server or to pin a backup for later use (in dev server most of the time).

I realize the pinning part is complicated because of the question of the wals. (and that the idea I propose here doesn't solve the problem, It ignores it). Increasing the retention is not practical in most cases.

For the "restore on another server" part. The easy way would be to restore from the backup server but:
- we have our backup on the database server (they are periodically sent to networker). We don't want to add IO on the production databases (Once to export the backup is fine).
- all the production database server are isolated from the rest of the dev servers, so we cannot do a "remote restore".
- sometime the developer team is not working on our infrastructure. We have to send them the backup.

What I usually do is :  
- create a new stanza
- copy the backup and wals to it
- modify the backup.info to remove old backups and adjust the checksum. 
That way I have a standalone backup that I can restore / copy to another sever. 

I wonder if:
- the need I have is common.
- there are better ways to do it.
- it could be a future feature of pgabckrest (export to an empty stanza a standalone backup).

Thx
Benoit

NB: I saw this issue before #100. But it didn't come to fruition

**Comment by dwsteele** [comment]
Pinning is not as hard as it seems.  pgBackRest is able to preserve the WAL required to make a backup consistent while removing the WAL in between.  This is already done when `retention-archive` is different from the backup retention, though this is not a commonly used feature.

Exporting can be a bit complicated due to the backup dependencies and WAL.  The way you are doing it looks fine, though the format of backup.info could change in the future and mess up your code.  That big a change would entail a major version bump, though, so you'll know it if it happens.

What I do is create a full backup with `archive-copy=y` and then just copy the entire backup directory to where I need it.  This directory can be restored directly on a dev server and backrest does not even need to be installed since the backup directory is a consistent cluster (even tablespace links are rewritten).  You'll need to do a recursive gunzip if the backup is compressed.  I wouldn't recommend this for production usage but it works great for dev/staging environments.

A formal export command would certainly be nice, but is not currently high on the list of priorities.
