### ISSUE TITLE
support openstack swift

### ISSUE THREAD

**Issue by nisc-acooper** [pgbackrest/pgbackrest#409]
Has anyone been able to leverage pgbackrest with openstack swift as a storage backend?  I have been unsuccessful using the swift3 compatibility layer (S3 api on swift).  

If there is enough interest, perhaps there could be an effort to create a new native storage backend for swift in pgbackrest?

**Comment by dwsteele** [comment]
I wouldn't be surprised if this is the same issue as #402.  Is that the error you were getting?

**Comment by nisc-acooper** [comment]
I think in my case, pgbackrest is trying to prefix the dns host name with the bucket name and thus not resolving our endpoint.  I have attempted to define both s3_endpoint and s3_host, but nothing appears to work when debugging at trace logging level.  It could still be something unique to our environment, hence my curiosity if anyone else has had success with swift+swift3 middleware.  

I really like the feature set and usability of pgbackrest, but we may have to use wal-e or pghoard for our environtment due to swift support.

It appears that the S3 driver is homegrown? There does appear to be a few basic perl modules for swift namely:

http://search.cpan.org/~masakyst/Net-OpenStack-Swift-0.01/lib/Net/OpenStack/Swift.pm
https://metacpan.org/pod/Net::OpenStack::Swift

I am more familiar with python, but if I have spare time I could attempt a first pass at implementing a swift driver (no guarantees).

**Comment by dwsteele** [comment]
>  I have attempted to define both s3_endpoint and s3_host,

Hmmm.  Setting `repo-s3-host` should definitely override the default behavior of prefixing the bucketname on the endpoint (though I use this option primarily for testing).

I'd be very interested to see what error you are getting.

> It appears that the S3 driver is homegrown

Yes.  It wasn't my first choice but the available libs were pretty primitive (most did not support authv4 or multi-part upload) and they did not work in the stream model that pgBackRest uses.

> if I have spare time I could attempt a first pass at implementing a swift driver

You are welcome to take a crack at it.  Basically, what you would need to do it create a new driver that implements all the functionality in the S3 driver:

https://github.com/pgbackrest/pgbackrest/blob/master/lib/pgBackRest/Storage/S3/Driver.pm

Don't use the Posix driver as a model because it implements additional functionality that isn't required for a repo.

One final note - any Perl modules used must be available as packages on RHEL6/7 and Debian  7+/Ubuntu 12.04+.  We never require CPAN to be installed.

Happy coding!

**Comment by dwsteele** [comment]
This has been added to the backlog so closing it for now.  You might want to try again with 1.23 to see if it fixes your issue.  If not - please post the error message you are getting and I'll take a look.
