### ISSUE TITLE
Very long backup time on 1.25

### ISSUE THREAD

**Issue by M1hacka** [pgbackrest/pgbackrest#437]
On 1.24 backup from standby took 2 hours (1,4 Tb database). After upgrade to 1.25 it took more than 8 hours with 100% standby CPU usage, than I killed it with `pgbackerst stop --force`... `pgbackrest info` doesn't show this backup, so I guess it hasn't been complete.
It may be somehow connected to high compress level in config (I'm not quite sure, if compress level was the same when I've done previouse backup with pgbackerst):
```
compress-level=9
compress-level-network=9
```

**Comment by dwsteele** [comment]
Yes, this was one of the bugs fixed in `1.25` -- that the `compress-level` settings were being ignored since `1.19`.  So you were really compressing at level `6` all along and if you go back to that setting you will see the same performance.

Also, `compress-level-network` is only used if the destination files are uncompressed but need to be transferred to a remote backup host (`backup-host` option) -- it has no effect on final compression levels and is not used at all for S3 backups.
