### ISSUE TITLE
Feature request: S3 / local support

### ISSUE THREAD

**Issue by Tostino** [pgbackrest/pgbackrest#443]
Hey all, finally taking a look at pgbackrest and love what I see so far.

One thing I was wondering about, was is there any planned support for S3 integration where everything is sent to S3, but you also keep a local cache of backups to enable faster recovery in the event one is required.

Pretty much a system where you can set the S3 / local retention policies separately, and restore command would look for a local copy of any backup prior to checking if it exists on S3.

Something like that would be extremely useful to me,  as I am required to keep 6 months of PITR backups, but do not have that kind of storage locally to support that.  The current S3 support is nice, I just wish I could keep local copies for faster (and cheaper...) restores.

**Comment by dwsteele** [comment]
Yes, we are planning to implement this feature but I can't tell you when it's coming.

It's possible to do this now using multiple config files (and two archive commands &&ed together) but there are some caveats so I don't recommend it.  The biggest caveat is that this method will not work with async archiving since there is only one async queue.
