### ISSUE TITLE
single db temporary restore 

### ISSUE THREAD

**Issue by edib** [pgbackrest/pgbackrest#464]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 1.19

2. PostgreSQL version: 9.6

3. Operating system/version - if you have more than one server (for example, a database server, a backup host server, one or more standbys), please specify each: 
dbserver: centos 7, backup server debian 8
4. Did you install pgBackRest from source or from a package?
no

7. Describe the issue:
I want to restore a single db in a cluster to a specified directory in the backup server. I mean I don't want to affect anything in the production. Is it safe to run?

here is my pgbackrest command:
`pgbackrest --stanza=mystanza --type time "--target=2017-12-24 12:00:00" --set=20171223-043633F_20171223-022304I --db-include=mydb --db-path=/data/restore20171225/data --link-all=y --tablespace-map-all=/data/restore20171225/tbs --log-level-console=info restore`

**Comment by dwsteele** [comment]
Yes, this is safe to run.  pgBackRest will not overwrite a running cluster and will not write to a non-empty directory unless `--delta` is specified.

However, if you are restoring on a backup server you may need to use a different config file with `--config=...` or use `--no-config` and specify everything on the command line.  The reason is that pgBackRest will error if you are trying to restore on a server that is not the database server if it can see that a database server is configured.

BTW - 1.19 is pretty old.  You'll definitely want to upgrade to 1.27.
