### ISSUE TITLE
Monitoring pgbackrest 

### ISSUE THREAD

**Issue by edib** [pgbackrest/pgbackrest#470]
I am trying to find a way to check pgbackrest is synced with postgres server. I think that first check pg_stat_archiver and get last_archived_wal value, then check if last_failed_wal and  last_archived_wal is not equal then compare it with pgbackrest info command's "wal archive max" value. 
Is it the correct way?

**Comment by dwsteele** [comment]
It think in most cases looking at `last_archived_time` and making sure that `last_archived_wal` is close to what the pgBackRest `info` command reports will work.  If you are using parallel archiving then WAL may be arriving a little out of order so you need to keep that in mind when making the comparison.

I also recommend using `archive_timeout` so that WAL gets archived during times when the database is not busy.

**Comment by edib** [comment]
I just wrote a simple script that checks time and wal diff.  
[backrest_check script](https://gist.github.com/edib/4819d7b68068c828965967187f760613)

**Comment by dwsteele** [comment]
Nice!  Yes, that's what I had in mind.
