### ISSUE TITLE
question: How to correctly update the pgbackrest 2.01 to version 2.02?

### ISSUE THREAD

**Issue by vitabaks** [pgbackrest/pgbackrest#527]
Hello!

question: 
How to correctly update the pgbackrest 2.01 to version 2.02?

pgbackrest is used in the archive_ command on the working database.

Thanks!

**Comment by dwsteele** [comment]
The safest way is to set `archive_command = false`, reload Postgres, and make sure no `pgbackrest` processes are running on any host.  Then update the packages on all hosts and finally re-enable archiving.

This is especially true if you are not installing from packages since it might take a while to complete the update.
