### ISSUE TITLE
[question] Export backup

### ISSUE THREAD

**Issue by Raphyyy** [pgbackrest/pgbackrest#550]
Hello and thanks for your amazing work

I want to ensure sustainability of my datas by backing up my pgBackRest repository.

I would like to know if I compress and export only the latest full backup, is this could be enough to permit a new pgBackRest instance to run from it and deploy a new db-host ?

If so, assuming all my db host are down, here is the process I had in mind to migrate pgBackRest on a new repository and deploy a new primary db : 
- Prepare pgbackrest on the new repository.
- Create the new stanza keeping the same name. 
- Decompress the `/{pgbackrestfolder}/{stanzafolder}/{latest-full-backup}` and `/{pgbackrestfolder}/{stanzafolder}/backup.info` from the old pgbackrest server in the new instance.
- Prepare pgbackrest on a new pg-primary host and configure archive_command
- Perform a restore.

Could you indicate me if I don't miss anything ?

**Comment by Raphyyy** [comment]
Thanks :)

When you said "The backup will not be consistent without WAL" but is this not the purpose of a full backup to restore from it and not from WAL ? 

Is there any other way to do this without backing up the whole repo ? I have backup-retention set to 3, and the whole repo take 50Go (14Go archive and 36Go backup) so this is slightly too much to backup.

**Comment by dwsteele** [comment]
Postgres *always* requires some WAL to do recovery.  This is not something that pgBackRest can control.

It's definitely possible to do what you want -- but there's no automated way to do it and it's complicated enough that I hesitate to describe it because without testing I might get it wrong.  You certainly don't want to discover this when doing an emergency restore.

Have you considered using S3?  Storage there is very cheap.

**Comment by Raphyyy** [comment]
I'll give a look on Amazon S3.
Thanks for details !
