### ISSUE TITLE
full backup timesout due to wal file not found

### ISSUE THREAD

**Issue by brunre01** [pgbackrest/pgbackrest#551]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.03

2. PostgreSQL version: 9.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHAT 7.2

4. Did you install pgBackRest from source or from a package?  package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
[postgresql-Mon.zip](https://github.com/pgbackrest/pgbackrest/files/2133459/postgresql-Mon.zip)

7. Describe the issue:

How do I tell pgbackrest to ignore backing up wal files prior to pgbackrest being installed and stanza created? pgbackrest timesout out as it tries to archive a wal file that doesnt exist anymore.

**Comment by dwsteele** [comment]
This is an unusual error -- Postgres is trying to archive a file that does not exist which could be due to some corruption in the archive_status directory.

I would set `archive_command = /bin/true` for a while and let this clear out.  Then set it back to the pgbackrest command and run `check` to ensure your archiving is working.  There's no point in running a backup until `check` succeeds.

**Comment by brunre01** [comment]
thank you . that seemed to have worked. i was able to run a backup successfully after setting archive_command to /bin/true. I waited 2 hours before setting it back to the pgbackrest command.
