### ISSUE TITLE
Update the user guide

### ISSUE THREAD

**Issue by sebastianwebber** [pgbackrest/pgbackrest#572]
Hi guys, how are you?

Looking the user guide in the website[1] I find that it uses the old 9.4 version.

I already fork the pgbackrest project and start to update the user guide to pg 10 but I'm new to Perl and I need help to build the docs.

There is some doc to help with this? I already tried to install Perl on my machine, but after running the `doc/doc.pl`, throws an error:

```
➜  doc git:(master) ./doc.pl
Can't locate XML/Checker/Parser.pm in @INC (you may need to install the XML::Checker::Parser module) (@INC contains: ./test/lib ./build/lib ./lib /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at lib/BackRestDoc/Common/Doc.pm line 13.
BEGIN failed--compilation aborted at lib/BackRestDoc/Common/Doc.pm line 13.
Compilation failed in require at ./doc.pl line 27.
BEGIN failed--compilation aborted at ./doc.pl line 27.
```
Can you guys help me to set up my machine to make this pull request?

Regards,

[1] https://pgbackrest.org/user-guide.html

**Comment by dwsteele** [comment]
Hi Sebastion,

The easiest way to build out test/doc environment is by using the Vagrantfile or by building an environment that looks like it: https://github.com/pgbackrest/pgbackrest/blob/master/test/Vagrantfile.  Unfortunately there's not much in the way of docs for building the docs (ironically) since we are the only ones who generally do it.

We are planning to build multiple versions of the documentation about the same time v11 is released since we have v11 specific instructions instructions.  Right now the docs build for two versions (9.4/Debian & 9.5/RHEL6) and I'll need to add some new features to the doc engine to get more versions working.

In practice v10 does not look very different from v9.6 but you are welcome to give it a go.

**Comment by dwsteele** [comment]
Closing for now -- let us know if you get it working.
