### ISSUE TITLE
compatability issue with stolon cluster

### ISSUE THREAD

**Issue by frelist** [pgbackrest/pgbackrest#575]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.04

2. PostgreSQL version: 9.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: redhat 7

4. Did you install pgBackRest from source or from a package? package pgbackrest-2.04-1.rhel7.x86_64.rpm

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

stolon cluster (https://github.com/sorintlab/stolon) links postgresql.auto.conf to /dev/null in order to disable changing postgresql parameter using alter system.

lrwxrwxrwx. 1 postgres postgres 9 Aug 13 00:33 postgresql.auto.conf -> /dev/null

When we try to backup the DB using pgBackRest, error 028 happened.  No problem when we backup other postgresql db using pgBackRest.

ERROR [028]: : /dev/dm-17 is not of type directory, file, or link

Look like pgBackRest tries to discover the directory of symoblic link.

Kindly advise whether the symbolic link is the root cause?  And is pgBackRest compatible with Stolon cluster?

**Comment by dwsteele** [comment]
pgBackRest scans any directory that's linked even when it's only a single file.  Usually that's what we want and it doesn't hurt much to scan and filter.  We're planning to change this because it's also a problem for shared tablespace directories that PG does not have access to, but that's a rare situation and easily fixable so we have not gotten to it yet.

pgBackRest is just flatly going to refuse to copy a device file, however.  The only thing we can think of is to offer a `--exclude` option so files like this can be excluded from the backup.  That means on restore that you (or Stolon) would be responsible for recreating this link.

Thoughts?

**Comment by frelist** [comment]
Thanks for the quick response.

I think your idea should work.  Stolon creates postgresql.auto.conf as a symbolic link when starting the DB.

**Comment by dwsteele** [comment]
Committed the `--exclude` feature at bef58a79743d3273d14de.  This will be in the next release.
