### ISSUE TITLE
Getting ASSERT: [025]: assertion 'this->type == varTypeString' failed when trying to do backup

### ISSUE THREAD

**Issue by Underhunden** [pgbackrest/pgbackrest#599]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.05

2. PostgreSQL version:
10.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS 7 fully patched

4. Did you install pgBackRest from source or from a package?
Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

----- pgbackrest.conf ------
[server]
pg1-path=/var/lib/pgsql/10/data

[global]
archive-async=y
archive-copy=n
spool-path=/db/logs/spool
start-fast=y
process-max=12
repo1-cipher-type=none
repo1-path=/backup
repo1-retention-diff=2
repo1-retention-full=2
repo1-s3-bucket=*********
repo1-s3-endpoint=s3.amazonaws.com
repo1-s3-region=************
repo1-s3-ca-file=/etc/pki/tls/certs/ca-bundle.crt
repo1-type=s3
start-fast=y
stop-auto=y

[global:archive-push]
compress-level=3

Note: I keep AWS secrets in a conf.d file.

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

archive_mode = on
archive_command = 'pgbackrest --stanza=bix archive-push %p'

    - errors in the postgresql log file before or during the time you experienced the issue
None

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
None

7. Describe the issue:
archive-push works perfectly, create-stanza also works but running the backup does not.

I get the following error:

-bash-4.2$ pgbackrest --stanza=server --log-level-console=info backup
ASSERT: [025]: assertion 'this->type == varTypeString' failed
        STACK TRACE:
        common/type/variant:varStr:806:(test build required for parameters)
            ... function(s) ommitted ...
        config/parse:configParse:(trace log level required for parameters)
        config/load:cfgLoad:(debug log level required for parameters)
        main:main:(debug log level required for parameters)

**Comment by dwsteele** [comment]
Can you provide your conf.d file with the secrets masked out so we can see if there is anything odd there?

**Comment by dwsteele** [comment]
Nevermind, I have reproduced it.

**Comment by Underhunden** [comment]
Of course.

/etc/pgbackrest/conf.d/s3.conf:
[global]
repo1-s3-key=******
repo1-s3-key-secret=*******

**Comment by dwsteele** [comment]
OK, I see it.  You have `start-fast=y` specified twice which makes the parser think it is an option that takes multiple values (like `recovery-option`).  It only blows up on backup because only backup uses that option.

We'll add a check to give a comprehensible error in this case, but meanwhile you should be good to go if you remove one of them.

**Comment by Underhunden** [comment]
Thanks for looking into this, could the same issue pop up for other options, and if so, how will several config files handle this? If they are included.

**Comment by dwsteele** [comment]
The issue is limited to boolean options, and yes, it will happen if you have the same boolean option in the same section in mutiple files.  There is no ordering or hierarchy in the config files -- they are combined and read as if they were a single file.

The only thing the fix does is give a clear error message.  It does not allow options to be duplicated.

**Comment by dwsteele** [comment]
Fixed at 5404628148a303:

Fix incorrect error message for duplicate options in configuration files.

Duplicating a non-multi-value option was not throwing the correct message when the option was a boolean.

The reason was that the option was being validated as a boolean before the multi-value check was being done. The validation code assumed it was operating on a string but was instead operating on a string list causing an assertion to fail.

Since it's not safe to do the multi-value check so late, move it up to the command-line and configuration file parse phases instead.
