### ISSUE TITLE
retention policy

### ISSUE THREAD

**Issue by Tiago-Anastacio** [pgbackrest/pgbackrest#643]
1. pgBackRest version:
2.0.7
2. PostgreSQL version:
9.5
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
rhel7
4. Did you install pgBackRest from source or from a package?
PostgreSQL community

Hello,

My main concern is the retention based on date. In production most of companies do a full backup on week-end and an incremental one during the week, we do.

I could have to launch a manual full backup for emergency reasons in production, and forgot about retention, so I could be short on retention without...

I tried to use pgbackrest info to compute something based on date and use pgbackrest expire but it is not that easy.

Thank you

**Comment by cmwshang** [comment]
To be clear, are you saying that if you have to perform a manual full backup outside of your automated scheduled backups, you do not want to expire according to the retention schedule you have set? Hopefully you have enough space in your repository and if you do, why not just use the"reset" prefix?  For example, if your pgbackrest.conf is configured with --repo1-retention-full=2 but you want pgbackrest to ignore that and not expire any full backups when you are running a manual "emergency" backup then why not just use:

pgbackrest --stanza=YOURSTANZA --type=full --reset-repo1-retention-full

If you have 2 full backups before you run this command, then you will have 3 afterwards since pgbackrest will not expire any full backups. See the explanation of "reset" in https://pgbackrest.org/command.html#introduction

**Comment by jacks33** [comment]
Thanks for the --reset hint

Yes it is my use case.

Anybody that raise a backup --type=full (and forgot --reset options as well) may lose oldest backup.

In a small company it may not happen, in a big company, despite all security procedures, it will. 
(just like disasters you just don't know when).


Date retention could be a soft limit combined with --repo1-retention--full parameter
This way it would be easy to implement.

Here is an example:

Options:
--repo1-retention-full=2
--repo1-retention-date-range=2 weeks

You do backup: pgbackrest backup --type=full

In the end of the backup pgbackrest checks retention so:
=> if (current_date - oldest backup date ) > --repo1-retention-date-range *AND* (number of full backups > --repo1-retention-full)
   then 
       check if after removing oldest backup we still have (current_date - oldest backup date ) > --repo1-retention-date-range
	   if yes 
	     remove oldest backup 
	   if no do nothing
   else 
      do nothing
   end

Note: --date-range is a soft limit because it could exceed range specified if we do not have enough full backups.
