### ISSUE TITLE
Convert diff to full?

### ISSUE THREAD

**Issue by ioguix** [pgbackrest/pgbackrest#644]
pgBackRest version: 2.07

Is it possible ton convert differential backup to full backup?

Main objective would be to create only one full backup, then using differential backup on a daily basis. No more full backup. That would avoid transferring data files that have no changes since last full backup (exactly what diff does in fact...).

During expiration, oldest diff backup is converted to full backup and the oldest full backup is deleted.

It would be similar than something like that:

~~~bash
cp -rl previous_backup current_backup
rsync -ac --delete prod:$PGDATA current_backup
rm -r previous
~~~

Any thoughts? advices?

**Comment by dwsteele** [comment]
Directly coverting a diff to a full is not a good idea.  If any files get corrupted in the backup then they may get propagated indefinitely and never corrected.

We have been considering a feature that will convert a diff to full but also checksum some or all of the files on the database server to ensure that here has been no corruption in the archive.  If only some files are checksummed then this would be done on a rolling basis so that every n weeks all the files will have been checked.

Currently we do not have a schedule for implementing this feature.

**Comment by ioguix** [comment]
> Directly coverting a diff to a full is not a good idea. If any files get corrupted in the backup then they may get propagated indefinitely and never corrected.

Yes, indeed.

> We have been considering a feature that will convert a diff to full but also checksum some or all of the files on the database server to ensure that here has been no corruption in the archive. If only some files are checksummed then this would be done on a rolling basis so that every n weeks all the files will have been checked.

If I understand correctly, you are speaking about recomputing the checksum server side for sanity checking some files with the manifest, even if the file has no changes? I suppose it's kind of a "partial" `backup --delta` which is recomputing the checksum for all the files?

Thanks!

**Comment by dwsteele** [comment]
> I suppose it's kind of a "partial" backup --delta which is recomputing the checksum for all the files?

Yes, that's the idea.

**Comment by ioguix** [comment]
So, isn't it possible in a first step to allow conversion from diff to full iif the backup has been done using `--delta`?

**Comment by dwsteele** [comment]
Hmmm, yeah, something like that should be possible.  It would still require copying the files since not all filesystems allow atomic renames of a directory -- S3, for instance.

I'm not sure what that command would look like, though.  Would it be a full backup with a special option or a completely new command?

**Comment by dwsteele** [comment]
That will only work for Posix file systems so I'm not in favor of it.

**Comment by ioguix** [comment]
I suppose `--repo-hardlink` already work only for posix filesystem, isn't it ? Couldn't it be applied to full backup only for posix FS?

**Comment by dwsteele** [comment]
It's a pretty bad idea to link a full backup to a previous backup set since corruption in that set will affect the next set.

The link mechanism is only for the convenience of the user (to make all backups in a set appear to be full) and is in no way used by pgBackRest.  Changing the storage semantics for one repo type makes the code more complex and harder to test so we are not likely to go in that direction.

Also, a Posix-only solution is not ideal since many are moving to object stores for their backups.

However this feature gets implemented, I think the full backup will need to be a copy.

**Comment by ioguix** [comment]
OK,

So if I try to sum up:
* converting a diff to full is ok using copy: need to define the command though
* linking is not OK because of FS limitation

Someone actually told me this is called "synthetic diff backup". I could find at least two backup tools supporting this: veeam and bacula.

What about such a command:

~~~
pgbackrest diff-to-full 20190102-064453F 20190102-064453F_20190102-064509D
~~~

**Comment by dwsteele** [comment]
Your summary seems about right to me.

I'm not in favor of your syntax, however, since it puts a major burden on the caller to figure out which backups to use.

I'd prefer something like:

`pgbackrest --stanza=<stanza> --type=full --copy-last backup`

Or something of the sort.  There's nothing special about a diff in the respect: the full can be copied from any type of backup as long as measures are taken to ensure that is is not corrupted, i.e. checksums.

**Comment by ioguix** [comment]
Well, we might have different understanding here. I realize there's in fact two ways to implement my original question: 
> During expiration, oldest diff backup is converted to full backup and the oldest full backup is deleted

Looking at your command, I understand it would copy the last full backup, then overwrite it with a diff backup.

In my last message, my proposal is purely on the backup server side, to convert an existing diff to a full backup. No connexions to the db server is involved. But I agree the syntax is not user friendly.

I'll try to think about some other syntax/parameters and get back to you soon.

**Comment by ioguix** [comment]
> Blindly copying a prior backup to a new full is dangerous and isn't something we would consider doing -- ever.

So merging an old full with one of its diff is dangerous? It seems to me this is almost the same action than restoring the backup based on the diff. When you restore a backup from a diff, you merge the previous full backup with the diff, isn't it?

But I suppose this is not your point, as you wrote previously, corruption in backup is your main issue I suppose:

> Directly coverting a diff to a full is not a good idea. If any files get corrupted in the backup then they may get propagated indefinitely and never corrected.

I am being paranoid most of the time with most subjects, backups included. But, we have a manifest with a hash for each backed up file and we can even check blocks checksums. I consider manifest + files hash + checksum is already enough to make sure the backup is clean. So in my opinion, this is not a "blind" copy. We can check each files after the synthetic full is created and before the old full is purged to avoid propagating corruption. As this is 100% done on the backup server side, there's no impact on PgSQL production.

<mode paranoid>The danger is more related to some bug or failure not being caught during the backup process: if a modified file is not backed up during a diff backup, this could definitely lead to a bad SF backup when merging the incomplete diff backup with its related full backup</mode>. But in fact, this danger already exist when you restore a diff backup. We must trust the diff backup algorithm.

Considering `F`: full, `D`: Diff, `SF`: synthetic full.
~~~
step 0: 0F -------> 0F-1D ----> 0F-2D -----> 0F-3D      1F--> ...
step 1: 0F -------> 0SF -------> 0SF-2D ---> 0SF-3D    1F-->...
step 2: 0SF -----> 0SF-2D --> 0SF-3D                        1F-->...
~~~

 `0SF` is a merge between `0F` and `0F-1D` (kind of a backup restore from `0F-1D` as I explained it earlier). All posterior diff backups are then rebranched on `0SF`. Then, we can purge the oldest Full backup `0F`. `1F` is just the next Full backup.

**Comment by achix** [comment]
Hello, I really enjoy your convo so far!
David thank you for considering this!

So when the --copy-last backup gets implemented we will have the equivalent : "reuse_backup=copy" functionality, by using pgbarman terminology. We will have time reduction, but still full space on disk. 

One question is what the behavior of --copy-last would be if called after a diff backup? Will this last diff backup be used first to construct a full backup and then get a new diff from there eventually converted to full, or would pgbackrest use the last full? I am a fan of the former. It would be great to have a certain degree of flexibility as far as space management is concerned. Then we could have e.g. one **--type=full --copy-last** e.g. every Sunday followed by pure type=diff every day. And while we are it, another thought would be to also be able to construct a full backup from a previous --type=incr so that space reduction would be even greater. 

Thanks!

**Comment by achix** [comment]
That is correct. I have tested it already :
https://github.com/postgrespro/pg_probackup/issues/43
The intention was just that:
Currently trying to test the remote_ssh branch.

**Comment by dwsteele** [comment]
We've decided that it only makes sense to implement something like this when we migrate the backup command to C, which will happen sometime this summer.

This feature is definitely on the radar, the question being the best way to implement it. Add to the feature board at https://github.com/pgbackrest/pgbackrest/projects/2#card-17933730.
