### ISSUE TITLE
does deleting incremental/differential backups  make the backup system invalid? 

### ISSUE THREAD

**Issue by edib** [pgbackrest/pgbackrest#653]
I have a full backup and some incremental backups depending on it. If I delete the incremental backups beginning of last one, is PITR backup or simple backup still valid?
ie. t0(f),t01(i),t02(i),t03(i),now if I delete t03(i), can I still get the point the point between t03(i) and now?

**Comment by dwsteele** [comment]
`pgBackRest` won't allow you to delete a backup that would make a remaining backup invalid.

However, if you manually delete backups then all bets are off.  The case you propose seems like it work would, but it would have to be done manually and we don't test it.  So, we don't recommend it.

If a backup had been made in invalid through some manual user intervention then you would certainly find out on restore since every file must be accounted for and checksummed.
