### ISSUE TITLE
Handling of "No space left on device" in archive-push

### ISSUE THREAD

**Issue by blogh** [pgbackrest/pgbackrest#672]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.10

2. PostgreSQL version: 11

3. Operating system/version : CentOS Linux release 7.6.1810 (Core) 

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable: 

[postgresql_config.log](https://github.com/pgbackrest/pgbackrest/files/2851714/postgresql_config.log)
[pgbackrest_config.log](https://github.com/pgbackrest/pgbackrest/files/2851715/pgbackrest_config.log)
[pgbackrest_reproducer.log](https://github.com/pgbackrest/pgbackrest/files/2851712/pgbackrest_reproducer.log)
[pgbackrest_warning_file_exists.log](https://github.com/pgbackrest/pgbackrest/files/2851713/pgbackrest_warning_file_exists.log) [A]
[pgbackrest_error_no_space_left.log](https://github.com/pgbackrest/pgbackrest/files/2851716/pgbackrest_error_no_space_left.log)  [B]

7. Describe the issue:

During an ArchivePush, when the FS pgbackrest is writing to is full, the first write returns :

> "No space left on device" [A]. 

The following archive push (same file) finds a archive with the correct checksum, pgbackrest exits with a warning : 

> "WAL segment XXXX already exists in the archive with the same checksum" [B]. 

Postgres thinks everything is fine and recycles or deletes the wals.

Quick exemple (trace level in the logs): 

```
-bash-4.2$ pgbackrest --stanza=main archive-push /var/lib/pgsql/11/data/pg_wal/000000010000000000000035
ERROR [064]: : unable to write to '/var/lib/pgsql/pgbackrest/archive/main/11-1/0000000100000000/000000010000000000000035-9bdb141404ca01bc083e20093a235082b40276ab.gz': No space left on device

-bash-4.2$ pgbackrest --stanza=main archive-push /var/lib/pgsql/11/data/pg_wal/000000010000000000000035
WARN: WAL segment 000000010000000000000035 already exists in the archive with the same checksum
HINT: this is valid in some recovery scenarios but may also indicate a problem.
```

My perl knowledge is limited, so I could be completely wrong.
If think it's because Base.pm:copy() does the copy and then calls FileWrite.close() with "bAtomic = True" which performs a move in that case. During the following call to archive-push, the file exists and a warning is issued.

The error seems to be caught in Hande.pm:write() but I dont think it's checked in Base.pm:copy(). I don't think the move should be performed in that case. I am not sure how to archive this yet.

**Comment by sfrost** [comment]
This looks to be a real issue based on your example, at least, though I haven't tested it myself.

To fix this, it seems like if there's an error during the writing of the file then under bAtomic, we shouldn't rename the file but instead maybe we should unlink the temp file..?  I'm a bit on the fence about that as the file might have some useful data in it, but if we unlink it then that's gone, then again, we'll return an error to PG and so PG should continue to hold on to the file so maybe that's ok.  Also, if we keep the temp file and PG calls archive command again, will we end up with another temp file?  That seems like it wouldn't be ideal since that would mean we keep having more and more, likely empty, files stored in the archive with different temp names.

In any case, I agree that this is something we'll want to fix, hopefully in time for the next release in a month or so.  I don't think this is urgent enough to call for something to happen sooner than that.

**Comment by dwsteele** [comment]
I think close() is somehow being called by an object destructor, though I'm not seeing an obvious candidate.  The error is definitely raised because the process is exiting with 64.

If this were running to the end of copy() we would see a close() of the source file in the log as well.  Move() should definitely not be called if the copy fails.  Leaving the tmp file in place is OK because it will be overwritten on retry (then moved).

**Comment by blogh** [comment]
Thanks for confirming !

Is there a better way to fix this than adding a "isDirty" flag in write() and check it during the close() ? Would it  impact the test suite ?

Should we unset "bAtomic" (it feels weird to me) ?

**Comment by dwsteele** [comment]
I think the best thing to do is to recode the destructors to only close open resources and not finalize the file.  Here's a patch that does that: d211c2b8b51ae5.

If you can reproduce your test case that would be great.  It's hard to make something fail in the middle of a write consistently so I have cheated somewhat in the unit tests.  Basically, if destroy/free is called before close() then that is an abort.

**Comment by blogh** [comment]
Hi thanks for the patch. I will try it today or tomorrow and get back to you.

**Comment by blogh** [comment]
Just tried it out wth the same test case as before:

current pgbackrest:

```
-bash-4.2$ pgbackrest --stanza=main archive-push /var/lib/pgsql/11/data/pg_wal/000000010000000000000047
ERROR [064]: : unable to write to '/var/lib/pgsql/pgbackrest/archive/main/11-1/0000000100000000/000000010000000000000047-c250583aff3b8282531571c642acfe87d106f85c.gz': No space left on device

-bash-4.2$ pgbackrest --stanza=main archive-push /var/lib/pgsql/11/data/pg_wal/000000010000000000000047
WARN: WAL segment 000000010000000000000047 already exists in the archive with the same checksum
HINT: this is valid in some recovery scenarios but may also indicate a problem.
```

patched pgbackrest:

```
-bash-4.2$ ppgbackrest --stanza=main archive-push /var/lib/pgsql/11/data/pg_wal/000000010000000000000048
ERROR [064]: : unable to write to '/var/lib/pgsql/pgbackrest/archive/main/11-1/0000000100000000/000000010000000000000048-96ac448dda3a217f810bcd884463aea91b8f30fd.gz': No space left on device

-bash-4.2$ ppgbackrest --stanza=main archive-push /var/lib/pgsql/11/data/pg_wal/000000010000000000000048
ERROR [064]: : unable to write to '/var/lib/pgsql/pgbackrest/archive/main/11-1/0000000100000000/000000010000000000000048-96ac448dda3a217f810bcd884463aea91b8f30fd.gz': No space left on device
```

**Comment by dwsteele** [comment]
OK, good.  We haven't decided whether or not to do a release for this.  How much pain is this causing you?

**Comment by blogh** [comment]
It's fine, we can wait.

**Comment by dwsteele** [comment]
Thanks for reporting this issue and following up with testing.  It's especially helpful since this impacted the C code as well.
