### ISSUE TITLE
Trouble when rotating keys

### ISSUE THREAD

**Issue by rdunklau** [pgbackrest/pgbackrest#680]
Hello,

We've noticed some behaviors that make it dangerous to try to rotate keys.

First, it would be much easier if we could configure several cipher pass options, with the first one used for ciphering backups, and if it doesn't work for deciphering move on to the next one. That way, we could smoothly rotate the backup key.

The second issue is quite dangerous I think: we tried setting up the repo in another path, with a new encryption key, and started archiving there. When taking our first backup in this new repo, we noticed that with our backup retention policy every WAL prior to the first backup was purged. This creates a hole in the WAL sequence between the two repos, which is actually a data loss. Fortunately, we were able to recover the WAL manually from pg_wal to prevent irreparable damage. By the way, can we reupload those salvaged WAL somehow ? Either manually or with pgbackrest, and will pgbackrest delete them again ? 

I would qualify this as a bug, and pgbackrest shouldn't try to purge WALs when it hasn't purged any backups.

This is slightly off topic, but maybe we should try to define a retention policy based on age instead of number of backups: aside from the aforementioned issue, changing a backup policy (for example,  switching from one backup per week to one per day, or taking a supplemental manual backup) makes it very hard to make sure the retention policy applied by pgbackrest matches what we want.

As for now, we have deactivated any backup-retention option to prevent something similar from occuring.

**Comment by dwsteele** [comment]
> First, it would be much easier if we could configure several cipher pass options, with the first one used for ciphering backups, and if it doesn't work for deciphering move on to the next one. That way, we could smoothly rotate the backup key.

This isn't really the way it works.  `cipher-pass` is only used to encrypt `backup.info` and `archive-info`.  `backup.info` contains a subkey that encrypts `backup.manifest` and each backup set has its own subkey.  WAL segments are encrypted with the subkey contained in `archive-info` -- since each WAL segment is unique this is deemed to be fairly safe.  Also each encrypted file is salted so identical files will generate different ciphertext even with the same key.

Of course, database files have a lot of structure which does increase the attack surface, but not by a lot since we never use the same key + salt on an identical file.

If you want to rotate the master key (cipher-pass) in case it gets lost then that's doable by just re-encrypting `archive.info` and `backup.info` with a new key.  You can do this with the openssl command-line tool since our encrypted files are compliant with that format.

For example, to decrypt archive.info (backup.info is the same):
```
openssl enc -d -k YOURKEY -md sha1 -aes-256-cbc -in archive.info
```

> The second issue is quite dangerous I think: we tried setting up the repo in another path, with a new encryption key, and started archiving there.

I don't see this as a bug.  WAL retention is based on the oldest backup -- if the "oldest" backup is in another repo that pgbackrest has no knowledge of then how would we ever know to expire?  In that case WAL would be retained forever.

> This is slightly off topic, but maybe we should try to define a retention policy based on age...

This is a oft-requested feature that is very high up on our road map.

> As for now, we have deactivated any backup-retention option to prevent something similar from occuring.

If you are going to manually manage a single cluster across multiple repos then this is your best option.  Retention can be enabled when the old repo is no longer in use.

**Comment by rdunklau** [comment]
Thank you very much for this explanation, that's a clever design. I'll try to come up with a patch to the doc for that if you're interested. 

> If the "oldest" backup is in another repo that pgbackrest has no knowledge of then how would we ever know to expire?

That's also a problem when migrating from another backup tool, and should at least be documented too. I still think it's a bug: pgbackrest should not delete WALs not associated to a backup it deleted itself, and warn about it, or provide a flag to force clean those things.

**Comment by dwsteele** [comment]
> Thank you very much for this explanation, that's a clever design.

Thanks!  We got help on this design from encryption experts.

> I'll try to come up with a patch to the doc for that if you're interested.

Yes, please.  More explanation is better when it comes to this sort of thing.

> That's also a problem when migrating from another backup tool.

In that case we recommend archiving to both tools:
```
archive_command = command1 && command2
```
> pgbackrest should not delete WALs not associated to a backup it deleted

But again that means the WAL would hang around forever until there was user intervention.  I'm just not convinced that this is a big enough deal to add options for.  It's the first time this has ever come up.

We do have an info message for this situation:
```
                        &log(INFO, "full backup total < ${iArchiveRetention} - using oldest full backup for ${strArchiveId} " .
                            "archive retention");
```
Not sure I want to make that WARN since it is the normal case for any new installation.

**Comment by dwsteele** [comment]
If you patch the docs please submit that as a PR.  Thanks!
