### ISSUE TITLE
Feature Request: Backwash to lower environments

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#681]
I created an issue, https://github.com/pgbackrest/pgbackrest/issues/304, about 2 years ago that showed how you could "fool" pgbackrest into doing backwashes to lower environments.  At the time, my issue was closed since it was regarded as a "forum" type question.  But pgbackrest is the only real backup solution for VLDBs, and refreshing prod to lower environments is a regular dba task.  So I am requesting that pgbackrest enable this important feature.

**Comment by sfrost** [comment]
There isn't a feature here- pgbackrest already supports this and is working exactly as intended.  This is exactly the configuration and setup envisioned, and used extensively, with the delta-restore option.  Yes, you can restore a database from whatever repo you have to some new location.  If you want to then back up that restored system to a different location then you need to update the configurations for that, or you could just avoid changing the configuration at all and use either environment variables or command-line parameters to run the restore.

Note that you do NOT have to change archive_command to point to the "prod" system, that's just flat out wrong and is dangerous because you could screw up your prod backups in your prod repo.

**Comment by MichaelDBA** [comment]
Thanks, Stephen, for your valuable time.
