### ISSUE TITLE
throttling archive-get-queue-max

### ISSUE THREAD

**Issue by marco44** [pgbackrest/pgbackrest#694]
Hi,

It's just a suggestion if feasible. Right now we have some replication with bursts of WAL. So to deal with this we have a large archive-get-queue-max(4GB or more), a large number of processes (8 or more), and are set with archive-async. The problem is that when we have no WAL activity, the load from pgbackrest is quite heavy… asking 256 WAL files simultaneously from 8 processes, every 5 seconds.

So I was wondering if throttling this would be interesting… something similar to the way a TCP window works. Like always ask for twice (or whatever constant) how many WAL we managed to read from previous fetch, up to what's left in archive-get-queue-max... That would limit the waste of resources for when there are very few WAL incoming I think.

Regards

**Comment by dwsteele** [comment]
I think the answer is to have the main process do a quick check to see how many WAL are actually available then determine the number of processes that would be appropriate to do the work.  And then perhaps increase the poll interval when the system has been idle for a while, since list commands are not free.

This is all doable, the trick is testing it.  Probably the best thing would be to start with just the main process check and leave window management for another day.

I'm deep in the archive-push code right now, but you are welcome to have a crack at it if you like.

**Comment by dwsteele** [comment]
I've been thinking about this a bit, and I think the answer is to implement some sort of back off like we do when waiting for notification files to come from the async process.  Also, we could look at historical trends to decide how many processes to spawn, or just have the async process generate the list before spawning any local processes.

We tend to see most standbys streaming from the primary and none of this is very important in that case, but for a log-shipping standby this would obviously be beneficial.

**Comment by marco44** [comment]
Yeah, exactly our use case: 95% of our servers are streaming. But we have a few replicates in log-shipping because they are in other data-centers, with no direct access to their primaries. And I agree that a back off would probably be sufficient. Historical trends could even be counter productive, for us at least, as this is all about managing the big bursts without wasting too much cpu while idling.

**Comment by dwsteele** [comment]
PR #1274 should address most of the issues brought up here, so closing.
