### ISSUE TITLE
S3 AWS credentials auto resolution from IAM server role

### ISSUE THREAD

**Issue by aleszeleny** [pgbackrest/pgbackrest#721]
Hi,
I've found post (see bellow) suggesting there were intentions for 2018 to use IAM host credentials for pgBackrest to authenticate to S3 instead of creating configuration include file with S3 credentials somewhat like:

`curl --silent  http://169.254.169.254/latest/meta-data/identity-credentials/ec2/security-credentials/ec2-instance/ | jq -r '"repo1-s3-key-secret="+.AccessKeyId, "repo1-s3-key="+.SecretAccessKey, "repo1-s3-token="+.Token,"#LastUpdated: "+.LastUpdated, "#Expiration: "+.Expiration'
`
What generally works for backup & restore, can be included in the beginning of backup/restore script, but i doubt how to exchange S3 credentials to make sure archive-push/archive-get commands to avoid transient issues while old file was removed and before new one is created. Therefore I'd like to kindly ask, whether and if yes when build-in AWS credential usage is expected to be available, or how to handle include configuration file update while avoiding transient issues for archive-push/archive-get commands.

Thanks Ales

@farrellit We are planning to provide this functionality in the fall.

Unfortunately, the available Perl APIs are a bit of a mess and seem to think you'd like to retrieve a file from S3 all at once.  For a highly-parallel process having the chance that each process could use multiple gigabytes of memory is not OK.  Also, none of them are available as packages, so that means rolling our own or requiring CPAN, which we won't do.

_Originally posted by @dwsteele in https://github.com/pgbackrest/pgbackrest/issues/518#issuecomment-417725677_

**Comment by dwsteele** [comment]
Yes, we are still planning to implement this functionality.

The delay is because we made the decision to migrate the entire code base to C and so adding new features means adding them in two places and writing two sets of tests.  You can imagine how we might not find that very productive.

The C migration is planned to be completed in October but we are contemplating adding an interface between Perl and the C storage layer to enable us to add features like this earlier.  I'm doing some of the prelim work for that right now, but we haven't made a final decision yet.

So the answer to your question is sometime between this summer and the end of the year depending on which development path we take.

**Comment by aleszeleny** [comment]
That makes sense, thanks for sharing this information. Thanks for all the work in pgBackrest!

**Comment by dwsteele** [comment]
We have implemented this feature in PR #1137. Please have a look if you can.
