### ISSUE TITLE
Allow backup from primary if backup-standby=y standby is down

### ISSUE THREAD

**Issue by dtseiler** [pgbackrest/pgbackrest#753]
I have a pgbackrest (2.14) setup with two nodes (primary and standby). Currently if `backup-standby=y` the standby database is down, a backup attempt will fail with:

```
ERROR [049]: : unable to find standby database - cannot proceed
```

I would like to see this reduced to a warning and then resume backing up from the primary (similar to how it will do this if the standby were removed from the pgbackrest config altogether.

**Comment by mahomedh** [comment]
This was the behaviour I had expected/hoped for too and was disappointed when it didn't work. But when I thought about it, I realised that you must have a reason for not backing up from the primary in the first place. Usually that reason is because you don't want to add the extra load to the primary. So why should it be ok to do this when the standby is down? After all, your normal load on the primary doesn't suddenly go down, unless of course the load wasn't high in the first place and you are backing up from standby because it's "nice to have" (which is true in my case to be fair).

The current workarounds I see are: 
1. Setup extra standby servers
2. Setup alerts to know when the backup fails
3. Have a process to remove `backup-standby=y` when no standbys are available

But all that being said, I would love an extra option too that allows you to backup from primary if standby is down :)

**Comment by dwsteele** [comment]
@mahomedh has it exactly.  This has come up in the past and we decided that putting more load on the primary in a situation where there are already failures in the system is not a good idea.  Backups are not all that important as long as you have one that is fairly recent -- the important thing is to keep up with WAL archiving.  There's plenty of time to get a backup when the system is stable again.

If you really need a backup, the solution is to have more standbys or remove backup-standby.  This can be overridden on the command line with `--no-backup-standby` so there's  no need to reconfigure for a one-off backup.

That said, we're not against an additional option to force this behavior, but it's not a high enough priority to code it in Perl.  Once the backup code is in C (October) we would be open to a patch.

**Comment by rpiras** [comment]
Hi, I see this issue closed, but I didn't find anything in 2.16 documentation that references the possibility to force a backup from master in case no standby is available. Am I missing anything?
Thanks

**Comment by sfrost** [comment]
You apparently also didn't read the comments on this issue, please do so.

**Comment by rpiras** [comment]
I did, but I'm still confused.
In particular, the sentence 
`Once the backup code is in C (October) we would be open to a patch.`
made me think that something would be implemented and I expected this issue to remain open until then (or should a new issue be opened to request such patch?)
Since milestone has been completed I was wondering if this was already implemented.

**Comment by sfrost** [comment]
If you have a patch to submit after the backup code has been migrated to C, then feel free to open a new issue/PR with it.

**Comment by rpiras** [comment]
I see, thanks
