### ISSUE TITLE
Question about checksums

### ISSUE THREAD

**Issue by bradnicholson** [pgbackrest/pgbackrest#758]
Question about the checksum description here:
https://pgbackrest.org/configuration.html#section-backup/option-checksum-page

If PG has checksums off, and I pass `checksum-page=y` - will pgBackRest generate and verify checksums still?  Or is it reliant on the page level checksums from Postgres?

I have some older, large databases that were initialized without checksums, and I'm trying to understand the impact that has on pgBackRest.

Thanks!

**Comment by dwsteele** [comment]
> If PG has checksums off, and I pass checksum-page=y - will pgBackRest generate and verify checksums still? 

It will not.

> Or is it reliant on the page level checksums from Postgres?

Yes, the checksums need to exist in order to be verified.  We don't know whether they exist or not unless they are enabled, in which case we expect them all to be correct.

If you explicitly set `checksum-page=y` and checksums are not enabled for the cluster you'll get a warning `unable to enable page checksums since they are not enabled in the database` but the backup will continue.

**Comment by bradnicholson** [comment]
Great - thanks for the answer.
