### ISSUE TITLE
Documentation bug for 2.15 release

### ISSUE THREAD

**Issue by melrifa1** [pgbackrest/pgbackrest#776]
We are trying to download pgbackrest v2.15 and following the steps in the documentation https://pgbackrest.org/user-guide.html#build

The link provided in the guide is not correct  and the result is `404: Not Found`
```
$  wget -q -O - \
> >        https://github.com/pgbackrest/pgbackrest/archive/release/2.15.tar.gz
-bash: https://github.com/pgbackrest/pgbackrest/archive/release/2.15.tar.gz: No such file or directory
```
@hunleyd pointed out the correct link is: https://github.com/pgbackrest/pgbackrest/archive/release/2.15.1.tar.gz

The question here, is the documentation going to be updated to have the correct url, or the package is going to be renamed?

**Comment by sfrost** [comment]
Thanks for reporting this, we're working on a solution to fix the documentation, but this is the first time we've had to do a 'X.Y.1' release, so it isn't something that we had run into previously and the toolchain wasn't quite set up to handle it.

There was a prior 2.15 release that was incorrectly stamped (it said 2.16 instead due to the wrong commit mistakenly being chosen for the release), so we can't simply re-release 2.15 or there would be confusion over which tarball is which.  If you have 2.15.1, that's the correct version to run.

Thanks!

**Comment by dwsteele** [comment]
This should be fixed on the website.  The `README.md` in the source repo will be fixed as soon as it goes through CI.

As Stephen said, our automated tools were not prepared to deal with a non-standard version number.  Hopefully it will not happen again.
