### ISSUE TITLE
Help command shows --repo-retention-full but that is actually deprecated

### ISSUE THREAD

**Issue by mpetronic** [pgbackrest/pgbackrest#791]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.10

2. PostgreSQL version: 9.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: CentOS 7.6

4. Did you install pgBackRest from source or from a package? Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

**pgbackest help** command shows commandline option **--repo-retention-full** but that name is deprecated and fails if used. You actually need to use **--retention-full**. Simply seems the help output needs updated to reflect what the code requires. Might already be fixed in 2.15 but I figured I would pass this just in case.

**Comment by cmwshang** [comment]
--repo-retention-full and all the repo options require a number after them and that is what is not clear in the help. **--retention-full** is **deprecated** but continues to work because pgbackrest currently maintains compatibility with deprecated options. If you read through the user guide (for example https://pgbackrest.org/user-guide.html#quickstart/retention) you can see that --repo1-retention-full is the option. 
As far as the help command goes, I agree it can be confusing. We will look at updating this to be more clear that options like --pg-path are indexed so a number (1 through 7 for pg* options) is required (i.e. pg1-path, pg2-path, etc).

**Comment by mpetronic** [comment]
Thanks for the clarification. I now see that I missed the "1", in
--repo1-retention-full (as the deprecated, but still working) option. Sorry
about that.

**Comment by cmwshang** [comment]
Just to be clear repo1-retention-full is not deprecated. It is the option to use. Because the option is not indexed in the help, it is confusing since you have to type repo-retention-full (vs adding the 1). For example, using the version you have (although I would strongly recommend upgrading), to get information on the option for the expire command through the help, you would type:

**pgbackrest help expire repo-retention-full**

which would return the following (note at the bottom it states 'retention-full' is deprecated):

pgBackRest 2.10 - 'expire' command - 'repo-retention-full' option help

Number of full backups to retain.

When a full backup expires, all differential and incremental backups associated
with the full backup will also expire. When the option is not defined a warning
will be issued. If indefinite retention is desired then set the option to the
max value.

current: 2

deprecated name: retention-full

**Comment by mpetronic** [comment]
Thank you for clarifying. I understand what you're saying. We are in the
process of upgrading as well as you've recommended
