### ISSUE TITLE
question on basic usage of pgbackrest?

### ISSUE THREAD

**Issue by pinakesh** [pgbackrest/pgbackrest#792]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: pgBackRest 2.13

2. PostgreSQL version: psql (PostgreSQL) 11.0

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Linux RHEL 7.6 (Maipo)

4. Did you install pgBackRest from source or from a package?  Yes

**Questions**

I have a few queries on pgbackrest usage, kindly suggest.

1> Is it possible to clone a cluster (from available backups and wal archives on repo server) till the latest committed transaction on Primary (even if wal not switched after the latest commit) or would the recovery be till the last log switched? 

2> Is it possible to validate backup pieces?

3> Would creating backups on repo server make Switchover/Failover transparesnt? (I think pg1- and pg2- parameters of pgbackrest.conf on Repo server needs to be swapped after Switchover/Failover)

4> Will pgbackrest be able to recover from errors and resume backup in case of errors like (lack of free space, power outage, network outage, system restart, system hangs, etc)?

5> Is it possible to monitor pgbackrest progress using :
i> Any Postgres table (similar to v$session_longops for RMAN in Oracle)
ii> Tools like Nagios/Icinga ??

6> During backup process will pgbackrest prevent/hinder access to the database for readers or writers i.e. will there be any kind of locking on tables/tablespaces?

Regards,
Pinakesh

**Comment by sfrost** [comment]
1) recovery would be until the last WAL log that's in the archive, so the last one switched since that's what would be in the archive.  Of course, this will almost certainly be very close to where the current primary is at, and if you have primary_conninfo configured being set in your recovery.conf then your new replica will catch up very quickly to the primary.
2) Whenever you restore a backup, pgbackrest will verify all of the checksums that are stored in the backup.  We recommend regular restores be performed to test that your backups are working and that they can be restored and that they haven't been corrupted.  We have considered adding a command to verify a backup in place but it hasn't gotten to the top of the queue yet.
3) Having an independent repo-server is strongly encouraged in a failover environment because then all of the configs on the PG servers can be identical and the repo config can have the configuration for all of the PG servers.
4) Yes, pgbackrest will automatically attempt to resume a failed backup when it's next run.  pgbackrest will also retry in a lot of cases where a retry may be able to succeed.
5) We'd suggest looking at pgmonitor and what pgmonitor does if you'd like to monitor pgbackrest.
6) No, pgbackrest will not lock or prevent access to the database in any way.  Note, however, that pgbackrest will, obviously, use up disk i/o resources as it's copying the files, to manage that you can control the number of processes which pgbackrest will concurrently use to perform the backup.

Thanks,

Stephen
