### ISSUE TITLE
1 TB backup takes about 1 hour on local ssd disks

### ISSUE THREAD

**Issue by ctadaikkappan** [pgbackrest/pgbackrest#807]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: want to try

2. PostgreSQL version: 9.6 to 11 has multiple database 

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
each system will have PR, PR HA, DR and DR HA. 

4. Did you install pgBackRest from source or from a package?
yet to install

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
the pg_basebackup takes about 1 hour per TB on SSD in local drive on different mount point without compression, with compression takes about 24 hours with db server load on single cpu. the db size is close to 3 tb and archive logs generated per day is close to 100,000 we would like explore pg_backrest to solve our issues

1) The space allocated for backup (reduction by 80%)
2) Time taken for backup (Expected reduction is 50%) 
3) Optimal usage of CPU few cores (not more then 50% of available number of CPU, 20 core server max 10 core can be used) with max usage of 60% per core

**Comment by sfrost** [comment]
Yes, pgbackrest can almost certainly help you.  You can configure the number of processes that you'd like pgbackrest to use, it can run in parallel and it's a heck of a lot faster than pg_basebackup.

The space required for the backup will likely be less since you can do incremental and differential backups, and they'll finish faster so you'll have less WAL.

There's no option to say "don't use more than 60% per core" because it doesn't make any sense.  If you want pgbackrest to use less resources, configure it to use fewer CPUs.  We may implement some kind of throttling some day for workloads where you'd prefer pgbackrest to use less than a single CPU, but we don't support that yet today and it doesn't sound like it's really what you're after anyway.

These issues aren't for configuration help nor are they for basic questions or consulting.  If you run into an issue with pgbackrest, please feel free to report it here, otherwise I encourage you to try it out for yourself following the ample documentation provided.
