### ISSUE TITLE
archive_cleanup-like functionality

### ISSUE THREAD

**Issue by machack666** [pgbackrest/pgbackrest#812]
I'm using `pgbackrest` for full backups/WAL archive on one server, as well as pushing to a remote repository which cannot talk back to this location due to network constraints/policy, so I'm effectively using it to log-ship to the remote server.

I have set up the remote server to treat its local repository as canonical (so the WAL and one full backup used to bootstrap this cluster).  WAL is continually copied/updated to this server in the proper `archive/` path from the origin server, and this server is using `pgbackrest` to do the recovery using `pgbackrest archive-get`.

Since I don't care about retaining the WAL/archive on this particular node and it's used to just apply and then remove, I'm looking for a way to use `pgbackrest` to cleanup WAL files as they are applied, similar to `pg_archivecleanup`, setting some invocation of `pgbackrest archive-cleanup` or similar.  Presumably this would be a `restore_option=archive_cleanup=pgbackrest ...` in `pgbackrest.conf`.

I've talked a bit with SnowMan about this feature, and he suggested a feature request.  I'm happy to write a patch to handle this, but looking for feedback in terms of anything I haven't thought of in this case before writing something.  Let me know if you need any more information.

Thanks,

David

**Comment by machack666** [comment]
So is this something that there is a patch for at this point, or were you waiting on me to put something together about this?

**Comment by dwsteele** [comment]
We were curious to see the script you are using to sync the archive part of the repo.

My concern at this point is that this expiration command would be based on a repo sync'd by user-created scripts or by configuring and archiving to multiple stanzas, which we don't officially support because are ways for data to get eaten if you are not super careful.  We plan to support this officially in the future.

Either way, it seems like an orphaned feature as things stand now.
