### ISSUE TITLE
archive-get command is stuck when process-max >= 16

### ISSUE THREAD

**Issue by rdunklau** [pgbackrest/pgbackrest#821]
1. pgBackRest version: 2.15.1 and 2.16

2. PostgreSQL version: 10

3. Operating system/version - Debian strech

4. Did you install pgBackRest from source or from a package? package

7. Describe the issue:

We noticed a strange behavior when performing a restore using pgbackrest. The archive-get async command sometimes get stuck when process-max is equal to 16 (but setting it down to 12 is no problem). We also used an older version from before the command was reimplemented in C and we could not reproduce the problem here.
What happens:
  - pgbackrest processes fetch their wal files
  - one child ends up being a zombie. Upon further inspection using strace, it's stderr file descriptor has been closed and so it terminates on a SIGPIPE
  - the parent never reaps the child
  - the restoration process is then blocked

We have no idea how does the child end up as a zombie, and what it was doing before that. Regarding the problem with stderr, we noticed that pgbackrest opens lots and lots of file descriptors, so we tweaked the nofile ulimit to a huge value, with no difference to that.

I'm sorry we're not able to give more information regarding this problem.

**Comment by dwsteele** [comment]
See #752 for details on this issue.  TL;DR postgres is consuming these handles and increasing the limit does not work since it will just consume more.  Also, it's doubtful that 16 processes is very useful unless you have off-the-charts latency to your repo.  pgBackRest has little trouble staying ahead of postgres with even a few process, generally four is the most you'd need even with high latency.

If child processes are behaving badly when they are starved for handles that's not great.  We'll have a look at making that work better, but it won't solve the problem in general.
