### ISSUE TITLE
PANIC:  could not locate a valid checkpoint record when starting pg after restore

### ISSUE THREAD

**Issue by RonJohn2** [pgbackrest/pgbackrest#839]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.07

2. PostgreSQL version:
9.6.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHEL 6.10

4. Did you install pgBackRest from source or from a package?
Package.

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/3619672/pgbackrest.conf.txt)

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

For the source cluster:
archive_command = 'pgbackrest --stanza=localhost archive-push %p'
archive_mode = on
listen_addresses = '*'
max_wal_senders = 0
wal_level = replica
port = 5432

For the new cluster, after pgbackrest completed.
#archive_command = 'pgbackrest --stanza=localhost archive-push %p'
#archive_mode = on
listen_addresses = '*'
max_wal_senders = 0
wal_level = replica
port = 5433

    - errors in the postgresql log file before or during the time you experienced the issue
See attached.
[pgstartup.log](https://github.com/pgbackrest/pgbackrest/files/3619674/pgstartup.log)
[postgresql-2019-09-17_01.log](https://github.com/pgbackrest/pgbackrest/files/3619675/postgresql-2019-09-17_01.log)

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
[localhost-restore.log.gz](https://github.com/pgbackrest/pgbackrest/files/3619678/localhost-restore.log.gz)

7. Describe the issue:
We have a database in /Database/9.6/data, listening on port 5432.
We need a copy of that database listening on port 5433.
(This should be trivial, and is trivial on every other RDBMS that I've ever worked with.)

This is what I did:
1. pgbackrest stop
2. Edited pgbackrest.conf to point stanza "localhost" db-path to the new data dir (/Database/9.6/backups/test/data).
3. pgbackrest restore --stanza=localhost
4. Copy $PGDATA/postgresql.conf to (/Database/9.6/backups/test/data)
5. Edit the relevant config values for the new cluster.

However, "pg_ctl start -D /path/to/restored/data" fails with the error mentioned in the subject line..  This looks to be similar to issue 697.   I've attached all the requested log files.

**Comment by RonJohn2** [comment]
When I run pg_ctl for the new data dir and increase the debug level, I see that it can't find pg_xlog/000000010000022D00000003.  The new pg_xlog dir is empty.  Is that correct?

**Comment by dwsteele** [comment]
It's easier to skip steps one and two and just specify `pg1-path` for the restore command.  Be sure to disable the `archive_command` on the new cluster so you don't pollute the archive.  If you are intending to run this a production cluster it will be to be assigned its own stanza before archiving is enabled.

However, it looks like what you did should have worked.  Is `backup_label` present in `/Database/9.6/backups/test`.  What does `recovery.conf` look like?  Did you change the path in `pgbackrest.conf` back or leave it as it was?

**Comment by RonJohn2** [comment]
On 9/17/19 7:08 AM, David Steele wrote:
>
> It's easier to skip steps one and two and just specify |pg1-path| for the 
> restore command. Be sure to disable the |archive_command| on the new 
> cluster so you don't pollute the archive.
>

I did that.

> If you are intending to run this a production cluster it will be to be 
> assigned its own stanza before archiving is enabled.
>
> However, it looks like what you did should have worked. Is |backup_label| 
> present in |/Database/9.6/backups/test|.
>

It was restored.  I needed to rename it because "pg_ctl start" complained.

> What does |recovery.conf| look like?
>

recovery_command = 'pgbackrest --log-level-console=info --stanza=localhost 
archive-get %f "%p"'

> Did you change the path in |pgbackrest.conf| back or leave it as it was?
>

I changed db-path to point to the /new/postgres/data folder.

-- 
Angular momentum makes the world go 'round.

**Comment by dwsteele** [comment]
> It was restored.  I needed to rename it because "pg_ctl start" complained.

What was the complaint?  Recovery *cannot* proceed without this file.

**Comment by RonJohn2** [comment]
On 9/17/19 9:31 AM, David Steele wrote:
>
>     It was restored. I needed to rename it because "pg_ctl start" complained.
>
> What was the complaint? Recovery /cannot/ proceed without this file.
>

I had to rename it after pgbackrest completed.

Attached is the snippet from the log file, with pg_ctl start run with debug 
level 5.

-- 
Angular momentum makes the world go 'round.

**Comment by dwsteele** [comment]
Looks like it is ignoring `recovery.conf` for some reason.  Anything about `recovery.conf` in the log?

**Comment by RonJohn2** [comment]
(Note that "pg_ctl start" also complained about file permissions the first time I ran it.  Had to do a "chmod -R 0700 /Database/9.6/backups/test/data".  Would that have impacted pgbackrest?)

What should I search for in the logs?

-bash-4.1$ grep recovery /Database/9.6/backups/test/pg_log/postgresql-2019-09-17_10.log
-bash-4.1$ 
-bash-4.1$ grep recovery /Database/9.6/backups/test/pgstartup.log 
-bash-4.1$

**Comment by sfrost** [comment]
Is there a recovery.conf in place in the data directory?

As David said before, you can't go removing backup_label- that file is *required* and will be moved by PG if, and only if, it's able to restore from the backup.

What it sounds like is happening is that your recovery command is failing somehow and not able to pull the needed WAL from the archive to be able to replay it.  The whole "remove backup_label" thing is COMPLETELY WRONG HERE- it's a HINT and it's the *wrong* hint because you *are* restoring from a backup.

Frankly, now that we have the non-exclusive backup capability, and the exclusive backup system is deprecated, we should change that hint because it's just plain misleading.

**Comment by RonJohn2** [comment]
> Is there a recovery.conf in place in the data directory?

The new data directory?  Yes.  I pasted it's contents into an earlier comment.

> Frankly, now that we have the non-exclusive backup capability, and the exclusive backup system is deprecated, we should change that hint because it's just plain misleading.

Yeah, telling people to do the wrong thing is pretty anti-productive.

Good thing I just renamed it instead of deleting it, so putting it back was trivial.  "pg_ctl start" still failed.

> What it sounds like is happening is that your recovery command is failing somehow and not able to pull the needed WAL from the archive to be able to replay it. 

Right.  So why might it be failing?  (Because otherwise, all our backups are unreliable, and we have to figure out a new strategy.

**Comment by sfrost** [comment]
As I said above, it seems likely that there's something going wrong with the restore command- you need to look at your logs to see *what* is going wrong, I don't have that info.

**Comment by sfrost** [comment]
Just a wild guess but stanza of "localhost" seems awful strange to me.

**Comment by RonJohn2** [comment]
>  you need to look at your logs to see what is going wrong, I don't have that info.

I attached all the logs to the comment that opened this incident.

> Just a wild guess but stanza of "localhost" seems awful strange to me.

How so, and what do you think it should look like?

**Comment by sfrost** [comment]
Those logs don't show any attempts to use recovery.conf or restore command, were they from after you removed backup label?

I'd suggest retrying the restore and look at the logs following that BEFORE hacking around and removing files that are critical to the restore process.

If you don't get much info from the logs, increase the verbosity, in both PG and pgbackrest.

This doesn't look like it's a pgbackrest issue based on what you've shown here, so I strongly suggest you look at the logs carefully and try to figure out what the misconfiguration is.

**Comment by RonJohn2** [comment]
> were they from after you removed backup label?

There's obviously a disconnect in communications.

To me it's obvious, and I thought made explicit, that "XX000 HINT:  If you are not restoring from a backup, try removing the file /blah/blah/backup_label" is generated by pg_ctl.  So why do you think that I removed it before running pg_ctl?

Please look at section #7 "Describe the issue:" in my original comment:

1. pgbackrest stop
2. Edited pgbackrest.conf to point stanza "localhost" db-path to the new data dir 
3. (/Database/9.6/backups/test/data).
4. pgbackrest restore --stanza=localhost
5. Copy $PGDATA/postgresql.conf to (/Database/9.6/backups/test/data)
6. Edit the relevant config values for the new cluster.

However, "pg_ctl start -D /path/to/restored/data" fails with the error mentioned in the subject line.. This looks to be similar to issue 697. I've attached all the requested log files.

Nothing to indicate that I removed backup_label before running "pg_ctl start" because... IT WAS THERE.

**Comment by sfrost** [comment]
You also clearly said "It was restored.  I needed to rename it because "pg_ctl start" complained." hence why I would be thinking that you moved/removed it (the effect is the same).

That you renamed it makes me suspicious that you also tried to run the pg_ctl again, and that's actually when you got the errors in the log, and that there were different errors reported in some prior log which provide a lot more useful information about what actually is going wrong here.

Based on the logs you've provided, it doesn't look like pgbackrest is ever even invoked during the recovery process, which would seem to imply that if there's an issue here, it's with PG, and that seems even more unlikely than there being an issue with pgbackrest (which is actually quite unlikely but, sure, maybe it's possible).

If you'd like to have additional help sorting out what's wrong, I'd suggest you wipe out the existing restore, step back and redo it from the start, double-check the backup_label file and the recovery.conf (though pgbackrest is quite reliable at putting those in place...) and reviewing the logs from when PG is started after the pgbackrest restore.  You could also optionally increase the log level of both PG and pgbackrest, see the documentation for how to do that.

**Comment by RonJohn2** [comment]
>  I'd suggest you wipe out the existing restore, step back and redo it from the start

I'll do that this afternoon.

**Comment by dwsteele** [comment]
I just did a test restore on 9.6.  `backup_label` is present, recovery.conf is:
```
restore_command = 'pgbackrest --stanza=demo archive-get %f "%p"'
```
`pgbackrest.conf`:
```
[demo]
pg1-path=/var/lib/postgresql/9.6/demo

[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
```
postgresql log is (note the `starting archive recovery`):
```
LOG:  database system was interrupted; last known up at 2019-09-18 13:35:25 UTC
LOG:  starting archive recovery
LOG:  restored log file "000000010000000000000003" from archive
LOG:  redo starts at 0/3000028
LOG:  consistent recovery state reached at 0/3000130
LOG:  redo done at 0/3000130
LOG:  restored log file "000000010000000000000003" from archive
LOG:  restored log file "00000002.history" from archive
LOG:  selected new timeline ID: 3
LOG:  archive recovery complete
LOG:  MultiXact member wraparound protections are now enabled
LOG:  autovacuum launcher started
LOG:  database system is ready to accept connections
```

**Comment by RonJohn2** [comment]
Attached are a transcript of all the commands I ran (including catting the conf files) , and from running "pg_ctl start" with debug level 5.

After I run pgbackrest and the **new** data dir is populated, should the **new** data/pg_xlog directory have a bunch of WAL files in it?  Because mine is empty.

$ du -a data/pg_xlog
4       data/pg_xlog/archive_status
8       data/pg_xlog
[localhost-restore.log.gz](https://github.com/pgbackrest/pgbackrest/files/3627512/localhost-restore.log.gz)
[transcript.txt](https://github.com/pgbackrest/pgbackrest/files/3627516/transcript.txt)
[postgresql-2019-09-18_12.log](https://github.com/pgbackrest/pgbackrest/files/3627519/postgresql-2019-09-18_12.log)

**Comment by dwsteele** [comment]
`pgbackrest` is still stopped as you can see from this error:
```
ERROR: [062]: stop file exists for all stanzas
```
You need to run `start` before you can do recovery.  I forgot that had been recommended on psql-general.

This brings up a point.  I think if you are running multiple instances of a db from the same stanza on the same machine you can run into some problems.  The way you have done it this last time is safe because you passed pg1-path on the command line and that was communicated to the archive-get command.  But if you look at the archive-get command generated by postgres:
```
pgbackrest --log-level-file=detail --pg1-path=/Database/9.6/backups/test/data --stanza=localhost archive-get 000000010000022C000000DE "pg_xlog/RECOVERYXLOG"
```
You'll notice that postgres has not fully qualified the location of the pg_xlog dir (this is normal), so pgbackrest prepends the pg1-path in order to get an absolute path than can be passed to another process (for async parallel processing).  If you were to modify pgbackrest.conf, do a restore, and then change pgbackrest.conf back I think you could end up copy WAL to the other cluster.  It's not a scenario we've ever seen, but we'd probably be best served using cwd here.

**Comment by RonJohn2** [comment]
So, just start pgbackrest before trying to start the new cluster?  (And disable archiving in the new cluster's postgres.conf, of course, until I create a new stanza for it.)

Anything else?

**Comment by dwsteele** [comment]
Sounds right to me.

**Comment by RonJohn2** [comment]
Also, what's "we'd probably be best served using **cwd** here" in this context?

**Comment by RonJohn2** [comment]
Restarting pgbackrest before starting the new cluster fixed the problem.

Thanks for your help.

**Comment by dwsteele** [comment]
> Also, what's "we'd probably be best served using cwd here" in this context?

I was referring to how we handle this in the code.  It would probably be best to use cwd() to build the wal path rather than relying on the pg1-path option.  If there's config munging going on we might restore WAL to the wrong place.

> Thanks for your help.

You are welcome.
