### ISSUE TITLE
Asynchronous s3 archive fails with 082, then recovers on its own

### ISSUE THREAD

**Issue by jpuris** [pgbackrest/pgbackrest#860]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.16

2. PostgreSQL version:
9.4.24

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu 18.04.3 LTS

4. Did you install pgBackRest from source or from a package?
Package
```
APT-Sources: http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main amd64 Packages
```

5. Please attach the following as applicable:
```
archive_command: "pgbackrest --stanza=osl1-prod archive-push %p && pgbackrest --stanza=osl1-prod_s3 archive-push %p"
```
pgbackrest.conf
```
[global]
process-max=6

archive-async=y
spool-path=/data/db/pgbackrest_spool
archive-get-queue-max=30G
archive-push-queue-max=30GB

log-level-file=debug
log-level-console=info

start-fast=y

repo1-cipher-type=aes-256-cbc

repo1-retention-diff=7
repo1-retention-full=4

[global:archive-push]
compress-level=3

[osl1-prod]
repo1-path=/data/pgbackrest

repo1-cipher-pass=redacted

pg1-path=/data/db/data

[osl1-prod_s3]
repo1-type=s3
repo1-s3-endpoint=s3.eu-central-1.amazonaws.com
repo1-s3-bucket=backrest
repo1-path=/
repo1-s3-key=redacted
repo1-s3-key-secret=redacted
repo1-s3-region=eu-central-1

repo1-cipher-pass=redacted

pg1-path=/data/db/data
```

_Attached log files_
Postgres
[pgbackrest_s3_error_082-postgres.log](https://github.com/pgbackrest/pgbackrest/files/3707124/pgbackrest_s3_error_082-postgres.log)
pbBackRest debug
[pgbackrest_s3_error_082-debug.log](https://github.com/pgbackrest/pgbackrest/files/3707125/pgbackrest_s3_error_082-debug.log)

7. Describe the issue:
**Asynchronous s3 archive fails with 082 for no apparent reason, then recovers on its own**
For some unknown reason for couple hours pgBackRest was unable to upload to s3.
The same WAL was tried to asynchronously upload every 60s according to PG logs, but in pgBackRest log (debug level), there is no explanation as to why this it was failing.

- What is error 082 ?
- No details about the error in debug logs.

**Comment by dwsteele** [comment]
82 is an archive timeout error.  This just means that the WAL segment was not pushed within the archive-timeout (default 60 seconds).  There's no error in the archive-push-async log because apparently there was no error on that side (at least not at debug level), but the notification process for Postgres was timing out.

There's a big gap here:
```
2019-10-09 08:20:43.754 P00  DEBUG:     protocol/helper::protocolLocalGet: => {name: local-6 protocol}
2019-10-09 10:22:47.665 P01 DETAIL: pushed WAL file '0000000D000004B300000007' to the archive
```
Looks like there was some kind of issue and pgbackrest kept retrying until it went through.  Not much else we can say without the debug logs for the local process, but it doesn't look like `--log-subprocess` was on.

**Comment by jpuris** [comment]
It turns out amazon had some major issues, some of our other services had problems with their APIs. It was indeed retrying, which can be seen in postgres log.

I will look into utilising `--log-subprocess`.

Thanks for the explanation @dwsteele.

**Comment by sean0101n** [comment]
I apologize for jumping in here.  This is an issue that has been in the back of my mind while I've been playing around with backups.  If we have an active database with a pgbackrest repo in s3, an s3 outage like this could potentially be dangerous (WAL continues to be generated, but can't be archived since the archive command is failing/retrying).

@dwsteele What would you suggest for dealing with this type of issue?  A thought I had was to have the archive command push the WAL to a local directory, then try to copy it up to the repo in s3, but I'm not sure if this is possible with pgbackrest.

**Comment by dwsteele** [comment]
@sean0101n Copying locally is not much help because that directory can also fill up.

The best thing is to make sure your wal volume is large enough to handle a reasonable outage, and have monitoring so you know when there is an outage.

**Comment by sfrost** [comment]
If availability is more important than the ability to do PITR, you can set in pgbackrest a maximum amount of WAL to be retained.  After that point, if pgbackrest is unable to push WAL to the remote system, it will just start lying the PostgreSQL and claiming that the WAL has been archived even though it hadn't been.  Obviously, that means you can no longer recover to any point in time after WAL starts getting thrown away, and you need to perform a new backup as soon as the repo becomes available again, but this will keep systems online during the repo outage.  Tradeoffs to consider, as with many things.

**Comment by sean0101n** [comment]
Thank you very much for both of your input!  I didn't know about this configuration parameter, but it sounds like a good, worst-comes-to-worst option.  Also, having an s3 outage alert would definitely be useful for situations like these.

Thanks again for the great work on this project!
