### ISSUE TITLE
Requirements to run pgbackrest on a replication members

### ISSUE THREAD

**Issue by gowtham500** [pgbackrest/pgbackrest#874]
Hello team,

Thanks for developing this awesome tool. Fell in love with it from the beginning.

Please let me know if my understanding is correct.

1. For replication - lets say 3 member node and 1 repository node. 

We have configured backup to run from repository node on standby. All goes well. IF there is a failover i saw previous threads that full backup should be started again. I re initiate a full backup after a failover and I am able to recover the data successfully. Please let me know if there is any other option to track failover and initiate full backup automatically from pgbackrest . or is this a manual process ?

2. How does a team who has DBs in prod handle backup after failover scenario effectively?
Should we wait for the next full backup? Or there any tools which helps in achieving this.

3. Does pgbackrest has pg_rewind support ?  or will there be a scenario where pg_rewind will be required as part of pgbackrest?

**Comment by dwsteele** [comment]
> Please let me know if there is any other option to track failover and initiate full backup automatically from pgbackrest

pgBackRest will automatically do a checksum delta backup when it detects a timeline switch.  If you are correctly promoting your standby then there will always be a timeline switch.  We used to recommend a full backup, but that has not been required since we added delta backup.  In other words, there is nothing special you need to do on failover.

> How does a team who has DBs in prod handle backup after failover scenario effectively? Should we wait for the next full backup? Or there any tools which helps in achieving this.

Hopefully this was answered above.

> Does pgbackrest has pg_rewind support ? or will there be a scenario where pg_rewind will be required as part of pgbackrest?

pg_rewind is a tool you would use *instead* of pgBackRest, not with pgBackRest.  I prefer not to use pg_rewind in any scenario where there might have been corruption.  Restoring from a backup is safer and delta restore makes it as fast as possible.

**Comment by gowtham500** [comment]
Wow Great. I configured backup now on standby and it did work without issues even after failover. 
Restore worked well too !! Timeline switches were automatically tracked. 
Amazing Work on this tool.

Thanks for all the good stuff.

**Comment by dwsteele** [comment]
Thanks!  Glad it's working for you.
