### ISSUE TITLE
Asymmetric Encryption

### ISSUE THREAD

**Issue by davidfetter** [pgbackrest/pgbackrest#875]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

Next

2. PostgreSQL version:

Any

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

All supported

4. Did you install pgBackRest from source or from a package?

N/A

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

N/A

7. Describe the issue:

It's great to have symmetric encryption. It would be even more awesome to have asymmetric encryption, so the backups/replicas/etc. would in general have different access controls from the origin node.

The crypto library appears to support this, so the majority of the work is in feature design, testing, writing the glue code, etc.

**Comment by dwsteele** [comment]
We always intended to support asymmetric compression but until now there didn't seem to be any interest.

I'm not quite sure what this solution would look like.  Currently we encrypt `archive.info`, `backup.info`, and `backup.manifest`.  However, if these were encrypted with a public key the host doing the backups would not be able to do its job unless it also had the private key, since access to these files is required.  So, it seems the structure of the info files would need to change somehow (not sure how) or they need to remain unencrypted (not ideal).

Thoughts?

**Comment by dwsteele** [comment]
Added a project card for this so closing: https://github.com/pgbackrest/pgbackrest/projects/8#card-84437886.
