### ISSUE TITLE
optional wal archiving

### ISSUE THREAD

**Issue by sean0101n** [pgbackrest/pgbackrest#900]
I'm suggesting a new feature (I don't believe there's currently an option for this, or a work-around) that can toggle on/off wal archiving for backups.

Our use case simply requires a consistent state to be reached during a restore, which would be met when simply restoring from a specific backup set.  WAL generated between/after finished backups is not necessarily needed, and simply adds on to s3 costs as we're continuously archiving to s3.  I'd assume it would also cut down on cpu load on the primary during high traffic.

This might be an unusual use-case, but I thought I'd throw this suggestion out there.  Let me know your thoughts.

Also, thanks for all the hard work on this project!

-Sean

**Comment by hlakshmi** [comment]
👍 for the feature as we are also having a similar use case.

**Comment by dwsteele** [comment]
We have thought about this before but it is a bit more complicated that it looks.  The archive-get and backup commands don't currently communicate but for this feature they would need to do so somehow.  There are a number of ways we could go about it but it would require some work.

In general giving up PITR capability is a pretty big negative so while we are not against the feature it is not currently on our roadmap.  We would be willing to look at a contribution, though!

**Comment by sean0101n** [comment]
@dwsteele Maybe backup and archive-push commands don't need to communicate to each other?  Could the archive-push command execute a quick pg_is_in_backup(), and if it returns true, push WAL to archive?  I'm most likely over-simplifying it here, but just an idea.

**Comment by dwsteele** [comment]
`pg_is_in_backup()` does not work with non-exclusive backup, which we use for PostgreSQL >= 9.6.

**Comment by sean0101n** [comment]
Just had another idea.. could the archive-push check for an existing backup lock file, and decide to archive if it exists?

**Comment by dwsteele** [comment]
Yeah, that could work and it is fairly cheap.

**Comment by sean0101n** [comment]
I simply tried out adding a test to the archive_command like this:
`archive_command = 'test -f /tmp/pgbackrest/db2-backup.lock || exit 0 && pgbackrest --stanza=db2 archive-push %p'`
This seems to work fine, and the backup restored as expected.  Maybe it doesn't need to be implemented in the code.  A side note in the documentation or something could let people know that adding a check for the lock file in the archive command will avoid accumulating potentially unnecessary WAL, but will forfeit PITR functionality.

**Comment by dwsteele** [comment]
That is very clever!

I'm not sure we want to endorse it in the documentation (yet) but it is a perfect proof of concept.

I do worry that it depends on 1) copying the stanza name multiple places 2) that we won't change the lock file names 3) a bit of shell syntax that is perhaps complex for average user.

On the plus side, if it's wrong the backup will fail during the archive check.

**Comment by sean0101n** [comment]
Yeah, I assume it may be better to place it in code and maybe add a configuration parameter to turn it on and off.  I'm not familiar with C, but I might find some time to figure out how to implement it and test.

**Comment by sfrost** [comment]
Yeah, I definitely don't think this should go into the documentation as-is, just strikes me as too risky that users may set it up incorrectly somehow and end up causing themselves problems...

Having an option for it seems reasonable though, and I agree that this use-case is reasonable.  There's another use-case for this, which is where someone would like to get a backup of their DB and then, after the backup is complete, archive that backup off somewhere else.  This is basically the pg_basebackup "just give me a simple and consistent backup" feature.

Does the proposed approach actually work if the repo is remote, as in, over ssh..?  If it doesn't, which I suspect may be the case, it should still be pretty straight-forward to ask through the protocol if it exists, but we'd need pgbackrest to do that, of course, rather than try to do it with a shell.

**Comment by bradnicholson** [comment]
An alternative workaround would be setting the archive_command `/bin/true` when there isn't a backup running.  Error prone and risky in the wrong hands, but should work.

**Comment by hlakshmi** [comment]
> I simply tried out adding a test to the archive_command like this:
> `archive_command = 'test -f /tmp/pgbackrest/db2-backup.lock || exit 0 && pgbackrest --stanza=db2 archive-push %p'`
> This seems to work fine, and the backup restored as expected. Maybe it doesn't need to be implemented in the code. A side note in the documentation or something could let people know that adding a check for the lock file in the archive command will avoid accumulating potentially unnecessary WAL, but will forfeit PITR functionality.

I like this idea and one thing which I would like to mention here is that if you want to validate the stanza before you start the backup, it will fail with error because the archive-push doesn't work as the lock file won't be created.

**Comment by fvannee** [comment]
> Does the proposed approach actually work if the repo is remote, as in, over ssh..? If it doesn't, which I suspect may be the case, it should still be pretty straight-forward to ask through the protocol if it exists, but we'd need pgbackrest to do that, of course, rather than try to do it with a shell.

It sort of works currently, but not reliably. The backup lock gets created on the postgres host as well, because the ssh command from repo to postgres is a 'backup' command, which takes the lock upon startup on the postgres host. However, this lock is released as soon as the process on the postgres host exits. This happens when the connection is freed, which appens right before the archive check. This can sometimes lead to race conditions, where the last WAL segment is missing and the backup fails. PR #1134 fixes this by delaying the freeing of the remote connection until after the WAL segments have been received.

**Comment by dwsteele** [comment]
Added a project card for this so closing.
