### ISSUE TITLE
pgbackrest control host, remote backup to s3.

### ISSUE THREAD

**Issue by darkl0rd** [pgbackrest/pgbackrest#909]
I'm wondering if the following scenario is possible:
```
          
   pgbackrest-server (S3 configuration, starts backup on clientN over SSH)
           |        
client1, client2, client3 (local db config, pg1-path, and possibly a remote s3-path)
           |
           S3 (The target, as defined by pgbackrest-server)
```
The 'pgbackrest-server' storing the S3 configuration (access-key and secret-key being the most important, keeping these in one place and not having to put them on the clients).
The 'pgbackrest-server' initializes the backup (over SSH) on clientN.
ClientN starts the backup using the configuration, as configurede on pgbackrest-server, and backs up to S3 .

I have managed to make the above work, but only when providing each client with a full S3 configuration. My goal is to make the clients "dumb", not having to expose (sensitive) information to them.

**Comment by dwsteele** [comment]
You'll need to configure each pg host with `repo1-host*` settings if you want this to work.  The reason is they'll need to archive their WAL through the repo server.

However, this not the best configuration because it makes your repo server a single point of failure for archiving.  It's OK if some backups fail as long as archiving continues to work, but if archiving falls behind that can mean data loss on a primary failure if no standby is up-to-date.

**Comment by darkl0rd** [comment]
I understand. What would you suggest? I am dealing with many (50+) Dockerized Postgres instances - ideally I do not want to have the full S3 configuration on each and every container, having a single point of control - but also from a security perspective.

**Comment by dwsteele** [comment]
One option is to limit the pg hosts to only read/write in the `archive` directory using S3 policies (see https://pgbackrest.org/user-guide.html#s3-support for an example) .  That would at least address your security concerns.

Another option is to monitor your WAL archiving very closely and respond quickly when something goes wrong.  This is not my favorite approach, but it is an option.
