### ISSUE TITLE
Backup from a standby best practice

### ISSUE THREAD

**Issue by philflorent** [pgbackrest/pgbackrest#932]
Hi,

The hospitals I work for often have this kind of architecture for their disaster recovery plan :
- primary site
- standby site (can be used for DSS work)

Hot standby is a great PostgreSQL feature in that case.

We previously used Debian 9+Barman 2.x+PostgreSQL 9.6 for our internal and beta applications to build mirror configurations with a "primary" Barman and a "standby" Barman. 
- the primary cluster was sending its WAL information to the standby cluster, to the primary Barman and it was saved by the primary Barman
- the standby cluster was sending its WAL information to the standby Barman and it was saved by the standby Barman.
The traffic between the two sites was minimized. After a failover, no immediate action was needed, the backups were already OK and ready for a PITR.

We know upgrade to Debian 10+PostgreSQL 11+pgBackRest 2.x.
I read the documentation and the similar questions but I am still a bit puzzled about standby backups. What is the best practice with pgBackRest ?

If I put the stanza on the primary site only, it receives the WAL information from the primary cluster and it's OK to minimize the WAL traffic. But, in case of a disaster, this stanza would also be lost. My backup server would not be ready and I would have to backup immediately the promoted clusters to a local stanza not to be at risk.
It's possible to always have a stanza on the standby site and pgBackRest backups mostly from the standby in this case. But what is the best practice for the WAL information ? Perhaps I miss something but currently I send twice the same WAL information from the primary site to the standby site (once for the standby cluster via WAL streaming and once for the stanza). It's OK but it is a big regression in terms of bandwidth consumption.

Best regards
Phil

**Comment by dwsteele** [comment]
This is a pretty big topic.

In general we recommend having a standby at the primary site so there is no performance degradation on the first failover.  The DR site can then use log shipping (i.e. restore_command only, no streaming rep) to minimize bandwidth.  You may also find this is faster since WAL is transferred compressed and in parallel when using `archive-async`.

You take the risk of losing your backups no matter which site you choose.  The typical solution is to backup to the primary site and then rsync the repo to the DR site.  The reverse is also fine.

We don't recommend archiving from a standby, even though we plan to support this feature at some point for completeness.  The reason is that streaming replication is pretty slow, and there's a good chance of the standby being behind.  Archiving from the primary gives you the best chance of being up to date because we can parallelize compression and transfer.

There are definitely some differences in how pgBackRest and Barman have approached these problems and your concerns are legitimate.  We plan to implement multi-repo support (i.e. auto rsync to a remote site) and archiving from standby, but we have not had the time/resources to do so yet.

**Comment by philflorent** [comment]
Thank you it's a clear answer. Barman is interesting for complex architectures and I like the one conf file by cluster thing but it's also a bit more complex and it lacked some features that were judged mandatory by smaller sites like backup compression.

"The typical solution is to backup to the primary site and then rsync the repo to the DR site."

I implemented that. We archive from the primary. A script present on both sites checks where it runs to rsync the archive stanza subfolder periodically. It is also called in case of a switchover after the primary cluster shutdown not to miss WAL files. 
With a pretty large "--archive-timeout" the pgbackrest backup command works OK on the standby. I always privilegiate native features if they exist but we can now do everything we could do with pg 9.6. 
We will analyze again more carefully the features of the various backup products with the Debian 11/PostgreSQL 13 (?) combination. It's not that easy to choose. Many products exist (pitrery, pgbackrest, barman, pg_probackup) but it will also depend on the company that will support us. We do the assistance but we will suscribe complementary support.
