### ISSUE TITLE
Question: Minimum privileges and hba rules for pgbackrest

### ISSUE THREAD

**Issue by gowtham500** [pgbackrest/pgbackrest#938]
hello team,
1. pgBackRest version:  2.23
2. PostgreSQL version: 12.1
3. OS- CentOS Linux release 7.7.1908
4. Installed pgbackrest from rpm in PostgreSQL repo.

What are the minimum privileges required for pgbackrest to take backup and archive WALs?

I tried to restrict my DB visibility and during that I noticed that pgbackrest fails to take backup unless we have below peer rule set and postgres user should have SUPERUSER permission.

```
# "local" is for Unix domain socket connections only
local   all    all     peer
```

I also tried below rule, but it failed.
```
# "local" is for Unix domain socket connections only
local  postgres   postgres      peer
```
Is this assumption right ? If not can you please provide clarity on below scenarios

1. Minimum permissions and hba rule required for standalone. Here Pgbackrest takes backup onto same host.

2. Minimum permissions (Apart from SSH connectivity among nodes)and hba rules required for dedicated backup admin host. Here Pgbackrest takes backup from standby onto to the backup host.

**Comment by dwsteele** [comment]
Since PostgreSQL 11 is is possible to run pgBackRest as a user other than postgres (e.g. pgbackrest), but it is a tricky configuration and we have not had time to test and document it yet.  See https://www.postgresql.org/docs/11/app-initdb.html (--allow-group-access).

> Minimum permissions and hba rule required for standalone. Here Pgbackrest takes backup onto same host.

This worked fine on a CentOS 7 test system:
```
# "local" is for Unix domain socket connections only
local  postgres   postgres      peer
```
But you may have better luck with:
```
# "local" is for Unix domain socket connections only
local  all   postgres      peer
```
This is required on Debian systems and perhaps elsewhere, too.

> Minimum permissions (Apart from SSH connectivity among nodes)and hba rules required for dedicated backup admin host. Here Pgbackrest takes backup from standby onto to the backup host.

The rules are the same because pgBackRest never connects to PostgreSQL remotely.  The connection is done locally via our protocol.

**Comment by dwsteele** [comment]
Since PostgreSQL 11 is is possible to run pgBackRest as a user other than postgres (e.g. pgbackrest), but it is a tricky configuration and we have not had time to test and document it yet.  See https://www.postgresql.org/docs/11/app-initdb.html (--allow-group-access).

> Minimum permissions and hba rule required for standalone. Here Pgbackrest takes backup onto same host.

This worked fine on a CentOS 7 test system:
```
# "local" is for Unix domain socket connections only
local  postgres   postgres      peer
```
But you may have better luck with:
```
# "local" is for Unix domain socket connections only
local  all   postgres      peer
```
This is required on Debian systems and perhaps elsewhere, too.

> Minimum permissions (Apart from SSH connectivity among nodes)and hba rules required for dedicated backup admin host. Here Pgbackrest takes backup from standby onto to the backup host.

The rules are the same because pgBackRest never connects to PostgreSQL remotely.  The connection is done locally via our protocol.
