### ISSUE TITLE
Feature Request for pgbackrest to support Azure cloud storage

### ISSUE THREAD

**Issue by talha129** [pgbackrest/pgbackrest#939]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: latest

2. PostgreSQL version: 11

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: linux

4. Did you install pgBackRest from source or from a package? : source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
    Hey, i just wanted to ask if the pgbackrest will support azure cloud storage as well in the future? We have all our backup files for every on azure cloud and we wanted to make it consistent with our database backups as well. We were looking to incorporate pgbackrest as a backup and restore utility but it turns out it only supports AWS S3 as of now. Is it possible to provide the azure sync as a pgbackrest feature in the near future? If someone is not already looking into it can you guys suggest me the way through how can we achieve this?

**Comment by dwsteele** [comment]
Azure support is planned but we don't have a timetable yet.  Storage drivers are not hard to write, but testing them is tricky.  We need to be able to test in isolation rather than against the service since we run many tests in parallel in a CI environment.  Azurite (https://github.com/azure/azurite) seems promising but we have not tested it.

If you know C, you are welcome to look at writing the driver yourself (or sponsor somebody to do it).  You can get started by looking at the S3 driver: https://github.com/pgbackrest/pgbackrest/tree/master/src/storage/s3

**Comment by dtseiler** [comment]
+1 for this request. Hoping to move from wal-g to pgbackrest but we need to use Azure cloud storage.

**Comment by dwsteele** [comment]
Thanks for the input, Don. We do expect to work on GCS/Azure support soon-ish but still have no fixed timeline.

**Comment by dtseiler** [comment]
Understood. I wish I had the skillset to help!

**Comment by dtseiler** [comment]
(I'll be happy to test anyway)

**Comment by noctarius** [comment]
Support for the Feature Request. Also happy to help. Looking to deploy TimescaleDB with pgbackrest to AKS.

**Comment by dwsteele** [comment]
> would CIFS support work with Azure Storage Files (which offers SMB3 shares)?

It might but you have to give it a try. If it does I'd imagine the performance would be terrible and I worry about what kind of atomicity it guarantees.

**Comment by dwsteele** [comment]
@talha129 @dtseiler @noctarius I have attached #1055 for a WIP Azure driver. It works fine with Azurite but I'm having trouble with actual Azure, perhaps because my storage permissions are not configured correctly. I'm completely new to Azure.

Could you give it a try?

**Comment by dwsteele** [comment]
@talha129 @dtseiler @noctarius The issue running against actual Azure has been fixed.

The problem was that I copied the driver from S3 as a template and S3 uses ISO-8601 dates but Azure requires RFC-2822 (HTTP standard dates). Azurite completely ignores the Date header (see https://github.com/Azure/Azurite/issues/459) so this was not caught in testing.

To make matters worse the first request made by pgBackRest is HEAD which does not return content and therefore no detailed error message, so all I got was the cryptic `Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.`. I altered one of the tests to send a POST and then got an error that indicated the Date header was in the wrong format. After fixing that everything worked fine.

The fixes have been pushed up to #1055. Please test if you can.

**Comment by dwsteele** [comment]
Committed at 3f4371d7a2 and 2f7823c627c627.
