### ISSUE TITLE
Any wrong env PGBACKREST_* variable breaks all

### ISSUE THREAD

**Issue by lkhomenk** [pgbackrest/pgbackrest#942]
1. pgBackRest version:
2.20
2. PostgreSQL version:
10.11
4. Did you install pgBackRest from source or from a package?
crunchy postgres-operator 4.2.1
7. Describe the issue:
If system running pgbackrest has any illegal `PGBACKREST_*` variable - running pgbackrest stucks - goes zombie or gives 082 error(Timeout) for all opperations get/push
Crunchy postgres-operator 4.2.1 + S3 pgbackrest config
Steps to reproduce:
1. `export PGBACKREST_VERSION=2.20` - illegal variable or any other with typo
`export PGBACKREST_PG_PORT=5432`
2. execute pgbackrest stanza-create/archive-push/archive-get
3. get warning on unsupported variable and 082 on pgbackrest calls

Fix: not to use such variables - of course.

**Comment by dwsteele** [comment]
Well, that's our namespace so what if we use `version` for an option name in the future?  Then you'd get a hard error instead of a warning.  I think it's better not to create env vars in the `PGBACKREST_` namespace to avoid potential problems in the future.

We agree that the zombie process is a bug.  You should get the warning and then everything should proceed normally.  We've made some improvements in this area in 2.24 so I'd like to see how that behaves before we make more adjustments.

**Comment by dwsteele** [comment]
Closing, but let us know if 2.24 does not improve the situation with zombie processes.
