### ISSUE TITLE
Delete manifest.gz files ?

### ISSUE THREAD

**Issue by Tahiti-steph** [pgbackrest/pgbackrest#954]
Hello,

I have a Linux serveur (CentOS Linux release 7.3.1611) with postgresql (10.7) cluster and pgBackRest (2.11) for backup.
Many files *.manifest.gz have been accumulating for several months without being purged (in directory /var/pgbackrest/backup/cluster/backup.history/2020/* )

Question: Can we delete these files? If so how?

cat pgbackrest.conf

[global]
log-path=/var/pgbackrest/log
repo-path=/var/pgbackrest
lock-path=/var/pgbackrest/lock
spool-path=/var/pgbackrest/spool
retention-full=2
link-all=y
stop-auto=y
compress-level=2

[cluster]
....

Thank you very much for your reply.
Tahiti-steph

**Comment by dwsteele** [comment]
This directory is never expired because it is intended for data mining.  The files are compressed to minimize space usage.  Is it using too much space or are you just curious?  I have a cluster with 1400 history files that uses ~80MB).

That said, if you want to delete older history files it's not a problem.  Just don't delete the history for any current backups.

**Comment by Tahiti-steph** [comment]
Hello David,

Tank you for your reply.
It's not using to much space yet, but as the serveur is sensible, we need to know what are those files.
We will delete one month old files.

Regards
Stephane

**Comment by Tahiti-steph** [comment]
Question solved
