### ISSUE TITLE
Unexpected time gap between restorated database and restore point

### ISSUE THREAD

**Issue by kkarolis** [pgbackrest/pgbackrest#956]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: **2.16-1.pgdg18.04+1**

2. PostgreSQL version: **9.5**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: single server, **Ubuntu Bionic**

4. Did you install pgBackRest from source or from a package? **package**

5. Please attach the following as applicable:

```text
# pgbackrest.conf
[global]
repo-path=/var/lib/pgbackrest
```

```text
# postgresql.conf
archive_command = 'pgbackrest --stanza=main archive-push %p'
archive_mode = on
listen_addresses = '*'
log_line_prefix = ''
max_wal_senders = 3
wal_level = hot_standby
```

Restoration log from first incorrect restore
[postgresql-9.5-main.log](https://github.com/pgbackrest/pgbackrest/files/4311245/postgresql-9.5-main.log)

7. Describe the issue:

I'm using PITR to recover in case an update of the application failed. In essence, it works like this:

1. if there are no backups, do a single `pgbackrest --stanza=main backup`
2. create a named restore point and get `$timestamp` of this action
3. do an application update (which includes DB changes), let's assume it fails
4. stop the DB
5. do `pgbackrest --delta --target-timeline=latest --type=time "--target=$timestamp" restore`
6. start the DB

Yesterday (2020-03-09) one such deployment failure happened and the recovery was initiated. However, even though the logs say `last completed transaction was at log time 2020-03-09 16:20:20.941812+01` I don't see any of the recent records. It seems the database is stuck around the 2019-11-20 date. After trying to recover once again I am not able to get records newer than 2019-11-20. I tried to recover to timelines 6-12 instead of the `'latest'`, but it seems to always end up on same date.

Some troubleshooting:

1. In the logs I see some WAL files are duplicated and tried to be pushed
```
postgresql-9.5-main.log:ERROR: [045]: WAL file '00000005000000000000008D' already exists in the archive
postgresql-9.5-main.log:ERROR: [045]: WAL file '000000010000000000000084' already exists in the archive
postgresql-9.5-main.log:ERROR: [045]: WAL file '000000010000000000000085' already exists in the archive
```
1. Can "duplicate" fails and failure to push them cause such a behavior?
2. Any ideas on how can such a big gap exist between last completed transaction and recovery stop point:
```text
recovery stopping before commit of transaction 27200, time 2020-03-09 15:29:48.634222+01
redo done at 0/8E025FE8
last completed transaction was at log time 2019-11-20 11:10:25.162873+01
```

**Comment by dwsteele** [comment]
> In the logs I see some WAL files are duplicated and tried to be pushed

This is generally caused by split-brain or a recovery that does not increment the timeline or promotion because there is no `recovery.conf` or `backup_label`.

It's also possible to see this race condition in older versions of Postgres because the history files can take a while to get to the archive and new promotions may pick an already-used timeline.  I fixed this in 2018 (https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=b981df4cc09aca978c5ce55e437a74913d09cccc) but you would need to be running a recent minor version of Postgres 9.5 to see the fix.  My guess is that this is your problem.

> Can "duplicate" fails and failure to push them cause such a behavior?

Yes, see above.

> Any ideas on how can such a big gap exist between last completed transaction and recovery stop point

My guess is that you did a restore at some point that was only recovered to 2019-11-20 (and then promoted) so that the new timeline didn't include any transactions after that date.  Since then you have been doing backups/restores off that truncated timeline and its descedents.
