### ISSUE TITLE
Improve test - README

### ISSUE THREAD

**Issue by pgstef** [pgbackrest/pgbackrest#972]
Hi,

In order to run the tests and avoid errors like `gcc: error: .build/...: No such file or directory`, pgbackrest has to be built, with something like

```
cd /backrest/src && ./configure
make -s -C /backrest/src
```

Do you think it could appear in the readme or be added to the test.pl script ?

**Comment by dwsteele** [comment]
This should no longer be true as of da89d0ad61574.  Now configure and make can be run anywhere. But the standard way is documented here: https://pgbackrest.org/user-guide.html#build

We could add build instructions to `test/README.md` but I think it might be misleading since building the project manually is not useful for testing with `test.pl`. `test.pl` handles building the project before running tests.

**Comment by pgstef** [comment]
Hi,
I've just re-run the test.pl (with a fresh git clone) and I don't have the error anymore indeed.
Sorry for the noise, we can close the issue ;-)
Kind regards,

**Comment by dwsteele** [comment]
No problem, it was probably an issue when you were running it before.  We've been trying really hard to make development smoother.
