### ISSUE TITLE
--prefix not taken into account anymore in 2.25

### ISSUE THREAD

**Issue by marco44** [pgbackrest/pgbackrest#980]
Is this really intended ? It breaks the archlinux packaging for instance.

I think it's linked to 237a3da4d69bf068652c6f5cc805c313f725b129, where @prefix@ is removed from makefile.in

**Comment by dwsteele** [comment]
Ugh, just overzealous cleanup on my part.  Restored at af734d69.

**Comment by marco44** [comment]
Yes, this fixes it. Wouldn't this deserve a release, as this may break most packaging systems ?

**Comment by dwsteele** [comment]
No, I think it's better if the file is patched at the package level for this release.

A release is very expensive in terms of time and I'm pretty sure Debian/Ubuntu and RHEL/CentoS are not affected since we test those packages in CI.

Where is the package source for Arch Linux?  I would like to add more package tests to our CI if possible so we catch these issues early.

**Comment by marco44** [comment]
https://aur.archlinux.org/packages/pgbackrest/

**Comment by df7cb** [comment]
Debian is affected, pgbackrest got erroneously moved to /bin instead of /usr/bin.

**Comment by dwsteele** [comment]
> Debian is affected, pgbackrest got erroneously moved to /bin instead of /usr/bin.

We test that the packages build, install, and work, but we are not testing for the location of `pgbackrest`.  We'll add that test to help prevent this sort of regression in the future.

Sorry for the trouble.
